#+title:      Willenbrock v. Latulippe, 125 Wash. 168, 215 P. 330 (1923)
#+date:       [1923-05-17 Thu 00:00]
#+filetags:   :assignment:case:law:scrutiny:strict:sublease:
#+identifier: 19230517T000000
#+signature:  sc

* Willenbrock v. Latulippe -- Supreme Court of Washington. | May 17, 1923 | 125 Wash. 168 | 215 P. 330

- Washington Citation :: Willenbrock v. Latulippe, 125 Wash. 168, 215 P. 330 (1923)
- All Citations :: 125 Wash. 168, 215 P. 330


                            125 Wash. 168

                     Supreme Court of Washington.

                             WILLENBROCK

                                  v.

                              LATULIPPE.

                              No. 17659.
                            May 17, 1923.

** Brief
:PROPERTIES:
:VISIBILITY: all
:END:

*** Issues

An Issue

*** Holdings

*** History

*** Facts

*** Law

*** Analysis

** Document Details

- [[*West Headnotes (3)][West Headnotes]]
- [[*Attorneys and Law Firms][Attorneys and Law Firms]]
- [[*Opinion][Opinion]]


** Synopsis

Department 2.

Appeal from Superior Court, Pierce County; W. D. Askren, Judge.

Action by Fred W. G. Willenbrock against Lawrence Latulippe. Decree for plaintiff, and defendant appeals. Affirmed.

** West Headnotes (3)

*** [1] Landlord and Tenant  [[1: 233-k-881(3)][233-k-881(3)]]  Time

- /233 Landlord and Tenant/
- /233-IV Particular Kinds of Tenancies and Attributes Thereof/
- /233-IV(E) Option to Purchase Premises/
- *233-k-876 Covenants*
- *233-k-881 Exercise of Purchase Option*
- *233-k-881(3) Time*
- /(Formerly 233k92(3))/

Notwithstanding that a lease for four years prohibited lessee from subletting except by consent of lessor, but gave lessee an option to purchase the premises at a named cash price, and such prohibition against subletting not amounting to a prohibition against assignment of the right to purchase, the right to purchase was not uncertain as to time, as it could be effectually claimed by lessee or his assignees at any time during the life of the lease.

- 2 Cases that cite this headnote

*** [2] Landlord and Tenant  [[2: 233-k-731][233-k-731]]  What constitutes breach of covenant

- /233 Landlord and Tenant/
- /233-IV Particular Kinds of Tenancies and Attributes Thereof/
- /233-IV(B) Assignment and Subletting/
- /233-IV(B)2 Restrictions as to Assignment or Subletting/
- *233-k-731 What constitutes breach of covenant*
- /(Formerly 233k76(3))/

Where a lease for four years prohibited lessee from subletting without consent of lessor, but gave lessee the option to purchase at a named cash price, in view of the option right to purchase making it something more than an ordinary lease, the prohibition against the subletting did not amount to a prohibition against assignment.

- 6 Cases that cite this headnote

*** [3] Landlord and Tenant  [[3: 233-k-732][233-k-732]]  Consent of Lessor, and Waiver Thereof

- /233 Landlord and Tenant/
- /233-IV Particular Kinds of Tenancies and Attributes Thereof/
- /233-IV(B) Assignment and Subletting/
- /233-IV(B)2 Restrictions as to Assignment or Subletting/
- *233-k-732 Consent of Lessor, and Waiver Thereof*
- *233-k-733 In general*
- /(Formerly 233k76(3))/

Where a lease prohibited subletting, but gave an option to purchase, evidence that assignee of the lease conducted some negotiations with lessor concerning his consent to the assignment held not to show that assignee consented to construction of the lease requiring owner’s consent to the assignment.

- 4 Cases that cite this headnote

** Attorneys and Law Firms

- <<*168>> <<**330>> G. P. Fishburne, of Tacoma, for appellant.
- Lund & Lund and Davis & Neal, all of Tacoma, for respondent.

** Opinion

PARKER, J.

The plaintiff, Willenbrock, assignee of Fred Leonard, seeks a decree of specific performance against the defendant, Latulippe, requiring him to execute a conveyance of land situated in Pierce county in pursuance of an option embodied in a lease of the land by him to Leonard. A trial upon the merits in the superior court for Pierce county resulted in the <<*169>> awarding of a decree in favor of Willenbrock as prayed for, from which Latulippe has appealed to this court.

On January 25, 1918, Latulippe, the owner of the land in question, executed and delivered a written lease therefor to Leonard for the term of four years, Leonard to pay rent therefor at the rate of $10 per month. The lease contains an option in favor of Leonard to purchase the land, reading as follows:

‘The lessee is hereby given and granted a first option to purchase the property hereby leased at the price of $1,500.00 cash.’

The lease does not contain any provision in terms prohibiting Leonard from assigning his rights thereunder, though it does in terms prohibit him from subletting the premises except by consent of Latulippe. No claim is made against either Willenbrock or Leonard rested upon nonpayment of rent. On November 8, 1920, by indorsement upon the back of the lease, Leonard made an assignment of his rights thereunder as follows:

‘For value received, I hereby sell, transfer, assign and set over to Fred W. G. Willenbrock, his heirs and assigns, all my right, title, and interest in and to the foregoing lease and option to purchase, hereby authorizing the lessor, Lawrence Latulippe, to receive from the said assignee all payments due under the terms of this lease and to convey to him or his assigns the title to the property, instead of to me. * * *’

Latulippe did not learn of the making of this assignment until December 1 1920, when it evidently came to his attention when he was paid the month’s rent then falling due by the attorney for Willenbrock, the assignee. About that time or very soon thereafter, Latulippe was requested to indorse upon the lease his approval of the assignment, which he refused to do, <<*170>> though he took the month’s rent then or theretofore paid to him by the attorney for Willenbrock knowing, we think, that the money came from Willenbrock as assignee of the lease. A few days later, on December 6, 1920, Latulippe wrote to Willenbrock as follows:

‘I will authorize the assignment of my lease to Fred Leonhard by him to you according to the terms of my annexed assignment. Attorney Lund gave me $10.00. If this $10.00 comes from you and you do not now want to go ahead with the lease, I will return you your $10.00. Otherwise I will keep same.’

This was accompanied by a paper which was in form a conditional approval of the assignment, reading as follows:

‘Whereas the following language, to wit: ‘The lessee is hereby given and granted a first option to purchase the property hereby leased at the price of $1,500.00 cash or upon such terms as may hereafter be agreed upon between the parties hereto’—was inserted by mistake in the annexed lease, and is ambiguous and meaningless, now therefore I hereby approve the assignment of the annexed lease to Fred W. G. Willenbrock, his heirs, and assigns with the understanding and agreement that said language is eliminated therefrom.

‘Lawrence Latulippe.’

This paper was not returned by Willenbrock to Latulippe. Thereafter rent was <<**331>> paid each month by Willenbrock and received by Latulippe until September, 1921, when Willenbrock tendered to Latulippe $1,500 in money and demanded conveyance of the land in compliance with the terms of the option to purchase embodied in the lease. The tender was refused by Latulippe; he also refusing to execute a deed for the land as demanded. The tender was kept good and the amount thereof deposited in court upon the commencement of this suit.

<<*171>> [1] <<1: 233-k-881(3)>> It is fire contended in behalf of Lattullippe that the option is void and of no effect because of uncertainty as to any specified time for exercising rights thereunder. It is true that there is no specific date mentioned prior to which the right to purchase may be exercised; but, the option being embodied in and made a part of the lease, it seems to us that it remained open for the exercise of the right of purchase on the part of Leonard, or Willenbrock, his assignee, at any time during the existence of the lease; that is, that it was a right the life of which was to be coincident with the life of the lease. We have seen that the right to purchase was claimed, accompanied by proper tender, at a time when the lease was in full force and effect. Having in mind the elementary rule that calls for the construction of contracts which will give full force to all of their provisions, rather than one that will impair the force and effect of any of their provisions (Pennsylvania Mortgage Inv. Co. v. Simms, 16 Wash. 243, 47 Pac. 441) we think no other conclusion can be arrived at than that the parties to the lease intended that the right given by the option could be effectually claimed at any time during the life of the lease. The decisions in Schroeder v. Gemeinder, 10 Nev. 355, and Anderson v. Anderson, 251 Ill. 415, 96 N. E. 265, Ann. Cas. 1912C, 556, seem to us to be directly in point in support of this view; and that the decisions in D’Arras v. Keyser, 26 Pa. 249, and Prout v. Roby, 15 Wall. 471, 21 L. Ed. 58, while not directly in point, lend strong support to this conclusion.

[2] <<2: 233-k-731>> Contention is next made that the terms of the lease prohibiting the subletting of the premises by Leonard prevented Willenbrock from exercising the option to purchase, even if Leonard had such right prior to the assignment of the lease; the argument being that the assignment of the lease was in legal effect a violation <<*172>> of the prohibition therein against subletting of the premises by Leonard. We think this argument is untenable. The prohibition against subletting, we are quite clear, does not amount to a prohibition against assignment, especially in view of the option right to purchase contained in the lease making it something more than an ordinary lease. Spencer v. Commercial Co., 30 Wash. 520, 71 Pac. 53; Cuschner v. Westlake, 43 Wash. 690, 86 Pac. 948; Burns v. Dufresne, 67 Wash. 158, 121 Pac. 46. In those decisions this court adopted the generally accepted view that prohibitions in leases against assignments and against subletting are not looked upon with favor by the courts, and will be strictly construed; and a prohibition in one of these respects will not amount to a prohibition in the other respect. 16 R. C. L. 832, 872. We conclude that this lease did not in terms or legal effect prevent Leonard from lawfully assigning all his rights therein, including his optional right to purchase, to Willenbrock, and that upon the execution of the assignment Willenbrock acquired all the rights under the lease, including the option, theretofore possessed by Leonard, regardless of any consent or approval of such assignment on the part of Latulippe.

[3] <<3: 233-k-732>> Some contention is made rested upon the theory that the parties to the contract have, by practical construction of its terms, caused the option clause embodied therein to be entirely eliminated therefrom; that is, by a practical construction of the contract put upon it by Latulippe and Willenbrock after the assignment. We cannot agree with this contention. After Willenbrock had by the assignment, become possessed of the absolute right to exercise the option to purchase, but not before, he and Latulippe did have some communication with each other looking to a formal approval <<*173>> of the assignment. This, however, consisted of practically nothing more than a request made in behalf of Willenbrock that such approval be formally given, the sending of a conditional approval by Latulippe, and the failure of Willenbrock to return it to Latulippe. This we think does not constitute an admission that unconditional approval of the assignment was necessary, though it may suggest that Willenbrock thought such approval was desirable on his part to remove all controversy which might arise on possible claims of Latulippe.

We think the judgment must be affirmed.

It is so ordered.

MAIN, C. J., and FULLERTON and TOLMAN, JJ., concur.

** End
#+STARTUP: show2levels
