#+title:      Diel v. Beekman, 1 Wn. App. 874, 465 P.2d 212 (1970)
#+date:       [1970-02-09 Mon 00:00]
#+filetags:   :case:evidence:law:parol:resulting:trust:
#+identifier: 19700209T000000
#+signature:  coa=div1

* Diel v. Beekman -- Court of Appeals of Washington, Division 1, Panel One. | February 9, 1970 | 1 Wash.App. 874 | 465 P.2d 212

- Washington Citation :: Diel v. Beekman, 1 Wn. App. 874, 465 P.2d 212 (1970)
- All Citations :: 1 Wash.App. 874, 465 P.2d 212


                           1 Wash.App. 874

             Court of Appeals of Washington, Division 1,

                              Panel One.

                  Harold F. DIEL et ux., Appellants,

                                  v.

                  Hilkeline G. BEEKMAN, Respondent.

                  Hilkeline G. BEEKMAN, Respondent,

                                  v.

                  Harold F. DIEL et ux., Appellants.

                           No. 31—40213—I.
                            Feb. 9, 1970.

** Brief
:PROPERTIES:
:VISIBILITY: all
:END:

*** Issues

*** Holdings

*** History

*** Facts

*** Law

*** Analysis

** Document Details

- [[*West Headnotes (8)][West Headnotes]]
- [[*Attorneys and Law Firms][Attorneys and Law Firms]]
- [[*Opinion][Opinion]]


** Synopsis

Action by residents of property to quiet title. The defendant sought same relief in a separate suit and the two actions were consolidated. The Superior Court, Snohomish County, Phillip Sheridan and Edward M. Nollmeyer, JJ., granted defendant’s motion for summary judgment and on this ground decree was entered quieting title in defendant and the residents appealed. The Court of Appeals, Swanson, J., held that where residents claimed that defendant purchased the land for the benefit of the residents and the $5,000 down payment was actually a loan to the residents from which the defendants agreed to take $5,000 worth of land, sufficient facts were alleged to make a prima facie showing of residents’ right to possession under the doctrine of resulting trust and whether or not leases from defendant to residents constituted the sole agreement between the parties, so as to render residents’ evidence of a resulting trust inadmissible, was factual question that could only be resolved by a trial.

Summary judgment set aside with directions.

Procedural Posture(s): On Appeal; Motion for Summary Judgment.

** West Headnotes (8)

*** [1] Appeal and Error  [[1: 30-k-4096][30-k-4096]]  Briefs and argument in general

- /30 Appeal and Error/
- /30-XVI Review/
- /30-XVI(J) Waiver of Error in Reviewing Court/
- *30-k-4094 Failure to Assert or Adequately Discuss Error*
- *30-k-4096 Briefs and argument in general*
- /(Formerly 30k1078(1))/

Argument advanced to trial court but not argued in brief on review is regarded as abandoned.

- 1 Case that cites this headnote

*** [2] Summary Judgment  [[2: 368H-k-45][368H-k-45]]  Genuine Issue or Dispute as to Material Fact
Summary Judgment-Materials Considered

- /368 HSummary Judgment/
- /368H-III Grounds for Summary Judgment;  Factors Considered/
- *368H-k-42 Absence of Issue of Fact*
- *368H-k-45 Genuine Issue or Dispute as to Material Fact*
- *368H-k-45(1) In general*
- /(Formerly 228k181(2))/
- /368 HSummary Judgment/
- /368H-VI Proceedings/
- /368H-VI(B) Materials Considered/
- *368H-k-301 In general*
- /(Formerly 228k181(2))/

Summary judgment shall be granted only if pleadings, affidavits, deposition and admissions on file show there is no genuine issue as to any material fact.

- 1 Case that cites this headnote

*** [3] Summary Judgment  [[3: 368H-k-49][368H-k-49]]  Viability of Claim or Defense
Summary Judgment-Favoring nonmovant;  disfavoring movant

- /368 HSummary Judgment/
- /368H-III Grounds for Summary Judgment;  Factors Considered/
- *368H-k-49 Viability of Claim or Defense*
- *368H-k-50 In general*
- /(Formerly 228k185(6))/
- /368 HSummary Judgment/
- /368H-IV Ascertaining Whether Fact Issue Exists/
- *368H-k-73 Presumptions and Inferences*
- *368H-k-75 Favoring nonmovant;  disfavoring movant*
- /(Formerly 228k185(2))/

In ruling on motion for summary judgment, court must consider material evidence and all reasonable inferences therefrom most favorable to nonmoving party and, when so considered, if reasonable men might reach different conclusions the motion should be denied.

- 4 Cases that cite this headnote

*** [4] Trusts  [[4: 390-k-62][390-k-62]]  Nature of resulting trust

- /390 Trusts/
- /390-I Creation, Existence, and Validity/
- /390-I(B) Resulting Trusts/
- *390-k-62 Nature of resulting trust*
- /(Formerly 390k2)/

“Resulting trust” is trust implied on law from intentions of parties to a given transaction.

*** [5] Trusts  [[5: 390-k-88][390-k-88]]  Parol evidence

- /390 Trusts/
- /390-I Creation, Existence, and Validity/
- /390-I(B) Resulting Trusts/
- *390-k-85 Evidence to Establish Trust*
- *390-k-88 Parol evidence*

Resulting trust may be established by parol evidence.

*** [6] Evidence Parol or Extrinsic Evidence Affecting Writings

- /157 Evidence/
- /157-XI Parol or Extrinsic Evidence Affecting Writings/
- /157-XI(A) In General/
- *157-k-1881 In general*
- /(Formerly 157k384)/

Parol evidence rule is not one of evidence but of substantive law.

- 7 Cases that cite this headnote

*** [7] Evidence  [[7: 157-k-1904][157-k-1904]]  Merger or integration provisions

- /157 Evidence/
- /157-XI Parol or Extrinsic Evidence Affecting Writings/
- /157-XI(B) Contracts and Agreements in General/
- *157-k-1904 Merger or integration provisions*
- /(Formerly 157k441(1))/

Before parol evidence rule can be applied, court must hear all extrinsic evidence and determine if parties intended that written agreement be complete integration, and if it is complete, written document stands and parol evidence is disregarded, but if integration is not complete, written agreement is replaced or supplemented by preponderate terms of parol agreement.

- 18 Cases that cite this headnote

*** [8] Summary Judgment  [[8: 368H-k-267][368H-k-267]]  Wills, trusts, and estates
Trusts-Questions for jury

- /368 HSummary Judgment/
- /368H-V Particular Cases and Contexts/
- *368H-k-267 Wills, trusts, and estates*
- /(Formerly 228k181(34))/
- /390 Trusts/
- /390-I Creation, Existence, and Validity/
- /390-I(B) Resulting Trusts/
- *390-k-90 Questions for jury*

Where residents claimed that defendant bought land for residents’ benefit and down payment was actually loan to residents, sufficient facts were alleged to make prima facie showing of residents’ right to possession under resulting trust and whether or not leases from defendant to residents constituted sole agreement between parties was factual question to be resolved by trial and case was not ripe for summary judgment. CR 56.

** Attorneys and Law Firms

- <<*875>> <<**213>> Clodfelter, Lindell & Carr, Allen Lane Carr, Seattle, for appellants.
- Black, Christensen & Nielsen, Andrew T. Nielsen, Everett, Rodney Boddington, Sultan, for respondent.

** Opinion

SWANSON, Judge.

Harold F. Diel and his wife brought an action to quiet title to certain real property on which they were residing and farming. The defendant, Hilkeline G. Beekman, in a separate suit sought the same relief for herself. The two actions were consolidated, and the defendant moved for a summary judgment in the Diels’ suit. A summary judgment was granted, and on this ground a decree was entered in the second suit quieting title in Beekman. The Diels appeal and assign error to the entry of the summary judgment dismissing their claim.

The undisputed facts disclose that on February 10, 1953, Arnold Beekman (since deceased) and his wife Hilkeline, the defendant here, contracted to buy certain real property from Phillip and Mary Harder. The down payment of $5,000 came from the Beekmans’ funds. On or about March 4, 1953, the Diels moved onto the property and on that date executed a written 3-year lease of the property. The Diels paid $200 a month to the Beekmans during this 3-year period as required by the lease. On July 30, 1956, the plaintiffs and defendant, Hilkeline Beekman, executed a 5-year lease containing an option to purchase. This lease likewise provided for rent of $200 per month. No written exercise of the option was made.

This second lease proved unsatisfactory; the plaintiffs could not pay the rent. Mrs. Beekman orally agreed to reduce the rent to $150 per month, and the Diels agreed to <<*876>> continue to pay taxes and insurance as they had under the prior lease. Such was the status between the parties at the time this action was commenced.

[1] <<1: 30-k-4096>> In their complaint, plaintiffs allege that the property in question was purchased by the Beekmans in their own name but on behalf of and for the benefit of plaintiffs. Plaintiffs state in their two affidavits that since the execution of the real estate contract between the Harders and the Beekmans, they, the plaintiffs, have made the contract payments, paid real estate taxes and insurance, and made $12,000 worth of improvements on the property. They also claim to have exercised the option contained in the 1953 lease. This latter contention has no merit, for even though an option to purchase real estate can be exercised orally, as in Spake v. Elder, 1 Wash.App. 116, 459 P.2d 820 (1969); Duprey v. Donahoe, 52 Wash.2d 129, 323 P.2d 903 (1958), the only option referred to in plaintiffs’ pleadings as having been exercised was contained in the 1956 lease. Consequently, it could not have been exercised in 1953 as claimed. Plaintiffs advanced this argument to the trial court but failed to argue it in their brief. It is therefore regarded as abandoned.

But, claim the plaintiffs, the facts set forth in the complaint, affidavits, and interrogatories support such legal theories as resulting trust, constructive trust, adverse possession, and laches upon which relief could be granted.

<<**214>> [2] <<2: 368H-k-45>> [3] <<3: 368H-k-49>> We must determine if the alleged facts, viewed most favorably to the plaintiffs, support any one of these theories. To ascertain the propriety of a summary judgment, we observe the following rules set forth in Balise v. Underwood, 62 Wash.2d 195, 199, 381 P.2d 966 (1963):

(2) Summary judgments shall be granted only if the pleadings, affidavits, depositions of admissions on file show there is no genuine issue as to any material fact, and that the moving party is entitled to judgment as a matter of law. * * * (CR 56); Capitol Hill Methodist Church of Seattle v. Seattle, 52 Wash.2d 359, 324 P.2d 1113.

<<*877>> (7) In ruling on a motion for summary judgment, the court must consider the material evidence and all reasonable inferences therefrom most favorably to the nonmoving party and, when so considered, if reasonable men might reach different conclusions the motion should be denied. Wood v. Seattle, 57 Wash.2d 469, 358 P.2d 140.

See Hudesman v. Foley, 73 Wash.2d 880, 441 P.2d 532 (1968).

[4] <<4: 390-k-62>> [5] <<5: 390-k-88>> First, plaintiffs advance the theory of a resulting trust which may be described generally as a trust implied in law from the intentions of the parties to a given transaction. Justice Weaver, speaking for our Supreme Court in Donaldson v. Greenwood, 40 Wash.2d 238, 249, 242 P.2d 1038 (1952), succinctly described the relationship in these words:

When title to property is taken in the name of a grantee other than the person advancing the consideration, the one in whose name title is taken is a resulting trustee for the person who paid the purchase price, in the absence of evidence of a contrary intent. (Citations.)

A resulting trust could arise under the facts of this case sub judice, if, pursuant to an oral agreement, the defendants loaned the plaintiffs the money to purchase the land to which defendants took title and providing this additional element is present:

(T)he principal must have paid over his money at or before the execution of the conveyance from the vendor to the agent, or * * * the principal (must) incur, at that time, an absolute obligation to pay as part of the original consideration of the purchase. The trust can not be created by an advance of the purchase money after the purchase has been made by the other with his own funds or on his own credit.

Carkonen v. Alberts, 196 Wash. 575, 578, 83 P.2d 899, 901, 135 A.L.R. 209 (1938). However, a resulting trust may be established by parol evidence. In re Spadoni’s Estate, 71 Wash.2d 820, 430 P.2d 965 (1967).

To support their theory, plaintiffs state in their affidavit that the defendant and her husband purchased the property <<*878>> on February 10, 1953, for the benefit of the plaintiffs. Then follow the specifics which we must view most favorably to the plaintiffs. Balise v. Underwood, Supra. The down payment is claimed to be a loan for which the Beekmans agreed to take $5,000 worth of land, the remainder of the property to go to the plaintiffs, since they were to make the contract payments. The plaintiffs state they moved onto the land about March 1, 1953, and thereafter made the contract payments through the Beekmans. Three years after the death of her husband, defendant Beekman is said to have agreed to take 12 acres of land as settlement for the $5,000 loan. It is also claimed that defendant made statements and admissions that the property belonged to the plaintiffs and that the leases were only an accommodation to enable plaintiffs to secure government loans. That the written leases were not intended to be leases, say the plaintiffs, in shown by the fact that they made $12,000 worth of capital <<**215>> improvements on the property with the knowledge of the defendant, and that the rent reduction in 1956 was consistent with the purchase contract.

[6] The defendant, in her answer and affidavit, makes contrary assertions of fact. She claims that the down payment for the land, as well as the contract payments, came from the defendant’s community funds. She says the plaintiffs leased the property on March 4, 1953, and again on July 30, 1956, such second lease terminating when the plaintiffs no longer paid the $200 monthly rent. These leases are claimed by the defendant to be the entire agreement between the parties. It is defendant Beekman’s contention, and the basis for the trial court’s ruling, that plaintiffs are seeking to substitute a prior oral contract for the written lease which is not permitted by the parol evidence rule. Defendant argues that one may not vary or contradict the terms of a written agreement by showing prior parol evidence without proof of fraud or mistake. This is just what the plaintiffs seek to do, Beekman says, in attempting to prove a resulting trust by parole evidence. It must be conceded that Beekman’s statement of the parol <<*879>> evidence rule is correct, but only is it correct so far as it goes; that is, the legal basis for the parol evidence rule is the theory of integration. A writing Intended to supersede earlier and contemporaneous expressions is given that effect. This does not mean, however, that simply because there is a written agreement, other evidence will not be considered as a preliminary matter. Defendant’s counsel has correctly asserted that the parol evidence rule is not one of evidence but of substantive law. That being so, it ought not be applied as a rule of evidence. In Barber v. Rochester, 52 Wash.2d 691, 697, 328 P.2d 711 (1958), Justice Foster, speaking for the court, discussed the rule and stated:

The trial court here, however, erroneously applied it (parol evidence rule) as an exclusionary rule of evidence. From an examination of the executory contract for the sale of the real property, the chattel mortgage covering the personal property, and the separate written agreement respecting the new-carsales, the trial court erroneously excluded the offered evidence which had, for its purpose, proof that the three writings did not embrace the entire agreement between the parties. Corbin states the correct rule in the following paragraph:

‘In determining these issues, or any one of them, there is no ‘parol evidence rule’ to be applied. On these issues, no relevant evidence, whether parol or otherwise, is excluded. No written document is sufficient, standing alone, to determine any one of them, however long and detailed it may be, however formal, and however many may be the seals and signatures and assertions. No one of these issues can be determined by mere inspection of the written document.’ 3 Corbin on Contracts 215, 216, s 573.

[7] <<7: 157-k-1904>> Here, as in Barber v. Rochester, Supra, defendant persuaded the trial court to regard plaintiffs’ parol evidence of a resulting trust to be inadmissible. Consequently, the trial court ruled that plaintiffs’ claim was not supported by legally admissible facts, and therefore, no material issue of fact existed. Whether the lease was the sole agreement is the question of fact. As was stated in Barber v. Rochester, Supra at 698, 328 P.2d at 715:

<<*880>> People have the right to make their agreements partly oral and partly in writing, or entirely oral or entirely in writing; and it is the court’s duty to ascertain from all relevant, extrinsic evidence, either oral or written, whether the entire agreement has been incorporated in the writing or not. That is a question of fact.

Thus, before the parol evidence rule can be applied, the court must hear all extrinsic evidence and determine if the parties Intended that the written agreement be the <<**216>> complete integration. If the integration is complete, the written document stands and the parol evidence is disregarded. If the integration is not complete, the written agreement is replaced or supplemented by the preponderate terms of the parol agreement. Barber v. Rochester, Supra; Dawson v. Shearer, 53 Wash.2d 766, 337 P.2d 46 (1959); Becker v. Lagerquist Bros., Inc., 55 Wash.2d 425, 348 P.2d 423 (1960); Kinne v. Lampson, 58 Wash.2d 563, 364 P.2d 510 (1961); University Properties, Inc. v. Moss, 63 Wash.2d 619, 388 P.2d 543 (1964); Dix Steel Co. v. Miles Constr., Inc., 74 Wash.2d 114, 443 P.2d 532 (1968); Black v. Evergreen Land Developers, Inc., 75 Wash.Dec.2d 251, 450 P.2d 470 (1969); R. Meisenholder, Evidence Law & Practice s 121 (1965).

At this juncture, we observe parenthetically that when this argument was presented to the trial court, the able and experienced trial judge continued the hearing on the motion to permit plaintiffs’ counsel to furnish legal authorities. The record indicates none were furnished.

[8] <<8: 368H-k-267>> Despite the unusual nature of the transaction as described by plaintiffs, sufficient facts are alleged to make a prima facie showing of a right to possession under the doctrine of resulting trust. Whether or not the leases constitute the sole agreement between the parties, so as to render plaintiffs’ parol evidence of a resulting trust inadmissible, is a factual question that can only be resolved by a trial[fn:1] or further proceedings pursuant to CR 56.

[fn:1] As stated in Bartlett v. Northern Pac. Ry., 74 Wash.2d 881, 883, 447 P.2d 735 (1968),

We would in no way derogate from the summary judgment as a proper and valuable instrument for preventing useless trials; but it should not be used. as in the present case, where a real doubt exists as to decisive factual issues.

<<*881>> The summary judgment appealed from is set aside with directions to proceed as though it had been denied.

JAMES, C.J., and FARRIS, J., concur.

** End
#+STARTUP: show2levels
