#+title:      OTR v. Flakey Jake’s, Inc., 112 Wn.2d 243, 770 P.2d 629 (1989)
#+date:       [1989-04-06 Thu 00:00]
#+filetags:   :assignment:case:law:lease:sublease:
#+identifier: 19890406T000000
#+signature:  sc

* OTR v. Flakey Jake’s, Inc. -- Supreme Court of Washington, En Banc. | April 6, 1989 | 112 Wash.2d 243 | 770 P.2d 629

- Washington Citation :: OTR v. Flakey Jake’s, Inc., 112 Wn.2d 243, 770 P.2d 629 (1989)
- All Citations :: 112 Wash.2d 243, 770 P.2d 629


                           112 Wash.2d 243

                     Supreme Court of Washington,

                               En Banc.

            OTR, an Ohio general partnership, Petitioner,

                                  v.

       FLAKEY JAKE’S, INC., a Delaware corporation, Defendant,

Martin Selig and Andrea Selig, individually and the marital community composed thereof, Respondents.

                             No. 54898–6.
                            April 6, 1989.

** Brief
:PROPERTIES:
:VISIBILITY: all
:END:

*** Issues

An Issue

*** Holdings

*** History

*** Facts

*** Law

*** Analysis

** Document Details

- [[*West Headnotes (5)][West Headnotes]]
- [[*Attorneys and Law Firms][Attorneys and Law Firms]]
- [[*Opinion][Opinion]]


** Synopsis

Lessor of commercial premises brought action for unlawful detainer against original lessee and assignee. The Superior Court, King County, Jack P. Scholfield, J., entered judgment against original lessee and dismissed action against assignee. The Court of Appeals affirmed on alternative grounds, and lessor petitioned for review. The Supreme Court, Pearson, J., held that: (1) assignee could not object to lessor’s failure to provide written consent to assignment, and (2) assignee’s subsequent subleasing of premises back to original lessee did not terminate assignee’s unlawful detainer liability.

Reversed and remanded.

** West Headnotes (5)

*** [1] Landlord and Tenant  [[1: 233-k-732][233-k-732]]  Consent of Lessor, and Waiver Thereof

- /233 Landlord and Tenant/
- /233-IV Particular Kinds of Tenancies and Attributes Thereof/
- /233-IV(B) Assignment and Subletting/
- /233-IV(B)2 Restrictions as to Assignment or Subletting/
- *233-k-732 Consent of Lessor, and Waiver Thereof*
- *233-k-733 In general*
- /(Formerly 233k76(3))/

Failure to obtain written consent to assignment of lease, if required under terms of lease, did not void assignment, but merely rendered assignment voidable at option of lessor.

- 8 Cases that cite this headnote

*** [2] Landlord and Tenant  [[2: 233-k-732][233-k-732]]  Consent of Lessor, and Waiver Thereof

- /233 Landlord and Tenant/
- /233-IV Particular Kinds of Tenancies and Attributes Thereof/
- /233-IV(B) Assignment and Subletting/
- /233-IV(B)2 Restrictions as to Assignment or Subletting/
- *233-k-732 Consent of Lessor, and Waiver Thereof*
- *233-k-733 In general*
- /(Formerly 233k76(3))/

Assignee of lease could not object to original lessor’s failure to provide written consent to assignment; restrictive covenant in lease being for lessor, only lessor was in position to challenge validity of assignment.

- 5 Cases that cite this headnote

*** [3] Landlord and Tenant  [[3: 233-k-1505][233-k-1505]]  Liability of lessee after assignment
Landlord and Tenant-Reassignment
Landlord and Tenant-Subletting

- /233 Landlord and Tenant/
- /233-VII Rent/
- /233-VII(A) Rights and Liabilities/
- /233-VII(A)6 Persons Liable/
- *233-k-1503 Transfer of Lease or Agreement*
- *233-k-1505 Liability of lessee after assignment*
- /(Formerly 233k80(2), 233k79(3))/
- /233 Landlord and Tenant/
- /233-VII Rent/
- /233-VII(A) Rights and Liabilities/
- /233-VII(A)6 Persons Liable/
- *233-k-1503 Transfer of Lease or Agreement*
- *233-k-1509 Reassignment*
- /(Formerly 233k80(2))/
- /233 Landlord and Tenant/
- /233-VII Rent/
- /233-VII(A) Rights and Liabilities/
- /233-VII(A)6 Persons Liable/
- *233-k-1511 Subletting*
- /(Formerly 233k79(3), 233k80(2))/

Contractually, neither act of subletting nor assigning absolves assignee/subsequent assignor of his express duty to pay rent to his landlord, absent release by landlord; where there is express covenant to pay rent in lease, assignee/subsequent assignor remains liable for that rent under privity of contract theory, even where landlord consents to assignment.

- 6 Cases that cite this headnote

*** [4] Landlord and Tenant  [[4: 233-k-772][233-k-772]]  Rights and liabilities of assignor
Landlord and Tenant-Liability of sublessor to landlord

- /233 Landlord and Tenant/
- /233-IV Particular Kinds of Tenancies and Attributes Thereof/
- /233-IV(B) Assignment and Subletting/
- /233-IV(B)5 Construction and Operation of Assignments/
- *233-k-772 Rights and liabilities of assignor*
- /(Formerly 233k80(1))/
- /233 Landlord and Tenant/
- /233-IV Particular Kinds of Tenancies and Attributes Thereof/
- /233-IV(B) Assignment and Subletting/
- /233-IV(B)6 Construction and Operation of Subleases/
- *233-k-792 Liability of sublessor to landlord*
- /(Formerly 233k80(1))/

If assignee’s successive conveyance is but subletting, assignee/subsequent assignor remains liable as tenant/sublandlord under privity of estate theory.

- 3 Cases that cite this headnote

*** [5] Landlord and Tenant  [[5: 233-k-771][233-k-771]]  Rights and liabilities of assignee
Landlord and Tenant-Liability of sublessor to landlord

- /233 Landlord and Tenant/
- /233-IV Particular Kinds of Tenancies and Attributes Thereof/
- /233-IV(B) Assignment and Subletting/
- /233-IV(B)5 Construction and Operation of Assignments/
- *233-k-771 Rights and liabilities of assignee*
- /(Formerly 233k80(1))/
- /233 Landlord and Tenant/
- /233-IV Particular Kinds of Tenancies and Attributes Thereof/
- /233-IV(B) Assignment and Subletting/
- /233-IV(B)6 Construction and Operation of Subleases/
- *233-k-792 Liability of sublessor to landlord*
- /(Formerly 233k80(1))/

Suspension agreement purporting to revoke lease assignment, if effective, amounted merely to subsequent subleasing of premises back to original lessee by assignee/sublandlord, which did not terminate privity of estate between assignee/sublandlord and original lessor, or thereby terminate any unlawful detainer liability. West’s RCWA 59.12.030.

- 2 Cases that cite this headnote

** Attorneys and Law Firms

- <<**629>> <<*244>> Bogle & Gates, Ronald T. Schaps, Robert F. Bakemeier, Michael P. Mirande, Seattle, for petitioner.
- Cairncross, Ragen & Hempelmann, John W. Hempelmann, Sylvester, Ruud, Petrie & <<**630>> Cruzen, Sherrie Bennett Campiche, Seattle, for respondents.

** Opinion

PEARSON, Justice.

This action involves statutory unlawful detainer liability for the possession of commercial office space (the premises) owned by OTR. We are asked whether an assignee of a lease may object to the original lessor’s failure to provide written consent to the assignment, and whether a subsequent subleasing of the premises back to the original lessee by the assignee/sublandlord terminates privity of estate between the assignee/sublandlord and the original lessor, and thus terminates unlawful detainer liability.

FACTS

On March 1, 1984, OTR’s predecessor leased a portion of the premises to Flakey Jake’s for a 3–year term. Through a series of subsequent amendments to that lease (OTR lease), and through other agreements to assign portions of the premises, the OTR lease ultimately concerned approximately 14,800 square feet and contained a covenant to pay <<*245>> rent in the sum of approximately $18,000.00 per month due on the first day of each calendar month.

The OTR lease placed restrictions on the tenant’s ability to assign or sublet:

Tenant shall not assign this Lease nor sublet the whole or any part of the Premises without first obtaining Landlord’s consent, which shall not be unreasonably withheld.

In addition, the OTR lease required that amendments or modifications to the lease were to be “only in writing signed by both parties.” It further provided for the payment of reasonable attorney fees to the successful party in any action brought arising out of the lease.

On January 27, 1985, Flakey Jake’s, as assignor, and Martin Selig, as assignee, entered into an “Agreement to Assign” (Flakey Jake assignment). Pursuant to that agreement, Selig assumed “all rights, duties, and liabilities” of Flakey Jake’s under the OTR lease. While Selig and Flakey Jake’s fully executed the Flakey Jake assignment, OTR did not provide its written consent. Nevertheless, OTR recognized Selig as the assignee of the OTR lease, accepted rental payments from Selig for the full amount due on the premises for each of the months of February through December 1985, and instructed its property manager to treat Selig as assignee of the OTR lease.

Selig, too, engaged in conduct confirming his position as assignee of the OTR lease. On February 28, 1985, Selig entered into either a sublease or partial assignment agreement (the record does not reveal the length of the term) with FirstWest Mortgage Corporation (FirstWest) for a portion of the premises. Accordingly, from March 4, 1985, to March 1, 1986, Selig accepted rent payment under that sublease from FirstWest. Selig also informed OTR’s agent that he was the assignee of the OTR lease, and Selig maintained his own signs at the premises advertising available space as recently as June 10, 1986.

The record reflects that in the winter of 1985, faced with serious financial difficulty, Flakey Jake’s informed OTR <<*246>> that should Flakey Jake’s be so called upon, it would be unable to make any payments pursuant to the OTR lease beginning January 1986. As a result of Flakey Jake’s financial difficulty, Selig contends that on December 16, 1985 Flakey Jake’s offered to restore possession of the premises in OTR as part of a settlement agreement. OTR, however, contends that no such discussion concerning possession of the premises occurred. On January 1, 1986, the first default in rent occurred.

The record further reveals that on January 31, 1986 Selig signed a suspension agreement that purportedly cancelled all of his obligations under the Flakey Jake assignment retroactively from December 1, 1985 for a period of 12 months. An agent of Flakey Jake’s signed the suspension agreement on February 18, 1986. Since the term of the OTR lease ran through February 1987, if effective, the suspension agreement between Selig and Flakey Jake’s resulted in a 3–month reversion in Selig commencing December 1, 1986. OTR <<**631>> was not informed of the existence of the suspension agreement until after the commencement of this action and has never consented to the agreement.

On May 15, 1986, OTR filed this action for unlawful detainer against Flakey Jake’s and Selig. OTR prayed for restitution of the premises and for judgment in the amount of rent in default for the months of January through May 1986, including double damages under RCW 59.12.170. Subsequently, the trial court ordered that a writ of restitution be issued restoring possession of the premises in OTR, and that judgment be entered against Flakey Jake’s in favor of OTR. In addition, the trial court dismissed the action against Selig, holding that the Flakey Jake assignment was not effective as between Selig and OTR, and that even if it had been, Selig had made an effective reassignment back to Flakey Jake’s prior to any default in rent. The trial court directed that judgment be entered against OTR in favor of Selig for costs and reasonable attorney fees in the amount of $8,488.37.

<<*247>> The Court of Appeals affirmed on alternative grounds, holding that the suspension agreement effectively terminated any possible landlord/tenant relationship between Selig and OTR at the time of the unlawful detainer action. Additionally, the court affirmed the award of attorney fees to Selig and awarded further attorney fees incurred by Selig on appeal in the amount of $10,000.

ANALYSIS

The unlawful detainer statute provides in part:

A tenant of real property for a term less than life is guilty of unlawful detainer ...

(3) When he continues in possession in person or by subtenant after a default in the payment of rent, and after notice in writing requiring in the alternative the payment of the rent or the surrender of the detained premises ...

RCW 59.12.030. The issue in this case is, therefore: Was Selig a tenant in possession in person or by subtenant after the default in rent occurred? As stated, the trial court held the Flakey Jake assignment to Selig was not valid to bind Selig to OTR, despite Selig’s signed acceptance of “all rights, duties, and liabilities” under the OTR lease, because OTR did not consent to the assignment in writing. This ruling was in error.

[1] <<1: 233-k-732>> [2] <<2: 233-k-732>> We have long recognized that an assignment of a lease occurs when the lessee/assignor transfers his or her whole interest in the lease without retaining any reversionary interest. Morrison v. Nelson, 38 Wash.2d 649, 657, 231 P.2d 335 (1951). Assuming, arguendo, that the terms of the OTR lease required OTR’s written consent to any assignment, failure to obtain written consent did not void the assignment, but merely rendered the assignment voidable at the option of the lessor, OTR. Morrison v. Nelson, supra; Sequin v. Plano, 160 Wash. 421, 295 P. 179 (1931). As we have previously held, “the invalidity of an assignment, on the ground that it has not been assented to by the lessor, can be raised only by the lessor.” Morrison, 38 Wash. at 659, 231 P.2d 335. <<*248>> The benefit of the restrictive covenant being for the lessor, only OTR was in a position to challenge the validity of the Flakey Jake assignment.

The law in Washington is in accord with other jurisdictions:

Restrictions against assignment or subletting imposed by the terms of the lease are intended for the benefit of the lessor [OTR’s predecessors] rather than the lessee, and likewise benefit the lessor’s assigns [OTR]; and if neither of these objects to a breach of the restriction no one else may do so. One to whom the term has been assigned [Selig] in breach of the restriction cannot set up the breach in defense of an action brought against him by the lessor on the lease or in defense of an action brought against him by the lessee [Flakey Jake’s] on obligations incident to the assignment.

(Footnotes omitted. Italics ours.) 51C C.J.S. Landlord & Tenant § 33c (1968).

<<**632>> In fact, having accepted rent for a period of 11 months from Selig, were the situation now reversed, and were OTR attempting at this point to deny its validity and thereby void the Flakey Jake assignment, it would most likely be estopped to do so. D’Ambrosio v. Nardone, 72 Wash. 172, 129 P. 1092 (1913); Field v. Copping, Agnew & Scales, 65 Wash. 359, 118 P. 329 (1911). Upon learning of the assignment, OTR had the option to declare a forfeiture or to recognize Selig as its tenant. However, after learning of the assignment and accepting the benefits of the assignment, OTR would not have been allowed to deny its validity:

As soon as they accepted rent in advance from the assignees, with full knowledge of all the facts, the right to declare a forfeiture was waived as fully and completely as by the written consent provided for in the lease itself.

Batley v. Dewalt, 56 Wash. 431, 433, 105 P. 1029 (1909).

Selig accepted the benefits of the assignment by pocketing his sublessee’s rent payments. He may not now rely upon a covenant, one that exists solely for the benefit of his landlord, to deny the validity of the assignment when the deal is no longer as profitable as he might have wished. <<*249>> Having accepted the benefits of the lease, he may not now cast aside his obligations. Had this become a profitable leasehold, would he so quickly seek to avoid the assignment?

Through the valid assignment which resulted in a conveyance, Selig came into privity of estate with OTR. Through his signed acceptance of all duties and liabilities of the OTR lease, Selig is further liable through privity of contract. What then is the effect of the suspension agreement executed by Selig and Flakey Jake’s? The Court of Appeals held the suspension agreement effectively reassigned the lease and thereby terminated Selig’s liability. This ruling was in error, as well.

The suspension agreement purported to revoke the Flakey Jake assignment for a 1–year term. If effective, the result was to create a 3–month reversion in Selig. As a result, even if effective, the suspension agreement did not effect a reassignment, but rather, merely a sublease. McDuffie v. Noonan, 176 Wash. 436, 29 P.2d 684 (1934); Sheridan v. O.E. Doherty, Inc., 106 Wash. 561, 181 P. 16 (1919). The Court of Appeals incorrectly chose to disregard the distinction between a sublease and an assignment. In this case, the character of the conveyance, in fact, determines the issue of liability. This, indeed, is as the law should be. The distinction between an assignment and a sublease is not merely form. Rather, distinct legal benefits inure, depending upon the nature of the conveyance. One example in an assignment/subsequent-sublease setting is the continued landlord/tenant relationship between the lessee/subsequent-sublandlord and the original lessor. A lessee/subsequent-assignor would maintain no such position.

The sublease between Selig and Flakey Jake’s was similar to the Flakey Jake assignment in that it was without the written consent of OTR; but unlike the assignment, it occurred without OTR’s knowledge, and thus without OTR’s acquiescence. This issue, however, simply has no bearing on the resolution of the case. Nevertheless, relying <<*250>> on Coulos v. Desimone, 34 Wash.2d 87, 208 P.2d 105 (1949), Selig appears to argue that the sublease is a valid assignment since no consent is necessary for a reassignment back to an original lessee; and thus, he argues, he should escape liability. As will be seen in the following analysis, such an argument not only fails to distinguish between an assignment and a sublease, but it wholly misses the mark with respect to liability.

[3] <<3: 233-k-1505>> Contractually, neither the act of subletting nor assigning absolves the assignee/subsequent-assignor of his express duty to pay rent to his landlord, absent a release by the landlord. Cobb Healy Inv. Co. v. Tall, 181 Wash. 300, 42 P.2d 1107 (1935). As a result, whether the sublease back to Flakey Jake’s was effective has no bearing on Selig’s contractual liability. This long-standing Washington rule is in accord with the Restatement:

<<**633>> (1) A transferor of an interest in leased property, who immediately before the transfer is obligated to perform an express promise contained in the lease that touches and concerns the transferred interest, continues to be obligated after the transfer if:

(a) the obligation rests on privity of contract, and he is not relieved of the obligation by the person entitled to enforce it ...

Restatement (Second) of Property § 1611)(a) (1977). Where there is an express covenant to pay rent in the lease, the assignee/subsequent-assignor remains liable for that rent under privity of contract theory, even where the landlord consents to the assignment. Puget Mill Co. v. Kerry, 183 Wash. 542, 49 P.2d 57 (1935) (overruling Harvard Inv. Co. v. Smith, 66 Wash. 429, 119 P. 864 (1912)); Johnson v. Goddard, 179 Wash. 493, 38 P.2d 208 (1934); Huston v. Graham, 169 Wash. 521, 14 P.2d 44 (1932);  <<*251>> DeLano v. Tennent, 138 Wash. 39, 244 P. 273 (1926); Johnson v. Norman, 98 Wash. 331, 167 P. 923 (1917)[fn:1]

[fn:1] We do not cite Tibbals v. Iffland, 10 Wash. 451, 39 P. 102 (1895) as support because the fact statement in that opinion is unclear. The opinion does not disclose whether the assignee/subsequent-assignor, Iffland, separately covenanted to pay rent. While Harvard Inv. Co. v. Smith, 66 Wash. 429, 119 P. 864 (1912) claims Tibbals supports its position, that is true only if Iffland actually covenanted to pay rent. If in fact Iffland did so covenant, Tibbals should have been overruled along with Harvard Inv. Co. However, other authorities have subsequently cited Tibbals for the proposition that an assignee/subsequent-assignor, such as Iffland, who does not separately covenant to pay rent, is not liable for rent following his subsequent assignment. Puget Mill Co. v. Kerry, 183 Wash. 542, 49 P.2d 57 (1935); Stoebuck, Law Between Landlord and Tenant in Washington: Part II, 49 Wash.L.Rev. 1013, 1057 n. 636 (1974). If these authorities have properly divined the facts in Tibbals, then it continues to be good law and supports our position today.

[4] <<4: 233-k-772>> [5] <<5: 233-k-771>> Furthermore, in addition to contractual liability, it follows from this analysis and the preceding authorities that if the successive conveyance is but a subletting, the assignee/subsequent-sublessor remains liable as tenant/sublandlord under a privity of estate theory as well. For purposes of this unlawful detainer action, this is the liability with which we are presently concerned. See also Brickum Inv. Co. v. Vernham Corp., 46 Wash.App. 517, 731 P.2d 533 (1987). If effective, the suspension agreement still resulted in a 3–month reversion in Selig. Therefore, at no time was the landlord/tenant relationship between OTR and Selig altered by the suspension agreement. Again, if the suspension agreement was valid, and assuming there was no tender of possession, Selig was in possession by subtenant when a default in rent occurred.

In purely theoretical terms (probably with little practical application), but perhaps helpful toward a thorough understanding of the present analysis, were there no express covenant to pay rent in the original lease, an assignee incurs liability for rent only while in possession of the premises, and such liability is based solely upon privity of estate. Seattle Lodge 211, Loyal Order of Moose v. Par–T–Pak Beverage Co., 55 Wash.2d 587, 349 P.2d 229 (1960). In such a situation, an assignment would release the assignor from <<*252>> any obligation to pay rent because it would terminate all privity of estate. National Bank of Commerce v. Dunn, 194 Wash. 472, 78 P.2d 535 (1938); Restatement (Second) of Property § 16.1 Comment e (1977). A subletting, on the other hand, would not, since privity of estate would still exist. Thus, had Selig not separately undertaken the obligations of the covenants in the lease, a successful reassignment, had one occurred, would have relieved him of all liability to OTR, there being no privity of estate nor privity of contract. Such, however, is not the case.[fn:2]

[fn:2] To further ponder the academic merits of the situation, were Selig not bound by privity of contract, and had his “suspension agreement” resulted in a true assignment, releasing him from liability at least through privity of estate, the question would then arise whether the assignment was merely “colorable”. In essence, the question would be whether his actions were merely a concealed attempt to avoid the burdens of the leasehold estate, while endeavoring to retain the “benefits derived from the use of the property.” National Bank of Commerce v. Dunn, 194 Wash. 472, 498, 78 P.2d 535 (1938). Due to Selig’s express covenant to pay rent, however, and his failure to effect a true assignment, we need not answer these questions.

<<**634>> As a result, assuming the best case scenario from Selig’s perspective, even if the suspension agreement is valid, it merely effected a valid sublet; thus, Selig remains liable through privity of estate. A factual question still exists, however, as to whether possession of the premises was ever tendered, thereby extinguishing privity of estate.

Accordingly, the Court of Appeals is reversed. The case is remanded for a factual determination of whether a tender of possession occurred. Upon remand, the case may properly continue in line with this opinion and our opinion in Munden v. Hazelrigg, 105 Wash.2d 39, 711 P.2d 295 (1985). The award of attorney fees to Selig by the trial court and Court of Appeals is reversed. Upon remand, pursuant to RAP 18.1, the trial court is instructed to award appropriate <<*253>> and reasonable attorney fees to the prevailing party pursuant to RCW 4.84.330 and article 25 of the OTR lease.

CALLOW, C.J., and UTTER, ANDERSEN, BRACHTENBACH, DORE, DOLLIVER and DURHAM, JJ., concur.

** End
#+STARTUP: show2levels
