#+title:      114 F.3d 115 (1997) Radecki v. Joura
#+date:       [1997-06-03 Tue 15:36]
#+filetags:   :accommodation:eviction:reasonable:right:ud:
#+identifier: 19970603T153650
#+signature:  fcoa8

* Case

RADECKI v. JOURA
United States Court of Appeals,Eighth Circuit.
Dr. Tadeusz RADECKI, Appellant, v. James JOURA;  Carol Joura, Appellees.

No. 95-4091.
Decided: June 03, 1997
Before HANSEN, MORRIS SHEPPARD ARNOLD, and MURPHY, Circuit Judges.
David R. Buntain, Lincoln, NE, for appellee. Appellant, pro se.
Tadeusz Radecki appeals from the district court's order granting defendants summary judgment on his federal housing-discrimination claim, and dismissing without prejudice his four related state law claims.   We reverse.

Radecki filed this complaint under 42 U.S.C. § 3604(f)(1) of the Fair Housing Act (FHA), claiming that defendants James and Carol Joura evicted him from his apartment because of his handicap.   Radecki alleged, inter alia, that he was a tenant in an apartment building defendants owned;  that he had a “handicap” under 42 U.S.C. § 3602(h), as he suffered from depression substantially limiting one or more of his major life activities;  that on August 13, 1993, he informed defendants he was “suffering from a long-term disability and requested a reasonable period of accommodation to prepare for” scheduled repairs and pest extermination in his apartment;  that defendants sent him a letter dated August 16 notifying him “he would have to permanently vacate the apartment”;  and that he was forcibly evicted therefrom pursuant to a state court writ of restitution.   Radecki also asserted four state law claims based upon his eviction.

Defendants moved for summary judgment.   In a supporting affidavit, Carol Joura attested, inter alia, that she and her husband took possession of Radecki's apartment building on July 1, 1993;  that Radecki was a month-to-month tenant;  that Radecki informed them on August 7 or 8 that he was “ill,” but “never told [them] that he was suffering from a disability or handicap or that he was requesting any accommodation [from them]”;  that, because of their difficulties in getting Radecki's cooperation and their need to eliminate cockroaches and mice in the apartment for the benefit of all their tenants, they sent Radecki a notice on August 16 to vacate the apartment by September 30;  that they first became aware of Radecki's claim of disability discrimination when their attorney told them about it after they had given Radecki the notice to vacate;  and that they obtained a restitution order on November 22, and Radecki was forcibly evicted on December 16.

Defendants subsequently submitted the transcript of Radecki's deposition;  his testimony included the following statements.   He told defendants he needed time to prepare for the extermination and repairs;  and on August 14, he specifically told them he was “ill,” he “need[ed] some more time because of [his] illness,” and it was a “long term illness.”   Radecki explicitly told defendants he had a disability on September 1;  he and his attorney told their attorney of his disability at some point after he received the notice to vacate.   Radecki told defendants “on September 1 and subsequently” that he was quite ill and wanted to stay in his apartment beyond September 30;  he filed complaints with HUD and the Nebraska Equal Opportunity Commission in an attempt to stop the eviction;  and in his October 27 HUD charge, he stated he was “being harassed to move because of [his] handicap.”

The district court granted defendants' motion for summary judgment on the FHA claim, finding as undisputed facts that Radecki had informed defendants twice before August 16 that he was “ill” and “it was long term,” but had not mentioned the nature of his illness;  and that Radecki asserted he or his attorney told defendants of his disability sometime after August 16.   Applying the framework of McDonnell Douglas Corp. v. Green, 411 U.S. 792, 93 S.Ct. 1817, 36 L.Ed.2d 668 (1973), the court set forth the following prima facie case which Radecki had the burden of proving:  a) he was a member of a class protected under the FHA;  b) defendants were aware of Radecki's membership in that class;  c) Radecki was willing and qualified to continue renting his apartment;  and d) defendants refused to permit Radecki to continue to rent the apartment.   After noting defendants did not dispute, for purposes of their motion, that Radecki suffered from clinical depression and thus had a “handicap” within the meaning of the FHA, the court concluded Radecki had failed to show the essential element that defendants knew of his handicap before sending him the eviction notice on August 16;  and, therefore, defendants were entitled to judgment as a matter of law.   The court also dismissed without prejudice Radecki's state law claims.   Radecki timely appealed.

 We review a grant of summary judgment de novo, applying the same standard as the district court.   See Miller v. National Cas. Co., 61 F.3d 627, 628 (8th Cir.1995).   As the McDonnell Douglas framework applies to FHA claims, see United States v. Badgett, 976 F.2d 1176, 1178 (8th Cir.1992), Radecki initially had to prove a prima facie case of discrimination by a preponderance of the evidence, see id.

 We hold the district court erred in limiting its “knowledge” inquiry to the date defendants sent Radecki the eviction notice (August 16).   In assessing whether and when defendants knew of Radecki's handicap, the court should have considered the date Radecki was actually evicted (December 16), as the FHA provides that unlawful discrimination occurs when a dwelling is “den [ied]” to a renter because of that renter's handicap.   See 42 U.S.C. § 3604(f)(1)(A);  see generally Trafficante v. Metropolitan Life Ins. Co., 409 U.S. 205, 211-12, 93 S.Ct. 364, 367-68, 34 L.Ed.2d 415 (1972) (FHA must be given “generous construction” to carry out “ ‘policy that Congress consider[s] to be of the highest priority’ ” (quoted source omitted));  Havens Realty Corp. v. Coleman, 455 U.S. 363, 380, 102 S.Ct. 1114, 1125, 71 L.Ed.2d 214 (1982) (FHA has broad, remedial purpose).   Consequently, we believe that Radecki's deposition testimony and Carol Joura's affidavit created a genuine issue of material fact as to the knowledge element:  Carol Joura attested defendants were informed of Radecki's discrimination claim after August 16;  and Radecki testified he explicitly told defendants he had a disability on September 1, he or his attorney told defendants of his handicap sometime after August 16, and his October 27 HUD charge indicated that defendants were harassing him to move because of his handicap.   Thus, summary judgment was improper.

On remand, the district court should also consider whether defendants discriminated against Radecki by refusing to accommodate his handicap.   See 42 U.S.C. § 3604(f)(3)(B) (discrimination under FHA occurs by “a refusal to make reasonable accommodations ․ when such accommodations may be necessary to afford such person equal opportunity to use and enjoy a dwelling”);  United States v. California Mobile Home Park Management Co., 29 F.3d 1413, 1416 (9th Cir.1994) (FHA imposes affirmative duty upon landlords to make reasonable accommodations for handicapped persons);  H.R.Rep. No. 100-711, at 28-29 (1988), reprinted in 1988 U.S.C.C.A.N. 2173, 2189-90 (courts should apply standard articulated in School Bd. of Nassau County v. Arline, 480 U.S. 273, 107 S.Ct. 1123, 94 L.Ed.2d 307 (1987), to determine whether FHA requires accommodations;  although tenancy may be denied if individual poses direct threat and significant risk of harm to health and safety of others, “[i]f a reasonable accommodation could eliminate the risk, entities covered under [the FHA] are required to engage in such accommodation”).

Accordingly, we reverse and remand for further proceedings consistent with this opinion.

PER CURIAM.
