#+title:      Port of Longview v. Int’l Raw Materials, Ltd., 96 Wn. App. 431, 979 P.2d 917 (1999)
#+date:       [1999-07-09 Fri 00:00]
#+filetags:   :case:commercial:defense:equitable:law:ud:
#+identifier: 19990709T000000
#+signature:  coa=div2

* Port of Longview v. International Raw Materials, Ltd. -- Court of Appeals of Washington, Division 2. | July 9, 1999 | 96 Wash.App. 431 | 979 P.2d 917

- Washington Citation :: Port of Longview v. Int’l Raw Materials, Ltd., 96 Wn. App. 431, 979 P.2d 917 (1999)
- All Citations :: 96 Wash.App. 431, 979 P.2d 917


                           96 Wash.App. 431

                   Court of Appeals of Washington,

                             Division 2.

              PORT OF LONGVIEW, Washington, Respondent,

                                  v.

            INTERNATIONAL RAW MATERIALS, LTD., Appellant.

                           No. 23546–3–II.
                            July 9, 1999.
** Brief

** Document Details

- [[*West Headnotes (21)][West Headnotes]]
- [[*Attorneys and Law Firms][Attorneys and Law Firms]]
- [[*Opinion][Opinion]]

** KeyCite:

- KeyCite Yellow Flag - Negative Treatment
- Distinguished byEight Is Enough, LLC. v. Ohlig, Wash.App. Div. 1, March 4, 2024

** Synopsis

Port authority brought unlawful detainer action against shipping company which was commercial tenant of port. The Superior Court, Cowlitz County, Stephen Warning, J., granted authority’s motion to dismiss shipping company’s affirmative defenses, and entered judgment for authority. The Supreme Court denied shipping company’s petition for direct review, and transferred matter. Following transfer, the Court of Appeals, Houghton, J., held that: (1) shipping company could assert as affirmative defense that attempt to evict was in retaliation for its public statements regarding operation of port, and thus in violation of its First Amendment rights; (2) statute granting immunity for good faith communications to government agencies applies only to civil liability, and thus was inapplicable; and (3) entry of prejudgment writ of restitution did not violate shipping company’s rights.

Reversed and remanded.

Procedural Posture(s): Motion to Dismiss.

** West Headnotes (21)

*** [1] Appeal and Error  [[1: 30-k-3555][30-k-3555]]  Review using standard applied below

- /30 Appeal and Error/
- /30-XVI Review/
- /30-XVI(D) Scope and Extent of Review/
- /30-XV I(D)13Summary Judgment/
- *30-k-3555 Review using standard applied below*
- /(Formerly 30k863)/

On review of summary judgment, an appellate court engages in the same inquiry as the trial court. CR 56(c).

*** [2] Appeal and Error  [[2: 30-k-3950][30-k-3950]]  Summary Judgment

- /30 Appeal and Error/
- /30-XVI Review/
- /30-XVI(F) Presumptions and Burdens on Review/
- /30-XVI(F)2 Particular Matters and Rulings/
- *30-k-3950 Summary Judgment*
- *30-k-3951 In general*
- /(Formerly 30k934(1))/

On review of summary judgment, appellate court considers all facts submitted and all reasonable inferences from them in the light most favorable to the nonmoving party. CR 56(c).

*** [3] Landlord and Tenant  [[3: 233-k-1781][233-k-1781]]  Nature and form

- /233 Landlord and Tenant/
- /233-VIII Reentry and Recovery of Possession by Landlord/
- /233-VIII(D) Actions for Unlawful Detainer/
- *233-k-1781 Nature and form*
- /(Formerly 233k288)/

Unlawful detainer action is a summary proceeding designed to facilitate recovery of possession of leased property; in such a proceeding, the primary issue is the right to possession. West’s RCWA 59.12.010 et seq.

- 3 Cases that cite this headnote

*** [4] Landlord and Tenant  [[4: 233-k-1787][233-k-1787]]  Defenses and grounds of opposition in general

- /233 Landlord and Tenant/
- /233-VIII Reentry and Recovery of Possession by Landlord/
- /233-VIII(D) Actions for Unlawful Detainer/
- *233-k-1783 Right of Action and Defenses*
- *233-k-1787 Defenses and grounds of opposition in general*
- /(Formerly 233k290(3))/

In defending against an unlawful detainer action, a tenant may raise affirmative equitable defenses, which include retaliatory eviction. West’s RCWA 59.12.010 et seq.

- 4 Cases that cite this headnote

*** [5] Landlord and Tenant  [[5: 233-k-1787][233-k-1787]]  Defenses and grounds of opposition in general

- /233 Landlord and Tenant/
- /233-VIII Reentry and Recovery of Possession by Landlord/
- /233-VIII(D) Actions for Unlawful Detainer/
- *233-k-1783 Right of Action and Defenses*
- *233-k-1787 Defenses and grounds of opposition in general*
- /(Formerly 233k290(3))/

Equitable defense to unlawful detainer action of retaliatory eviction does not arise whenever it seems equitable to recognize it, but only when there is a substantive legal right, as distinguished from a mere moral right. West’s RCWA 59.12.010 et seq.

- 6 Cases that cite this headnote

*** [6] Equity  [[6: 150-k-62][150-k-62]]  Equity follows the law

- /150 Equity/
- /150-I Jurisdiction, Principles, and Maxims/
- /150-I(C) Principles and Maxims of Equity/
- *150-k-62 Equity follows the law*

An equitable defense arises only when there is a substantive legal right, that is, a right that comes within the scope of judicial action, as distinguished from a mere moral right.

- 3 Cases that cite this headnote

*** [7] Equity  [[7: 150-k-45][150-k-45]]  Adequacy of Legal Remedy

- /150 Equity/
- /150-I Jurisdiction, Principles, and Maxims/
- /150-I(B) Remedy at Law and Multiplicity of Suits/
- *150-k-45 Adequacy of Legal Remedy*
- *150-k-46 In general*

To assert an equitable defense, the procedure prescribed by statute for the enforcement of the asserted substantive right must be inadequate or the ordinary and usual remedies unavailing.

- 1 Case that cites this headnote

*** [8] Constitutional Law  [[8: 92-k-1766][92-k-1766]]  Transit systems and stations
Landlord and Tenant-Defenses and grounds of opposition in general

- /92 Constitutional Law/
- /92-XVII IFreedom of Speech, Expression, and Press/
- /92X-VIII(G) Property and Events/
- /92X-VIII(G)2 Government Property and Events/
- *92-k-1766 Transit systems and stations*
- /(Formerly 92k90.1(4))/
- /233 Landlord and Tenant/
- /233-VIII Reentry and Recovery of Possession by Landlord/
- /233-VIII(D) Actions for Unlawful Detainer/
- *233-k-1783 Right of Action and Defenses*
- *233-k-1787 Defenses and grounds of opposition in general*
- /(Formerly 233k290(3))/

Shipping company which was commercial tenant of port authority could assert as affirmative defense in unlawful detainer action claim that attempt to evict company was in retaliation for company’s public statements expressing hope that authority would make adequate investments to ensure environmentally safe operation of port, and thus violated company’s First Amendment free speech rights; speech in question related to subject property, free speech was substantive right worthy of protection, authority was a government entity, and company was not otherwise in breach of lease. U.S.C.A. Const.Amend. 1; West’s RCWA 59.12.010 et seq.

- 2 Cases that cite this headnote

*** [9] Landlord and Tenant  [[9: 233-k-1781][233-k-1781]]  Nature and form

- /233 Landlord and Tenant/
- /233-VIII Reentry and Recovery of Possession by Landlord/
- /233-VIII(D) Actions for Unlawful Detainer/
- *233-k-1781 Nature and form*
- /(Formerly 233k288)/

Court presiding over a unlawful detainer action may decide issues related to rightful possession of the subject property. West’s RCWA 59.12.010 et seq.

- 4 Cases that cite this headnote

*** [10] Landlord and Tenant  [[10: 233-k-1792][233-k-1792]]  Jurisdiction

- /233 Landlord and Tenant/
- /233-VIII Reentry and Recovery of Possession by Landlord/
- /233-VIII(D) Actions for Unlawful Detainer/
- *233-k-1790 Actions*
- *233-k-1792 Jurisdiction*
- /(Formerly 233k288)/

Although court presiding over an unlawful detainer action does not sit as a court of general jurisdiction to decide issues unrelated to possession of the subject property, it may resolve any issues necessarily related to the parties’ dispute over such possession. West’s RCWA 59.12.010 et seq.

- 4 Cases that cite this headnote

*** [11] Constitutional Law Freedom of Speech, Expression, and Press
Constitutional Law-Criticism of government or officials

- /92 Constitutional Law/
- /92-XVII IFreedom of Speech, Expression, and Press/
- /92X-VIII(A) In General/
- /92X-VIII(A)1 In General/
- *92-k-1490 In general*
- /(Formerly 92k90(1))/
- /92 Constitutional Law/
- /92-XVII IFreedom of Speech, Expression, and Press/
- /92X-VIII(A) In General/
- /92X-VIII(A)3 Particular Issues and Applications in General/
- *92-k-1550 Criticism of government or officials*
- /(Formerly 92k90(1))/

First Amendment prevents the government from prohibiting constitutionally protected speech, and prohibits it from silencing speech it disapproves, especially criticism of the government itself. U.S.C.A. Const.Amend. 1.

*** [12] Constitutional Law  [[12: 92-k-1495][92-k-1495]]  Entities protected

- /92 Constitutional Law/
- /92-XVII IFreedom of Speech, Expression, and Press/
- /92X-VIII(A) In General/
- /92X-VIII(A)1 In General/
- *92-k-1495 Entities protected*
- /(Formerly 92k90(1))/

Corporation is entitled to the same free speech protections under First Amendment as any individual. U.S.C.A. Const.Amend. 1.

*** [13] Constitutional Law  [[13: 92-k-1494][92-k-1494]]  Applicability to governmental or private action;  state action

- /92 Constitutional Law/
- /92-XVII IFreedom of Speech, Expression, and Press/
- /92X-VIII(A) In General/
- /92X-VIII(A)1 In General/
- *92-k-1494 Applicability to governmental or private action;  state action*
- /(Formerly 92k90(1))/

Port authority which was a municipal corporation established pursuant to statute was a public entity and government actor, for purposes of First Amendment’s free speech guarantee. U.S.C.A. Const.Amend. 1.

*** [14] Constitutional Law Freedom of Speech, Expression, and Press

- /92 Constitutional Law/
- /92-XVII IFreedom of Speech, Expression, and Press/
- /92X-VIII(A) In General/
- /92X-VIII(A)1 In General/
- *92-k-1490 In general*
- /(Formerly 92k90(1))/

It is important that the First Amendment’s free speech guarantee assure individuals the freedom to speak out on matters relating to the functioning of government. U.S.C.A. Const.Amend. 1.

*** [15] Constitutional Law Government Property and Events
Landlord and Tenant-Defenses and grounds of opposition in general

- /92 Constitutional Law/
- /92-XVII IFreedom of Speech, Expression, and Press/
- /92X-VIII(G) Property and Events/
- /92X-VIII(G)2 Government Property and Events/
- *92-k-1730 In general*
- /(Formerly 92k90.1(4))/
- /233 Landlord and Tenant/
- /233-VIII Reentry and Recovery of Possession by Landlord/
- /233-VIII(D) Actions for Unlawful Detainer/
- *233-k-1783 Right of Action and Defenses*
- *233-k-1787 Defenses and grounds of opposition in general*
- /(Formerly 233k290(3))/

Commercial tenant of a government landlord may, in some circumstances, assert its First Amendment right to free speech as an equitable affirmative defense in an unlawful detainer action. U.S.C.A. Const.Amend. 1; West’s RCWA 59.12.010 et seq.

- 2 Cases that cite this headnote

*** [16] Water Law  [[16: 405-k-2565][405-k-2565]]  Employees and employment issues

- /405 Water Law/
- /405-XV Navigable Waters/
- /405-XV(B) Rights of Public/
- /405-XV(B)3 Harbors, Ports, and Terminals/
- *405-k-2559 Port Authorities, Districts, Commissions, and Boards*
- *405-k-2565 Employees and employment issues*
- /(Formerly 233k291(11))/

To establish a prima facie case of retaliatory discharge in governmental landlord’s unlawful detainer action, based upon the exercise of protected First Amendment rights, commercial tenant must demonstrate that (1) the disputed speech addressed a matter of public concern, and (2) the speech was a substantial or motivating factor in the landlord’s adverse decision to seek eviction; if tenant satisfies this burden, the burden shifts to landlord to prove it would have sought eviction regardless of the protected conduct, i.e., that it had another legal basis for pursuing the unlawful detainer action. U.S.C.A. Const.Amend. 1; West’s RCWA 59.12.010 et seq.

- 2 Cases that cite this headnote

*** [17] Libel and Slander  [[17: 237-k-40][237-k-40]]  Qualified Privilege

- /237 Libel and Slander/
- /237-II Privileged Communications, and Malice Therein/
- *237-k-40 Qualified Privilege*
- *237-k-41 In general*

Statute establishing immunity for persons who make good faith communications to government agencies affords immunity only from civil liability, or in other words, from the threat of a civil action for damages. West’s RCWA 4.24.510.

*** [18] Water Law  [[18: 405-k-2564][405-k-2564]]  Tort claims;  immunity

- /405 Water Law/
- /405-XV Navigable Waters/
- /405-XV(B) Rights of Public/
- /405-XV(B)3 Harbors, Ports, and Terminals/
- *405-k-2559 Port Authorities, Districts, Commissions, and Boards*
- *405-k-2564 Tort claims;  immunity*
- /(Formerly 233k291(4.5))/

Statute granting immunity to persons who make good faith communications to government agencies was inapplicable to unlawful detainer action brought by port authority against shipping company which was its commercial tenant, in which company alleged that eviction was in retaliation for public statements it had made regarding operation of port; statute affords immunity only from civil liability, and authority did not seek damages, but only adjudication of its rights to possession and termination of tenancy. West’s RCWA 4.24.510, 59.12.010 et seq.

- 2 Cases that cite this headnote

*** [19] Water Law  [[19: 405-k-2572][405-k-2572]]  Leases and licenses to use harbor premises or facilities

- /405 Water Law/
- /405-XV Navigable Waters/
- /405-XV(B) Rights of Public/
- /405-XV(B)3 Harbors, Ports, and Terminals/
- *405-k-2572 Leases and licenses to use harbor premises or facilities*
- /(Formerly 233k291(17))/

Writ of restitution served in connection with unlawful detainer action does not have any immediate effect on the tenant’s property interests. West’s RCWA 59.12.100.

- 2 Cases that cite this headnote

*** [20] Water Law  [[20: 405-k-2572][405-k-2572]]  Leases and licenses to use harbor premises or facilities

- /405 Water Law/
- /405-XV Navigable Waters/
- /405-XV(B) Rights of Public/
- /405-XV(B)3 Harbors, Ports, and Terminals/
- *405-k-2572 Leases and licenses to use harbor premises or facilities*
- /(Formerly 233k291(17))/

Although writ of restitution in connection with unlawful detainer action may be issued ex parte, tenant is provided with notice of the action and given an opportunity to respond before the writ will be executed. West’s RCWA 59.12.100.

*** [21] Water Law  [[21: 405-k-2572][405-k-2572]]  Leases and licenses to use harbor premises or facilities

- /405 Water Law/
- /405-XV Navigable Waters/
- /405-XV(B) Rights of Public/
- /405-XV(B)3 Harbors, Ports, and Terminals/
- *405-k-2572 Leases and licenses to use harbor premises or facilities*
- /(Formerly 233k291(17))/

Entry of prejudgment writ of restitution in unlawful detainer action was permissible, even though writ was entered without providing tenant with notice and opportunity to be heard, where tenant received notice before writ of restitution was to be enforced, and had an opportunity to be heard on the merits before any judgment was entered. West’s RCWA 59.12.100.

- 2 Cases that cite this headnote

** Attorneys and Law Firms

- <<**919>> <<*433>> Ben Shafton, Morse & Bratt, Vancouver, for Appellant.
- Donald Lee Donaldson, Darrel S. Ammons, Walstead Mertsching Husemoen Etal, Longview, for Respondent.

** Opinion

HOUGHTON, J.

International Raw Materials, Ltd. (IRM) appeals a trial court order evicting it from <<**920>> commercial property at the Port of Longview (Port). IRM argues that the trial court erred in striking its affirmative defenses and in <<*434>> granting a prejudgment writ. We reverse and remand for further proceedings.

*** FACTS

The facts are undisputed. Since 1981, IRM has been both a tenant and a customer of the Port. It operates a bulk loading facility where it loads commodities onto ships bound overseas. Its current lease with the Port expires in 2012. In December 1994, IRM and the Port entered into a second agreement under which IRM rented a small office on the second floor of one of the dock buildings for $150 plus tax per month. Either party, upon 30–days notice, could cancel the agreement.

One of the Port’s other customers imports coal tar pitch. In August 1997, IRM obtained the Material Safety Data Sheet on this substance. The document identifies a number of health hazards associated with coal tar pitch. It states that the material contains known carcinogens and the vapors cause moderate to severe irritation of the eyes, nose, throat, and respiratory tract. In liquid form it can cause burning and itching; when burned it can emit hazardous fumes; and long-term exposure has been associated with skin, kidney and lung cancer.

In August 1997, the LONGVIEW DAILY NEWS published an article about the Port’s expansion of its importation of coal tar pitch and the economic benefits of doing so. IRM’s President, W.P. O’Neill, responded by writing a letter to the newspaper editor in which he expressed his view that “adequate investments ... be made in the proper facilities to ensure the environmentally safe discharge of this product.” Kenneth O’Hollaren, Executive Director of the Port, responded to O’Neill’s letter, expressing confidence in the Port’s procedures for handling coal tar pitch. The LONGVIEW DAILY NEWS published both letters.

On September 12, 1997, O’Neill and others attended a meeting with Port officials to discuss a variety of subjects. At that meeting, O’Neill expressed concern about the safety <<*435>> of his employees who worked in close proximity to the coal tar pitch. Three days later, O’Hollaren sent IRM a letter notifying it that the Port elected to terminate IRM’s office rental agreement effective October 16, 1997. In the letter, O’Hollaren said it might be helpful to explain the Port’s reasons for the cancellation although the agreement did not require the Port to give a reason. He explained that “given Mr. O’Neill’s comments, it would be foolish to continue the present office arrangement and hence this notice to vacate.”

*** IRM did not vacate the office, and in October 1997, the Port filed an unlawful detainer action. After a hearing, the court entered an order denying the request for a writ of restitution and dismissing the complaint.

On November 26, 1997, the Port notified IRM, in writing, that its tenancy was terminated effective December 31, 1997. This notice also informed IRM that the Port had alternate rental space available for it at another location in the Port facility. IRM refused to vacate the office, and on January 7, 1998, IRM tendered its rent for January.[fn:1]

[fn:1] Nothing in the record indicates whether this rent was accepted.

On January 7, 1998, the Port filed another unlawful detainer action, together with a motion for writ of restitution. The same day, the trial court signed a writ of restitution, conditioned upon the Port’s posting a $1,000 bond. On January 9, the court entered a writ of restitution commanding the sheriff to deliver possession of the property to the Port on January 15.

On January 12, IRM moved to quash the writ and to raise the amount of the Port’s bond. The court increased the Port’s bond to $25,000 and allowed IRM to post a counter-bond of $40,000 to prevent execution of the writ. Both parties posted the required bonds and IRM remained in possession of the premises.

On January 14, IRM filed an answer, including affirmative defenses of immunity, under RCW 4.24.510, retaliatory eviction, and retaliatory eviction based upon the exercise of <<*436>> free speech rights. The Port moved to <<**921>> dismiss the affirmative defenses and for judgment on the pleadings under CR 12. Under CR 12(c), the trial court treated the matter as a motion for summary judgment. And, upon review of the parties’ arguments, the trial court dismissed IRM’s affirmative defenses, granted the Port’s motion for judgment on the pleadings, awarded it $189.10 in costs, and ordered the office space restored to the Port.

The Supreme Court denied IRM’s petition for direct review and transferred the matter to this court.

*** ANALYSIS

**** Standard of Review

[1] <<1: 30-k-3555>> [2] <<2: 30-k-3950>> The trial court dismissed IRM’s affirmative defenses under CR 12(c), treating the matter as a motion for summary judgment under CR 56(c). On review of summary judgment, an appellate court engages in the same inquiry as the trial court. Hill v. J.C. Penney, Inc., 70 Wash.App. 225, 238, 852 P.2d 1111, review denied, 122 Wash.2d 1023, 866 P.2d 39 (1993). Summary judgment is appropriate if there is no genuine issue of material fact and the moving party is entitled to judgment as a matter of law. Clements v. Travelers Indem. Co., 121 Wash.2d 243, 249, 850 P.2d 1298 (1993). The appellate court considers all facts submitted and all reasonable inferences from them in the light most favorable to the nonmoving party. Clements, 121 Wash.2d at 249, 850 P.2d 1298. The motion should be granted only if, from all the evidence, reasonable persons could reach but one conclusion. Clements, 121 Wash.2d at 249, 850 P.2d 1298.

*** AFFIRMATIVE DEFENSES

**** Unlawful Detainer and Retaliatory Eviction

[3] <<3: 233-k-1781>> [4] <<4: 233-k-1787>> An unlawful detainer action under RCW 59.12 is a summary proceeding designed to facilitate recovery of possession of leased property and, in such a proceeding, the primary issue is the right to possession. Motoda v. Donohoe, 1 Wash.App. 174, 175, 459 P.2d 654 (1969), review denied, 77 Wash.2d 962 (1970); <<*437>> Heaverlo v. Keico Indus., Inc., 80 Wash.App. 724, 733, 911 P.2d 406 (1996) (purpose of unlawful detainer proceeding is to provide “speedy and summary resolution of possession”). In defending against an unlawful detainer action, a tenant may raise affirmative equitable defenses, which include retaliatory eviction. Stephanus v. Anderson, 26 Wash.App. 326, 331, 613 P.2d 533, review denied, 94 Wash.2d 1014 (1980); Motoda, 1 Wash.App. at 175, 459 P.2d 654.

[5] <<5: 233-k-1787>> [6] <<6: 150-k-62>> [7] <<7: 150-k-45>> The equitable defense of retaliatory eviction, however, does not arise “whenever it seems ‘equitable’ to recognize it.” Stephanus, 26 Wash.App. at 331, 613 P.2d 533; but cf., Weil v. Kaplan, 175 Misc.2d 482, 670 N.Y.S.2d 666 (N.Y.Sup.App.Term (1997)) (because of equitable nature of defense of retaliatory eviction, no per se rule can be laid down to govern limitations of its applicability). An equitable defense arises only when there is “a substantive legal right, that is, a right that comes within the scope of judicial action, as distinguished from a mere moral right.” Motoda, 1 Wash.App. at 175, 459 P.2d 654; see Stephanus, 26 Wash.App. at 331, 613 P.2d 533 (equitable defense must be premised upon an established substantive legal right). Moreover, to assert an equitable defense, the procedure prescribed by statute for the enforcement of the asserted substantive right must be inadequate or the ordinary and usual remedies unavailing. Motoda, 1 Wash.App. at 175, 459 P.2d 654; see Stephanus, 26 Wash.App. at 334, 613 P.2d 533 (equity cannot provide a remedy where legislation expressly denies it).[fn:2]

[fn:2] In determining whether an equitable affirmative defense exists in a particular situation, a number of courts have adopted the following balancing test: whether the public policies furthered by protecting defendants from eviction outweigh the interests in preserving the summary nature of unlawful detainer proceedings. Barela v. Superior Court, 30 Cal.3d 244, 178 Cal.Rptr. 618, 636 P.2d 582, 586 (1981); S.P. Growers Ass’n v. Rodriguez, 17 Cal.3d 719, 131 Cal.Rptr. 761, 762, 552 P.2d 721, 723 (1976).

*** IRM first contends the trial court erred in dismissing as an affirmative defense its claim of retaliatory eviction. According to IRM, the Port’s actions in seeking to evict IRM <<**922>> were retaliatory and in violation of its constitutional right to free speech. IRM argues that it should have been entitled <<*438>> to assert its right of free speech as an affirmative defense, as a matter of law.

[8] <<8: 92-k-1766>> The Port counters that the trial court lacked jurisdiction to consider IRM’s affirmative defense of free speech because that issue is unrelated to the rightful possession of the subject property under the parties’ commercial lease. The Port contends that such an affirmative defense cannot be asserted, as a matter of law, in an unlawful detainer action in the commercial lease context.

We agree with IRM and hold that it is entitled to assert its free speech rights under the First Amendment of the United States Constitution as an equitable affirmative defense in the unlawful detainer action because: (1) the speech relates to possession of the subject property; (2) free speech is a substantive legal right worthy of protection in this context; (3) the landlord is a government entity; and (4) IRM is not otherwise in breach of the lease agreement.

The Port claims that the issue of IRM’s free speech rights are not related to possession of the leased property. We disagree.

[9] <<9: 233-k-1781>> [10] <<10: 233-k-1792>> A court presiding over a unlawful detainer action may decide issues related to rightful possession of the subject property. See Young v. Riley, 59 Wash.2d 50, 52, 365 P.2d 769 (1961). Although the court does not sit as a court of general jurisdiction to decide issues unrelated to possession of the subject property, Young, 59 Wash.2d at 52, 365 P.2d 769, it may resolve any issues necessarily related to the parties’ dispute over such possession. See First Union Management, Inc. v. Slack, 36 Wash.App. 849, 854, 679 P.2d 936 (1984).

Here, the Port’s commercial property leased by IRM is an integral and necessary part of its business operations. IRM’s concerns, therefore, about the Port’s management of coal tar pitch, which contains toxins and carcinogens that could potentially harm the environment at the Port, bear upon and affects its operations. Thus, any adverse effect upon the environment stemming from the coal tar pitch and its handling could potentially affect IRM’s business operations at the port.

<<*439>> Moreover, it is reasonable for IRM to have concerns for the occupational safety of its employees and of others working at the Port. Because concerns about the proper management of the coal tar pitch intake are germane to IRM’s operations, IRM’s ability to voice concerns about the Port’s conduct in handling the coal tar pitch relates to possession of the subject property. See Murphy v. Smallridge, 196 W.Va. 35, 468 S.E.2d 167, 172 (1996) (tenant’s report to state environmental agency of landlord’s illegal dumping on leased premises constituted a right incidental to tenancy and therefore supported a retaliatory eviction defense); Pohlman v. Metropolitan Trailer Park, Inc., 126 N.J.Super. 114, 312 A.2d 888, 891 (Ch.Div. 1973) (tenant’s conduct in petitioning local government for zoning ordinance amendments germane to tenant-landlord relationship).

[11] The First Amendment of the United States Constitution prevents the government from prohibiting constitutionally protected speech. State v. Riles, 135 Wash.2d 326, 346, 957 P.2d 655 (1998). This protection prohibits the state from silencing speech it disapproves, especially criticism of the government itself. State ex rel. Public Disclosure Comm’n v. 119 Vote No! Comm., 135 Wash.2d 618, 626, 957 P.2d 691 (1998).

Based upon this principle, courts have protected the free speech rights of public employees against retaliatory discharge or other adverse actions by a governmental employer for exercise of First Amendment rights. See Board of County Comm’rs v. Umbehr, 518 U.S. 668, 675, 116 S.Ct. 2342, 135 L.Ed.2d 843 (1996) (First Amendment’s guarantee of free speech protects government employees and independent contractors from termination because of their speech on matters of public concern); Perry v. Sindermann, 408 U.S. 593, 597, 92 S.Ct. 2694, 33 L.Ed.2d 570 (1972) (government workers constitutionally protected from dismissal for publicly or privately criticizing their employer’s practices); see also White v. State, 131 Wash.2d 1, 10–12, 929 P.2d 396 (1997); see e.g., <<**923>> Edwards v. Department of Transp., 66 Wash.App. 552, 558, 832 P.2d 1332 (1992) <<*440>> (department violated engineer’s free speech rights by reducing engineer’s salary for sending letter to city expressing concerns about agency inefficiency); cf. Binkley v. City of Tacoma, 114 Wash.2d 373, 387, 787 P.2d 1366 (1990) (municipality’s decision to reassign employee based upon interests in maintaining efficient operation without disruptions in workplace outweighed employee’s free speech rights).

In White, 131 Wash.2d at 10–12, 929 P.2d 396, the Supreme Court addressed the issue of free speech rights and articulated a standard for deciding whether an employee’s assertion of First Amendment rights may be asserted against a government employer. The White court held that the “first inquiry [as to] ... whether the speech involved is protected by the First Amendment,” is a question of the law. White, 131 Wash.2d at 11, 929 P.2d 396. This inquiry requires two steps: first, the court decides whether the speech may be fairly characterized as constituting speech on a matter of public concern, and, if so then the court decides whether the employee’s interest is greater than the government’s interest in promoting efficiency in the public service it performs. White, 131 Wash.2d at 11, 929 P.2d 396.

Whether an employee’s speech addresses a matter of public concern, the White court explained, is determined by the content, form, and context of the statement, as indicated by the entire record; and of these factors, content is the most important. White, 131 Wash.2d at 11, 929 P.2d 396. See also Edwards, 66 Wash.App. at 560, 832 P.2d 1332 (court looks to intent behind employee’s speech to determine whether employee meant to raise an issue of public concern). Thus, the party who bears the burden of balancing the free speech rights versus the governmental interest is “the party who seeks to justify his or her actions in light of First Amendment rights and restrictions.” White, 131 Wash.2d at 13, 929 P.2d 396.[fn:3]

[fn:3] The White court recognized that, among courts, there is “some confusion” with respect to which party bears the burden of balancing the interests. White, 131 Wash.2d at 13–14, 929 P.2d 396. Some courts place the burden upon the party asserting the retaliatory conduct, see e.g., Johnson v. Multnomah County, Or., 48 F.3d 420, 422 (9th Cir.), cert. denied, 515 U.S. 1161, 115 S.Ct. 2616, 132 L.Ed.2d 858 (1995); Moore v. City of Wynnewood, 57 F.3d 924, 931 (10th Cir.1995), although others require the employer to demonstrate that its interests in efficiency in the workplace justified the adverse action against the party asserting its constitutional rights. See e.g., Rankin v. McPherson, 483 U.S. 378, 388, 107 S.Ct. 2891, 97 L.Ed.2d 315 (1987); Connick v. Myers, 461 U.S. 138, 149, 103 S.Ct. 1684, 75 L.Ed.2d 708 (1983). But in the White court’s view, despite this ambivalence in the law, the “framework for deciding First Amendment cases in the public employment setting is clear” and the “respective burdens of the parties fall naturally” upon the party asserting the improper retaliatory conduct. White, 131 Wash.2d at 14, 929 P.2d 396.

Recently, in Umbehr, 518 U.S. 668, 116 S.Ct. 2342, 135 L.Ed.2d 843, the U.S. Supreme <<*441>> Court extended recognition of First Amendment protection for public employees against adverse conduct by their employer to private independent government contractors. In Umbehr, the plaintiff had contracted with the county government to provide trash hauling services. During the contract term, the plaintiff voiced criticism of the county board and its policies. The plaintiff wrote letters and editorials in local newspapers and attended public meetings to express similar criticism. The county terminated his contract and the plaintiff filed a lawsuit against the board alleging violation of his free speech rights.

The district court concluded that independent contractors did not have “the same First Amendment protections granted to government employees,” and dismissed the action. Umbehr v. McClure, 840 F.Supp. 837, 838 (D.Kan.1993). But the 10th Circuit Court of Appeals reversed, holding that “an independent contractor is protected under the First Amendment from retaliatory governmental action, just as an employee would be.” Umbehr v. McClure, 44 F.3d 876, 883 (10th Cir.), cert. denied, 515 U.S. 1161, 115 S.Ct. 2616, 132 L.Ed.2d 859 (1995).

The United States Supreme Court agreed with the 10th Circuit, holding that independent contracts were entitled, as a matter of law, to the same free speech protection as government employees. Because of the “similarities between government employees <<**924>> and government contractors,” the Court observed that in each situation a retaliatory “threat of loss” of a “valuable financial benefit” could potentially “chill speech on matters of public concern by those who, because of their dealings of the government, ‘are often in the best position to know what ails the agencies <<*442>> for which they work.’ ” Umbehr, 518 U.S. at 674, 116 S.Ct. 2342 (quoting Waters v. Churchill, 511 U.S. 661, 674, 114 S.Ct. 1878, 128 L.Ed.2d 686 (1994)).

In so holding, the Court balanced “the interests of the [independent contractor] ... in commenting upon matters of public concern and the interest of the State ... in promoting the efficiency of the public services it performs....” Umbehr, 518 U.S. at 675, 116 S.Ct. 2342 (quoting Pickering v. Board of Educ. of Township High Sch. Dist. 205, 391 U.S. 563, 568, 88 S.Ct. 1731, 20 L.Ed.2d 811 (1968)). The Court set forth a two-part test for determining whether a right to free speech existed with regard to a government contract. The contractor must show (1) that the disputed speech addressed a matter of public concern, and (2) that the speech was a substantial or motivating factor in the government’s termination of the contract. Umbehr, 518 U.S. at 685, 116 S.Ct. 2342. Nevertheless, the government could prevail if it could demonstrate, by a preponderance of the evidence, that it would have terminated the contract regardless of the disputed speech, or, that legitimate countervailing governmental interests outweighed the free speech interests at stake. Umbehr, 518 U.S. at 685, 116 S.Ct. 2342.

[12] <<12: 92-k-1495>> [13] <<13: 92-k-1494>> Here, IRM urges us to recognize its free speech rights as an equitable affirmative defense against the Port’s unlawful detainer action. IRM asks us to extend protection of its free speech rights from public employees and public contractors to private tenants of government landlords. IRM, as a corporation, is entitled to the same free speech protections as any individual. See First Nat’l Bank of Boston v. Bellotti, 435 U.S. 765, 98 S.Ct. 1407, 55 L.Ed.2d 707 (1978). We agree that extension is appropriate because, to hold otherwise, could chill IRM’s free speech rights.[fn:4]

[fn:4] As a municipal corporation established pursuant to statute, the Port is a public entity and government actor. See RCW 53.04 et seq.

[14] It is important that the guarantee of free speech under the First Amendment assure individuals the freedom to speak out on matters relating to the functioning of government.  <<*443>> Richmond Newspapers, Inc. v. Virginia, 448 U.S. 555, 575, 100 S.Ct. 2814, 65 L.Ed.2d 973 (1980); see Landmark Communications v. Virginia, 435 U.S. 829, 838, 98 S.Ct. 1535, 56 L.Ed.2d 1 (1978) (a major purpose of First Amendment is protecting free discussion of governmental affairs). For a free debate of ideas often results in the wisest governmental policies. See Dennis v. United States, 341 U.S. 494, 503, 71 S.Ct. 857, 95 L.Ed. 1137 (1951). As such, the Port should not restrict individuals, including its commercial tenants, from disclosing constitutionally protected information they lawfully acquire or from expressing an opinion critical of the government absent state interests of the highest order. See United States v. Aguilar, 515 U.S. 593, 605, 115 S.Ct. 2357, 132 L.Ed.2d 520 (1995).

We realize that some courts have declined to recognize retaliatory eviction as an affirmative defense in cases involving a commercial lease. See e.g., Espenschied v. Mallick, 633 A.2d 388 (D.C.1993). But in such cases, the lessor was a private entity, unlike here where the lessor is a government entity. Other courts, however, have recognized retaliatory eviction in the context of a commercial lease. See e.g., Custom Parking, Inc. v. Superior Court, 138 Cal.App.3d 90, 187 Cal.Rptr. 674 (1982) (where commercial tenant threatened with eviction after employees and officers refused to perjure themselves in the landlord’s favor, court recognized retaliatory eviction defense, concluded that “to preclude the defense would be to create a class of litigants, commercial landlords, with a legally sanctioned means of punishing tenants who testify honestly but adversely to the landlord and third parties”); Windward Partners v. Delos Santos, 59 Haw. 104, 577 P.2d 326 (1978) (recognizing commercial tenant’s right to assert retaliatory eviction defense where <<**925>> landlord terminated tenancy because tenant publicly testified against landlord’s pecuniary interests at agency hearing, concluding that retaliatory defense was “equally applicable to non-residential tenants”; court perceived “no justifiable legal premise[ ] to distinguish between the two classes of tenants”).

[15] <<*444>> Thus, in summary, it is logical to extend recognition of First Amendment protection to a commercial tenant to a government landlord where (1) the speech relates to possession of the subject property; (2) free speech is a substantive legal right worthy of protection in this context; and (3) the tenant is not otherwise in breach of the lease agreement. Because we hold that a commercial tenant of a government landlord may, in some circumstances, assert its right to free speech as an equitable affirmative defense in the unlawful detainer action, we remand for further proceedings taking into consideration the following criteria.

[16] <<16: 405-k-2565>> To establish a prima facie case of retaliatory discharge in the unlawful detainer action based upon the exercise of First Amendment rights, IRM must demonstrate that (1) the disputed speech addressed a matter of public concern, and (2) the speech was a substantial or motivating factor in the Port’s adverse decision to seek eviction. See White, 131 Wash.2d at 10, 929 P.2d 396. If IRM satisfies this burden, the burden shifts to the Port, as a government landlord, to prove it would have sought eviction regardless of the employee’s protected conduct, i.e., that it had another legal basis for pursuing the unlawful detainer action. See White, 131 Wash.2d at 11, 929 P.2d 396.

Because the standard set forth above assures the government the opportunity to demonstrate another legal basis for seeking eviction, our conclusion that IRM is entitled to assert its free speech rights as an equitable affirmative defense to the Port’s unlawful detainer action does not render the government powerless. IRM’s assertion of First Amendment rights in the unlawful detainer action, as in the employment or independent contractor context in White and Umbehr respectively, is necessarily contingent upon its compliance with its other contractual and legal obligations under the lease. If the Port demonstrates another legal basis for seeking eviction, IRM’s affirmative defense will not stand. See e.g., RCW 59.12.030 (tenant is guilty of unlawful detainer for failing to pay rent, failing to perform any other condition or covenant of the lease, committing waste upon the demised property, setting up any unlawful business, or maintaining any nuisance thereupon).

<<*445>> Finally, because we conclude that IRM’s free speech rights under federal law provide it with an affirmative defense against the Port’s unlawful detainer action, we do not reach IRM’s argument under state law.

*** IMMUNITY FROM CIVIL LIABILITY

IRM next contends it is immune from civil liability based upon RCW 4.24.510. The Port, however, argues that RCW 4.24.510 is inapplicable in the current proceedings because the Port seeks no damages or civil liability against IRM, and that its “sole purpose” in instituting the unlawful detainer action is to terminate IRM’s at-will tenancy and regain possession of the subject commercial property. The Port’s assertion is correct.

**** RCW 4.24.510 provides that

[a] person who in good faith communicates a complaint or information to any agency of federal, state, or local government regarding any matter reasonably of concern to that agency shall be immune from civil liability on claims based upon the communication to the agency. A person prevailing upon the defense provided for in this section shall be entitled to recover costs and reasonable attorney’s fees incurred in establishing the defense.

In providing individuals with immunity under RCW 4.24.510, the Legislature has sought “to protect individuals who make good-faith reports to appropriate governmental bodies,” recognizing that “the threat of a civil action for damages can act as a deterrent to citizens” lodging such reports. RCW 4.24.500 (emphasis added).

[17] <<17: 237-k-40>> [18] <<18: 405-k-2564>> By its plain language, thus, RCW 4.24.510 affords immunity only from “civil liability,” that is, from the threat of a “civil <<**926>> action for damages.” Here, the Port does not seek damages from IRM, but only that its rights to possession and termination of the commercial tenancy be adjudicated pursuant to the limited summary proceeding under RCW 59.12. The proceeding before the trial court was limited to determining the rights of the parties specifically <<*446>> with respect to the subject property and their possession rights thereto. See Heaverlo, 80 Wash.App. at 733, 911 P.2d 406 (purpose of unlawful detainer proceeding is to determine parties’ solely as to issue of possession and related issues thereto). RCW 4.24.510 is inapplicable to the instant unlawful detainer proceeding.

*** PREJUDGMENT WRIT OF RESTITUTION

Finally, IRM contends the trial court erred in granting a prejudgment writ of restitution and in failing to quash that writ. According to IRM, the trial court issued the writ without providing IRM with notice and an opportunity to be heard. We disagree.

[19] <<19: 405-k-2572>> [20] <<20: 405-k-2572>> [21] <<21: 405-k-2572>> A writ of restitution does not have any immediate effect on the tenant’s property interests. The unlawful detainer statute provides that the sheriff shall serve the writ of restitution “forthwith” on the defendant, “and shall not execute the same for three days thereafter, not until the defendant has been served with summons in the action....” RCW 59.12.100. Under this statutory scheme, although the writ may be issued ex parte, the defendant is provided with notice of the action and given an opportunity to respond before the writ will be executed. Here, IRM received notice before the writ of restitution was to be enforced. It also had an opportunity to be heard on the merits before any judgment was entered, and it still has not been evicted from the office space.

*** ATTORNEY FEES

IRM requests attorney fees under RCW 4.24.510. Because we hold that RCW 4.24.510 does not apply, we decline to award attorney fees.

MORGAN, P.J., and SEINFELD, J., concur.
