#+title:      Josephinium Associates v. Kahli, 111 Wn. App. 617, 45 P.3d 627 (2002)
#+date:       [2002-05-06 Mon 00:00]
#+filetags:   :case:defense:discrimination:equitable:law:rlta:ud:
#+identifier: 20020506T000000
#+signature:  coa=div1

* Josephinium Associates v. Kahli -- Court of Appeals of Washington, Division 1. | May 6, 2002 | 111 Wash.App. 617 | 45 P.3d 627

- Washington Citation :: Josephinium Associates v. Kahli, 111 Wn. App. 617, 45 P.3d 627 (2002)
- All Citations :: 111 Wash.App. 617, 45 P.3d 627, 23 NDLR P 155


                          111 Wash.App. 617

                   Court of Appeals of Washington,

                             Division 1.

JOSEPHINIUM ASSOCIATES, d/b/a Josephinium, Respondent/Cross–Appellant,

                                  v.

               Skye KAHLI, Appellant/Cross–Respondent.

                            No. 46677–1–I.
                             May 6, 2002.
** Brief

** Document Details

- [[*West Headnotes (16)][West Headnotes]]
- [[*Attorneys and Law Firms][Attorneys and Law Firms]]
- [[*Opinion][Opinion]]

** KeyCite:

- KeyCite Yellow Flag - Negative Treatment
- Declined to Extend byIBF, LLC v. Heuft, Wash.App. Div. 1, July 23, 2007

** Synopsis

Landlord brought unlawful detainer action against tenant for nonpayment of rent. The Superior Court, King County, Larry Jordan, J., issued a writ of restitution. Landlord and tenant appealed. The Court of Appeals, Ellington, J., held that: (1) as a matter of first impression, tenant could raise the defense of unlawful discrimination in landlord’s unlawful detainer action, and (2) evidence was sufficient to support finding that landlord did not intentionally discriminate against tenant or fail to reasonably accommodate her disability.

Affirmed.

Procedural Posture(s): On Appeal.

** West Headnotes (16)

*** [1] Appeal and Error  [[1: 30-k-3137][30-k-3137]]  De novo review

- /30 Appeal and Error/
- /30-XVI Review/
- /30-XVI(D) Scope and Extent of Review/
- /30-XVI(D)1 In General/
- *30-k-3137 De novo review*
- /(Formerly 30k893(1))/

The Court of Appeals reviews questions of law de novo.

- 1 Case that cites this headnote

*** [2] Appeal and Error Sufficiency of Evidence

- /30 Appeal and Error/
- /30-XVI Review/
- /30-XVI(D) Scope and Extent of Review/
- /30-XV I(D)10Sufficiency of Evidence/
- *30-k-3441 In general*
- /(Formerly 30k1010.1(1))/

The Court of Appeals reviews challenges to findings of fact for sufficiency of the evidence.

*** [3] Action  [[3: 13-k-6][13-k-6]]  Moot, hypothetical or abstract questions

- /13 Action/
- /13-I Grounds and Conditions Precedent/
- *13-k-6 Moot, hypothetical or abstract questions*

A case is technically moot if the court cannot provide the basic relief originally sought, or can no longer provide effective relief.

- 22 Cases that cite this headnote

*** [4] Landlord and Tenant  [[4: 233-k-1805][233-k-1805]]  Review

- /233 Landlord and Tenant/
- /233-VIII Reentry and Recovery of Possession by Landlord/
- /233-VIII(D) Actions for Unlawful Detainer/
- *233-k-1790 Actions*
- *233-k-1805 Review*
- /(Formerly 233k291(18))/

The Court of Appeals would review the issue of whether discrimination defenses could be raised in an unlawful detainer action, despite mootness of the issue since tenant had vacated her apartment, since the issue was a matter of continuing and substantial public interest.

- 6 Cases that cite this headnote

*** [5] Appeal and Error  [[5: 30-k-781][30-k-781]]  Want of Actual Controversy

- /30 Appeal and Error/
- /30-XIII Dismissal, Withdrawal, or Abandonment/
- *30-k-779 Grounds for Dismissal*
- *30-k-781 Want of Actual Controversy*
- *30-k-781(1) In general*

The Court of Appeals may review a moot case if it contains matters of continuing and substantial public interest.

- 3 Cases that cite this headnote

*** [6] Appeal and Error  [[6: 30-k-781][30-k-781]]  Want of Actual Controversy

- /30 Appeal and Error/
- /30-XIII Dismissal, Withdrawal, or Abandonment/
- *30-k-779 Grounds for Dismissal*
- *30-k-781 Want of Actual Controversy*
- *30-k-781(1) In general*

In deciding whether review of a moot case is appropriate, the Court of Appeals considers: (1) the public or private nature of the question presented; (2) the desirability of an authoritative determination which will provide future guidance to public officers; and (3) the likelihood that the question will recur; a further consideration is whether there is genuine adverseness and quality advocacy on the issues.

- 1 Case that cites this headnote

*** [7] Civil Rights  [[7: 78-k-1083][78-k-1083]]  Discrimination by reason of handicap, disability, or illness

- /78 Civil Rights/
- /78-I Rights Protected and Discrimination Prohibited in General/
- *78-k-1074 Housing*
- *78-k-1083 Discrimination by reason of handicap, disability, or illness*
- /(Formerly 78k131)/

An accommodation is reasonable, and therefore required under the Fair Housing Amendments Act, if it does not cause a fundamental alteration in the nature of a program or undue financial and administrative burdens. Civil Rights Act of 1968, § 804(f), as amended, 42 U.S.C.A. § 3604(f).

- 2 Cases that cite this headnote

*** [8] Civil Rights  [[8: 78-k-1083][78-k-1083]]  Discrimination by reason of handicap, disability, or illness

- /78 Civil Rights/
- /78-I Rights Protected and Discrimination Prohibited in General/
- *78-k-1074 Housing*
- *78-k-1083 Discrimination by reason of handicap, disability, or illness*
- /(Formerly 78k131)/

To accommodate a handicapped tenant, a landlord may be required under the Fair Housing Amendments Act to incur reasonable costs and/or change a generally applicable rule so that the burden is less onerous on the disabled tenant. Civil Rights Act of 1968, § 804(f), as amended, 42 U.S.C.A. § 3604(f).

*** [9] Civil Rights  [[9: 78-k-1083][78-k-1083]]  Discrimination by reason of handicap, disability, or illness

- /78 Civil Rights/
- /78-I Rights Protected and Discrimination Prohibited in General/
- *78-k-1074 Housing*
- *78-k-1083 Discrimination by reason of handicap, disability, or illness*
- /(Formerly 78k131)/

In determining what constitutes a reasonable accommodation under the Fair Federal Housing Amendments Act, the fact-finder should balance the burdens imposed on the landlord and the benefits gained by the tenant. Civil Rights Act of 1968, § 804(f), as amended, 42 U.S.C.A. § 3604(f).

- 2 Cases that cite this headnote

*** [10] Forcible Entry and Detainer  [[10: 179-k-6][179-k-6]]  Nature and Form of Remedy

- /179 Forcible Entry and Detainer/
- /179-I Civil Liability/
- *179-k-6 Nature and Form of Remedy*
- *179-k-6(1) In general*

An “unlawful detainer” action is a summary proceeding to determine the right to possession of property. West’s RCWA 59.12.010 et seq.

- 11 Cases that cite this headnote

*** [11] Forcible Entry and Detainer  [[11: 179-k-6][179-k-6]]  Nature and Form of Remedy

- /179 Forcible Entry and Detainer/
- /179-I Civil Liability/
- *179-k-6 Nature and Form of Remedy*
- *179-k-6(1) In general*

Issues unrelated to possession are not properly part of an unlawful detainer action. West’s RCWA 59.12.010 et seq.

- 6 Cases that cite this headnote

*** [12] Civil Rights  [[12: 78-k-1083][78-k-1083]]  Discrimination by reason of handicap, disability, or illness
Landlord and Tenant-Defenses

- /78 Civil Rights/
- /78-I Rights Protected and Discrimination Prohibited in General/
- *78-k-1074 Housing*
- *78-k-1083 Discrimination by reason of handicap, disability, or illness*
- /233 Landlord and Tenant/
- /233-VIII Reentry and Recovery of Possession by Landlord/
- /233-VIII(C) Actions for Recovery of Possession/
- *233-k-1755 Defenses*
- *233-k-1756 In general*
- /(Formerly 233k298(1))/

Discrimination may be raised as a defense in summary eviction proceedings when the discrimination arises out of the tenancy. West’s RCWA 59.18.380.

- 4 Cases that cite this headnote

*** [13] Forcible Entry and Detainer  [[13: 179-k-12][179-k-12]]  Defenses

- /179 Forcible Entry and Detainer/
- /179-I Civil Liability/
- *179-k-12 Defenses*
- *179-k-12(1) In general*

An equitable defense to an unlawful detainer action arises when there is a substantive legal right, that is, a right that comes within the scope of judicial action, as distinguished from a mere moral right and the usual legal remedies are unavailing. West’s RCWA 59.12.010 et seq.

- 1 Case that cites this headnote

*** [14] Forcible Entry and Detainer  [[14: 179-k-12][179-k-12]]  Defenses

- /179 Forcible Entry and Detainer/
- /179-I Civil Liability/
- *179-k-12 Defenses*
- *179-k-12(1) In general*

To protect the summary nature of the unlawful detainer action, defenses arise out of the tenancy only when they affect the tenant’s right of possession or are based on facts which excuse a tenant’s breach. West’s RCWA 59.12.010 et seq.

- 11 Cases that cite this headnote

*** [15] Civil Rights  [[15: 78-k-1083][78-k-1083]]  Discrimination by reason of handicap, disability, or illness
Landlord and Tenant-Answer

- /78 Civil Rights/
- /78-I Rights Protected and Discrimination Prohibited in General/
- *78-k-1074 Housing*
- *78-k-1083 Discrimination by reason of handicap, disability, or illness*
- /233 Landlord and Tenant/
- /233-VIII Reentry and Recovery of Possession by Landlord/
- /233-VIII(C) Actions for Recovery of Possession/
- *233-k-1758 Actions*
- *233-k-1766 Answer*
- /(Formerly 233k305)/

Tenant asserted a cognizable unlawful discrimination defense in landlord’s unlawful detainer action, where tenant’s asserted defense to nonpayment of rent was landlord’s discrimination. West’s RCWA 59.18.380.

- 9 Cases that cite this headnote

*** [16] Civil Rights  [[16: 78-k-1083][78-k-1083]]  Discrimination by reason of handicap, disability, or illness
Landlord and Tenant-Weight and sufficiency

- /78 Civil Rights/
- /78-I Rights Protected and Discrimination Prohibited in General/
- *78-k-1074 Housing*
- *78-k-1083 Discrimination by reason of handicap, disability, or illness*
- /(Formerly 78k131)/
- /233 Landlord and Tenant/
- /233-VIII Reentry and Recovery of Possession by Landlord/
- /233-VIII(C) Actions for Recovery of Possession/
- *233-k-1758 Actions*
- *233-k-1768 Evidence*
- *233-k-1768(4) Weight and sufficiency*
- /(Formerly 233k308(3))/

Evidence in unlawful detainer action was sufficient to support finding that landlord did not intentionally discriminate against tenant or fail to reasonably accommodate her disability by failing to transfer her to a lower income apartment or converting her apartment to a lower income unit; tenant failed to pay her rent, and redesignation of tenant’s unit to a unit available to lower income tenants would have cost $3,000 per year in rent and would have set a negative precedent to other tenants since tenant’s apartment was much larger than other apartments offered to families with similar incomes. Civil Rights Act of 1968, § 804, as amended, 42 U.S.C.A. § 3604; West’s RCWA 59.12.010 et seq., 59.18.380.

- 2 Cases that cite this headnote

** Attorneys and Law Firms

- <<**629>> <<*619>> David Koch, Seattle, for Appellant.
- Richard Cohan, Seattle, for Respondent.

** Opinion

ELLINGTON, J.

In an unlawful detainer action, the tenant may assert only those equitable defenses which affect the right of possession. Skye Kahli failed to pay her rent. The trial court permitted Kahli to assert disability <<*620>> discrimination as an affirmative defense to her landlord’s unlawful detainer. Under the unusual circumstances here, the defense bore upon Kahli’s right of possession, and was properly asserted. After trial on the merits, the court found Kahli had not proved her defense, and issued a writ of restitution. The record supports the court’s findings. We therefore affirm the trial court in all respects.

**** Facts

Josephinium Associates operates a nonprofit apartment building called The Josephinium, which is owned and managed by the Archdiocesan Housing Authority of Catholic Community Services of Western Washington. The Housing Authority receives government funds to provide housing opportunities for low income and special needs tenants.

The Josephinium apartments comprise 222 units. Six of the units are rented at market rates. The others, called “restricted units,” are rented below market rate to eligible households, based upon tenants’ annual income as compared to the Seattle–Everett Standard Metropolitan Statistical Area (SMSA). Seventy-two units are 30 percent restricted units (meaning the units are rented only to households with incomes at or below 30 percent of the SMSA); 111 are 50 percent restricted units; and 24 are 60 percent restricted units.

Some 40 to 50 percent of the Josephinium’s tenants are disabled. The Josephinium employs a resident services coordinator, whose duties include providing liaison for tenants to services and to case managers, and organizing projects and special events.

Skye Kahli moved into a 60 percent restricted unit at the Josephinium in 1994. Kahli is disabled, and her income consists of $530 per month in Social Security benefits. Until January 1999, Kahli also received a subsidy from the Shelter Care Plus rent assistance program, which paid all but $125 of her $506 rent.

<<*621>> In January 1999, Kahli lost her rent subsidy, leaving only her disability benefits. Loss of the subsidy meant that Kahli was eligible for a 30 percent unit, and she repeatedly requested that the Josephinium either transfer her to an available 30 percent unit or redesignate her 60 percent unit as a 30 percent unit. A 30 percent unit was available and such transfers were permitted, but the Josephinium refused to transfer Kahli. The Josephinium also refused to redesignate her unit as a 30 percent unit.

Kahli’s lease expired at the end of November, 1999. The Josephinium offered her a new lease,[fn:1] which Kahli signed. In December, however, she tendered only $276 in rent, which she testified was the rent for a vacant 30 percent unit on her floor. Her tender was refused. The Josephinium filed an unlawful detainer action for nonpayment of rent.

[fn:1] The rent increased to $531, which reflected a building-wide increase of five percent.

Kahli asserted disability discrimination as a defense. Specifically, she claimed that the Josephinium refused to redesignate her unit <<**630>> or transfer her because of her disability, and refused to make reasonable accommodation for her disability. The Josephinium denied discrimination, and also argued that discrimination was not a cognizable defense in an unlawful detainer action for nonpayment.

The court ruled that under the circumstances presented, Kahli’s allegations of disability discrimination constituted a cognizable defense to the unlawful detainer. After trial, the court found that the Josephinium did not intentionally discriminate against Kahli or fail to reasonably accommodate her disability. The court issued a writ of restitution. Both parties appeal.

**** Discussion

[1] <<1: 30-k-3137>> [2] We review questions of law de novo.[fn:2] We review challenges to findings of fact for sufficiency of the evidence. <<*622>> The record must contain sufficient evidence to persuade a rational, fair-minded person of the truth of the premise in question.[fn:3]

[fn:2] Mountain Park Homeowners Ass’n v. Tydings, 125 Wash.2d 337, 341, 883 P.2d 1383 (1994).

[fn:3] Canron, Inc. v. Fed. Ins. Co., 82 Wash.App. 480, 486, 918 P.2d 937 (1996).

**** Mootness

[3] <<3: 13-k-6>> [4] <<4: 233-k-1805>> “A case is technically moot if the court cannot provide the basic relief originally sought, or can no longer provide effective relief.”[fn:4] The record indicates that Kahli vacated her apartment at the Josephinium on May 25, 2000. Kahli’s case is thus moot.

[fn:4] Snohomish County v. State, 69 Wash.App. 655, 660, 850 P.2d 546 (1993) (citation omitted).

[5] <<5: 30-k-781>> [6] <<6: 30-k-781>> We may review a moot case if it contains “ ‘matters of continuing and substantial public interest.’ ”[fn:5] In deciding whether review is appropriate, we consider: “ ‘(1) the public or private nature of the question presented; (2) the desirability of an authoritative determination which will provide future guidance to public officers; and (3) the likelihood that the question will recur.’ ”[fn:6] A further consideration is “ ‘whether there is genuine adverseness and quality advocacy on the issues.’ ”[fn:7]

[fn:5] In re R.A.W., 104 Wash.App. 215, 220, 15 P.3d 705 (2001) (quoting Dunner v. McLaughlin, 100 Wash.2d 832, 838, 676 P.2d 444 (1984)).

[fn:6] R.A.W., 104 Wash.App. at 220, 15 P.3d 705 (quoting Dunner, 100 Wash.2d at 838, 676 P.2d 444).

[fn:7] King County v. Cent. Puget Sound Growth Mgmt. Hearing Bd., 91 Wash.App. 1, 23, 951 P.2d 1151 (1998) (quoting Klickitat County Citizens Against Imported Waste v. Klickitat County, 122 Wash.2d 619, 632, 860 P.2d 390, 866 P.2d 1256 (1993)), aff’d in part, rev’d in part, 138 Wash.2d 161, 979 P.2d 374 (1999).

The question of whether discrimination defenses can be asserted in unlawful detainer actions arises with some frequency, and the case law is unsettled. The parties are genuinely adverse, the quality of advocacy is good, and the record includes a thoughtful analysis by an experienced and highly respected trial judge. This case presents a matter of continuing and substantial public interest. We therefore reach the merits.

**** <<*623>> Disability Discrimination

The federal Fair Housing Amendments Act of 1988 (FHAA) prohibits discrimination in housing on the basis of handicap.[fn:8] Unlawful discrimination includes discrimination in “terms, conditions, or privileges of sale or rental of a dwelling, or in the provision of services or facilities in connection with such dwelling.”[fn:9] Discrimination also includes “refusal to make reasonable accommodations in rules, policies, practices, or services, when such accommodations may be necessary to afford such person equal opportunity to use and enjoy a dwelling.”[fn:10] Washington law imposes the same prohibitions and requirements, and provides for various remedies, including injunctive relief.[fn:11]

[fn:8] 42 U.S.C. § 3604(f).

[fn:9] 42 U.S.C. 3604(f)(a).

[fn:10] 42 U.S.C. § 3604(f)(3)(B); United States v. California Mobile Home Park Mgmt. Co., 29 F.3d 1413, 1416 (9th Cir.1994); Groner v. Golden Gate Gardens Apartments, 250 F.3d 1039, 1044 (6th Cir.2001).

[fn:11] RCW 49.60.222, .225.

[7] <<7: 78-k-1083>> [8] <<8: 78-k-1083>> [9] <<9: 78-k-1083>> Kahli alleges direct discrimination and refusal to make reasonable accommodation. <<**631>> An accommodation is reasonable, and therefore required, if it does not cause a “fundamental alteration in the nature of a program” or “ ‘undue financial and administrative burdens.’ ”[fn:12] To accommodate a handicapped tenant, a landlord may be required to incur reasonable costs and/or change a generally applicable rule so that the burden is less onerous on the disabled tenant.[fn:13] Whether a requested accommodation is required under the FHAA is “ ‘highly fact-specific, requiring case-by-case determination.’ ”[fn:14] In determining what constitutes a reasonable accommodation, the fact-finder should balance the burdens <<*624>> imposed on the landlord and the benefits gained by the tenant.[fn:15]

[fn:12] Groner, 250 F.3d at 1044 (quoting Smith & Lee Assocs., Inc. v. City of Taylor, 102 F.3d 781, 795–96 (6th Cir.1996)).

[fn:13] Hubbard v. Samson Mgmt. Corp., 994 F.Supp. 187, 189 (S.D.N.Y.1998).

[fn:14] Groner, 250 F.3d at 1044 (quoting California Mobile Home Park, 29 F.3d at 1418.)

[fn:15] Bronk v. Ineichen, 54 F.3d 425, 428 (7th. Cir.1995); Marthon v. Maple Grove Condominium Ass’n, 101 F.Supp.2d 1041, 1051 (N.D.Ill.2000); Groner, 250 F.3d at 1044.

Kahli alleges she was denied transfer to a less-expensive unit, or redesignation of her own unit, because of her disability. She also alleges she was denied reasonable accommodation for her disability by way of assistance in becoming eligible for the transfer. If Kahli’s contentions are true, the Josephinium violated the discrimination laws. We must determine whether unlawful discrimination can constitute a defense in an unlawful detainer action.

**** Defenses in Unlawful Detainer Actions

[10] <<10: 179-k-6>> [11] <<11: 179-k-6>> [12] <<12: 78-k-1083>> An unlawful detainer action is a summary proceeding to determine the right to possession of property.[fn:16] Its history is grounded in the preservation of peaceful and lawful remedies for the landlord, to avoid forcible evictions.[fn:17] The action is narrow, and the court’s jurisdiction is limited to settling the right of possession.[fn:18] “Issues unrelated to possession are not properly part of an unlawful detainer action.”[fn:19]

[fn:16] RCW 59.12; Heaverlo v. Keico Indus., Inc., 80 Wash.App. 724, 728, 911 P.2d 406 (1996).

[fn:17] See, e.g., Young v. Riley, 59 Wash.2d 50, 52, 365 P.2d 769 (1961).

[fn:18] Munden v. Hazelrigg, 105 Wash.2d 39, 45, 711 P.2d 295 (1985) (citing cases).

[fn:19] Heaverlo, 80 Wash.App. at 728, 911 P.2d 406.

[13] <<13: 179-k-12>> [14] <<14: 179-k-12>> The unlawful detainer statute permits a tenant to assert “any legal or equitable defense or set-off arising out of the tenancy.”[fn:20] An equitable defense arises when “there is ‘a substantive legal right, that is, a right that comes within the scope of judicial [juridicial] action, as distinguished from a mere moral right’ ” and the usual legal <<*625>> remedies are unavailing.[fn:21] To protect the summary nature of the unlawful detainer action, defenses “arise out of the tenancy” only when they affect the tenant’s right of possession or are “ ‘based on facts which excuse a tenant’s breach.’ ”[fn:22] Where a defense exists that arises out of the tenancy, the court must consider it.[fn:23] Conversely, where a defense or counterclaim is not necessary to determining the right to possession, the court has no jurisdiction to consider it in an unlawful detainer action.[fn:24] When the tenant’s breach is failure to pay rent, the inquiry is “whether there is any legal justification for nonpayment.”[fn:25]

[fn:20] RCW 59.18.380.

[fn:21] Port of Longview v. Int’l Raw Mats., Ltd., 96 Wash.App. 431, 437, 979 P.2d 917 (1999) (quoting Motoda v. Donohoe, 1 Wash.App. 174, 175, 459 P.2d 654 (1969)).

[fn:22] Munden, 105 Wash.2d at 45, 711 P.2d 295 (quoting First Union Mgmt., Inc. v. Slack, 36 Wash.App. 849, 854, 679 P.2d 936 (1984)).

[fn:23] Sprincin King St. Partners v. Sound Conditioning Club Inc., 84 Wash.App. 56, 67, 925 P.2d 217 (1996) (“when the counterclaim is based on facts which excuse a tenant’s breach, the court must consider it”).

[fn:24] See First Union Mgmt., Inc. v. Slack, 36 Wash.App. 849, 853–54, 679 P.2d 936 (1984).

[fn:25] Heaverlo, 80 Wash.App. at 731, 911 P.2d 406. See also Income Prop. Inv. Corp. v. Trefethen, 155 Wash. 493, 284 P. 782 (1930) (equitable defenses available in unlawful detainer actions); Andersonian Inv. Co. v. Wade, 108 Wash. 373, 184 P. 327 (1919) (rule prohibiting defenses too broad; tenant may defend by setting up any defense, legal or equitable, which will excuse his breach); Brown v. Baruch, 24 Wash. 572, 64 P. 789 (1901) (equitable estoppel defense permitted); Himpel v. Lindgren, 159 Wash. 20, 291 P. 1085 (1930) (tenants may raise affirmative equitable defenses); Watkins v. Balch, 41 Wash. 310, 83 P. 321 (1906) (same—part performance of an oral contract); Northcraft v. Blumauer, 53 Wash. 243, 101 P. 871 (1909) (same—part performance of an oral lease).

<<**632>> The right to be free from discriminatory eviction is a substantive legal right, and ordinary civil remedies are unavailing in the face of a summary eviction proceeding. A landlord cannot simply decide to evict all tenants of color. If unlawful discrimination is the reason for an eviction, the defense certainly affects the tenant’s right of possession.

Most jurisdictions permit unlawful discrimination to be asserted as a defense in summary eviction proceedings.[fn:26] <<*626>> Washington cases have not previously confronted this precise question. The only discussion in our cases occurred in Housing Authority v. Terry.[fn:27] There, the tenant was evicted for breach of a lease covenant because he created a threat to the health and safety of other tenants. Terry claimed the landlord failed to make reasonable accommodation to him as a handicapped person. The Supreme Court vacated the writ of restitution because the landlord had failed to provide the required statutory notice. The court did not consider Terry’s discrimination claim, both because it was moot, and because “counterclaims may not be asserted in an unlawful detainer action.”[fn:28] As authority for the latter statement, Terry relied on Granat v. Keasler[fn:29] and Woodward v. Blanchett,[fn:30] both of which involved counterclaims not germane to the right of possession. The Terry court undertook no further analysis, and there is no indication the court intended to overrule long-standing case law defining when defenses arise out of a tenancy.

[fn:26] See Newell v. Rolling Hills Apartments, 134 F.Supp.2d 1026, 1038 (N.D.Iowa 2001) (collecting and summarizing cases; holding defense applies in Iowa); Ansonia Acquisition I. LLC v. Francis, 1999 WL 1076142, <<*5>>, 26 Conn. L. Rptr. 363 (Conn.Super.1999); Lable & Co. v. Flowers, 104 Ohio App.3d 227, 235, 661 N.E.2d 782 (1995); Mascaro v. Hudson, 496 So.2d 428, 429 (La.App.1986); Ellis v. Minneapolis Comm’n on Civil Rights, 319 N.W.2d 702, 704 (Minn.1982); Marine Park Assocs. v. Johnson, 1 Ill.App.3d 464, 274 N.E.2d 645 (1971); Abstract Inv. Co. v. Hutchinson, 204 Cal.App.2d 242, 248, 22 Cal.Rptr. 309 (1962). See also Arnold Murray Constr., L.L.C. v. Hicks, 621 N.W.2d 171 (S.D.2001); Malibu Inv. Co. v. Sparks, 996 P.2d 1043 (Utah 2000); Boulder Meadows v. Saville, 2 P.3d 131 (Colo.App.2000); Hous. Auth. of City of Bangor v. Maheux, 748 A.2d 474, 476 (Me.2000); City Wide Assocs. v. Penfield, 409 Mass. 140, 564 N.E.2d 1003 (1991); Schuett Inv. Co. v. Anderson, 386 N.W.2d 249 (Minn.App.1986). But see Lake in the Woods Apartment v. Carson, 651 S.W.2d 556, 558 (Mo.App.1983).

[fn:27] 114 Wash.2d 558, 789 P.2d 745 (1990).

[fn:28] Terry, 114 Wash.2d at 570, 789 P.2d 745.

[fn:29] 99 Wash.2d 564, 570, 663 P.2d 830 (1983).

[fn:30] 36 Wash.2d 27, 216 P.2d 228 (1950).

Discrimination may be a defense that arises out of the tenancy. When it does, the statute permits a tenant to assert the defense and requires the court to consider it.

**** Kahli’s Case

[15] <<15: 78-k-1083>> [16] <<16: 78-k-1083>> Where a tenant does not pay the agreed rent, the tenant’s defense must constitute an excuse for that breach. While <<*627>> discrimination is extremely unlikely to be such a defense, it is not a logical impossibility. This is one of those unlikely cases: if true, Kahli’s defense excused her nonpayment, because had the Josephinium not discriminated against her, Kahli would have occupied a 30 percent unit, and would have owed no more rent than she tendered. The trial court properly concluded that Kahli asserted a cognizable discrimination defense in this unlawful detainer action.

It is undisputed that Kahli is disabled, that the Josephinium had notice of her disabilities, that a 30 percent restricted unit was available, and that the Josephinium had permitted tenants to transfer in the past. It is also undisputed that the Josephinium refused Kahli’s request for transfer solely because of her failure to maintain her current unit in acceptable condition, and that her failure to do so resulted from her mental and physical disabilities.

<<**633>> Kahli was eligible for state-paid chore services, and had previously been able to keep up her apartment. Her chore worker moved away in 1998, however, and her apartment quickly fell into an unacceptable condition. The evidence showed that Kahli’s unit was filthy, debris-filled, infested with pests, and damaged by pets. The Josephinium provides its tenants with assistance from volunteer chore workers, but declined to provide assistance to Kahli on grounds her apartment posed a health hazard to the volunteer. The Josephinium’s services coordinator made efforts to assist Kahli by trying to help her arrange for a new state-paid chore worker and by arranging for cleaning assistance from volunteer crews. Beginning in January 1999, the Josephinium made six attempts to fumigate Kahli’s unit. Kahli did not cooperate with efforts to arrange for a new state chore worker and, on each occasion that fumigation or cleaning was scheduled, she refused to permit the workers to enter. Finally, in October 1999, Kahli requested that the Josephinium send a cleaning crew to her unit. But Kahli apparently becomes overwhelmed by the presence of people in her apartment, and when the crew arrived, she refused them access.

<<*628>> The Josephinium made no further attempt to provide services for Kahli. In November, the new lease was executed. When Kahli failed to pay $531 in rent in December 1999, the Josephinium filed this unlawful detainer action. The Josephinium did not respond to subsequent communications from Kahli.

In March, 2000, a health inspector issued a citation to Kahli for the condition of her unit. When he reinspected in April, he found a “great improvement.”[fn:31] Significant problems remained, however. Despite the cleaning Kahli had done, the Josephinium’s witnesses estimated that transferring her to a new unit would have cost an estimated $3,000 to $5,000 for additional cleaning, paint, carpet, and replacement of pest-infested appliances. The Josephinium’s manager expected the same damage to occur in a new unit, and Kahli’s counselor agreed that the condition of her unit would likely “revert unless there were enough external structures set in place.” He acknowledged that he had not succeeded in meeting that goal despite treating her from 1988 to 1999.[fn:32]

[fn:31] Report of Proceedings (RP) (Apr. 18, 2000) at 121.

[fn:32] RP (Apr. 18, 2000) at 114.

The Josephinium explained that redesignating Kahli’s unit from a 60 percent unit to a 30 percent unit was infeasible for several reasons. First, the designation of rent percentages was derived by square footage, with the 60 percent apartments being the largest. Kahli’s unit occupied a corner and offered a view. A redesignation would have cost $3,000 per year in rent. In addition, the Josephinium’s financial witness testified that redesignation would set a precedent and create an “absolutely detrimental” effect on the long-term financial health of the building.[fn:33]

[fn:33] RP (Apr. 18, 2000) at 172.

The trial court found that the Josephinium’s justifications for refusing to transfer Kahli or redesignate her unit were legitimate and nonpretextual, and that the Josephinium had fulfilled its duty of reasonable accommodation <<*629>> by its offers of services to Kahli. Ultimately, the court ruled that Kahli failed to link the Josephinium’s termination of her tenancy to her disabilities. The evidence supports the court’s findings.

A landlord is not required to incur significant expense or fundamentally alter its programs to accommodate a disability.[fn:34] Most landlords offer no services to tenants, and a tenant’s disability does not create an obligation to do so. At the Josephinium, however, services were available, and Kahli could request such services as an accommodation. The services were amply offered. The court did not err in finding the Josephinium had fulfilled its duty of accommodation, and that its reasons for denying Kahli a transfer or redesignation were legitimate and nondiscriminatory.

[fn:34] Groner v. Golden Gate Gardens Apartments, 250 F.3d 1039, 1044 (6th Cir.2001).

Finally, Kahli contends the Josephinium’s accommodation efforts were inadequate because after the eviction notice was served, <<**634>> her requests for meetings were ignored. She contends the Josephinium’s duty to accommodate her continued to the date of actual eviction, and that the court erred by ignoring events after the notice. Kahli relies upon Radecki v. Joura,[fn:35] and Roe v. Housing Authority,[fn:36] but neither case so holds. Radecki concerns the question of knowledge of a disability, not its reasonable accommodation.[fn:37] Roe holds that accommodation must be attempted before housing can be denied.[fn:38] Neither case discussed a landlord’s duty after accommodation has been offered and has failed, but physical eviction has not yet occurred.

[fn:35] 114 F.3d 115 (8th Cir.1997).

[fn:36] 909 F.Supp. 814 (D.Colo.1995).

[fn:37] Radecki, 114 F.3d at 116–17.

[fn:38] Roe, 909 F.Supp. at 822–23.

Further, Kahli’s accommodation claim is unusually difficult. For many months, the Josephinium attempted to assist Kahli with her housekeeping. Those efforts failed, through no fault of the Josephinium. Still, the Josephinium renewed Kahli’s lease. Only after she failed to pay her rent <<*630>> did these proceedings begin. At that point, Kahli’s defense depended upon the existence of facts excusing her failure to pay rent—which must be facts existing at the time of her breach. We do not address whether efforts to accommodate a disability may be required after an eviction notice in other circumstances; presumably a landlord may not escape an obligation to accommodate merely by serving a notice to vacate. Here, a failure to accommodate could not excuse Kahli’s breach if the failure occurred after the breach, so post-notice conduct was irrelevant. In addition, Kahli’s postnotice communications did not propose a plan of requested accommodation, but only requested a meeting to discuss such a plan. The court did not ignore postnotice conduct, but rather found none relevant to Kahli’s defense. The court was correct.

The trial court did not err in its finding that the Josephinium attempted reasonable accommodation of Kahli’s disability, and that Kahli failed to show her eviction resulted from her disability. The discrimination laws require accommodation of disability, not financial circumstances.

**** Conclusion

The court properly permitted unlawful discrimination to be asserted as a defense to this unlawful detainer action. But the evidence supports the court’s findings that no such discrimination occurred. The court therefore properly issued the writ.

Affirmed.

KENNEDY, J., and APPELWICK, J., concur.
