#+title:      126 Wash.App. 382 Housing Authority of City of Pasco and Franklin County v. Pleasant (2005)
#+date:       [2005-03-15 Tue 15:30]
#+filetags:   :case:possession:rlta:trial:
#+identifier: 20050315T153028

* NOTES
What case authority is there to restore a tenant to possession following an eviction?

The general proposition that even if a tenant vacates pending the execution of a writ of restitution, the tenant does not thereby concede the right to possession and the court

#+begin_quote
We can determine whether Ms. Pleasant's right to possession was wrongfully terminated by the improper issuance of a writ and provide relief by restoring her possession.


Hous. Auth. of City of Pasco & Franklin Cnty. v. Pleasant, 126 Wn. App. 382, 389, 109 P.3d 422, 426 (2005)
#+end_quote

* CASE

Housing Authority of City of Pasco and Franklin County v. Pleasant
Court of Appeals of Washington, Division 3, Panel Seven. | March 15, 2005 | 126 Wash.App. 382 | 109 P.3d 422

Document Details

Outline
Synopsis
West Headnotes
Attorneys and Law Firms
Opinion
All Citations

KeyCite:

KeyCite Yellow Flag - Negative Treatment
 Distinguished by Angelo Property Co., LP v. Hafiz, Wash.App. Div. 2, April 17, 2012

washington Citation:

Hous. Auth. of City of Pasco & Franklin Cnty. v. Pleasant, 126 Wn. App. 382, 109 P.3d 422 (2005)

All Citations:

126 Wash.App. 382, 109 P.3d 422

Search Details

Search Query:

HACPFC Pleasant

Jurisdiction:

Washington

Delivery Details

Date:

January 30, 2024 at 5:27 PM

Delivered By:

Lincoln Harvey

Client ID:

PROCESS

Status Icons:



Inline KeyCite:

Inline KeyCite completed successfully.





KeyCite Yellow Flag - Negative Treatment
 	Distinguished by Angelo Property Co., LP v. Hafiz, Wash.App. Div. 2, April 17, 2012
126 Wash.App. 382
Court of Appeals of Washington,
Division 3,
Panel Seven.
HOUSING AUTHORITY OF the CITY OF PASCO AND FRANKLIN COUNTY, Respondent,
v.
Ianthia PLEASANT, Appellant.
No. 22687–5–III.
|
March 15, 2005.
Synopsis
Background: City housing authority filed an eviction summons and complaint for unlawful detainer against public housing tenant. The Superior Court, Franklin County, Vic L. Vanderschoor, J., issued writ of restitution of premises. Tenant vacated the premises and appealed.

Holdings: The Court of Appeals, Schultheis, J., held that:

[1] tenant’s appeal was not moot, even though she had vacated the premises

[2] tenant was not required to post bond in order to appeal writ of restitution;

[3] housing authority was not entitled to writ of restitution following show cause hearing; and

[4] tenant was not entitled to reasonable attorney fees on appeal.

Reversed and remanded.

Procedural Posture(s): On Appeal.


West Headnotes (23)


[1]

Appeal and ErrorProceedings on Written Evidence


30Appeal and Error
30XVIReview
30XVI(D)Scope and Extent of Review
30XVI(D)11Verdict, Findings, and Sufficiency of Evidence:  Additional Considerations
30k3521Proceedings on Written Evidence
30k3522In general
(Formerly 30k893(1))


When the record consists entirely of written material, an appellate court stands in the same position as the trial court and reviews the record de novo.
5 Cases that cite this headnote



[2]

Landlord and TenantReview


233Landlord and Tenant
233XPublic and Publicly Subsidized Housing
233X(E)Termination of Tenancy;  Eviction
233k2075Proceedings
233k2082Review
(Formerly 268k717.5(8))


Public housing tenant’s appeal of writ of restitution of the premises was not moot in unlawful detainer action, even though she had vacated the premises, as she continued to assert a right of possession.




[3]

ActionMoot, hypothetical or abstract questions


13Action
13IGrounds and Conditions Precedent
13k6Moot, hypothetical or abstract questions


A case is technically moot if the court cannot provide the basic relief originally sought, or can no longer provide effective relief.
4 Cases that cite this headnote



[4]

PropertyPossession in general
PropertyRight to exclude;  ouster


315Property
315IIIProperty Rights and Interests
315III(A)In General
315k62Ownership, Possession, and Incidents Thereof in General
315k67Possession in general
(Formerly 315k10)
315Property
315IIIProperty Rights and Interests
315III(A)In General
315k62Ownership, Possession, and Incidents Thereof in General
315k72Right to exclude;  ouster
(Formerly 315k10)


One may have a right to the possession as against another who has the possession, as in the simple case of one who has been ousted from the land by another.




[5]

Forcible Entry and DetainerNecessity of possession
Forcible Entry and DetainerRight of plaintiff to possession


179Forcible Entry and Detainer
179ICivil Liability
179k9Prior Possession of Plaintiff
179k9(1)Necessity of possession
179Forcible Entry and Detainer
179ICivil Liability
179k10Right of plaintiff to possession


In an unlawful detainer context, it is the right to possession that is pivotal, not mere present possession.
5 Cases that cite this headnote



[6]

Landlord and TenantReview


233Landlord and Tenant
233XPublic and Publicly Subsidized Housing
233X(E)Termination of Tenancy;  Eviction
233k2075Proceedings
233k2082Review
(Formerly 233k291(18))


When the right to possession is at issue in an unlawful detainer action, the issue is not moot on appeal simply because the tenant has vacated the premises.
11 Cases that cite this headnote



[7]

Landlord and TenantActions


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1791In general
(Formerly 233k290(.5))


Once an unlawful detainer action is commenced and the tenant does not concede the landlord’s right to possession, the tenant has the right to have the issue determined.
8 Cases that cite this headnote



[8]

Landlord and TenantDefenses and grounds of opposition in general


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1783Right of Action and Defenses
233k1787Defenses and grounds of opposition in general
(Formerly 233k290(3))


A tenant’s relinquishment of the property does not necessarily mean the right to possession is undisputed so as to preclude a challenge to an unlawful detainer action.




[9]

ActionMoot, hypothetical or abstract questions


13Action
13IGrounds and Conditions Precedent
13k6Moot, hypothetical or abstract questions


An issue is not moot if a court can still provide effective relief.
1 Case that cites this headnote



[10]

Landlord and TenantProceedings


233Landlord and Tenant
233XPublic and Publicly Subsidized Housing
233X(E)Termination of Tenancy;  Eviction
233k2075Proceedings
233k2076In general
(Formerly 233k291(.5))


Tenant was not required to post bond in unlawful detainer action in order to appeal writ of restitution of the premises, as tenant had vacated the premises. West’s RCWA 59.18.390(1), 59.12.200.
3 Cases that cite this headnote



[11]

Landlord and TenantPretrial bonds


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1802Pretrial bonds
(Formerly 233k291(15))


A bond is required only if the tenant, after receipt of a writ of restitution of the premises, wishes to continue to occupy the premises pending trial on an unlawful detainer claim. West’s RCWA 59.18.390(1), 59.12.200.
4 Cases that cite this headnote



[12]

Forcible Entry and DetainerRequisites and proceedings for transfer of cause


179Forcible Entry and Detainer
179ICivil Liability
179k42Review
179k43Appeal and Trial De Novo
179k43(4)Requisites and proceedings for transfer of cause


A bond is not a jurisdictional condition precedent to the maintenance of an appeal under the unlawful detainer statutory scheme. West’s RCWA 59.18.390(1), 59.12.200.
2 Cases that cite this headnote



[13]

Landlord and TenantReview


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1805Review
(Formerly 233k291(18))


An appeal bond need only be filed in an unlawful detainer action if the tenant seeks a stay of the proceedings pending review. West’s RCWA 59.18.390(1), 59.12.200.
2 Cases that cite this headnote



[14]

Landlord and TenantEquitable considerations


233Landlord and Tenant
233IVParticular Kinds of Tenancies and Attributes Thereof
233IV(F)Termination
233IV(F)2Breach of Covenant or Condition
233k911Equitable considerations
(Formerly 233k103(1))


As a general rule, forfeiture or termination of leases is not favored and never enforced in equity unless the right thereto is so clear as to permit no denial.




[15]

Landlord and TenantIllegal conduct


233Landlord and Tenant
233XPublic and Publicly Subsidized Housing
233X(E)Termination of Tenancy;  Eviction
233k2071Grounds for Recovery or Nonrecovery
233k2073Violation of Tenancy
233k2073(5)Illegal conduct
(Formerly 268k717.5(6))


City housing authority was not entitled to writ of restitution of the premises following show cause hearing, even though tenant admitted to criminal conduct in her affidavit; tenant challenged allegations that she was in material noncompliance with her lease terms, there was no competent evidence regarding the lease itself, and there was no affidavit required for proof of service of notice. West’s RCWA 59.12.130, 59.12.140; CR 4(g).
3 Cases that cite this headnote



[16]

Forcible Entry and DetainerPresumptions and burden of proof


179Forcible Entry and Detainer
179ICivil Liability
179k29Evidence
179k29(1)Presumptions and burden of proof


The burden is upon the plaintiff in an unlawful detainer action to prove, by a preponderance of the evidence, the right to possession.
9 Cases that cite this headnote



[17]

Forcible Entry and DetainerInquisition or Other Summary Proceeding, and Review Thereof


179Forcible Entry and Detainer
179ICivil Liability
179k21Inquisition or Other Summary Proceeding, and Review Thereof
179k21(.5)In general


A show cause hearing in an unlawful detainer action is a summary proceeding.
4 Cases that cite this headnote



[18]

Forcible Entry and DetainerTraverse and proceedings thereon in general


179Forcible Entry and Detainer
179ICivil Liability
179k21Inquisition or Other Summary Proceeding, and Review Thereof
179k21(2)Traverse and proceedings thereon in general


In summary proceedings in an unlawful detainer action, the rules of evidence still apply; inadmissible evidence may not be considered.
1 Case that cites this headnote



[19]

Forcible Entry and DetainerRequisites and sufficiency


179Forcible Entry and Detainer
179ICivil Liability
179k11Notice to Quit and Demand of Possession
179k11(2)Requisites and sufficiency


A writ of restitution of the premises cannot issue without competent evidence to prove substantial compliance with the notice requirements of the unlawful detainer statute. West’s RCWA 59.12.040.
1 Case that cites this headnote



[20]

Landlord and TenantTrial


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1803Trial
(Formerly 233k291(16))


When a tenant challenges her landlord’s allegations in an unlawful detainer action that she was in material noncompliance with her lease terms, she is entitled to a trial. West’s RCWA 59.12.040.
3 Cases that cite this headnote



[21]

Landlord and TenantProceedings


233Landlord and Tenant
233XPublic and Publicly Subsidized Housing
233X(E)Termination of Tenancy;  Eviction
233k2075Proceedings
233k2076In general
(Formerly 233k291(.5))


A landlord may apply for a writ of restitution of the premises to expeditiously determine who should possess the property while an unlawful detainer action is pending against tenant. West’s RCWA 59.18.370.
1 Case that cites this headnote



[22]

Forcible Entry and DetainerInquisition or Other Summary Proceeding, and Review Thereof


179Forcible Entry and Detainer
179ICivil Liability
179k21Inquisition or Other Summary Proceeding, and Review Thereof
179k21(.5)In general


A show cause hearing is not the final determination of the rights of the parties in an unlawful detainer action. West’s RCWA 59.18.380.
4 Cases that cite this headnote



[23]

Landlord and TenantRemedies


233Landlord and Tenant
233XPublic and Publicly Subsidized Housing
233X(E)Termination of Tenancy;  Eviction
233k2075Proceedings
233k2081Remedies
(Formerly 233k291(14))


Tenant was not entitled to reasonable attorney fees on appeal which successfully challenged writ of restitution of premises; unlawful detainer statute only provided for attorney fees if landlord had removed or excluded tenant without a court order, and did not provide for attorney fees for a wrongfully issued writ. West’s RCWA 59.18.290(1); RAP 18.1.
3 Cases that cite this headnote



Attorneys and Law Firms
**424 George Fearing, Attorney at Law, Kennewick, WA, for Appellant.
Kenneth J. Diamond, Lisa Marie Vanderford–Anderson, Attorneys at Law, Seattle, WA, for Respondent.
Opinion

SCHULTHEIS, J.

*385 ¶ 1 Ianthia Pleasant was evicted from public housing administered by the Housing Authority of the City of Pasco and Franklin County (Housing Authority) for lease violations. In the Housing Authority’s ensuing unlawful detainer action, the trial court issued a writ of restitution of premises at a show cause hearing. Ms. Pleasant vacated the premises and appealed. She contends the writ issued on insufficient and incompetent evidence and she was entitled to a trial. We agree, reverse, and remand for trial.



*386 FACTS
¶ 2 On July 18, 2003, the Housing Authority filed an eviction summons and complaint for unlawful detainer against Ms. Pleasant. The complaint alleged two bases for eviction involving lease violations. The first charged a variety of lease violations over the preceding year, including the most recent failure of a semiannual inspection of the premises. The Housing Authority served a 30–day notice terminating tenancy on March 27. An informal hearing through the agency was decided against her. Her request for a formal hearing was denied as untimely. The second basis for eviction alleged a lease violation for criminal activity for which Ms. Pleasant was served a three-day notice to terminate. The Housing Authority contended that Ms. Pleasant engaged in prohibited criminal activity, as evidenced by her arrest on May 21, 2003. She was charged with third degree assault of a child when she struck her 13–year–old son several times with a plastic clothes hanger because he failed to obey her. The charge was reduced to fourth degree assault, a misdemeanor, on May 27.

¶ 3 Ms. Pleasant filed a written answer to the complaint and a counterclaim. She denied the contentions and alleged harassment and/or discrimination on the basis of disability and race.

¶ 4 On December 5, 2003, the Housing Authority filed a motion for an order to show cause why a writ of restitution should not issue. The court entered an order to show cause on December 8. A show cause hearing was scheduled for December 22. Ms. Pleasant opposed the issuance of the writ by filing an affidavit in which she challenged the facts for the Housing Authority’s first basis for eviction (the multiple violations). A friend of Ms. Pleasant’s also filed an affidavit that contradicted these facts. On the second basis for eviction (the assault arrest) she countered that the misdemeanor to which she pleaded guilty while acting pro se was not a crime for which eviction was appropriate as it did not endanger other tenants. She also pointed out she had never had her children taken away because of abuse.

*387 ¶ 5 On December 22, 2003, the trial court issued a writ of restitution. The judge took no testimony. On December 23, the sheriff served a notice to terminate by December 31 or face forceful eviction. Ms. Pleasant vacated and filed this appeal. She seeks to regain housing through the Housing Authority’s facilities.



DISCUSSION

STANDARD OF REVIEW
[1] ¶ 6 When the record consists entirely of written material, an appellate court stands in the same position as the trial court and reviews the record de novo. Progressive Animal Welfare Soc’y v. Univ. of Wash., 125 Wash.2d 243, 252, 884 P.2d 592 (1994); **425 Amren v. City of Kalama, 131 Wash.2d 25, 32, 929 P.2d 389 (1997). Additionally, the dispositive issue in this case is the procedural requirements under the unlawful detainer statutes. Issues of statutory interpretation are reviewed de novo. Hartson P’ship v. Goodwin, 99 Wash.App. 227, 231, 991 P.2d 1211 (2000).



MOOTNESS
[2] [3] ¶ 7 “ ‘A case is technically moot if the court cannot provide the basic relief originally sought, or can no longer provide effective relief.’ ” Josephinium Assocs. v. Kahli, 111 Wash.App. 617, 622, 45 P.3d 627 (2002) (quoting Snohomish County v. State, 69 Wash.App. 655, 660, 850 P.2d 546 (1993)). The Housing Authority argues that since Ms. Pleasant does not have possession of the premises, the appeal is moot. However, the law draws a distinction between possession and the right of possession. Kessler v. Nielsen, 3 Wash.App. 120, 126, 472 P.2d 616 (1970).

[4] [5] [6] ¶ 8 “ ‘[O]ne may have a right to the possession as against another who has the possession, as in the simple case of one who has been ousted from the land by another.”’ Id. (quoting 1 HERBERT THORNDIKE TIFFANY, THE LAW OF REAL PROPERTY § 20, at 28 (Basil Jones ed., 3d ed. 1939)). In an unlawful detainer context, it is the right to possession that is pivotal, not mere present possession. *388 Little v. Catania, 48 Wash.2d 890, 893, 297 P.2d 255 (1956); First Union Mgmt., Inc. v. Slack, 36 Wash.App. 849, 853–54, 679 P.2d 936 (1984); Motoda v. Donohoe, 1 Wash.App. 174, 175, 459 P.2d 654 (1969). When the right to possession is at issue, the issue is not moot. Lochridge v. Natsuhara, 114 Wash. 326, 330, 194 P. 974 (1921). The Washington Supreme Court has specifically held that an unlawful detainer case is not moot simply because the tenant does not have possession of the premises at the time of appeal. Id. “[E]ven though the [landlords] were in possession at the time of the appeal, the [tenants] who were still asserting their possessory right had to be precluded as to this right. The action was not moot until this issue had been determined vis-à-vis the parties.” Kessler, 3 Wash.App. at 126, 472 P.2d 616. Here, Ms. Pleasant continues to assert a right to possession. The issue is therefore not moot.

¶ 9 The Housing Authority relies on Josephinium, 111 Wash.App. 617, 45 P.3d 627. In that case, Division One of this court, without discussion or citation to authority, held that the tenant’s evacuation during the pendency of the action mooted the issue. Id. at 622, 45 P.3d 627. Neither the legal nor the factual basis upon which Division One determined the issue to be moot is clear. The court did not consider the tenant’s right to possession when addressing mootness.1 Nonetheless, Josephinium is distinguishable on its facts. The unlawful detainer in Josephinium was based upon the landlord’s refusal of the tenant’s tender of a reduced rent payment. The case before us does not deal with failure to pay rent. Additionally, the court in Josephinium appears to have decided the issue was moot because the tenant vacated voluntarily, i.e., without compulsion of a writ. See Kato v. Union Oil Co., 91 Wash. 302, 157 P. 688 (1916) (holding that return of property was not a voluntary *389 satisfaction of the judgment even where appellant neither sought stay of execution nor gave supersedeas bond); Proctor v. Appleby, 110 Wash. 403, 411–12, 188 P. 481 (1920) (holding that surrender of stock in compliance with judgment before appeal perfected did not amount to a cessation of the controversy thereby barring appeal); Josevig–Kennecott Copper Co. v. James F. Howarth Co., 261 F. 567, 568 (9th Cir.1919) (applying Washington law and determining that where stock was transferred to the plaintiff after time that supersedeas bond could be had, and transfer was made under threat of contempt, transfer did not affect right to appeal). That is also not the case here.

1

Although moot, Division One reached the merits on an exception to mootness: the issue of whether the tenant’s asserted defense of disability discrimination was a cognizable defense was a matter of “continuing and substantial public interest.” Josephinium, 111 Wash.App. at 622, 45 P.3d 627. The court addressed the right to possession in the context of the tenant’s disability discrimination defense. Id . at 624–26, 45 P.3d 627. It held that under the facts of the case, the defense bore upon the tenant’s right to possession.


**426 [7] [8] [9] ¶ 10 Once an unlawful detainer action is commenced and the defendant does not concede the right to possession, the defendant has the right to have the issue determined. Kessler, 3 Wash.App. at 126–27, 472 P.2d 616. A tenant’s relinquishment of the property does not necessarily mean the right to possession is undisputed. Sullivan v. Purvis, 90 Wash.App. 456, 459, 966 P.2d 912 (1998). An issue is not moot if a court can still provide effective relief. State v. Turner, 98 Wash.2d 731, 733, 658 P.2d 658 (1983). Here, the right to possession is disputed. We can determine whether Ms. Pleasant’s right to possession was wrongfully terminated by the improper issuance of a writ and provide relief by restoring her possession.



BOND REQUIREMENT
[10] ¶ 11 The Housing Authority argues that since Ms. Pleasant did not seek to retain possession of the premises and post a bond pending appeal, she has no right to appeal. RCW 59.18.390(1) provides that within three days of the service of the writ of restitution, the tenant
may execute to the plaintiff a bond to be filed with and approved by the clerk of the court in such sum as may be fixed by the judge, with sufficient surety to be approved by the clerk of the court, conditioned that they will pay to the plaintiff such sum as the plaintiff may recover for the use and occupation of the premises, or any rent found due, together with all damages *390 the plaintiff may sustain by reason of the defendant occupying or keeping possession of the premises.
(Emphasis added.) The legislature’s use of “may” instead of “must” makes it permissive. Canyon Lumber Co. v. Sexton, 93 Wash. 620, 626, 161 P. 841 (1916).

[11] ¶ 12 RCW 59.12.200 provides that “if the [tenant] appealing desires a stay of proceedings pending review, the [tenant] shall execute and file a bond.” (Emphasis added.) RCW 59.12.220 provides that if a writ of restitution has been issued and executed, then the posting of the bond entitles the tenant to be restored to possession of the premises, where the tenant is entitled to remain until the appeal is determined. A bond is required only if the tenant wishes to continue to occupy the premises pending trial. It is to secure the landlord against losses during the pendency of the proceedings when the tenant continues to occupy the premises. RCW 59.18.390.

[12] [13] ¶ 13 The bond need be filed only if the tenant seeks a stay pending review. A bond is not a jurisdictional condition precedent to the maintenance of an appeal under the unlawful detainer statutory scheme.



SUMMARY PROCEEDINGS FOR PENDENTE LITE WRIT
¶ 14 Since the dispute involves a residential lease we apply the Residential Landlord–Tenant Act of 1973, chapter 59.18 RCW, to this case. However, the procedures found in the unlawful detainer statutes, chapter 59.12 RCW, apply to the extent they are not supplanted by those found in the Residential Landlord–Tenant Act.

[14] ¶ 15 As a general rule, forfeiture or termination of leases is “ ‘not favored and never enforced in equity unless the right thereto is so clear as to permit no denial.’ ” Shoemaker v. Shaug, 5 Wash.App. 700, 704, 490 P.2d 439 (1971) (quoting John R. Hansen, Inc. v. Pac. Int’l Corp., 76 Wash.2d 220, 228, 455 P.2d 946 (1969)). At any time during an unlawful detainer proceeding the landlord may apply to the court for a pendente lite writ of restitution. RCW 59.18.370. *391 In order to obtain such a writ of restitution the landlord must apply to the court for an order directing the tenant to appear and show cause why a writ should not issue restoring the landlord to possession of the property. Id. At the time of the show cause hearing “[t]he court shall examine the parties and witnesses orally to ascertain the merits of the complaint and answer.” RCW 59.18.380 (emphasis added). “[I]f it shall appear that the [landlord] has the right to be restored to possession of the property, the court shall enter an order directing the issuance of a writ of restitution.” Id. “The court shall also enter an order directing the parties to proceed to trial on the complaint and answer in the usual manner.” Id. (emphasis added). The court may also at that time **427 address other relief requested by the landlord together with the tenant’s defenses and set-off claims as relates to that relief. Id.

¶ 16 Here, neither party provided the transcript from the show cause hearing at which the writ of restitution issued. Ms. Pleasant contends that the judge did not conduct an evidentiary hearing as contemplated by the statute. The Housing Authority claims that the documentary evidence provided by Ms. Pleasant was a sufficient basis for the issuance of the writ of restitution. Nonetheless, the Housing Authority concedes that the judge did not hear testimony or examine the parties or witnesses; rather, it based the issuance of the writ on argument.

¶ 17 The statute uses the mandatory term “shall,” which requires that the parties and any witnesses be examined. RCW 59.18.380. Its use of the word “shall” is presumptively imperative and operates to create a mandatory duty. See State v. Marking, 100 Wash.App. 506, 510, 997 P.2d 461 (2000). The examination of parties and witnesses is not a formality as the Housing Authority asserts. It is the basis for the issuance of the writ pendente lite. Further, the statute uses the term “shall” in directing that the matter be set for trial. RCW 59.18.380.

*392 ¶ 18 The Housing Authority asserts2 that since there is no report of proceedings we must assume the evidence sustained the court’s findings. That rule limits review to a determination of whether the findings support the judgment. Chace v. Kelsall, 72 Wash.2d 984, 987, 435 P.2d 643 (1967). Because the court made no findings, the rule does not apply.

2

The Housing Authority included an unpublished case to support this proposition. It need not, and will not, be considered. RAP 10.4(h); Sundquist Homes, Inc. v. Snohomish County Pub. Util. Dist. No. 1, 140 Wash.2d 403, 409 n. 3, 997 P.2d 915 (2000).




ISSUANCE OF WRIT
[15] [16] [17] [18] [19] ¶ 19 The burden is upon the plaintiff in an unlawful detainer action to prove, by a preponderance of the evidence, the right to possession. Duprey v. Donahoe, 52 Wash.2d 129, 135, 323 P.2d 903 (1958). A show cause hearing in an unlawful detainer action is a summary proceeding. Carlstrom v. Hanline, 98 Wash.App. 780, 788, 990 P.2d 986 (2000). In summary proceedings, the rules of evidence still apply; inadmissible evidence may not be considered. Unger v. Cauchon, 118 Wash.App. 165, 177 n. 34, 73 P.3d 1005 (2003) (citing Dunlap v. Wayne, 105 Wash.2d 529, 535, 716 P.2d 842 (1986)). At oral argument, the Housing Authority argued that because Ms. Pleasant admitted to criminal conduct in her affidavit, it needed no more proof. However, because there is no competent evidence regarding a lease at all, the Housing Authority cannot prove a violation under one. Further, a writ of restitution cannot issue without competent evidence to prove substantial compliance with the statutory notice requirements. Marsh–McLennan Bldg., Inc. v. Clapp, 96 Wash.App. 636, 641–42, 980 P.2d 311 (1999). For instance, proof of service of the notice under the unlawful detainer statutes requires an affidavit. Id. at 640–41, 980 P.2d 311 (citing RCW 59.12.040 and CR 4(g)). There is no affidavit here.

[20] ¶ 20 Moreover, if the pleadings in an unlawful detainer action disclose a material issue of fact, the issue must be resolved at trial. RCW 59.12.130; Meadow Park *393 Garden Assocs. v. Canley, 54 Wash.App. 371, 372, 773 P.2d 875 (1989). Specifically, when a tenant challenges her landlord’s allegations that she was in material noncompliance with her lease terms, she is entitled to a trial. Meadow Park, 54 Wash.App. at 372, 773 P.2d 875. That is precisely the contention made by Ms. Pleasant.

¶ 21 Ms. Pleasant contends the lease and its termination are subject to the U.S. Housing Act. The Housing Authority’s own materials cite to the U.S. Housing Act and point out that Ms. Pleasant is subject to its provisions. The U.S. Housing Act requires that the tenancies be terminated only for “serious or repeated violation of the terms or conditions of the lease or for other good cause” and that termination for “criminal activity” threaten the “health, safety, or right to peaceful enjoyment of the premises by other tenants.” 42 U.S.C. § 1437d(l )(5), (6). The issue of whether these requirements are met **428 under the statute was an inappropriate issue to summarily resolve. See Hartson P’ship v. Goodwin, 99 Wash.App. 227, 237, 991 P.2d 1211 (2000). Ms. Pleasant was entitled to a trial on this issue.

¶ 22 The writ was premature. We need not address the merits of the forfeiture or the defenses that should be addressed at trial on remand. See id.



TRIAL REQUIRED
¶ 23 Whether or not the court issues a pendente lite writ at the show cause hearing, the court is required to enter an order directing the matter to proceed to trial. RCW 59.18.380. See also RCW 59.12.130 (providing that all factual issues in unlawful detainer actions must be determined by a jury unless one is waived). RCW 59.18.410 also requires the entry of a final judgment following trial. The court did not set a trial in this case, nor was a final judgment entered.

[21] [22] ¶ 24 The Housing Authority asserts that no trial was required because the show cause hearing is the only summary proceeding required under the statute. It relies *394 on Carlstrom, 98 Wash.App. 780, 990 P.2d 986. In Carlstrom, Division One of this court observed, “Show cause hearings are summary proceedings to determine the issue of possession pending a lawsuit.” Id. at 788, 990 P.2d 986 (emphasis added) (citing Meadow Park, 54 Wash.App. at 375, 773 P.2d 875). The statute allows a landlord to apply for a writ to expeditiously determine who should possess the property while an unlawful detainer action is pending. Meadow Park, 54 Wash.App. at 376, 773 P.2d 875. In fact, since a pendente lite writ issues on summary proceedings, the landlord is typically required to post a bond3 to take possession. RCW 59.18.380. That is because “[a] show cause hearing is not the final determination of the rights of the parties in an unlawful detainer action.” Carlstrom, 98 Wash.App. at 788, 990 P.2d 986. Carlstrom does not support the Housing Authority’s argument.

3

Under these facts, the Housing Authority, as a quasi-municipal corporation, would probably be exempt from having to file a bond. RCW 4.96.050. See RCW 4.96.010(2) (providing that RCW 4.96.050 applies to municipal and quasi-municipal corporations); RCW 35.82.030 (authorizing creation of housing authorities); Housing Auth. of City of Seattle v. City of Seattle, 56 Wash.2d 10, 13, 351 P.2d 117 (1960) (observing that housing authorities were created as municipal corporations).




ATTORNEY FEES
[23] ¶ 25 Under RAP 18.1, a party may recover reasonable attorney fees and expenses on appeal if applicable law grants the party such right. Ms. Pleasant requested attorney fees under RCW 59.18.410. That statute, however, applies only to fees and costs to a landlord on final judgment. RCW 59.18.290(1)4 provides for attorney fees when the landlord removes or excludes a tenant without a court order. Gray v. Pierce County Housing Auth., 123 Wash.App. 744, 759–60, 97 P.3d 26 (2004). Here, a writ was issued. The statute does not provide for attorney fees for a wrongfully *395 issued writ. She has provided no clear authority for attorney fees.

4

RCW 59.18.290(1) provides: “It shall be unlawful for the landlord to remove or exclude from the premises the tenant thereof except under a court order so authorizing. Any tenant so removed or excluded in violation of this section may recover possession of the property or terminate the rental agreement and, in either case, may recover the actual damages sustained. The prevailing party may recover the costs of suit or arbitration and reasonable attorneys fees.”




CONCLUSION
¶ 26 The pendente lite writ of restitution was issued on incompetent evidence and without examination of the parties and witnesses as required by statute. Ms. Pleasant was wrongfully denied a trial. We therefore reverse and remand for trial. Ms. Pleasant’s request for fees is denied.

WE CONCUR: KATO, C.J., and KURTZ, J.
All Citations
126 Wash.App. 382, 109 P.3d 422
End of Document

© 2024 Thomson Reuters. No claim to original U.S. Government Works.
