#+title:      131 Wash.App. 1035 Kendall v. Klein (2006)
#+date:       [2006-02-13 Mon 14:50]
#+filetags:   :5918060:case:need:rlta:unpublished:
#+identifier: 20060213T145030

* Email message
[[mu4e:msgid:MN6PR14MB7341E4032A1F08A9526448BCD17E2@MN6PR14MB7341.namprd14.prod.outlook.com][Re: [HTF] Can Landlord be Liable for Tenant's Hotel Costs]]

* Brief

** Measure of Damages for LL Breach of Duties under RLTA

The court, in its findings of fact and conclusions of law, stated that
Klein breached his duties under the RLTA by not providing water
service but then did not award any damages to Kendall.

The proper measure of damages for a breach of a landlord's duties
under RCW 59.18.060 is
- the difference between the value of the lease as warranted and the
  value of the lease with the defects. RCW 59.18.110(1)(b).

Thus, if Kendall had proved that the lease's value was diminished
because of the lack of water, the trial court could have awarded a
partial or complete return of rent paid.

- Kendall v. Klein, 131 Wn. App. 1035 (2006)


** Damages cannot be speculative and must be proven with reasonable certainty

A damage award cannot be speculative, but must be reasonably
certain. Larsen v. Walton Plywood Co., 65 Wn.2d 1, 16, 390 P.2d 677
(1964). Kendall, however, did not put forth any evidence about the
diminished value of the property without potable water.
- He testified about the inconvenience that resulted from the lack of
  potable water, but never placed a value on that inconvenience or
  opined about a diminished value.
- He also did not bring forth any expert witnesses to testify about
  the diminished value.
- The only evidence about the value of the lease was Kendall and
  Klein's testimony agreeing that $600 a month was a low price for the
  property and that they arrived at that price because the property
  had so many defects.

Without putting forward any evidence as to the damages flowing from
the breach of Klein's duty to provide potable water to the property,
Kendall was not entitled to a rent reduction and the trial court's
finding of no reimbursement is supported by the evidence.

- Kendall v. Klein, 131 Wn. App. 1035 (2006)

** Breach of LL Duties to Repair

When a landlord has notice of property defects but fails to make
repairs, the tenant may sue and recover damages for the landlord's
breach. The measure of damages is the diminution in rental value of
the premises caused by the defects. Pappas v. Zerwoodis, 21 Wn.2d 725,
153 P.2d 170 (1944).

- Kendall v. Klein, 131 Wn. App. 1035 (2006)


As with the rental reimbursement Kendall sought for the lack of water,
he again failed to prove how much the lease's value was diminished
because of the defects. Without any evidence as to the diminished
value of the lease, the trial court had no basis to award a rental
reimbursement and we affirm its refusal to do so.

* Case

Kendall v. Klein
Court of Appeals of Washington, Division 1. | February 13, 2006 | Not Reported in P.3d | 131 Wash.App. 1035

Document Details

Outline
Attorneys and Law Firms
Unpublished Opinion
All Citations

washington Citation:

Kendall v. Klein, 131 Wn. App. 1035 (2006)

All Citations:

Not Reported in P.3d, 131 Wash.App. 1035, 2006 WL 322362

Search Details

Jurisdiction:

Washington

Delivery Details

Date:

January 29, 2024 at 4:46 PM

Delivered By:

Lincoln Harvey

Client ID:

PROCESS

Status Icons:



Inline KeyCite:

Inline KeyCite completed successfully.




131 Wash.App. 1035
NOTE: UNPUBLISHED OPINION, SEE WA R GEN GR 14.1
Court of Appeals of Washington,
Division 1.
Greg KENDALL, a single man, Appellant,
v.
Joe KLEIN, a single man, Respondent.
No. 54998–7–I.
|
Feb. 13, 2006.
Appeal from Superior Court of Whatcom County; Hon. Michael F. Moynihan, J.
Attorneys and Law Firms
David G. Porter, Attorney at Law, Bellingham, WA, for Appellant.
Jeffrey J. Arntzen, Attorney at Law, Blaine, WA, Thomas Hughes Flattery, Attorney at Law, Bellingham, WA, for Respondent.



Unpublished Opinion
COLEMAN, J.
*1 Greg Kendall sued his former landlord, Joe Klein, after he vacated Klein’s property. Kendall appeals the trial court’s finding that he was not entitled to damages for the lack of potable water to the property or for Klein’s failure to make certain repairs. He also argues that he should have been reimbursed for the labor he expended making repairs to the property. Because the record supports all of the trial court’s findings as to damages and reimbursements due to Kendall, we affirm those findings. We do, however, reverse the court’s award of attorney fees to Klein.



IFACTS
Kendall began renting property in Blaine from Klein on September 1, 1998. The piece of property had multiple buildings on it, and Kendall intended to use his portion of the property as both his residence and for his tree service business. Klein also lived on the property in a recreational vehicle. When Kendall contracted with Klein and commenced his tenancy, there was no Blaine City Water service to the house. The water service had been terminated months earlier due to a billing dispute between the city and Klein. Kendall knew there was no water service, but there was a well on the property and Klein told Kendall he could use the well water while he handled the billing dispute with the city. Kendall was not satisfied with the well water because a test had revealed it was unsatisfactory, and Klein addressed the problem by providing Kendall with five gallons of bottled water per week. Kendall continued to use well water for bathing and other nondrinking purposes. Blaine City Water was not reconnected to the property until August 18, 1999—347 days after Kendall’s lease commenced.

The house and property had many physical and structural defects, and Kendall notified Klein of these defects. From October 1998 to November 1999, Kendall deducted his repair expenses from his rent payments. In December 1999, Klein hired a property manager, and the manager discontinued the deductions because there had not been a deduction agreement in writing.

Kendall gave Klein written notice in January 2000 of remaining defects on the property, but Klein did not repair any of these defects. Kendall remained on the property despite the defects. Later that spring, when he discovered that operating his business did not comply with the zoning requirements of the property, Kendall began searching for a more suitable location. He vacated Klein’s property on July 30, 2000. After moving out, Kendall sued Klein, claiming, inter alia, that he had breached duties under the Residential Landlord–Tenant Act (RLTA) by not providing water service, that he had intentionally terminated his tenant’s water supply within the meaning of RCW 59.18.300, that he had breached an oral contract to reimburse Kendall for out-of-pocket costs and labor expended making repairs to the property, and that he had breached his duty to repair defects after written notice was provided.

The trial court ruled that Klein had breached his duty to provide water service to his tenant and his duty to repair and that he had agreed to reimburse Kendall’s out-of-pocket expenses. Kendall was awarded $5,159.89 for out-of-pocket expenses and $5,000 in attorney fees. The trial court offset Kendall’s attorney fees award by $1,000, for an award to Klein for successfully defending Kendall’s claim that he intentionally terminated Kendall’s water supply. The trial court refused to award Kendall any rent deduction during the period where Blaine City Water service was not connected to the property and also denied his claim for a rent deduction under RCW 59 .18.110 for alleged structural and safety defects in the property that Klein did not repair. Kendall appeals, asserting five assignments of error.



ANALYSIS

Termination of Utilities
*2 RCW 59.18.300 awards a tenant $100 for each day a landlord unlawfully terminates utilities to the leased property. Kendall argues that this statute applies to the situation here and therefore argues it was error for the trial court to deny his request for the award for 347 days without water service. Klein argues that this statute covers a different situation—one where the landlord terminates services during the lease.

Kendall correctly points out that the statute does not specify that the termination of water service must occur during the lease in order to trigger the $100 a day award. But it is not logical to assume that an RCW 59.18.300 termination could occur before the start of a tenancy because the statute uses the language “landlord” and “tenant,” and before a lease exists, there is no landlord or tenant. Furthermore, another section of the RLTA more closely addresses the situation here:
The landlord will at all times during the tenancy keep the premises fit for human habitation, and shall in particular:
...
(10) Except where the building is not equipped for the purpose, provide facilities adequate to supply heat and water and hot water as reasonably required by the tenant.
RCW 59.18.060. It is clear that the utilities termination section is intended to prohibit landlords from attempting to evict tenants by cutting off utilities service, but that situation did not occur here. Because the trial court applied the RLTA section that logically applies to this situation—lack of water as a breach of landlord’s duty to maintain habitability rather than as an intentional termination—we affirm the trial court’s refusal to award damages under RCW 59.18.300.



Rent Reimbursement
Kendall requested a return of all rent he paid to Klein during the 347 days there was no water service to the property. The trial court found that because Kendall remained on the property, even without water, he “got his money’s worth.” Verbatim Report of Proceedings (VRP) (Aug. 31, 2004) at 138. Kendall acknowledges that he did not vacate the premises (he testified he could not afford to move), but he argues he had the right to request the return of rental payments, based on the diminished value of the lease due to the lack of water, without vacating. See RCW 59.18.110(1)(b); Luxon v. Caviezel, 42 Wn.App. 261, 266 (noting that a house purchaser need not move off the property to prove breach of an implied warranty of habitability).

The court, in its findings of fact and conclusions of law, stated that Klein breached his duties under the RLTA by not providing water service but then did not award any damages to Kendall. The proper measure of damages for a breach of a landlord’s duties under RCW 59.18.060 is the difference between the value of the lease as warranted and the value of the lease with the defects. RCW 59.18.110(1)(b). Thus, if Kendall had proved that the lease’s value was diminished because of the lack of water, the trial court could have awarded a partial or complete return of rent paid.

*3 A damage award cannot be speculative, but must be reasonably certain. Larsen v. Walton Plywood Co., 65 Wn.2d 1, 16, 390 P.2d 677 (1964). Kendall, however, did not put forth any evidence about the diminished value of the property without potable water. He testified about the inconvenience that resulted from the lack of potable water, but never placed a value on that inconvenience or opined about a diminished value. He also did not bring forth any expert witnesses to testify about the diminished value. The only evidence about the value of the lease was Kendall and Klein’s testimony agreeing that $600 a month was a low price for the property and that they arrived at that price because the property had so many defects. Without putting forward any evidence as to the damages flowing from the breach of Klein’s duty to provide potable water to the property, Kendall was not entitled to a rent reduction and the trial court’s finding of no reimbursement is supported by the evidence.



Reimbursement of Labor Costs
Kendall testified that he and Klein agreed that Kendall would be reimbursed $15 per hour for any labor he expended making repairs to the property. Klein did not support or refute this testimony specifically; he did testify that they did not make arrangements for reimbursement except in a few specific circumstances—they had no ongoing understanding. Kendall submitted exhibits consisting of all the receipts for costs expended making repairs to the property, which included an amount for his own labor (not broken down by hour or explained beyond the final total). The court, however, found that Kendall was not entitled to an award for his labor because such costs “[had not been] contemplated by the parties.”

Klein argues that because he testified that there was no formal arrangement about reimbursement, the court could have inferred from that testimony that the parties did not contemplate reimbursement for Kendall’s labor. Furthermore, Klein asserts that because Kendall deducted out-of-pocket expenses, but not costs for his own labor, from his rent checks, and because Kendall never asked for reimbursement for his labor prior to filing suit, the court’s finding was supported by substantial evidence.

This court reviews findings of fact for substantial evidence. Landmark Dev., Inc. v. City of Roy, 138 Wn.2d 561, 573, 980 P.2d 1234 (1999). Here, the trial record contains both Kendall’s testimony about the reimbursement arrangement and Klein’s testimony disputing the existence of such an arrangement. Klein also testified that Kendall never asked for reimbursement for his labor prior to filing suit and that he had never deducted labor costs from his rent checks (but only deducted out-of-pocket expenses). We thus affirm the trial court’s judgment as to the credibility of the conflicting testimony because it is supported by substantial evidence.



Failure to Make Repairs
Kendall testified that he gave Klein written notice of property defects, but Klein did not make any of the repairs. Because these defects remained, Kendall argued that he should receive a rent reduction of $300 per month for the seven months the defects persisted before he vacated the property.

*4 When a landlord has notice of property defects but fails to make repairs, the tenant may sue and recover damages for the landlord’s breach. The measure of damages is the diminution in rental value of the premises caused by the defects. Pappas v. Zerwoodis, 21 Wn.2d 725, 153 P.2d 170 (1944). As with the rental reimbursement Kendall sought for the lack of water, he again failed to prove how much the lease’s value was diminished because of the defects. Without any evidence as to the diminished value of the lease, the trial court had no basis to award a rental reimbursement and we affirm its refusal to do so.



Klein’s Attorney Fees at Trial
The trial court awarded attorney fees to both Kendall and Klein, with Klein’s smaller award offsetting Kendall’s award. Klein’s attorney did not enter declarations or evidence of any kind explaining the attorney fees accrued in this case. When questioned by the court, Klein’s attorney orally estimated the amount that he (and another attorney not present) was owed on the case, but admitted he did not have any paperwork or accounting to support his $4,500 estimate. Kendall objected to this request for fees without supporting documentation. The court explained, without clarity, why it was awarding attorney fees to Klein:
What I’m going to do ... is award the plaintiff $5,000 in attorney’s fees, and down below I’ll award the defendant $1,000 in attorney’s fees. And that’s because of the—while I’m not taking the actual causes of action, I’m waiting; I think because of the wait I’ll make your client pay.
VRP (Aug. 31, 2004) at 142.

Kendall argues on appeal that Klein was not entitled to any attorney fees because his attorney had not made any declaration about fees to support the court’s award, but he cites no authority for this position. Klein argues that because he successfully defended Kendall’s claim that RCW 59.18.300 (which authorizes an attorney fees award to the prevailing party) applied to the case, the court acted within its discretion to grant an award to him.

Because it is undisputed that Klein prevailed on the issue of RCW 59.18.300’s applicability, Klein would have been entitled to attorney fees. But Klein’s attorney admitted to the court that he had not prepared declarations delineating the requested fees. He estimated that he had incurred $4,500 in attorney fees overall, but did not specify how much was spent on the claims on which he prevailed. The court chose to award Klein $1,000 in attorney fees, without investigating further into the basis for a fee award. Attorney fees awards “should be based on more than just estimation or conjecture.” Austin v. U.S. Bank, 73 Wn.App. 293, 310, 869 P.2d 404 (1994). Washington courts have been clear that this state follows the “lodestar” methodology for determining attorney fee awards, and this methodology requires documentation of the work performed. McGreevy v. Oregon Mut. Ins. Co., 90 Wn.App. 283, 291–92, 951 P.2d 798 (1998). Minimally, such documentation must include the number of hours worked, the type of work performed, and the category of attorney who performed the work. McGreevy, 90 Wn.App. at 292. Because Klein’s attorney provided no such documentation, Klein’s attorney fee award was improper and we reverse, crediting Klein’s award back to Kendall.



Attorney Fees on Appeal
*5 Kendall argues that because he was awarded attorney fees below, he should be awarded attorney fees on appeal if he proves to be the prevailing party. Klein argues that because there was no statutory basis for the award to Kendall below (because the authorizing statute cited by the trial court does not actually contain an attorney fee provision), Kendall should not be awarded attorney fees by this court.

Although both parties were awarded fees below, neither party should have been awarded fees. The court erroneously based its award to Kendall on a statute (RCW 59.18.060) that does not provide for fees, and Klein did not provide the requisite proof to support his estimate of attorney fees. Because Klein does not challenge Kendall’s award below, that award stands. Because it should not have been granted, Kendall would not be permitted to collect attorney fees on appeal even if he were the prevailing party. But as he is not the prevailing party, Kendall is not entitled to collect attorney fees on appeal in any event and we reject his request for fees.

Although Klein should not have been granted fees below because of the lack of proof, an award was statutorily authorized and he prevailed on this issue on appeal. Thus, we award Klein appellate attorney fees on the issue of the applicability of RCW 59.18.300 if he complies with the requirements of RAP 18.1.

We affirm in part, but reverse Klein’s attorney fee award.

WE CONCUR: DWYER and BAKER, JJ.
All Citations
Not Reported in P.3d, 131 Wash.App. 1035, 2006 WL 322362
End of Document

© 2024 Thomson Reuters. No claim to original U.S. Government Works.
