#+title:      RCW 11.114.140. Use of custodial property
#+date:       [2007-07-01 Sun 00:00]
#+filetags:   :law:rcw:statute:
#+identifier: 20070701T000000

* RCW 11.114.140. Use of custodial property

West’s Revised Code of Washington Annotated 
Title 11. Probate and Trust Law (Refs & Annos)
Chapter 11.114. Uniform Transfers to Minors Act (Refs & Annos)

                        West’s RCWA 11.114.140
                11.114.140. Use of custodial property
                       Effective: July 1, 2007

** (1) 
A custodian may deliver or pay to the minor or expend for the minor’s benefit so much of the custodial property as the custodian considers advisable for the use and benefit of the minor, without court order and without regard to (a) the duty or ability of the custodian personally or of any other person to support the minor, or (b) any other income or property of the minor which may be applicable or available for that purpose.

** (2) 
On petition of an interested person or the minor if the minor has attained the age of eighteen years, the court may order the custodian to deliver or pay to the minor or expend for the minor’s benefit so much of the custodial property as the court considers advisable for the use and benefit of the minor.

** (3) 
A delivery, payment, or expenditure under this section is in addition to, not in substitution for, and does not affect any obligation of a person to support the minor.

* Credits

[2006 c 204 § 5, eff. July 1, 2007; 1991 c 193 § 14.]

* OFFICIAL NOTES

Effective date--2006 c 204: See note following RCW 11.114.090.

