#+title:      Rosen v. Ascentry Techs., Inc., 143 Wn. App. 364, 177 P.3d 765 (2008)
#+date:       [2008-02-25 Mon 00:00]
#+filetags:   :case:law:
#+identifier: 20080225T000000
#+signature:  coa=div1

* Rosen v. Ascentry Technologies, Inc. -- Court of Appeals of Washington, Division 1. | February 25, 2008 | 143 Wash.App. 364 | 177 P.3d 765

- Washington Citation :: Rosen v. Ascentry Techs., Inc., 143 Wn. App. 364, 177 P.3d 765 (2008)
- All Citations :: 143 Wash.App. 364, 177 P.3d 765


                          143 Wash.App. 364

                   Court of Appeals of Washington,

                             Division 1.

                      Geoffrey ROSEN, Appellant,

                                  v.

ASCENTRY TECHNOLOGIES, INC., and Federico and Jane Doe Pacquing, husband and wife, Respondents.

                            No. 58478–2–I.
                            Feb. 25, 2008.

** Brief
:PROPERTIES:
:VISIBILITY: all
:END:

*** Issues

*** Holdings

*** History

*** Facts

*** Law

*** Analysis

** Document Details

- [[*Synopsis][Synopsis]]
- [[*West Headnotes (6)][West Headnotes]]
- [[*Attorneys and Law Firms][Attorneys and Law Firms]]
- [[*Opinion][Opinion]]

** KeyCite:

- KeyCite Yellow Flag - Negative Treatment
- Distinguished byArya Holdings, Ltd. v. Eastside Funding, LLC, Wash.App. Div. 2, April 21, 2020

** Synopsis

Background: Former employee filed action against employer for breach of contract and unpaid wages, and parties negotiated a settlement and release agreement. Employee subsequently moved for partial summary judgment on original claims after employer defaulted on payment, and employer filed cross-motion to enforce agreement. The Superior Court, King County, Michael S. Spearman, J., dismissed case with prejudice and ordered that judgment be entered for employee consistent with amount of settlement. Employee appealed.

[Holding:] The Court of Appeals, Lau, J., held that settlement agreement did not show a clear intent that employee would release claims in exchange for employer’s promise to pay rather than in exchange for payment itself, and therefore employee could pursue original claims when employer defaulted.

Reversed and remanded.

Procedural Posture(s): On Appeal; Motion for Summary Judgment.

** West Headnotes (6)

*** [1] Accord and Satisfaction  [[1: 8-k-17][8-k-17]]  Effect of accord without satisfaction

- /8 Accord and Satisfaction/
- *8-k-15 Execution of Accord as Satisfaction*
- *8-k-17 Effect of accord without satisfaction*

Settlement agreement, under which employer agreed to pay former employee $50,000 for claims of non-wage general damages for breach of contract in exchange for employee’s release of all known and unknown claims, did not show clear intent that employee would release his claims in exchange for employer’s promise to pay rather than in exchange for payment itself, as necessary to overcome presumption that agreement was an executory accord, and therefore employee could pursue original claims when employer defaulted; there was no provision restricting employee to collecting $50,000 in case of default, and agreement required him to dismiss original lawsuit only upon receiving settlement payment.

- 2 Cases that cite this headnote

*** [2] Appeal and Error  [[2: 30-k-3767][30-k-3767]]  Construction, interpretation, and application in general

- /30 Appeal and Error/
- /30-XVI Review/
- /30-XVI(D) Scope and Extent of Review/
- /30-XV I(D)22Substantive Matters/
- *30-k-3765 Contracts*
- *30-k-3767 Construction, interpretation, and application in general*
- /(Formerly 30k893(1))/

Absent disputed facts, the legal effect of a contract is a question of law that appellate court reviews de novo.

- 3 Cases that cite this headnote

*** [3] Contracts  [[3: 95-k-312(3)][95-k-312(3)]]  Failure to make payments

- /95 Contracts/
- /95-V Performance or Breach/
- *95-k-312 Acts or Omissions Constituting Breach in General*
- *95-k-312(3) Failure to make payments*

An unpaid installment is a material breach of a contract.

- 2 Cases that cite this headnote

*** [4] Contracts  [[4: 95-k-321][95-k-321]]  Rights and Liabilities on Breach

- /95 Contracts/
- /95-V Performance or Breach/
- *95-k-321 Rights and Liabilities on Breach*
- *95-k-321(1) In general*

A party is barred from enforcing a contract that it has materially breached.

- 5 Cases that cite this headnote

*** [5] Accord and Satisfaction  [[5: 8-k-26(1)][8-k-26(1)]]  Presumptions and burden of proof
Novation-Evidence

- /8 Accord and Satisfaction/
- *8-k-26 Evidence*
- *8-k-26(1) Presumptions and burden of proof*
- /278 Novation/
- *278-k-12 Evidence*

A settlement agreement is presumed to be an executory accord unless the parties clearly intended the agreement to be a substituted contract.

- 2 Cases that cite this headnote

*** [6] Compromise, Settlement, and Release  [[6: 89-k-385][89-k-385]]  Performance and breach

- /89 Compromise, Settlement, and Release/
- /89-III Construction, Operation, and Effect/
- /89-III(A) In General/
- *89-k-383 Duties, Rights, and Violations in General*
- *89-k-385 Performance and breach*
- /(Formerly 89k20(2))/

State courts’ favoring of amicable settlement of disputes and their inclination to view settlements with finality does not mean that courts must interpret settlement agreements to forever bar the revival of original claims even if breached.

- 2 Cases that cite this headnote

** Attorneys and Law Firms

- <<**766>> Michael Alan Jacobson, Michael A. Jacobson PS, Seattle, WA, for Appellant.
- Talis Merle Abolins, Campell Dille Barnett, Puyallup, WA, for Respondents.

** Opinion

LAU, J.

<<*366>> ¶ 1 This case concerns the effect of a settlement agreement entered into by Geoffrey Rosen after he sued the respondents, Ascentry Technologies, Inc. and Federico Pacquing. Ascentry concedes it breached the agreement, but argues that Rosen may no longer pursue his original claims because he clearly released them in exchange for Ascentry’s promise to pay $50,000, and not in exchange for payment itself. The trial court ruled that the parties reached a binding agreement, dismissed Rosen’s case with prejudice, and ordered Ascentry to pay Rosen $50,000 consistent with the agreement.

¶ 2 Settlement agreements may have the effect of immediately and permanently extinguishing one party’s claims in exchange for the other party’s promise to perform. But under Washington law, the intent to establish such an agreement must be expressly clear. Because it is not clear from the agreement that Rosen released his original claims in exchange for Ascentry’s promise to pay, we reverse.

FACTS

¶ 3 Rosen sued his former employer, Ascentry, and Ascentry’s chief executive officer, Pacquing, for breach of contract and unpaid wages. The parties then negotiated a “Settlement and Release Agreement” that is the subject of this appeal.

<<*367>> ¶ 4 In its recital, the agreement states,

In exchange for the benefits set forth, Mr. Rosen agrees to execute this Agreement which includes a full release of all claims and dismissal of the Lawsuit.

NOW THEREFORE, in exchange for the mutual consideration described herein, the sufficiency of which is hereby acknowledged, the parties agree as follows[.]

Clerk’s Papers (CP) at 172. In paragraph 2, the agreement provides,

In exchange for Mr. Rosen’s release of all known and unknown claims, Ascentry agrees to pay Mr. Rosen the sum of Fifty Thousand Dollars ($50,000) as payment for disputed claims of non-wage general damages for breach of contract.... The Settlement Payment shall be made in the form of two cashier’s checks payable to the order of “Geoffrey Rosen.” The first check shall be provided to Mr. Rosen on or before Friday, February 18, 2005. The second check shall be provided to Mr. Rosen within two (2) business days of Ascentry finalizing the closing of its acquisition deal and receiving funds from the acquisition, which Ascentry anticipates to be completed by March 1, 2005.

CP at 172. The agreement’s fourth paragraph explains Rosen’s agreement to dismiss his lawsuit after receipt of payment.

Mr. Rosen agrees to dismiss his Lawsuit with Prejudice. Specifically, he agrees to execute and file an Order of Dismissal with Prejudice in a form to be provided by Ascentry within three (3) business days of receipt of the Settlement Payment.

CP at 173.

¶ 5 In paragraph 8, Rosen acknowledges his full opportunity to review and consult with legal counsel before signing the agreement. Paragraph 9 gives him a set period of time to decide whether to sign, and a period of seven days after signing to revoke.

Consideration Period/Revocation. Mr. Rosen acknowledges having been given twenty-one (21) days in which to consider this Agreement and the option to sign it in fewer than 21 days <<*368>> if desired. Any negotiations surrounding the language or terms of this Agreement shall not re-start the 21–day consideration period. Mr. Rosen acknowledges that he may revoke this Agreement within seven (7) days of signing it, by delivering a signed written letter of revocation to Ascentry’s attorney, Lawton H. Humphrey, at Davis Wright Tremaine LLP.

CP at 173.

¶ 6 Pacquing signed a copy of the agreement on February 7, 2005, and Rosen signed <<**767>> a different, but identical, copy on February 11, 2005. The first cashier’s check became due on February 18, 2005, which was also the last day for Rosen to send “a signed written letter” revoking the agreement. CP at 173

¶ 7 Ascentry did not pay Rosen, and Rosen did not seek to have his original lawsuit dismissed. A little over one year after the first payment was due, Rosen sent Ascentry a letter revoking the agreement. Shortly after sending the letter, he moved for partial summary judgment, arguing that the agreement was void because, among other reasons, Ascentry “never paid the consideration specified in the agreement.” CP at 79.

¶ 8 Ascentry filed a cross-motion to enforce the agreement. The court ruled that “the parties reached a binding settlement,” dismissed the case with prejudice, and ordered that judgment be entered for Rosen against Ascentry “in the amount of $50,000 consistent with the settlement agreement.” CP at 355. Rosen moved for reconsideration twice, and the court denied both motions. Rosen appeals.

ANALYSIS

[1] <<1: 8-k-17>> ¶ 9 Rosen contends that in light of Ascentry’s failure to pay, the settlement agreement is unenforceable by Ascentry and he should be allowed to pursue his original claims. Ascentry acknowledges it breached the agreement, but argues that Rosen may no longer pursue his original claims because he released them in exchange for Ascentry’s promise to pay $50,000—not in exchange for payment itself. We <<*369>> conclude that the court erred when it dismissed the case and limited Rosen’s remedy to a judgment of $50,000.

[2] <<2: 30-k-3767>> [3] <<3: 95-k-312(3)>> [4] <<4: 95-k-321>> ¶ 10 “Absent disputed facts, the legal effect of a contract is a question of law that we review de novo.” Keystone Masonry v. Garco Constr., 135 Wash.App. 927, 932, 147 P.3d 610 (2006). Here, there are no disputed facts because Ascentry concedes that it breached the agreement by failing to pay Rosen. An unpaid installment is a material breach. See Jacks v. Blazer, 39 Wash.2d 277, 286, 235 P.2d 187 (1951) (“[F]ailure to make ... payment ... was a breach of the contract, so material in nature that it operated as a discharge of it.”). A party is barred from enforcing a contract that it has materially breached. Bailie Communications, Ltd. v. Trend Bus. Sys., 53 Wash.App. 77, 81, 765 P.2d 339 (1988) (“ ‘A material failure by one party gives the other party the right to withhold further performance’.... The breaching party has a reasonable time to cure, after which the injured party may either sue for total breach or rescind and obtain restitution.”) (quoting RESTATEMENT (SECOND) OF CONTRACTS § 241 cmt. e (1981)). Thus, Ascentry was not entitled to enforce the settlement agreement because it breached and Rosen was free to pursue his original claims.

[5] <<5: 8-k-26(1)>> ¶ 11 Ascentry argues, however, that Rosen may no longer pursue his original claims because he released them in exchange for Ascentry’s promise to pay $50,000—not in exchange for payment itself. In other words, Ascentry argues that the settlement was a “substituted contract” that, upon being considered and signed by Rosen, immediately and forever extinguished Rosen’s previous claims. Corbin on Contracts explains the distinction between a substituted contract and an executory accord.

The operation and effect of the compromise on the original agreement are the distinguishing characteristics of the executory accord and the substituted contract. With the immediate discharge of the original claim by the substituted contract, rights in the original agreement are not revived upon a breach of the compromise agreement, the substituted contract. The original claim is discharged upon the making of an <<*370>> enforceable agreement between the parties; no rights or remedies in the original claim remain. Contrariwise, with an executory accord, pending full performance of the accord—the compromise agreement—the original claim is merely suspended. It is not discharged until the promised performance is complete. Breach of the accord empowers the claimant with the choice of enforcing the accord or the original claim.

13 Sarah Howard Jenkins CORBIN ON CONTRACTS § 69.1 at 278 (rev. ed.2003). We reject Ascentry’s argument because in Washington, a settlement agreement is presumed <<**768>> to be an executory accord unless the parties clearly intended the agreement to be a substituted contract.

¶ 12 A settlement agreement is presumed to be an executory accord, not a substituted contract. In Buob v. Feenaughty Mach. Co., 191 Wash. 477, 71 P.2d 559 (1937), the court explained,

“Ordinarily an executory contract constituting an accord is not a bar to an action upon the original claim; ‘satisfaction,’ that is, full performance of the contract of accord, is also necessary. If the parties so intend, the contract of accord may itself be taken as a satisfaction and discharge of the original claim; but the intention must be clear, and the presumption is otherwise.”

Buob, 191 Wash. at 491, 71 P.2d 559 (emphasis added) (quoting Wyatt v. New York, O & W.R. Co., 45 F.2d 705, 708 (2d Cir.1930)). Williston on Contracts also states that there is a presumption that a settlement is an executory accord.

It is often difficult to determine as a matter of fact whether the parties agreed that the new promise should itself be the satisfaction of the original cause of action—a substituted contract—or whether they contemplated the performance of the accord as the satisfaction. Unless there is clear evidence that the accord itself was intended as the satisfaction, it must be presumed that the parties contemplated the performance of the accord as the satisfaction, for it is not a probable inference that a creditor intends merely an exchange of its present cause of action for another.

It is generally more reasonable to suppose that it bound itself to surrender its rights only when the new contract of accord was performed.

<<*371>> 29 Richard A. Lord, WILLISTON ON CONTRACTS § 73:37 at 397 (4th ed.2003) (footnote omitted).

¶ 13 To overcome the presumption that a settlement agreement is an executory accord, the parties’ intent to do so must be clear. In Rogers v. City of Spokane, 9 Wash. 168, 174, 37 P. 300 (1894), the court stated, “[W]here it is the promise to perform instead of the performance that is accepted, it must explicitly appear that such was the intention of the parties ....” (Emphasis added.) See also Buob, 191 Wash. at 490, 71 P.2d 559 (“If it is claimed that the creditor intended to accept the promise as a satisfaction and not the performance, then that intention must be clearly shown.”); Joyner v. Seattle, 144 Wash. 641, 647, 258 P. 479 (1927) (“ ‘[W]here it is a promise to perform instead of the performance that is accepted, it must explicitly appear that such was the intention of the parties ....’ ”) (quoting “Rogers, 9 Wash. at 174,));  Williston & Lord, supra, § 73:37, at 117  (“Unless there is clear evidence that the accord itself was intended as the satisfaction, it must be presumed that the parties contemplated the performance of the accord as the satisfaction....”) (Emphasis added.) (Footnote omitted.)

¶ 14 It is not clear that the parties intended that Rosen would immediately and permanently release his claims in exchange for Ascentry’s promise to pay. The agreement states,

In exchange for Mr. Rosen’s release of all known and unknown claims, Ascentry agrees to pay Mr. Rosen the sum of Fifty Thousand Dollars ($50,000) as payment for disputed claims of non-wage general damages for breach of contract (“Settlement Payment”). The Settlement Payment shall be made in the form of two cashier’s checks payable to the order of “Geoffrey Rosen.” The first check shall be provided to Mr. Rosen on or before Friday, February 18, 2005. The second check shall be provided to Mr. Rosen within two (2) business days of Ascentry finalizing the closing of its acquisition deal and receiving funds from the acquisition, which Ascentry anticipates to be completed by March 1, 2005.

<<*372>> CP at 172. Though Ascentry relies heavily on this provision, it does not clearly state that Rosen released his claims in exchange for Ascentry’s promise to pay.

¶ 15 Ascentry claims that “the agreement made it clear that in the event of defendants’ default, Rosen could proceed immediately to judgment under the terms of the agreement....” Br. of Resp’t at 19. But Ascentry does not cite to any provision in the <<**769>> agreement to support this statement or any provision that restricts Rosen to collecting $50,000 in case of default. In fact, the agreement does not discuss default at all, and Rosen was required to dismiss his original lawsuit only upon “receipt of the Settlement Payment ....” and “in a form to be provided by Ascentry within three (3) business days of receipt of the Settlement Payment.” CP at 173 (para. 4). To overcome the presumption that the agreement was an executory accord, the parties’ intent to do so must be “clearly shown,” and here it was not. Buob, 191 Wash. at 490, 71 P.2d 559.[fn:1]

[fn:1] Ascentry also relies on Langlois v. Langlois, 169 N.Y.S.2d 170, 5 A.D.2d 75 (1957), in which the court stated,

A settlement agreement ought to be construed as a superceding agreement, if the original claim was a disputed and unliquidated claim, like a claim for damages in tort, in settlement of which the defendant agreed to pay a fixed sum upon delivery of a general release.

Langlois, 169 N.Y.S.2d at 173 (emphasis added). The court noted, however, that “there is a strong line of authority in this State to the effect that an agreement settling a tort claim made prior to suit or made out of court during the pendency of the action is presumed to be a mere executory accord.” Langlois, 169 N.Y.S.2d at 174. While Rosen’s claim was disputed and unliquidated, the agreement was made out of court. More importantly, the rule in Washington is that a settlement agreement is presumed to be an executory accord, and Ascentry has not overcome this presumption.

[6] <<6: 89-k-385>> ¶ 16 Ascentry argues that “enforcement of Rosen’s settlement is supported by the important public policy favoring the negotiated resolution of disputes.” Br. of Resp’t at 19. It is true that Washington courts favor amicable settlement of disputes and are inclined to view settlements with finality. Snyder v. Tompkins, 20 Wash.App. 167, 173, 579 P.2d 994 (1978). And the Washington Supreme Court has recognized that CR 2A and RCW 2.44.010 “give certainty and finality to settlements and compromises ...” Eddleman v. McGhan, <<*373>>  45 Wash.2d 430, 432, 275 P.2d 729 (1954). This does not mean, however, that courts must interpret settlement agreements to forever bar the revival of original claims even if the settlement agreement is breached. The presumption in Washington is that a settlement agreement acts as an executory accord and this presumption may be overcome only by a clear showing that the parties intended the agreement to be a substituted contract.

¶ 17 Ascentry complains that “[i]f Rosen were allowed to revive original claims despite an agreement as clear and explicit as this one, courts (and parties) would be faced with a barrage of previously settled causes of action months, if not years, after the settlement was reached.” Br. of Resp’t at 20. But as explained above, the settlement agreement in this case is not clear and explicit. Moreover, Rosen would not be allowed to revive his original claims if Ascentry had simply paid him under the terms of the settlement. In light of Ascentry’s breach, Rosen should be allowed to pursue his original claims.

¶ 18 For the foregoing reasons, we reverse and remand.

WE CONCUR: ELLINGTON and AGID, JJ.

** End
#+STARTUP: show2levels
