#+title:      Doheny Homes, LLC v. Lee, 182 Wn. App. 1050 (2014)
#+date:       [2014-08-11 Mon 00:00]
#+filetags:   :abandonment:case:damages:goodfaith:law:mitigation:repair:
#+identifier: 20140811T000001
#+signature:  coa=div1=unpub

* Doheny Homes, LLC v. Lee -- Court of Appeals of Washington, Division 1. | August 11, 2014 | Not Reported in P.3d | 182 Wash.App. 1050

- Washington Citation :: Doheny Homes, LLC v. Lee, 182 Wn. App. 1050 (2014)
- All Citations :: Not Reported in P.3d, 182 Wash.App. 1050, 2014 WL 3930453


                          182 Wash.App. 1050

          ** NOTE: UNPUBLISHED OPINION, SEE WA R GEN GR 14.1

                   Court of Appeals of Washington,

                             Division 1.

DOHENY HOMES, LLC, a Washington limited liability company, Respondents,

                                  v.

Lincoln Warren LEE, II and Carlene Tudor Lee, husband and wife, and the marital community comprised thereof, Appellants.

                            No. 69798–6–I.
                            Aug. 11, 2014.

** Brief
:PROPERTIES:
:VISIBILITY: all
:END:

*** Issues

*** Holdings

*** History

*** Facts

*** Law

*** Analysis

** Document Details

- [[**Attorneys and Law Firms][Attorneys and Law Firms]]
- [[**NOTE: UNPUBLISHED OPINION, SEE WA R GEN GR 14.1][UNPUBLISHED OPINION]]



- Appeal from King County Superior Court; Hon. Susan Craighead.
- ** Attorneys and Law Firms
- Michele K. McNeill, Skyline Law Group PLLC, Bellevue, WA, for Appellants.
- Shawna M. Lydon, Betts Patterson & Mines PS, Seattle, WA, for Respondents.


** UNPUBLISHED OPINION

SPEARMAN, C.J.

<<*1>> This appeal involves a landlord-tenant dispute between Brian and Trina Doheny and Lincoln Lee and Carlene Tudor–Lee.1 The trial court concluded after a bench trial that the Lees, who lived in a townhome owned by the Dohenys, were liable for breaching the lease agreement when they moved out. The Lees appeal. We conclude that substantial evidence supports the trial court’s findings of fact, and that the findings as a whole support the court’s conclusions of law that (1) Lincoln Lee did not properly terminate the lease agreement under RCW 59.18.090 and (2) he was liable for breach of the lease agreement. With respect to the damages award, we reject the Lees’ arguments that (1) the Dohenys’ failure to mitigate their damages meant they were not entitled to any damages and (2) the damages award should not have accounted for those months that had not passed at the time of trial. We agree with the Lees, however, that (1) Lincoln was entitled to the return of his deposit because the Dohenys did not timely mail the statement regarding the deposit and (2) Carlene could not be held liable for damages for breach of the lease agreement where she was not a party to the agreement and was not married to Lincoln until after the relevant events. We affirm in part, reverse in part, and remand.

1

The Lees are a married couple, but were not married until after the events that gave rise to the lawsuit underlying this appeal. The Dohenys are a married couple.

*** FACTS

Lincoln Lee and Trina Doheny had a son together in 1995. Trina2 later married Brian Doheny. In August 2006, in an effort to allow Lincoln to live close to his son, the Dohenys agreed to rent to him a townhome (“the Property”) near their own residence. Lincoln and Doheny Homes, LLC3 executed a lease agreement under which Lincoln agreed to rent the Property for $1,800 per month until July 31, 2014. Lincoln also agreed to prepay the last month’s rent. The lease agreement listed Doheny Homes’ address as “600–108th Ave NE, Ste. 536, Bellevue, WA 98004.” Exhibit (Ex.) 14. This was the office address of Trina’s company, Extend Networks. Lincoln delivered his monthly rental payments to that address.

2

For clarity, the parties’ first names will be used when referring to them in an individual capacity. “The Lees” refers to Lincoln Lee and Carlene Tudor–Lee. “The Dohenys” refers to Brian Doheny and Trina Doheny.

3

Doheny Homes, LLC, a property management company and rental depository, was the landlord of the Property and is the respondent on appeal. Doheny Homes is owned by the Dohenys. For simplicity, we will refer to the Dohenys as the landlords of the Property.

In August 2009, Lincoln became engaged to Carlene Tudor–Lee. Carlene moved into the Property in January 2010 but was never added to the lease. That month, Lincoln asked the Dohenys to be relieved from his lease obligation because he and Carlene wanted to move into a larger home to accommodate her two children from a former marriage. The Dohenys did not agree, though the parties dispute whether the Dohenys agreed to allow Lincoln to sublet the Property.4 By August 2010, the relationship between Lincoln and Trina had soured. By December, Carlene was searching for available rental properties. On December 21, she contacted Columbia Homes LLC to inquire about a townhome for rent.

4

The Dohenys claim they agreed to allow Lincoln to sublet the Property, while the Lees claim the Dohenys refused. This issue was not addressed by the trial court’s findings of fact.

On December 26, the Lees woke up to a cold home and determined that the radiant heating system had failed. The gas fireplace also did not work. That same day, Lincoln signed a lease agreement for the Columbia Homes townhome.5 However, the Lees did not attempt to advise the Dohenys of the problem with the heating system until the next day.

5

Carlene had poor credit and did not sign the lease. The Lees maintain that the new lease agreement would not have been binding until it was signed by the landlord, who had agreed to give them a three day grace period to back out.

<<*2>> On December 27, Lincoln mailed a “Notice Requesting Repairs” to the Dohenys via certified mail to Trina’s office. Ex. 3. The letter stated, “The radiant heat system is not working and the unit has no heat” and “The gas fireplace will not ignite and is inoperable.” Ex. 3. Previously, Lincoln had not sent the Dohenys notices in the mail when repairs were needed, as he lived across the street from the Dohenys.

Trina received the notice requesting repairs at her office the next day, December 28, at 12:43 p.m. That day, Brian went to the Property to inspect the heating system. He knocked on the door but no one answered. He could not enter the Property because the locks had been changed. Early the next day, December 29, Brian returned and knocked on the door. Again no one answered. The Dohenys sent a text message to the Lees that day, requesting access to the Property to inspect the heating issue. That afternoon, Lincoln called Brian and they agreed that Brian would come to the Property that evening. Brian inspected the heating issue that evening.

The next day, December 30, the Lees mailed the Dohenys a “Notice of Intent to Vacate Because of Unmade Repairs” via certified mail, again to Trina’s office. Ex. 4. Trina rejected delivery, and the Dohenys did not receive or read the letter. That day, the Dohenys made an appointment with Brennan Heating for January 4, 2011, which was the first available appointment after the holidays. Also that day, Lincoln sent a text message to Brian asking when the heating system would be fixed. Brian responded that Brennan Heating would inspect the heating system on January 4, 2011.

The Lees moved out of the Property the next day, December 31. On January 4, 2011, the Dohenys learned that the Lees had moved out when Brian entered the Property to allow Brennan Heating inside. Brennan Heating determined that it had to order a part before it could fix the heating system. On January 6, the Dohenys mailed a letter to Lincoln seeking rent for January and late fees. The heating system was repaired on January 11. On January 18, the Dohenys mailed to Lincoln’s work address6 a “Fourteen (14) Day Notice in Regard to Deposit” explaining their basis for retaining the last month’s deposit. Ex. 30.

6

The Lees did not leave a forwarding address when they moved out.

On March 2, Lincoln filed a small claims action against the Dohenys to recover his deposit. On April 14, the Dohenys, through Doheny Homes, filed a complaint against the Lees in superior court for breach of lease. At the hearing on the small claims action, the Dohenys informed the court that the small claims issue would be resolved in superior court. The Lees counterclaimed for constructive eviction and violations of the Washington Residential Landlord–Tenant Act of 1973 (RLTA), chapter 59.18 RCW.

The Dohenys did not list the Property for rent until May 2011. At that time, they listed the Property only on Craigslist, an online listing service. They did not lower the rental rate until July 2012 and did not add photographs until August 2012. The Property was rented for $1,600 per month in September 2012, approximately 20 months after the Lees had vacated the premises.

<<*3>> A bench trial was held in November 2012. The trial court issued an oral ruling on November 9, concluding that the Lees had not acted in good faith in terminating the lease7 and that the Dohenys had acted in good faith and within a reasonable time in responding to the notice requesting repairs. The court concluded that the Dohenys complied with RCW 59.18.060 and that the Lees were liable for breaching the lease agreement. The court concluded, however, that the Dohenys did not make a reasonable effort to mitigate their damages and rerent the Property. The court awarded the Dohenys damages equal to four months of rental payments under the lease agreement, plus the difference in the monthly rental amount between their lease with Lincoln and their lease with the new tenant for a period of 44 months, which was the amount of time remaining under the lease. The trial court rejected the Lees’ claim for Lincoln’s deposit, concluding that the Dohenys had sent a statement within 14 days of learning of the abandonment. The court entered written findings of fact and conclusions of law; an order granting the Dohenys’ motion for fees and costs; and a judgment in the amount of $58,724.44.8 The Lees appeal.9

7

The trial court concluded, among other things, that “[i]t was significant to the court that the Lees initiated a lease agreement to reside at the new property while continuing to interact with the Dohenys concerning the repair of the heating issue; this caused the court concern in that it suggested there was a design and intention on the part of the Lees to break the lease agreement and move out of the property.” Clerk’s Papers (CP) 131.

8

The amount of the judgment was comprised of $16,000 in damages, $40,000 in attorney fees, and $2,724.44 in statutory costs.

9

On May 10, 2013, the Lees filed for bankruptcy. On July 17, 2013, the Lees filed their notice of bankruptcy, and the commissioner stayed this proceeding on July 22, 2013. On August 19, 2013, the Dohenys received notification from the bankruptcy court that the Lees were granted a discharge. On September 24, 2013, the bankruptcy court directed creditors (including the Dohenys) to file a proof of claim, which the Dohenys did. As of January 2014, the bankruptcy case remained open for the sole purpose of this appeal. On January 16, 2014, the stay in this court was lifted.

*** DISCUSSION

“When a trial court has weighed the evidence in a bench trial, appellate review is limited to determining whether substantial evidence supports its findings of fact and, if so, whether the findings support the trial court’s conclusions of law. Substantial evidence exists when there is a sufficient quantity of evidence to persuade a fair-minded, rational person that a finding is true.” Hegwine v. Longview Fibre Co., Inc., 132 Wn.App. 546, 555–56, 132 P.3d 789 (2006) (citations omitted), aff’d, 162 Wn.2d 340, 172 P.3d 688 (2007). Unchallenged findings are verities on appeal. Cowiche Canyon Conservancy v. Bosley, 118 Wn.2d 801, 808, 828 P .2d 549 (1992). Conclusions of law are reviewed de novo. Hegwine, 132 Wn.App. at 556.

The Lees assign error to numerous findings of fact and conclusions of law, as well as the judgment. They contend the trial court erred in (1) concluding that they were liable for breaching the lease agreement; (2) awarding the Dohenys damages; (3) rejecting their claim for Lincoln’s deposit; and (4) concluding that Carlene was liable for any damages. We address these contentions in turn.

**** Dohenys’ Claim for Breach of Lease

***** i. Liability

This case is governed by the RLTA and the lease agreement between Lincoln and Doheny Homes. The RLTA provisions of particular relevance are RCW 59.18.020, .060, .070, and .090. RCW 59.18.060 pertains to a landlord’s duty to maintain habitable premises, providing, in relevant part, that “[t]he landlord will at all times during the tenancy keep the premises fit for human habitation, and shall in particular: ... (8) Maintain all electrical, plumbing, heating, and other facilities and appliances supplied by him or her in reasonably good working order; ... (11) Provide facilities adequate to supply heat and water and hot water as reasonably required by the tenant.” RCW 59.18.070 requires a landlord to timely remedy defective conditions, providing, in relevant part:

<<*4>> If at any time during the tenancy the landlord fails to carry out the duties required by RCW 59.18.060 or by the rental agreement, the tenant may, in addition to pursuit of remedies otherwise provided him or her by law, deliver written notice to the person designated in RCW 59.18.060(14), or to the person who collects the rent, which notice shall specify the premises involved, the name of the owner, if known, and the nature of the defective condition. The landlord shall commence remedial action after receipt of such notice by the tenant as soon as possible but not later than the following time periods, except where circumstances are beyond the landlord’s control:

(1) Not more than twenty-four hours, where the defective condition deprives the tenant of hot or cold water, heat, or electricity, or is imminently hazardous to life;

....

In each instance the burden shall be on the landlord to see that remedial work under this section is completed promptly. If completion is delayed due to circumstances beyond the landlord’s control, including the unavailability of financing, the landlord shall remedy the defective condition as soon as possible.

Under RCW 59.18.090,

If, after receipt of written notice, and expiration of the applicable period of time, as provided in RCW 59.18.070, the landlord fails to remedy the defective condition within a reasonable time, the tenant may:

(1) Terminate the rental agreement and quit the premises upon written notice to the landlord without further obligation under the rental agreement, in which case he or she shall be discharged from payment of rent for any period following the quitting date, and shall be entitled to a pro rata refund of any prepaid rent, and shall receive a full and specific statement of the basis for retaining any of the deposit together with any refund due in accordance with RCW 59.18.280.

RCW 59.18.090(1). Lastly, RCW 59.18.020 provides that “[e]very duty under this chapter and every act which must be performed as a condition precedent to the exercise of a right or remedy under this chapter imposes an obligation of good faith in its performance or enforcement.”10

10

Thus, the Lees are incorrect in asserting that the trial court impermissibly considered the relative good faith of the parties and the reasonableness of their actions.

The Lees’ appeal is based primarily on their argument that the Dohenys failed to comply with RCW 59.18.060 and .070 because they did not commence remedial action within 24 hours of receiving the notice requesting repairs. The Lees claim the evidence showed that the Dohenys did not even come to the Property until after the 24 hour period had passed. They contend such failure permitted them to terminate the lease under RCW 59.18.090.

We reject these arguments. The trial court concluded that the Dohenys’ ability to commence repairs to the heating system was delayed by circumstances beyond their control under RCW 59.18.070. The court’s conclusion was supported by its findings of fact that (1) Brian attempted to inspect the heating system the same day the Dohenys received notice of the issue but was prevented from doing so because the Lees had changed the locks; (2) Brian made another attempt to inspect the heating issue early in the day on December 29, 2010 but no one answered the door; (3) Brian sent a text message to Lincoln on December 29 to request access to the Property; and (4) Brian inspected the heating issue on the evening of December 29. There was substantial evidence, in the form of Brian and Trina’s testimony, to support these findings.11 Thus, the fact that the Dohenys did not commence repairs within 24 hours did not automatically permit the Lees to terminate the lease agreement without further obligation.

11

This court views the evidence in the light most favorable to the prevailing party below and defers to the trial court regarding witness credibility and conflicting testimony. Hegwine, 132 Wn.App. at 556. We thus reject the Lees’ contention that the trial court erred in concluding that the Dohenys’ ability to access the Property was delayed by Lincoln’s changing the locks without the Dohenys’ knowledge or permission. The Lees point out that Lincoln testified that he had changed the lock with Trina’s permission after the keys to the former lock were lost and that he had provided Trina with a copy of the new key. But Brian testified that Lincoln had not asked for permission to change the locks. We likewise reject the Lees’ contention that Brian’s testimony that he attempted to access the Property on December 28, 2010 is contravened by “the balance of the record” because Carlene and her son testified that they were present at the Property at the time and that nobody came by.

<<*5>> Where the completion of repairs is delayed due to circumstances beyond the landlord’s control, RCW 59.18.070 requires the landlord to remedy the defective condition “as soon as possible.” Here, the trial court concluded that the Dohenys met this requirement where they (1) made a good-faith effort to respond to, inspect, and repair the heating issue once they became aware of it; (2) responded to the notice requesting repairs within a reasonable time; and (3) repaired the heating issue in good faith and within a reasonable time. These conclusions are supported by the trial court’s unchallenged findings that (1) on December 30, 2010, less than one day after Brian inspected the heating issue in the evening of December 29, the Dohenys made an appointment with Brennan Heating for January 4, 2011; (2) the Lees moved out on December 31, 2010; (3) Brennan Heating’s inspection on January 4 revealed that a part had to be ordered before the repair could be made; and (4) Brennan Heating fixed the heating issue on January 11, 2011.

RCW 59.18.090 permits a tenant to terminate a rental agreement and move out “[i]f, after receipt of written notice, and expiration of the applicable period of time, as provided in RCW 59.18.070, the landlord fails to remedy the defective condition within a reasonable time.” The Lees contend they properly terminated the lease agreement because the Dohenys failed to commence remedial action within 24 hours and failed to promptly remedy the heating issue.

Again, we reject this argument. Given the trial court’s findings of fact and conclusions of law, the Lees did not give the Dohenys a “reasonable time” under RCW 59.18.090 to remedy the heating issue before they moved out. Thus, a statutory prerequisite for terminating the lease agreement was not met. As the trial court found, the Dohenys received notice of the heating issue on December 28, 2010 and could not access the Property until the evening of December 29. The Lees sent the notice to vacate less than one day after Brian was able to inspect the heating issue and moved out less than two days after he inspected the heating issue. These findings, along with the trial court’s findings in support of its conclusion that the Dohenys repaired the heating system in good faith and within a reasonable time, support the court’s conclusion that the Lees did not properly terminate the lease agreement under RCW 59.18.090.

The Lees also contend that the trial court erroneously concluded that, because the Lees did not indicate the condition was an emergency and did not demand that the heat be fixed more quickly, the Dohenys did not have a duty to commence remedial action within 24 hours. But the trial court did not make such a conclusion. Rather, the court’s findings that the notice requesting repairs did not (1) indicate the lack of heat was a threat to the health or safety of the occupants, (2) indicate the heating issue was an emergency, or (3) request heating devices or other accommodations tended to support the court’s conclusions as to (1) the reasonableness of the Dohenys’ response, (2) whether the Dohenys’ response was made in good faith under the circumstances, and (3) whether the Dohenys met RCW 59.18.060(11), which requires landlords to “[p]rovide facilities adequate to supply heat.”

<<*6>> Finally, the Lees contend that the trial court erred in concluding that their method of notifying the Dohenys of the heating issue was “significantly different” than the past practice of communication between the parties. They contend the conclusion was erroneous because the notice requesting repairs was sent as required by the lease and the RLTA and because Lincoln delivered rental payments to Trina’s office address. While it is undisputed that the Lees complied with the RLTA and the lease agreement in notifying the Dohenys, the trial court did not conclude that the notice did not comply with the RLTA or the lease agreement. Rather, the court concluded that the Lees did not act reasonably in notifying the Dohenys of the heating issue where the method of communication was significantly different than the past practice of communication between the parties. This related to the court’s conclusion that the Lees’ means of notification was for the purpose of meeting their minimal requirements under the law rather than remedying any risk of harm to the Property’s occupants. Furthermore, while the notice requesting repairs was sent to the same address to which Lincoln sent rental payments, the trial court’s finding that the means of notice regarding the heating issue was not consistent with the past practice of communication between the parties was supported by the evidence that Lincoln had previously communicated the need to repair a defect verbally and that the Dohenys lived across the street from him. In any event, the trial court’s conclusion regarding the method of communication was not germane to its conclusions that (1) the Dohenys, once they received notice of the heating issue, responded within a reasonable time and (2) the Lees did not properly terminate the lease agreement under RCW 59.18.090.

***** ii. Damages

The Lees also contend that the trial court erred in awarding damages.12 They first contend that the court, while properly concluding that the Dohenys failed to mitigate their damages, erroneously concluded that the Dohenys were entitled to any damages. The Dohenys respond that the trial court did consider their failure to mitigate in calculating damages. The record supports the Dohenys’ contention.

12

We reject the Dohenys’ contention that the Lees improperly object to the amount of damages for the first time on appeal because they failed to raise their arguments below; did not object to the proposed findings of fact and conclusions of law, and stipulated to the judgment. The Lees made their arguments objecting to the damages award in their trial brief and during closing argument. The trial court made an oral ruling—in which it rejected the Lees’ arguments—and requested the parties to draft proposed findings of fact and conclusions of law consistent with its ruling. The findings of fact, conclusions of law, and stipulated judgment were merely consistent with the trial court’s ruling. The Dohenys cite no authority for the proposition that the Lees have waived their arguments under these circumstances.

This court reviews a trial court’s decision to award damages for an abuse of discretion. Banuelos v. TSA Wash., Inc., 134 Wn.App. 607, 613, 141 P.3d 652 (2006). A trial court abuses its discretion when its decision is manifestly unreasonable or based on untenable grounds. State ex rel. Carroll v. Junker, 79 Wn.2d 12, 26, 482 P.2d 775 (1971).

RCW 59.18.310 provides, in relevant part:

If the tenant defaults in the payment of rent and reasonably indicates by words or actions the intention not to resume tenancy, the tenant shall be liable for the following for such abandonment: PROVIDED, That upon learning of such abandonment of the premises the landlord shall make a reasonable effort to mitigate the damages resulting from such abandonment:

<<*7>> ....

(2) When the tenancy is for a term greater than month-to-month, the tenant shall be liable for the lesser of the following:

(a) The entire rent due for the remainder of the term; or

(b) All rent accrued during the period reasonably necessary to rerent the premises at a fair rental, plus the difference between such fair rental and the rent agreed to in the prior agreement, plus actual costs incurred by the landlord in rerenting the premises together with statutory court costs and reasonable attorneys’ fees.

Under the statute, a landlord must mitigate damages. “The doctrine of avoidable consequences, also known as mitigation of damages, prevents recovery for damages the injured party could have avoided through reasonable efforts.” Cobb v. Snohomish County, 86 Wn.App. 223, 230, 935 P.2d 1384 (1997).

Here, the trial court awarded damages under RCW 59.18.310(2)(b).13 The court evidently found that a “period reasonably necessary to rerent the premises at a fair rental,” RCW 59.18.310, was four months, which was significantly less than the period it in fact took the Dohenys to rerent the Property.14 Thus, the court took the Dohenys’ failure to mitigate into consideration and did not award damages for the entire period it took the Dohenys to find renters. The trial court also awarded $200 per month for each remaining month of the lease term, to account for the difference between the rent under the lease with Lincoln and the rent under the new lease. The trial court’s calculation of damages was consistent with the statute and was not an abuse of discretion.

13

In its oral ruling, the court stated:

The plaintiffs did not make a reasonable effort to obtain new tenants to mitigate damages. The manner of advertising was not reasonable initially, the pricing was not adjusted, and the—I—and so that in crafting a decision in this particular case I do find in favor of the plaintiffs in this particular case.

But my belief is that—and from my knowledge and from the testimony—is that the damages in this case would be payment of the full amount of rent for a period that would indicate four months of rent. And for the remaining amount of time left under the lease it would be the difference between the current lease and the lease that existed initially, which I understand is a $200 per month difference.

14

The Dohenys listed the Property in May 2011 and did not find renters until September 2012, approximately 16 months later.

The Lees also contend that, because there was no acceleration clause in the lease agreement, the damages award should not have included $200 per month for those months that had not passed at the time of trial. They cite Myers v. W. Farmers Ass’n, 75 Wn.2d 133, 449 P.2d 104 (1969) in support. But Myers did not analyze damages calculated under RCW 59.18.310 and is inapposite.

**** Lees’ Counterclaim for Return of Deposit

The Lees contend that the Dohenys did not mail the statement regarding the deposit within the time limit specified in RCW 59.18.280 and that Lincoln was therefore entitled to the return of his deposit.15 We agree.

15

The Dohenys do not dispute the Lees’ assertion that Lincoln paid $1,900 toward the last month’s rent.

RCW 59.18.280 provides, in relevant part:

Within fourteen days after the termination of the rental agreement and vacation of the premises or, if the tenant abandons the premises as defined in RCW 59.18.310, within fourteen days after the landlord learns of the abandonment, the landlord shall give a full and specific statement of the basis for retaining any of the deposit together with the payment of any refund due the tenant under the terms and conditions of the rental agreement....

The notice shall be delivered to the tenant personally or by mail to his or her last known address. If the landlord fails to give such statement together with any refund due the tenant within the time limits specified above he or she shall be liable to the tenant for the full amount of the deposit.

<<*8>> Here, the trial court found that the Dohenys never received the notice to vacate and that they did not learn of the Lees’ abandonment until January 4, 2011.16 The court also found that the Dohenys mailed the statement of deposit on January 18, 2011. The court then concluded that the Dohenys sent the statement of deposit within 14 days of learning of the Lees’ abandonment, in accordance with RCW 59.18.280.

16

The trial court made an unchallenged finding that “[Brian] noticed the Lees had vacated the property on January 4, 2011, when he arrived at the property to let Brennan Heating inside to inspect the heating issue.” The court’s finding that the Dohenys never received the notice of intent to vacate was supported by substantial evidence because the Dohenys testified that they did not receive it.

We disagree with the trial court’s approach and reverse as to the Lees’ counterclaim for Lincoln’s deposit. While the Dohenys may not have received actual notice of the Lees’ abandonment until January 4, 2011, the evidence showed they received constructive notice on December 31, 2010. The lease agreement provided, “Any notice which either party may or is required to give, may be given by mailing the same, by certified mail ... to [the Dohenys] at the address shown below.” Ex. 1, ¶ 28. The only address for the Dohenys in the lease agreement was Trina’s office address. The Lees mailed the notice to vacate to that address on December 30, 2010, and the Dohenys do not dispute the Lees’ contention that Trina rejected the mailing. Moreover, Trina had accepted delivery of certified mail—the Lees’ notice requesting repairs—at that address only several days before the Lees sent the notice to vacate. Under these circumstances, the Dohenys may not rely on the date that they actually learned of the abandonment; instead, constructive notice will be imputed to them. The Dohenys’ mailing of the statement of deposit on January 18, 2011 was not within 14 days of December 31, 2010, the expected delivery date of the notice to vacate.17 Lincoln was thus entitled to the return of his deposit.

17

The Dohenys do not dispute the Lees’ contention that December 31, 2010 was the expected delivery date for the notice to vacate.

**** Carlene’s Liability for Damages

Finally, the Lees contend the trial court erred in concluding that Carlene was liable for any damages where she was not a party to the lease agreement and was not married to Lincoln until after the events in question.18 They contend Carlene is not liable for any debt or liability incurred by Lincoln prior to their marriage, citing RCW 26.16.200. The Dohenys respond that Carlene is liable because she benefited from the lease agreement when she lived at the Property and because she attached herself to Lincoln’s counterclaims and became a party to the litigation. They cite deElche v. Jacobsen, 95 Wn.2d 237, 622 P.2d 835 (1980) in support of their position.

18

The trial concluded that “[t]he Lees are liable to the Dohenys for breach of the lease agreement.” CP 131 (emphasis added).

We agree with the Lees. RCW 26.16.200 states, in relevant part:

Neither person in a marriage or state registered domestic partnership is liable for the debts or liabilities of the other incurred before marriage or state registered domestic partnership, nor for the separate debts of each other, nor is the rent or income of the separate property of either liable for the separate debts of the other: PROVIDED, That the earnings and accumulations of the spouse or domestic partner shall be available to the legal process of creditors for the satisfaction of debts incurred by such spouse or domestic partner prior to the marriage or the state registered domestic partnership....

<<*9>> Here, whether Lincoln’s breach of the lease agreement was a “debt” or a “liability” under RCW 26.16.200, it was undisputedly incurred before the Lees were married. Nor does deElche support the Dohenys’ position. In deElche, the couple was married when the husband committed a tort and when the judgment against the husband was entered. 95 Wn.2d at 238. The court held that, where the husband’s tort was not in the management of community business or for the community’s benefit, the husband’s separate property would be primarily liable but that if such separate property was insufficient, the plaintiff was entitled to recover from the husband’s half interest in community property. Id. at 246. That case did not address the circumstances presented here.

Where Carlene was not married to Lincoln during the events in question and was not a party to the lease agreement, she was, at most, a month-to-month tenant. The Dohenys do not dispute the Lees’ contentions that, if tenancy was month-to-month, Carlene terminated her tenancy at the end of December 2010 and the rent was prepaid by Lincoln through January 2011.

**** Attorney’s Fees on Appeal

Both parties request attorney’s fees on appeal, citing an attorney’s fee provision in the lease agreement.19 Additionally, the Lees cite RCW 59.18.280 (entitling the prevailing party in an action to recover a deposit to recover costs and reasonable attorney’s fees) and RCW 4.84.010 (allowing recovery of certain costs to the prevailing party). We conclude that there is no substantially prevailing party on appeal and do not award fees to either party.

19

The attorney’s fee provision states, “In any legal action to enforce the terms hereof or relating to the premises, regardless of the outcome, the Owner or agent shall be entitled to all costs incurred in connection with such action, including a reasonable attorney’s fee.” Ex. 1 ¶ 27.

Affirmed in part, reversed in part, and remanded for further proceedings.

*** WE CONCUR: LEACH and DWYER, JJ.

** End
#+STARTUP: show2levels
