#+title:      DLI Properties LLC v. Hill, 29 Cal. App. 5th Supp. 1, 240 Cal. Rptr. 3d 306 (Cal. App. Dep’t Super. Ct. 2018)
#+date:       [2018-09-17 Mon 00:00]
#+filetags:   :case:law:
#+identifier: 20180917T000000

* DLI Properties LLC v. Hill -- Appellate Division, Superior Court, California., LOS ANGELES COUNTY. | September 17, 2018 | 29 Cal.App.5th Supp. 1 | 240 Cal.Rptr.3d 306

- Washington Citation :: DLI Properties LLC v. Hill, 29 Cal. App. 5th Supp. 1, 240 Cal. Rptr. 3d 306 (Cal. App. Dep’t Super. Ct. 2018)
- All Citations :: 29 Cal.App.5th Supp. 1, 240 Cal.Rptr.3d 306, 18 Cal. Daily Op. Serv. 11,288

** Brief

** Document Details

- Outline
- Synopsis
- West Headnotes
- Attorneys and Law Firms
- OPINION
- All Citations

** KeyCite:

- KeyCite Yellow Flag - Negative Treatment
- Distinguished byGroup XIII Properties LP v. Stockman, Cal.Super.A.D., September 6, 2022

* Case

                        29 Cal.App.5th Supp. 1

           Appellate Division, Superior Court, California.

                         LOS ANGELES COUNTY.

            DLI PROPERTIES LLC, Plaintiff and Respondent,

                                  v.

               Cherokee HILL, Defendant and Appellant.

                            No. BV 032016
                           Filed 9/17/2018
** Synopsis

Background: Owner of residential home filed unlawful detainer action after tenant failed to pay rent and defaulted on lease agreement. After denial of tenant’s motion for nonsuit, the Superior Court, Los Angeles County, No. 16UA0882, Paul A. Bacigalupo, J., entered judgment on jury verdict for owner and denied motion for judgment notwithstanding the verdict (JNOV), and tenant appealed.

Holdings: The Superior Court, Appellate Division, Richardson, J., held that:

[1] owner failed to comply with statutory management disclosure requirements, and

[2] owner was not a “successor owner” within meaning of statute prohibiting a successor owner from evicting a tenant for nonpayment of rent absent compliance with management disclosures.

Affirmed.

Procedural Posture(s): On Appeal; Motion for Non-Suit; Motion for Judgment Notwithstanding the Verdict (JNOV).

** West Headnotes (16)

*** [1] Appeal and Error  [[1: 30-k-105][30-k-105]]  Dismissal, nonsuit, or direction of verdict

- /30 Appeal and Error/
- /30-III Decisions Reviewable/
- /30-III(E) Nature, Scope, and Effect of Decision/
- *30-k-105 Dismissal, nonsuit, or direction of verdict*

Denial of a motion for nonsuit or directed verdict may be reviewed on appeal from the judgment.

*** [2] Judgment  [[2: 228-k-199][228-k-199]]  Notwithstanding Verdict
TrialNature and grounds in general
TrialNature and Grounds

- /228 Judgment/
- /228-VI On Trial of Issues/
- /228-VI(A) Rendition, Form, and Requisites in General/
- *228-k-199 Notwithstanding Verdict*
- *228-k-199(1) In general*
- /388 Trial/
- /388-VI Taking Case or Question from Jury/
- /388-VI(C) Dismissal or Nonsuit/
- *388-k-159 Nature and grounds in general*
- /388 Trial/
- /388-VI Taking Case or Question from Jury/
- /388-VI(D) Direction of Verdict/
- *388-k-167 Nature and Grounds*
- *388-k-168 In general*

Function of motions for nonsuit, directed verdict, and judgment notwithstanding the verdict is to prevent the moving defendant from the necessity of undergoing any further exposure to legal liability when there is insufficient evidence for an adverse verdict.

*** [3] Judgment  [[3: 228-k-199][228-k-199]]  Notwithstanding Verdict
TrialNature and grounds in general
TrialNature and Grounds

- /228 Judgment/
- /228-VI On Trial of Issues/
- /228-VI(A) Rendition, Form, and Requisites in General/
- *228-k-199 Notwithstanding Verdict*
- *228-k-199(1) In general*
- /388 Trial/
- /388-VI Taking Case or Question from Jury/
- /388-VI(C) Dismissal or Nonsuit/
- *388-k-159 Nature and grounds in general*
- /388 Trial/
- /388-VI Taking Case or Question from Jury/
- /388-VI(D) Direction of Verdict/
- *388-k-167 Nature and Grounds*
- *388-k-168 In general*

The purpose of motions for nonsuit, directed verdicts and judgment notwithstanding the verdict (JNOV) is to allow a party to prevail as a matter of law where the relevant evidence is already in.

*** [4] Judgment  [[4: 228-k-199(3.10)][228-k-199(3.10)]]  Where there is no evidence to sustain verdict
Trial”No” evidence;  total failure of proof
TrialNature and grounds in general

- /228 Judgment/
- /228-VI On Trial of Issues/
- /228-VI(A) Rendition, Form, and Requisites in General/
- *228-k-199 Notwithstanding Verdict*
- *228-k-199(3.10) Where there is no evidence to sustain verdict*
- /388 Trial/
- /388-VI Taking Case or Question from Jury/
- /388-VI(A) Questions of Law or of Fact in General/
- *388-k-139.1 Evidence*
- *388-k-139.1(5) Submission to or Withdrawal from Jury*
- *388-k-139.1(7) ”No” evidence;  total failure of proof*
- /388 Trial/
- /388-VI Taking Case or Question from Jury/
- /388-VI(C) Dismissal or Nonsuit/
- *388-k-159 Nature and grounds in general*

Trial court may grant motions for nonsuit, directed verdict, and judgment notwithstanding the verdict only if it appears from the evidence, viewed in the light most favorable to the party securing the verdict, that there is no substantial evidence to support it.

*** [5] Appeal and Error  [[5: 30-k-3956][30-k-3956]]  Preverdict motions;  direction of verdict
Appeal and ErrorPostverdict motions;  judgment notwithstanding verdict (JNOV)
JudgmentEvidence and inferences that may be considered or drawn
TrialHearing and determination

- /30 Appeal and Error/
- /30-XVI Review/
- /30-XVI(F) Presumptions and Burdens on Review/
- /30-XVI(F)2 Particular Matters and Rulings/
- *30-k-3954 Taking Case or Question from Jury;  Judgment as a Matter of Law*
- *30-k-3956 Preverdict motions;  direction of verdict*
- /30 Appeal and Error/
- /30-XVI Review/
- /30-XVI(F) Presumptions and Burdens on Review/
- /30-XVI(F)2 Particular Matters and Rulings/
- *30-k-3954 Taking Case or Question from Jury;  Judgment as a Matter of Law*
- *30-k-3957 Postverdict motions;  judgment notwithstanding verdict (JNOV)*
- /228 Judgment/
- /228-VI On Trial of Issues/
- /228-VI(A) Rendition, Form, and Requisites in General/
- *228-k-199 Notwithstanding Verdict*
- *228-k-199(3.2) Evidence and inferences that may be considered or drawn*
- /388 Trial/
- /388-VI Taking Case or Question from Jury/
- /388-VI(D) Direction of Verdict/
- *388-k-178 Hearing and determination*

In reviewing the denial of motions for nonsuit, directed verdict, and judgment notwithstanding the verdict, the appellate court, like the trial court, must evaluate the evidence in the light most favorable to the plaintiff.

*** [6] Appeal and Error  [[6: 30-k-3566][30-k-3566]]  De novo review
Appeal and ErrorDe novo review

- /30 Appeal and Error/
- /30-XVI Review/
- /30-XVI(D) Scope and Extent of Review/
- /30-XV I(D)14Taking Case or Question from Jury;  Judgment as a Matter of Law/
- *30-k-3562 Preverdict Motions;  Direction of Verdict*
- *30-k-3566 De novo review*
- /30 Appeal and Error/
- /30-XVI Review/
- /30-XVI(D) Scope and Extent of Review/
- /30-XV I(D)14Taking Case or Question from Jury;  Judgment as a Matter of Law/
- *30-k-3571 Postverdict Motions;  Judgment Notwithstanding Verdict (Jnov)*
- *30-k-3575 De novo review*

Where motions for nonsuit, directed verdict, and judgment notwithstanding the verdict raise legal issues, such as the application of law to undisputed facts or the interpretation of a statute, appellate court reviews the trial court’s ruling under a de novo standard of review.

*** [7] Statutes  [[7: 361-k-1080][361-k-1080]]  Language and intent, will, purpose, or policy
StatutesPlain Language;  Plain, Ordinary, or Common Meaning
StatutesContext

- /361 Statutes/
- /361-III Construction/
- /361-III(A) In General/
- *361-k-1078 Language*
- *361-k-1080 Language and intent, will, purpose, or policy*
- /361 Statutes/
- /361-III Construction/
- /361-III(B) Plain Language;  Plain, Ordinary, or Common Meaning/
- *361-k-1091 In general*
- /361 Statutes/
- /361-III Construction/
- /361-III(E) Statute as a Whole;  Relation of Parts to Whole and to One Another/
- *361-k-1153 Context*

Court interpreting a statute begins with the statute’s actual words, the most reliable indicator of legislative intent, assigning them their usual and ordinary meanings, and construing them in context.

*** [8] Statutes  [[8: 361-k-1369][361-k-1369]]  Clarity and ambiguity;  multiple meanings

- /361 Statutes/
- /361-III Construction/
- /361-III(M) Presumptions and Inferences as to Construction/
- *361-k-1366 Language*
- *361-k-1369 Clarity and ambiguity;  multiple meanings*

If the words of a statute themselves are not ambiguous, court presumes the Legislature meant what it said, and the statute’s plain meaning governs.

*** [9] Statutes  [[9: 361-k-1102][361-k-1102]]  What constitutes ambiguity;  how determined
StatutesPlain, literal, or clear meaning;  ambiguity

- /361 Statutes/
- /361-III Construction/
- /361-III(C) Clarity and Ambiguity;  Multiple Meanings/
- *361-k-1102 What constitutes ambiguity;  how determined*
- /361 Statutes/
- /361-III Construction/
- /361-III(H) Legislative History/
- *361-k-1242 Plain, literal, or clear meaning;  ambiguity*

If the language of a statute allows more than one reasonable construction, court may look to such aids as the legislative history of the measure and maxims of statutory construction.

*** [10] Statutes  [[10: 361-k-1187][361-k-1187]]  Policy considerations;  public policy

- /361 Statutes/
- /361-III Construction/
- /361-III(F) Extrinsic Aids to Construction/
- *361-k-1187 Policy considerations;  public policy*

In cases of uncertain meaning of words in a statute, court may consider the consequences of a particular interpretation, including its impact on public policy.

*** [11] Antitrust and Trade Regulation  [[11: 29T-k-200][29T-k-200]]  Housing rentals

- /29 TAntitrust and Trade Regulation/
- /29T-III Statutory Unfair Trade Practices and Consumer Protection/
- /29T-III(C) Particular Subjects and Regulations/
- *29T-k-200 Housing rentals*

Owner of leased residence failed to comply with statutory management disclosure requirements for landlords, where rental agreement identified management company as “Landlord” but did not identify or designate an owner or an agent who was authorized to act on the owner’s behalf for service of process, and lease did not disclose the “usual street address” of such persons or entities, a valid telephone number, or the contact information for any of the persons authorized to manage the premises. Cal. Civ. Code § 1962.

*** [12] Landlord and Tenant  [[12: 233-k-627][233-k-627]]  Rights and liabilities of grantee or assignee
Mortgages and Deeds of TrustLeases

- /233 Landlord and Tenant/
- /233-III Landlord’s Title and Reversion/
- /233-III(A) Rights and Powers of Landlord/
- *233-k-624 Transfer of Reversion*
- *233-k-627 Rights and liabilities of grantee or assignee*
- /266 Mortgages and Deeds of Trust/
- /266-XIII Foreclosure/
- /266-XIII(H) Title and Rights of Purchaser/
- *266-k-2042 Nature and Extent of Rights Acquired*
- *266-k-2048 Leases*

After a leased property is sold or transferred, the transferee takes subject to the existing lease; this new owner steps into the landlord’s shoes and becomes the successor landlord, assuming the terms and conditions of the lease the tenant had with the prior owner, and the same is true when the property is sold through foreclosure.

- 1 Case that cites this headnote

*** [13] Landlord and Tenant  [[13: 233-k-627][233-k-627]]  Rights and liabilities of grantee or assignee
Landlord and TenantCreation of new tenancy

- /233 Landlord and Tenant/
- /233-III Landlord’s Title and Reversion/
- /233-III(A) Rights and Powers of Landlord/
- *233-k-624 Transfer of Reversion*
- *233-k-627 Rights and liabilities of grantee or assignee*
- /233 Landlord and Tenant/
- /233-IV Particular Kinds of Tenancies and Attributes Thereof/
- /233-IV(F) Termination/
- /233-IV(F)1 In General/
- *233-k-904 Creation of new tenancy*

Residential building owner which had purchased building at foreclosure sale was not a “successor owner” within meaning of statute prohibiting a successor owner from evicting a tenant for nonpayment of rent absent compliance with management disclosures, where owner did not assume existing lease and its terms and conditions, but instead executed a new, separate lease with tenant through its management company, and that lease controlled the tenancy and the rights and obligations of the parties. Cal. Civ. Code § 1962(c).

- 1 Case that cites this headnote

*** [14] Landlord and Tenant  [[14: 233-k-1747][233-k-1747]]  Right to Maintain Action and Conditions Precedent
ProcessMailing as constructive service

- /233 Landlord and Tenant/
- /233-VIII Reentry and Recovery of Possession by Landlord/
- /233-VIII(C) Actions for Recovery of Possession/
- *233-k-1747 Right to Maintain Action and Conditions Precedent*
- *233-k-1748 In general*
- /313 Process/
- /313-II Service/
- /313-II(B) Substituted Service/
- *313-k-76 Mode and Sufficiency of Service*
- *313-k-82 Mailing as constructive service*

When an owner, successor owner, manager, or agent fails to comply with statutory requirements to disclose and keep current specified information, the tenant is excused from effecting personal service on them, and he is permitted to effect service of process by mail, and there is no other penalty imposed on the owner for its failure to comply; however, when a successor owner or manager fails to provide the specified information, it also is prohibited from evicting the tenant based on unpaid rent accruing during the period of noncompliance. Cal. Civ. Code §§ 1962, 1962.7.

*** [15] Landlord and Tenant  [[15: 233-k-1747][233-k-1747]]  Right to Maintain Action and Conditions Precedent

- /233 Landlord and Tenant/
- /233-VIII Reentry and Recovery of Possession by Landlord/
- /233-VIII(C) Actions for Recovery of Possession/
- *233-k-1747 Right to Maintain Action and Conditions Precedent*
- *233-k-1748 In general*

Primary purpose for adding subdivision to statute providing that a successor owner or manager who fails to provide specified information to a tenant is prohibited from evicting the tenant based on unpaid rent accruing during the period of noncompliance was to ensure successor owners and/or their managers would notify their tenants where they were to send rent payments so as to avoid evictions based on nonpayment of rent. Cal. Civ. Code § 1962(c).

- 1 Case that cites this headnote

*** [16] Landlord and Tenant  [[16: 233-k-1783][233-k-1783]]  Right of Action and Defenses

- /233 Landlord and Tenant/
- /233-VIII Reentry and Recovery of Possession by Landlord/
- /233-VIII(D) Actions for Unlawful Detainer/
- *233-k-1783 Right of Action and Defenses*
- *233-k-1784 In general*

Where an owner or its manager enters into a new lease with an existing tenant, the owner or its manager is not a “successor” owner or manager for purposes of providing that a successor owner or manager who fails to provide specified information to a tenant is prohibited from evicting the tenant based on unpaid rent accruing during the period of noncompliance, and an unlawful detainer action based on nonpayment of rent is not prohibited. Cal. Civ. Code § 1962.

<<**308>> Appeal from an order of the Superior Court of Los Angeles County, Lancaster, Trial Judge Paul A. Bacigalupo. Affirmed. Lancaster Trial Court No. 16UA0882
** Attorneys and Law Firms

- BASTA, Inc., Daniel J. Bramzon, Kevin Hermansen, Los Angeles, Ross T. Kutach and Eric M. Post, for Defendant and Appellant.
- Nussbaum, Brandon S. Dimond and Lane M. Nussbaum, Glendale, for Plaintiff and Respondent.

** OPINION

Richardson, J.

<<**309>> *4 INTRODUCTION

Plaintiff DLI Properties, LLC filed an unlawful detainer action against defendant Cherokee Hill after she failed to pay rent and defaulted on the parties’ lease agreement. Defendant raised as an affirmative defense plaintiff’s failure to comply with Civil Code section 1962 ’s1 disclosure requirements. On appeal, defendant contends section 1962, subdivision (c), bars a “successor owner” from instituting eviction proceedings based on nonpayment of rent during the period of statutory noncompliance and, in her case, plaintiff did not make the required disclosures in the rental agreement. We determine that plaintiff was not a successor owner for purposes of section 1962, subdivision (c) and affirm.

1

All further statutory references are to the Civil Code unless otherwise indicated.

BACKGROUND2

2

The facts pertaining to defendant’s default under the lease and failure to comply with the three-day notice are omitted as irrelevant to the issues on appeal.

Defendant moved into the subject property in 2011, when she entered into a rental agreement with the owners, Prince E. Cullum, Sr. and Bernice Leola Cullum. The Cullums lost the home to foreclosure, and the property was sold to plaintiff on September 8, 2015.

Plaintiff hired Strategic Property Management, Inc. (Strategic) to manage the property. On the date of the sale, Strategic and defendant executed a new rental agreement for the premises. In the written month-to-month rental agreement, “Strategic Property Management Inc.” was listed as “Landlord.” Defendant was directed to pay rent to “DLI Properties LLC” at “P.O. Box 1029 Agoura Hills, Ca 91376” (¶ 3). Regarding service of notices, defendant <<*5>> was directed to send notices to “Landlord: Strategic Property Management Inc [¶] P.O. Box 1029 [¶] Agoura Hills, Ca 91376” (¶ 36).

At the trial, Olinka Morales testified she was employed by Strategic to manage the property. She identified the rental lease agreement between Strategic and defendant noted above. During cross-examination, Morales stated that Fabiola Mendoza and Beverly Jacobo were also authorized to manage the property. She testified the business address for Strategic was not the post office box address listed in the rental agreement, but rather a street address.

Outside the presence of the jury, defendant moved for nonsuit, claiming the action was barred under section 1962, subdivision (c). Defendant argued section 1962 required the rental agreement to disclose certain information for effecting personal service, and the evidence presented in plaintiff’s case-in-chief established lack of compliance. Plaintiff countered that section 1962 did not apply to the circumstances of this case. The court denied the motion.

Defendant testified Strategic became the “new landlord” in September 2015, and <<**310>> she had contacts and communications with it concerning habitability issues pertaining to the property. After the parties rested, defendant moved for a directed verdict based on plaintiff’s failure to comply with section 1962. As before, plaintiff maintained the statute did not apply because it only implicated “successor owners” and, in this instance, the parties had executed a new lease. The court denied defendant’s motion.

The jury returned a verdict in favor of plaintiff, finding plaintiff served a valid three-day notice and did not breach the warranty of habitability. Thereafter, defendant moved for judgment notwithstanding the verdict (JNOV), once again arguing plaintiff had not complied with section 1962. The trial court denied the motion, stating, “The court finds that the owner, plaintiff, through its management agent complied with the Code under 1962 for purposes of notice.”

DISCUSSION

[1] <<1: 30-k-105>>Defendant contends the court should have granted a nonsuit or issued a directed verdict in her favor, and the court erred in denying her JNOV motion. (Code Civ. Proc., §§ 581c, 630, 629.)3

3

Denial of a motion for nonsuit or directed verdict may be reviewed on appeal from the judgment. (Adams v. City of Fremont (1998) 68 Cal.App.4th 243, 263, 80 Cal.Rptr.2d 196.)

<<*6>> Motions for Nonsuit, Directed Verdict, and JNOV

[2] <<2: 228-k-199>> [3] <<3: 228-k-199>>“While made at different times, the three motions are analytically the same and governed by the same rules. [Citation.] The function of these motions is to prevent the moving defendant from the necessity of undergoing any further exposure to legal liability when there is insufficient evidence for an adverse verdict. [Citation.] Put another way, the purpose of motions for nonsuit, directed verdicts and jnovs is to allow a party to prevail as a matter of law where the relevant evidence is already in.” (Fountain Valley Chateau Blanc Homeowner’s Assn. v. Dept. of Veterans Affairs (1998) 67 Cal.App.4th 743, 750, 79 Cal.Rptr.2d 248, italics omitted.)

[4] <<4: 228-k-199(3.10)>> [5] <<5: 30-k-3956>> [6] <<6: 30-k-3566>>A trial court may grant these motions “only if it appears from the evidence, viewed in the light most favorable to the party securing the verdict, that there is no substantial evidence to support it. [Citation.]” (Gonzales v. City of Atwater (2016) 6 Cal.App.5th 929, 946, 212 Cal.Rptr.3d 137; Adams v. City of Fremont, supra, 68 Cal.App.4th at p. 262, 80 Cal.Rptr.2d 196.) In reviewing the denial of these motions, the appellate court, like the trial court, must evaluate the evidence in the light most favorable to the plaintiff. (Id. at p. 263, 80 Cal.Rptr.2d 196.) Where, as here, the motions “raise[ ] legal issues, such as the application of law to undisputed facts or the interpretation of a statute, we review the trial court’s ruling ‘under a de novo standard of review.’ [Citations.]” (Gonzales v. City of Atwater, supra, 6 Cal.App.5th at pp. 946-947, 212 Cal.Rptr.3d 137.)

Statutory Interpretation

We are tasked to determine whether the rental agreement at issue conformed to the requirements of section 1962, subdivision (a), and whether subdivision (c)’s prohibition applied to plaintiff. This appeal then involves resolving questions of law based on undisputed facts, and we review the trial court’s ruling de novo. (Krechuniak v. Noorzoy (2017) 11 Cal.App.5th 713, 723, 217 Cal.Rptr.3d 740.)

[7] <<7: 361-k-1080>> [8] <<8: 361-k-1369>> [9] <<9: 361-k-1102>> [10] <<10: 361-k-1187>>In construing section 1962, we must “ ‘ “ ‘ “ascertain the intent of the lawmakers <<**311>> so as to effectuate the purpose of the statute.” ’ ” ’ ” (De Vries v. Regents of the University of California (2016) 6 Cal.App.5th 574, 593, 211 Cal.Rptr.3d 435.) We begin, as always, with the statute’s actual words, the “most reliable indicator” of legislative intent, “assigning them their usual and ordinary meanings, and construing them in context. If the words themselves are not ambiguous, we presume the Legislature meant what it said, and the statute’s plain meaning governs. On the other hand, if the language allows more than one reasonable construction, we may look to such aids as the legislative history of the measure and maxims of statutory construction. In cases of uncertain meaning, we may also consider the consequences of a *7 particular interpretation, including its impact on public policy. [Citations.]” (Wells v. One2One Learning Foundation (2006) 39 Cal.4th 1164, 1190, 48 Cal.Rptr.3d 108, 141 P.3d 225.)

Civil Code Section 1962, Subdivisions (a) and (b)

Section 1962, subdivision (a) provides, in pertinent part, “Any owner of a dwelling structure specified in Section 1961 or a party signing a rental agreement or lease on behalf of the owner shall do all of the following: [¶] (1) Disclose therein the name, telephone number, and usual street address at which personal service may be effected of each person who is: [¶] (A) Authorized to manage the premises. [¶] (B) An owner of the premises or a person who is authorized to act for and on behalf of the owner for the purpose of service of process and for the purpose of receiving and receipting for all notices and demands. [¶] (2) Disclose therein the name, telephone number, and address of the person or entity to whom rent payments shall be made.”

Section 1962, subdivision (c) provides, “The information required by this section shall be kept current and this section shall extend to and be enforceable against any successor owner or manager, who shall comply with this section within 15 days of succeeding the previous owner or manager. A successor owner or manager shall not serve a notice pursuant to paragraph (2) of Section 1161 of the Code of Civil Procedure or otherwise evict a tenant for nonpayment of rent that accrued during the period of noncompliance by a successor owner or manager with this subdivision. Nothing in this subdivision shall relieve the tenant of any liability for unpaid rent.”

Plain language

It is clear from the plain terms of the statute that the requirement to disclose pertinent information applies to two distinct entities—“owners” and “successor owners.” Section 1962, subdivision (a) expressly states it applies to “[a]ny owner ... or a party signing a rental agreement or lease on behalf of the owner” and requires the disclosure of specified information. Section 1962, subdivision (c) states the disclosure requirements “shall extend to and be enforceable against any successor owner or manager.” Section 1962, subdivision (c) further provides that if a successor owner or manager fails to provide the specified information, the prohibition against eviction applies. There is no similar penalty for an owner or its agent who fails to comply with disclosure requirements under either section 1962, subdivision (a) or (c).

[11] <<11: 29T-k-200>>The undisputed evidence presented at trial established plaintiff’s noncompliance with disclosure requirements. Defendant points out the rental agreement identified “SPM” as the “Landlord” but did not identify or designate an <<*8>> owner or an agent who was authorized to act on the owner’s behalf for service of process. The lease also did not disclose the “usual street address” of such persons or entities, a valid telephone number, or the contact information **312 for any of the persons authorized to manage the premises.

Based on these omissions, defendant contends the trial court erred in finding plaintiff complied with the requirements. We agree the evidence established a lack of strict compliance. Nevertheless, as we explain below, based on our conclusion that section 1962, subdivision (c) did not apply to plaintiff, we affirm the judgment and the court’s denials of defendant’s motions. (Leyva v. Crockett & Co., Inc. (2017) 7 Cal.App.5th 1105, 1108, 212 Cal.Rptr.3d 879 [“ ‘We are not bound by the issues actually decided by the trial court. “The appellate court should affirm the judgment of the trial court if it is correct on any theory of law applicable to the case” ’ ”].)

Ambiguity

Defendant contends that, under the statute, “if a new owner assumes a previously signed lease agreement ... that successor-owner must still provide ... disclosures.” She does not respond, however, to plaintiff’s argument that a new owner who does not assume the existing lease, but instead executes a separate new lease with the tenant, is an owner and not a successor owner for purposes of section 1962, subdivision (c) ’s bar against evictions.

The question then becomes whether plaintiff qualifies as a successor owner to which subdivision (c) applies. Because section 1962 does not define “owner” or “successor owner,” and it is silent as to whether a new owner who executes a separate new lease with the tenant is an “owner,” there is a legitimate ambiguity in the statute.

[12] <<12: 233-k-627>>After a property is sold or transferred, the transferee takes subject to the existing lease; this new owner steps into the landlord’s shoes and becomes the successor landlord, assuming the terms and conditions of the lease the tenant had with the prior owner. (See Kirk Corp. v. First American Title Co. (1990) 220 Cal.App.3d 785, 809, 270 Cal.Rptr. 24.) The same is true when the property is sold through foreclosure, as was the case here. (See Nativi v. Deutsche Bank National Trust Co. (2014) 223 Cal.App.4th 261, 275, 167 Cal.Rptr.3d 173.)

Plaintiff argues the term “successor owner” “clearly refers to an owner who acquired a property ... during the tenancy” and succeeded to ownership and assumed the existing lease. Black’s Law Dictionary defines “Successor” as: “One that succeeds or follows; one who takes the place that another has left, <<*9>> and sustains the like part or character; ...” (Black’s Law Dict. (6th ed. 1990) p. 1431, col. 2, boldface omitted.) Notably, the Legislature chose to use the phrase “successor owner or manager” rather than “successor in interest,” which has a more restrictive definition—“One who follows another in ownership ... of property.” (Ibid.) This seems to suggest that the applicability of section 1962, subdivision (c) is not dependent on whether a person or entity succeeds in “ownership” of the subject property, and it supports our conclusion that the term “successor owner” or “successor ... manager” is referring to the rights and duties, not in the property, but rather with respect to the existing lease. (See River Garden Retirement Home v. Franchise Tax Bd. (2010) 186 Cal.App.4th 922, 954, 113 Cal.Rptr.3d 62 [“every word and phrase has significance and was chosen for a purpose”].)

[13] <<13: 233-k-627>>In this case, after plaintiff purchased the subject property, it did not assume the existing lease and its terms and conditions. Rather, it’s management company, Strategic, executed a new and separate lease with defendant. Defendant’s tenancy and the rights and obligations of the parties were, therefore, controlled by <<**313>> this new lease. As a consequence, plaintiff was not succeeding to the rights and obligations of the prior owners (the Cullums) under the prior rental agreement.

[14] <<14: 233-k-1747>>For purposes of this appeal, we agree with plaintiff that there is an important distinction to be made between an owner whose identity may not be known following a sale of the property and an owner (or owner’s manager) whose identity is made known because a new lease is executed. When an owner, successor owner, manager, or agent fails to comply with section 1962 ’s requirements to disclose and keep current specified information, the tenant, under section 1962.7, is excused from effecting personal service on them, and he is permitted to effect service of process by mail. There is no other penalty imposed on the owner for its failure to comply. However, when a successor owner or manager fails to provide the specified information, it also is prohibited from evicting the tenant based on unpaid rent accruing during the period of noncompliance.

This disparate treatment of owner and successor owner/manager for the same dereliction of their statutory duty indicates the prohibition is meant to specifically target successor owners and their managers to address a danger posed by the change in ownership. There is a greater likelihood a tenant would not be aware of relevant information concerning a successor owner/manager rather than an owner with which he enters into a lease agreement. Therefore, the prohibition against evictions encourages and incentivizes a successor owner/manager to disclose such information.

<<*10>> Our interpretation is informed and bolstered by the legislative history and analysis of Assembly Bill No. 1953, which added subdivision (c) to section 1962 in 2012.

The key issue before the Assembly Committee on Judiciary was whether tenants should “be protected from eviction by a successor owner of the rental property for nonpayment of rent that could have otherwise been paid and received if that owner had complied with existing law requiring prompt notice of where to pay rent.” (Assem. Com. on Judiciary, Analysis of Assem. Bill No. 1953 (2011-2012 Reg. Sess.) as amended Mar. 29, 2012 p. 1, capitalization omitted.)

The bill’s author explained the need for additional law: “Purchasers or rental properties, especially foreclosed homes, are increasingly allowing months to go by without notifying tenants where to pay rent. When a new owner fails to timely inform the tenant to whom rent should be paid, but then months later serve [sic] a three-day notice demanding all of the accumulated rent, many low-income tenants no longer have the money to pay and keep their homes. Good tenants end up losing their housing because their landlord failed to comply with the law, unnecessarily creating nonpayment situations. This bill will help prevent unnecessary evictions after ownership changes.” (Assem. Com. on Judiciary, Analysis of Assem. Bill No. 1953 (2011-2012 Reg. Sess.) as amended Mar. 29, 2012, p. 4.)

Tenants Together, a sponsor of the bill, noted that “some tenants have received three day pay-or-quit notices from their landlord for failure to pay rent when such failure occurred only because the tenant had not been properly notified by the new owner of the property where to send the rent payment. With accounts of rental scams increasingly in the news ..., supporters contend that it is reasonable for tenants to refrain from sending rent to the person they know to be the former owner, or other unknown persons, unless they have received proper notice from the new <<**314>> owner were to send rent, as required by law. As acknowledged by the California Apartment Association, ‘It is logical to assume that if a new owner doesn’t provide notice to a tenant about change in ownership, the new owner cannot expect to receive the rent timely.’ ” (Assem. Com. on Judiciary, 3d reading analysis of Assem. Bill No. 1953 (2011-2012 Reg. Sess.) as amended May 9, 2012, p. 2.)

The bill’s author also noted the abuse “[i]n rent control jurisdictions,” where “new owners in some cases delay notifying tenants where to send rent, allow rent to build up, and then after many months evict for nonpayment in order to vacate homes of low-rent tenants. In addition, the failure of new owners to timely notify tenants where to pay rent can lead to particular <<*11>> problems for tenants who receive benefits such as SSI, as these tenants risk losing their benefits if they accumulate too much money in their bank accounts.” (Sen. Judiciary Com., Analysis of Assem. Bill No. 1953 (2011-2012 Reg. Sess.) as amended May 9, 2012, p. 3.)

[15] <<15: 233-k-1747>>Thus, the legislative history makes clear the primary purpose for adding subdivision (c) to section 1962 was to ensure successor owners and/or their managers would notify their tenants where they were to send rent payments so as to avoid evictions based on nonpayment of rent. The instant case did not involve any of the scenarios for which the legislature had expressed concern and which prompted the addition of section 1962, subdivision (c). In fact, any concern about successor owner abuse along those lines was effectively addressed by the execution of a new lease between plaintiff’s manager and defendant on the day plaintiff became the owner of the property.

[16] <<16: 233-k-1783>>Where, as here, an owner or its manager enters into a new lease with an existing tenant, the owner or its manager is not a “successor” owner or manager for purposes of section 1962, subdivision (c), and subdivision (c) does not apply to bar an unlawful detainer action. As such, any deficiencies in the information disclosed in the new lease are addressed by operation of section 1962.7. Our conclusion is supported by a common sense interpretation of section 1962 and the legislative history relating to the addition of subdivision (c).4

4

Contrary to defendant’s argument, our interpretation does not render subdivision (c) a nullity because it still applies to new owners who assume an existing lease with the tenant.

DISPOSITION

The judgment is affirmed. Plaintiff to recover costs on appeal.

P. McKay, P. J., and Ricciardulli, J., concurred.
