#+title:      City of Seattle v. Long, 198 Wn.2d 136, 493 P.3d 94 (2021)
#+date:       [2021-08-12 Thu 00:00]
#+filetags:   :case:law:
#+identifier: 20210812T000000

* City of Seattle v. Long -- Supreme Court of Washington, En Banc. | August 12, 2021 | 198 Wash.2d 136 | 493 P.3d 94

- Washington Citation :: City of Seattle v. Long, 198 Wn.2d 136, 493 P.3d 94 (2021)
- All Citations :: 198 Wash.2d 136, 493 P.3d 94

** Brief

** Document Details

- Outline
- Synopsis
- West Headnotes
- Attorneys and Law Firms
- Opinion
- Concurring Opinion
- All Citations

** KeyCite:

- KeyCite Yellow Flag - Negative Treatment
- Distinguished byState v. Griepsma, Wash.App. Div. 1, March 13, 2023

* Case

                           198 Wash.2d 136

                     Supreme Court of Washington,

                               En Banc.

                     CITY OF SEATTLE, Respondent,

                                  v.

                   Steven Gregory LONG, Petitioner.

                             No. 98824-2
                        Filed: August 12, 2021
** Synopsis

Background: Truck owner sought review of municipal court order requiring him to reimburse city $547.12 for impoundment costs via payment plan of $50 per month, for truck that served as owner’s home. The Superior Court, King County, Catherine Shaffer, J., affirmed in part and reversed part. City petitioned for discretionary review, and owner cross-petitioned. The Court of Appeals, 13 Wash.App.2d 709, 467 P.3d 979, affirmed in part and reversed in part. Parties sought further review.

Holdings: In a case of first impression, the Supreme Court, en banc, Madsen, J., held that:

[1] truck automatically qualified as a homestead;

[2] homestead claim was premature;

[3] impoundment did not violate state constitutional provision protecting against unwarranted government intrusions into private affairs;

[4] impoundment and associated costs were partially punitive and thus constituted fines;

[5] a court considering whether a fine is constitutionally excessive should consider a person’s ability to pay; and

[6] payment plan as imposed violated excessive fines clause.

Affirmed in part and reversed in part.

González, C.J., filed concurring opinion.

Procedural Posture(s): Petition for Discretionary Review; On Appeal; Motion for Summary Judgment.

** West Headnotes (49)

*** [1] Appeal and Error  [[1: 30-k-3555][30-k-3555]]  Review using standard applied below

- /30 Appeal and Error/
- /30-XVI Review/
- /30-XVI(D) Scope and Extent of Review/
- /30-XV I(D)13Summary Judgment/
- *30-k-3555 Review using standard applied below*

Supreme Court reviews a summary judgment order de novo, engaging in the same inquiry as the trial court.

- 5 Cases that cite this headnote

*** [2] Homestead  [[2: 202-k-1][202-k-1]]  Nature of estate or right

- /202 Homestead/
- /202-I Nature, Acquisition, and Extent/
- /202-I(A) Nature, Creation, and Duration of Estate or Right in General/
- *202-k-1 Nature of estate or right*

Homestead act implements the policy that each citizen have a home where the family may be sheltered and live beyond the reach of financial misfortune. Wash. Rev. Code Ann. § 6.13.010 et seq.

- 3 Cases that cite this headnote

*** [3] Homestead  [[3: 202-k-5][202-k-5]]  Construction of homestead laws in general

- /202 Homestead/
- /202-I Nature, Acquisition, and Extent/
- /202-I(A) Nature, Creation, and Duration of Estate or Right in General/
- *202-k-5 Construction of homestead laws in general*

Homestead act is favored in law, and courts construe it liberally so it may achieve its purpose of protecting family homes. Wash. Rev. Code Ann. § 6.13.010 et seq.

*** [4] Appeal and Error  [[4: 30-k-3173][30-k-3173]]  Statutory or legislative law

- /30 Appeal and Error/
- /30-XVI Review/
- /30-XVI(D) Scope and Extent of Review/
- /30-XVI(D)2 Particular Subjects of Review in General/
- *30-k-3169 Construction, Interpretation, or Application of Law*
- *30-k-3173 Statutory or legislative law*

Meaning of a statute is a question of law that Supreme Court reviews de novo.

*** [5] Statutes  [[5: 361-k-1071][361-k-1071]]  Intent

- /361 Statutes/
- /361-III Construction/
- /361-III(A) In General/
- *361-k-1071 Intent*
- *361-k-1072 In general*

A court’s fundamental objective in construing a statute is to ascertain and carry out the legislature’s intent.

- 3 Cases that cite this headnote

*** [6] Statutes Plain Language;  Plain, Ordinary, or Common Meaning

- /361 Statutes/
- /361-III Construction/
- /361-III(B) Plain Language;  Plain, Ordinary, or Common Meaning/
- *361-k-1091 In general*

If a statute’s meaning is plain on its face, a court must follow that plain meaning.

- 1 Case that cites this headnote

*** [7] Statutes  [[7: 361-k-1082][361-k-1082]]  Construction based on multiple factors

- /361 Statutes/
- /361-III Construction/
- /361-III(A) In General/
- *361-k-1082 Construction based on multiple factors*

A statute’s plain meaning is discerned from the ordinary meaning of the language, the context of the statute, related provisions, and the statutory scheme as a whole.

- 6 Cases that cite this headnote

*** [8] Statutes  [[8: 361-k-1156][361-k-1156]]  Superfluousness

- /361 Statutes/
- /361-III Construction/
- /361-III(E) Statute as a Whole;  Relation of Parts to Whole and to One Another/
- *361-k-1156 Superfluousness*

Whenever possible, statutes are to be construed so no clause, sentence, or word shall be superfluous, void, or insignificant.

- 4 Cases that cite this headnote

*** [9] Statutes  [[9: 361-k-1105][361-k-1105]]  Purpose and intent;  determination thereof
StatutesPlain, literal, or clear meaning;  ambiguity

- /361 Statutes/
- /361-III Construction/
- /361-III(C) Clarity and Ambiguity;  Multiple Meanings/
- *361-k-1103 Resolution of Ambiguity;  Construction of Unclear or Ambiguous Statute or Language*
- *361-k-1105 Purpose and intent;  determination thereof*
- /361 Statutes/
- /361-III Construction/
- /361-III(H) Legislative History/
- *361-k-1242 Plain, literal, or clear meaning;  ambiguity*

If a statute is ambiguous, a court may look to the legislative history of the statute and the circumstances surrounding its enactment to determine legislative intent.

*** [10] Homestead  [[10: 202-k-42][202-k-42]]  Necessity
HomesteadNature of property in general

- /202 Homestead/
- /202-I Nature, Acquisition, and Extent/
- /202-I(C) Acquisition and Establishment/
- *202-k-41 Declaration or Certificate*
- *202-k-42 Necessity*
- /202 Homestead/
- /202-I Nature, Acquisition, and Extent/
- /202-I(D) Property Constituting Homestead/
- *202-k-58 Nature of property in general*

Homestead act automatically protects personal property occupied as a principal residence, and no declaration is required. Wash. Rev. Code Ann. § 6.13.040(1).

*** [11] Statutes  [[11: 361-k-1366][361-k-1366]]  Language

- /361 Statutes/
- /361-III Construction/
- /361-III(M) Presumptions and Inferences as to Construction/
- *361-k-1366 Language*
- *361-k-1367 In general*

A court presumes that the legislature says what it means and means what it says.

- 3 Cases that cite this headnote

*** [12] Statutes  [[12: 361-k-1375][361-k-1375]]  Similarity or difference

- /361 Statutes/
- /361-III Construction/
- /361-III(M) Presumptions and Inferences as to Construction/
- *361-k-1372 Statute as a Whole;  Relation of Parts to Whole and to One Another*
- *361-k-1375 Similarity or difference*

When the legislature uses two different terms in the same statute, a court presumes the legislature intends the terms to have different meanings.

*** [13] Homestead  [[13: 202-k-42][202-k-42]]  Necessity
HomesteadNature of property in general

- /202 Homestead/
- /202-I Nature, Acquisition, and Extent/
- /202-I(C) Acquisition and Establishment/
- *202-k-41 Declaration or Certificate*
- *202-k-42 Necessity*
- /202 Homestead/
- /202-I Nature, Acquisition, and Extent/
- /202-I(D) Property Constituting Homestead/
- *202-k-58 Nature of property in general*

Truck that served as owner’s home and that was impounded by city for parking infraction automatically qualified as a homestead without need for owner to file a declaration. Wash. Rev. Code Ann. § 6.13.040(1).

*** [14] Homestead  [[14: 202-k-197][202-k-197]]  Contest and determination of claim

- /202 Homestead/
- /202-V Protection and Enforcement of Rights/
- *202-k-197 Contest and determination of claim*

Truck owner’s homestead claim seeking shield against attachment, execution, or forced sale of his truck that served as his home and that was impounded by city for parking infraction was premature, where city did not seek to collect on owner’s debt in the form of impoundment costs for which magistrate set up payment plan to reimburse city. Wash. Rev. Code Ann. §§ 6.13.030, 6.13.070.

*** [15] Creditors’ Remedies Particular Remedies--Execution

- /108 HCreditors’ Remedies/
- /108H-VI Particular Remedies--Execution/
- /108H-VI(A) In General/
- *108H-k-321 In general*

An “execution” is a judicial mode of obtaining the debt recovered by judgment such as a lien.

*** [16] Creditors’ Remedies  [[16: 108H-k-322][108H-k-322]]  Particular forms of execution

- /108 HCreditors’ Remedies/
- /108H-VI Particular Remedies--Execution/
- /108H-VI(A) In General/
- *108H-k-322 Particular forms of execution*

A “forced sale” is a nonconsensual sale to recover a debt.

*** [17] Homestead  [[17: 202-k-5][202-k-5]]  Construction of homestead laws in general

- /202 Homestead/
- /202-I Nature, Acquisition, and Extent/
- /202-I(A) Nature, Creation, and Duration of Estate or Right in General/
- *202-k-5 Construction of homestead laws in general*

Homestead act operates as a shield to protect against creditors’ actions; it is not a sword to prevent such actions in the first instance. Wash. Rev. Code Ann. § 6.13.010 et seq.

*** [18] Homestead  [[18: 202-k-61][202-k-61]]  Amount or Extent

- /202 Homestead/
- /202-I Nature, Acquisition, and Extent/
- /202-I(D) Property Constituting Homestead/
- *202-k-61 Amount or Extent*
- *202-k-62 In general*

A “debt” contemplated by homestead act’s shield against attachment, execution, or forced sale for the debts of the owner is determined at adjudication. Wash. Rev. Code Ann. §§ 6.13.030, 6.13.070.

*** [19] Appeal and Error  [[19: 30-k-169][30-k-169]]  Necessity of presentation in general

- /30 Appeal and Error/
- /30-V Presentation and Reservation in Lower Court of Grounds of Review/
- /30-V(A) Issues and Questions in Lower Court/
- *30-k-169 Necessity of presentation in general*

Generally, a party waives the right to raise an issue on appeal that was not raised before the trial court.

- 1 Case that cites this headnote

*** [20] Appeal and Error  [[20: 30-k-170(2)][30-k-170(2)]]  Constitutional questions

- /30 Appeal and Error/
- /30-V Presentation and Reservation in Lower Court of Grounds of Review/
- /30-V(A) Issues and Questions in Lower Court/
- *30-k-170 Nature or Subject-Matter of Issues or Questions*
- *30-k-170(2) Constitutional questions*

To obtain review of unpreserved error on the basis that it is manifest error affecting a constitutional right, an appellant must show (1) the error is manifest and (2) the error is truly of constitutional dimension. Wash. R. App. P. 2.5(a).

- 3 Cases that cite this headnote

*** [21] Appeal and Error  [[21: 30-k-170(2)][30-k-170(2)]]  Constitutional questions

- /30 Appeal and Error/
- /30-V Presentation and Reservation in Lower Court of Grounds of Review/
- /30-V(A) Issues and Questions in Lower Court/
- *30-k-170 Nature or Subject-Matter of Issues or Questions*
- *30-k-170(2) Constitutional questions*

In determining whether an unpreserved error may be reviewed on the basis that it is manifest error affecting a constitutional right, a reviewing court looks to the asserted claim and assesses whether, if correct, it implicates a constitutional interest. Wash. R. App. P. 2.5(a).

- 2 Cases that cite this headnote

*** [22] Appeal and Error  [[22: 30-k-170(2)][30-k-170(2)]]  Constitutional questions

- /30 Appeal and Error/
- /30-V Presentation and Reservation in Lower Court of Grounds of Review/
- /30-V(A) Issues and Questions in Lower Court/
- *30-k-170 Nature or Subject-Matter of Issues or Questions*
- *30-k-170(2) Constitutional questions*

Whether an error is manifest under rule providing for review of unpreserved manifest error affecting a constitutional right requires a showing of actual prejudice. Wash. R. App. P. 2.5(a).

- 3 Cases that cite this headnote

*** [23] Search, Seizure, and Arrest  [[23: 349-k-488][349-k-488]]  Persons and Personal Effects in General

- /349 Search, Seizure, and Arrest/
- /349-II Searches and Seizures in General/
- /349-II(C) Persons, Places, and Things Protected/
- *349-k-488 Persons and Personal Effects in General*
- *349-k-489 In general*
- /(Formerly 349k26 Searches and Seizures)/

A two-step analysis applies to determine the existence of a violation of state constitutional provision protecting against unwarranted government intrusions into private affairs, with a court first determining whether the action complained of disturbs one’s private affairs, and, if so, then determining whether authority of law justifies the intrusion. Wash. Const. art. 1, § 7.

*** [24] Search, Seizure, and Arrest  [[24: 349-k-1767][349-k-1767]]  Validity; reasonableness

- /349 Search, Seizure, and Arrest/
- /349-XI Judicial Review or Determination/
- /349-XI(C) Presumptions, Inferences, and Burden of Proof/
- *349-k-1765 Warrantless Searches in General*
- *349-k-1767 Validity; reasonableness*
- /(Formerly 349k24 Searches and Seizures)/

Warrantless seizures are per se unreasonable. Wash. Const. art. 1, § 7.

*** [25] Search, Seizure, and Arrest  [[25: 349-k-1767][349-k-1767]]  Validity; reasonableness

- /349 Search, Seizure, and Arrest/
- /349-XI Judicial Review or Determination/
- /349-XI(C) Presumptions, Inferences, and Burden of Proof/
- *349-k-1765 Warrantless Searches in General*
- *349-k-1767 Validity; reasonableness*
- /(Formerly 349k192.1 Searches and Seizures)/

State bears the burden of demonstrating that a warrantless seizure falls into a narrow exception to the rule that warrantless seizures are per se unreasonable. Wash. Const. art. 1, § 7.

- 1 Case that cites this headnote

*** [26] Search, Seizure, and Arrest  [[26: 349-k-445][349-k-445]]  Vehicles

- /349 Search, Seizure, and Arrest/
- /349-II Searches and Seizures in General/
- /349-II(B) What Constitutes Search or Seizure/
- *349-k-440 Particular Cases and Contexts in General*
- *349-k-445 Vehicles*
- /(Formerly 349k18 Searches and Seizures)/

Impounding a car is a “seizure” under the State Constitution. Wash. Const. art. 1, § 7.

*** [27] Search, Seizure, and Arrest  [[27: 349-k-661][349-k-661]]  Impoundment and Inventory

- /349 Search, Seizure, and Arrest/
- /349-II Searches and Seizures in General/
- /349-II(E) Grounds and Scope/
- /349-II(E)2 Particular Cases and Contexts/
- *349-k-650 Motor Vehicles*
- *349-k-661 Impoundment and Inventory*
- *349-k-661(1) In general*
- /(Formerly 48Ak349.5(12))/

A vehicle may be lawfully impounded in the course of enforcing traffic regulations if the driver committed a traffic offense for which the legislature has expressly authorized impoundment.

*** [28] Search, Seizure, and Arrest  [[28: 349-k-661][349-k-661]]  Impoundment and Inventory

- /349 Search, Seizure, and Arrest/
- /349-II Searches and Seizures in General/
- /349-II(E) Grounds and Scope/
- /349-II(E)2 Particular Cases and Contexts/
- *349-k-650 Motor Vehicles*
- *349-k-661 Impoundment and Inventory*
- *349-k-661(1) In general*
- /(Formerly 349k66 Searches and Seizures)/

If no probable cause exists to seize a vehicle and a reasonable alternative to impoundment exists, it is unreasonable to impound the vehicle. Wash. Const. art. 1, § 7.

*** [29] Search, Seizure, and Arrest  [[29: 349-k-555][349-k-555]]  Reasonableness in general

- /349 Search, Seizure, and Arrest/
- /349-II Searches and Seizures in General/
- /349-II(E) Grounds and Scope/
- /349-II(E)1 In General/
- *349-k-555 Reasonableness in general*
- /(Formerly 349k23 Searches and Seizures)/

Reasonableness of a search or seizure is decided in light of the facts of the case, and a police officer must consider reasonable alternatives. Wash. Const. art. 1, § 7.

- 1 Case that cites this headnote

*** [30] Search, Seizure, and Arrest  [[30: 349-k-661][349-k-661]]  Impoundment and Inventory

- /349 Search, Seizure, and Arrest/
- /349-II Searches and Seizures in General/
- /349-II(E) Grounds and Scope/
- /349-II(E)2 Particular Cases and Contexts/
- *349-k-650 Motor Vehicles*
- *349-k-661 Impoundment and Inventory*
- *349-k-661(1) In general*
- /(Formerly 349k66 Searches and Seizures)/

Impoundment of a vehicle is lawful under state constitutional provision protecting against unwarranted government intrusions into private affairs only if, in the judgment of the impounding officer, it is reasonable under the circumstances and there are no reasonable alternatives. Wash. Const. art. 1, § 7.

- 1 Case that cites this headnote

*** [31] Automobiles  [[31: 48A-k-12][48A-k-12]]  Parking or standing

- /48 AAutomobiles/
- /48A-I Control, Regulation, and Use in General/
- *48A-k-12 Parking or standing*

Impoundment of truck for parking infraction after city posted notice of violation of 72-hour parking ordinance did not violate state constitutional provision protecting against unwarranted government intrusions into private affairs, where truck owner told officers his truck was in need of repairs and could not be driven, even though owner used truck as his home and did not have access to it for 21 days. Wash. Const. art. 1, § 7.

*** [32] Homestead  [[32: 202-k-5][202-k-5]]  Construction of homestead laws in general

- /202 Homestead/
- /202-I Nature, Acquisition, and Extent/
- /202-I(A) Nature, Creation, and Duration of Estate or Right in General/
- *202-k-5 Construction of homestead laws in general*

A vehicle owner can object to impoundment of vehicle that is his or her home and the payment of fees, but the homestead act is not a sword to prevent impoundment. Wash. Rev. Code Ann. §§ 6.13.030, 6.13.070.

*** [33] Homestead  [[33: 202-k-197][202-k-197]]  Contest and determination of claim

- /202 Homestead/
- /202-V Protection and Enforcement of Rights/
- *202-k-197 Contest and determination of claim*

Homestead protections are resolved upon enforcement, not issuance, of a parking ticket or impoundment of a vehicle that is the owner’s home. Wash. Rev. Code Ann. §§ 6.13.030, 6.13.070.

*** [34] Appeal and Error  [[34: 30-k-755][30-k-755]]  Necessity
Constitutional LawRelation to Constitutions of Other Jurisdictions

- /30 Appeal and Error/
- /30-XII Briefs/
- *30-k-755 Necessity*
- /92 Constitutional Law/
- /92-V Construction and Operation of Constitutional Provisions/
- /92-V(A) General Rules of Construction/
- *92-k-616 Relation to Constitutions of Other Jurisdictions*
- *92-k-617 In general*

When a party urges a different or more protective interpretation under the State Constitution for the first time, the Supreme Court expects supportive briefing, particularly when the language of that provision is identical to the federal constitutional provision.

- 1 Case that cites this headnote

*** [35] Fines  [[35: 174-k-1.3][174-k-1.3]]  Excessive fines

- /174 Fines/
- *174-k-1.3 Excessive fines*

The excessive fines clause limits the government’s power to extract payments, whether in cash or in kind, as punishment for some offense. U.S. Const. Amend. 8; Wash. Const. art. 1, § 14.

- 7 Cases that cite this headnote

*** [36] Fines  [[36: 174-k-1.3][174-k-1.3]]  Excessive fines

- /174 Fines/
- *174-k-1.3 Excessive fines*

A qualifying “fine” under the excessive fines clause is a payment to a sovereign as punishment for some offense. U.S. Const. Amend. 8; Wash. Const. art. 1, § 14.

- 4 Cases that cite this headnote

*** [37] Fines  [[37: 174-k-1.3][174-k-1.3]]  Excessive fines

- /174 Fines/
- *174-k-1.3 Excessive fines*

To trigger the excessive fines clause, a sanction must be a fine and it must be excessive. U.S. Const. Amend. 8; Wash. Const. art. 1, § 14.

- 16 Cases that cite this headnote

*** [38] Fines  [[38: 174-k-1.3][174-k-1.3]]  Excessive fines

- /174 Fines/
- *174-k-1.3 Excessive fines*

Qualifying fines under the excessive fines clause must be at least partially punitive. U.S. Const. Amend. 8; Wash. Const. art. 1, § 14.

- 12 Cases that cite this headnote

*** [39] Fines  [[39: 174-k-1.3][174-k-1.3]]  Excessive fines

- /174 Fines/
- *174-k-1.3 Excessive fines*

First step in an excessive fines inquiry is whether the state action is punishment, and the second inquiry is whether the fine is constitutionally excessive. U.S. Const. Amend. 8; Wash. Const. art. 1, § 14.

- 1 Case that cites this headnote

*** [40] Appeal and Error  [[40: 30-k-3722][30-k-3722]]  Constitutional Rights, Civil Rights, and Discrimination in General

- /30 Appeal and Error/
- /30-XVI Review/
- /30-XVI(D) Scope and Extent of Review/
- /30-XV I(D)22Substantive Matters/
- *30-k-3722 Constitutional Rights, Civil Rights, and Discrimination in General*
- *30-k-3723 In general*

The question of whether a fine is constitutionally excessive is subject to de novo review. U.S. Const. Amend. 8; Wash. Const. art. 1, § 14.

- 2 Cases that cite this headnote

*** [41] Automobiles  [[41: 48A-k-12][48A-k-12]]  Parking or standing
FinesExcessive fines

- /48 AAutomobiles/
- /48A-I Control, Regulation, and Use in General/
- *48A-k-12 Parking or standing*
- /174 Fines/
- *174-k-1.3 Excessive fines*

Impoundment and associated costs for truck that had a parking infraction were partially punitive and thus constituted fines under excessive fines clause, even though owner retrieved truck and costs were intended to reimburse city for towing and storage fees, where costs were imposed only as a result of the impoundment, which city code characterized as a penalty. U.S. Const. Amend. 8; Wash. Const. art. 1, § 14.

- 3 Cases that cite this headnote

*** [42] Courts  [[42: 106-k-97][106-k-97]]  Decisions of United States Courts as Authority in State Courts

- /106 Courts/
- /106-II Establishment, Organization, and Procedure/
- /106-II(G) Rules of Decision/
- *106-k-88 Previous Decisions as Controlling or as Precedents*
- *106-k-97 Decisions of United States Courts as Authority in State Courts*
- *106-k-97(1) In general*

On federal constitutional questions, the state Supreme Court is bound only by decisions of the United States Supreme Court.

- 1 Case that cites this headnote

*** [43] Fines  [[43: 174-k-1.3][174-k-1.3]]  Excessive fines

- /174 Fines/
- *174-k-1.3 Excessive fines*

Touchstone of constitutional inquiry under excessive fines clause is principle of proportionality; the amount of the forfeiture must bear some relationship to the gravity of the offense that it is designed to punish. U.S. Const. Amend. 8; Wash. Const. art. 1, § 14.

- 1 Case that cites this headnote

*** [44] Fines  [[44: 174-k-1.3][174-k-1.3]]  Excessive fines

- /174 Fines/
- *174-k-1.3 Excessive fines*

A fine violates the excessive fines clause if it is grossly disproportional to the gravity of a defendant’s offense. U.S. Const. Amend. 8; Wash. Const. art. 1, § 14.

- 8 Cases that cite this headnote

*** [45] Fines  [[45: 174-k-1.3][174-k-1.3]]  Excessive fines

- /174 Fines/
- *174-k-1.3 Excessive fines*

Test to determine whether a fine is grossly disproportional in violation of excessive fines clause includes: (1) nature and extent of crime, (2) whether violation was related to other illegal activities, (3) other penalties that may be imposed for violation, and (4) extent of harm caused. U.S. Const. Amend. 8; Wash. Const. art. 1, § 14.

- 8 Cases that cite this headnote

*** [46] Fines  [[46: 174-k-1.3][174-k-1.3]]  Excessive fines

- /174 Fines/
- *174-k-1.3 Excessive fines*

Excessiveness a fine concerns more than just an offense itself; it also includes consideration of an offender’s circumstances. U.S. Const. Amend. 8; Wash. Const. art. 1, § 14.

- 1 Case that cites this headnote

*** [47] Fines  [[47: 174-k-1.3][174-k-1.3]]  Excessive fines

- /174 Fines/
- *174-k-1.3 Excessive fines*

Central tenet of the excessive fines clause is to protect individuals against fines so oppressive as to deprive them of their livelihood. U.S. Const. Amend. 8; Wash. Const. art. 1, § 14.

- 2 Cases that cite this headnote

*** [48] Fines  [[48: 174-k-1.3][174-k-1.3]]  Excessive fines

- /174 Fines/
- *174-k-1.3 Excessive fines*

A court considering whether a fine is constitutionally excessive should consider a person’s ability to pay. U.S. Const. Amend. 8; Wash. Const. art. 1, § 14.

- 2 Cases that cite this headnote

*** [49] Automobiles  [[49: 48A-k-12][48A-k-12]]  Parking or standing
FinesExcessive fines

- /48 AAutomobiles/
- /48A-I Control, Regulation, and Use in General/
- *48A-k-12 Parking or standing*
- /174 Fines/
- *174-k-1.3 Excessive fines*

City’s impoundment of truck for parking infraction and $547.12 payment plan of $50 per month for impoundment costs were unconstitutionally excessive for truck owner who used truck as residence, where nature of offense was a civil parking infraction that carried a $44 fine, city suspended enforcement of the 72-hour parking violation during COVID-19 pandemic signaling that city viewed violation as a relatively minor offense, there was no evidence that the infraction was related to any other criminal activity, truck was not parked in residential area or area of hot demand for city vehicles, owner made at most $700 per month, owner was attempting to save for apartment to move himself out of homelessness, and owner could not access his tools for work as general tradesman during impoundment. U.S. Const. Amend. 8; Wash. Const. art. 1, § 14.

- 1 Case that cites this headnote

West Codenotes
Prior Version Recognized as Unconstitutional
Wash. Rev. Code Ann. §§ 46.55.350, 46.55.360
<<**97>> Appeal from King County Superior Court, Docket No: 17-2-15099-1, Honorable Catherine D. Shaffer, Judge
** Attorneys and Law Firms

- James Elliot Lobsenz, Carney Badley Spellman, Alison Sophia Bilow, Columbia Legal Services, Seattle, WA, for Petitioner.
- Erica Franklin, Seattle City Attorney’s Office, Robert Bertelson Mitchell Jr., Aaron Edward Millstein, K&L Gates LLP, Seattle, WA, Michael Jordan Thompson, Attorney at Law, Polson, MT, for Respondent.
- Thomas E. WeaverJr., Attorney at Law, Bremerton, WA, for Amicus Curiae on behalf of Wa Association of Criminal Defense Lawyers.
- William R. Maurer, Institute For Justice, Seattle, WA, for Amici Curiae on behalf of Institute for Justice, Southern Poverty Law Center, Oregon Law Center, Equal Justice Under Law, Policy Advocacy Clinic, MacArthur Justice Center.
- William R. Maurer, Institute For Justice, Seattle, WA, Lisa Foster, Fines and Fees Justice Center, New York, NY, for Amicus Curiae on behalf of Fines and Fees Justice Center.
- Nancy Lynn Talner, Breanne Schuster, American Civil Liberties Union of Washington, Julia Mizutani, Attorney at Law, Seattle, WA, for Amicus Curiae on behalf of Aclu of Washington.
- Alexandria Marie Hohman, The Washington Defender Association, Seattle, WA, for Amicus Curiae on behalf of Washington Defender Association.
- Ann Marie Logerfo, Logerfo Garella, PLLC, Seattle, WA, for Amicus Curiae on behalf of Interfaith Task Force On Homelessness.
- Sara Rankin, Homeless Rights Advocacy Project, Seattle, WA, for Amicus Curiae on behalf of Homeless Rights Advocacy Project.
- Tristia Bauman, National Law Center on Homelessness, Washington, DC, for Amicus Curiae on behalf of National Law Center On Homelessness and Poverty.
- Kymberly Kathryn Evanson, Pacifica Law Group LLP, Seattle, WA, for Amicus Curiae on behalf of International Municipal Lawyers Association.
- Kimberly Noel Gordon, Law Offices of Gordon & Saunders PLLC, Seattle, WA, Marsha L. Levick, Jessica Feierman, Lindsey E. Smith, Juvenile Law Center, Philadelphia, PA, for Amicui Curiae on behalf of Juvenile Law Center, African American Juvenile Justice Project, Center for Children and Youth Justice, Children and Family Justice Center, Civitas Childlaw Center, COAlition for Juvenile Justice, Justice Policy Institute, Legal Counsel for Youth and Children, National Center for Youth Law, National Juvenile Defender Center, National Juvenile Justice Network, Public Counsel, Teamchild, UC Berkeley School of Law Policy Advocacy Clinic, W. Haywood Burns Institute, Youth Advocate Programs, Inc., Youth Correctional Leaders for Justice.
- Todd Maybrown, Allen Hansen Maybrown & Offenbecher, PS, Seattle, WA, for Amici Curiae on behalf of Professor Alexes Phd Harris, Professor Mary Phd Pattillo.
- Carrie Suzanne Graf, Northwest Justice Project, Olympia, WA, Scott Crain, Northwest Justice Project, Seattle, WA, for Amicus Curiae on behalf of Northwest Justice Project.
- Amanda Nicole Martin, Northwest Consumer Law Center, Seattle, WA, for Amicus Curiae on behalf of Northwest Consumer Law Center.
- Daniel G Lloyd, Vancouver City Attorney’s Office, Vancouver, WA, Duncan McGehee Greene, Van Ness Feldman LLP, Seattle, WA, for Amicus Curiae on behalf of Washington State Association of Municipal Attorneys.
- Prachi Vipinchandra Dave, Public Defender Association, Rebecca Charney Fish, Catherine A Bentley, Attorneys at Law, Seattle, WA, for Amicus Curiae on behalf of Public Defender Association.
- Toby James Marshall, Terrell Marshall Law Group PLLC, Seattle, WA, Leslie A. Bailey, Brian Hardingham, John He, Public Justice, PC, Oakland, CA, for Amicus Curiae on behalf of Public Justice.
- Mary B. McCord, Seth Wayne, Institute for Constitutional Advocacy, Washington, DC, for Amicus Curiae on behalf of Institute for Constitutional Advocacy and Protection.
- Claudia Wilner, Linda Morris, Nat. Center for Law & Eco Justice, New York, NY, for Amicus Curiae on behalf of National Center for Law and Econimic Justice.
- John W. Whitehead, Douglas R. McKusick, Rutherford Institute, Charlottesville, VA, for Amicus Curiae on behalf of Rutherford Institute.

** Opinion

MADSEN, J.

<<**99>> *142 ¶1 Steven Gregory Long parked his truck on property owned by the city of Seattle for more than 72 hours, violating Seattle Municipal Code (SMC) 11.72.440(B). For this civil infraction, a city-contracted towing company impounded Long’s truck. Long contested the infraction and eventually agreed to a payment plan to reimburse the city for the costs of the impoundment. He now argues, among other things, that the impoundment violated Washington’s homestead act, ch. 6.13 RCW, and the federal excessive fines clause. For the reasons discussed below, we affirm in part and reverse in part.

*** BACKGROUND

¶2 In 2016, Long was living in his truck. Long, then a 56-year-old member of the Confederated Salish and Kootenai <<*143>> Tribes of the Flathead Nation, worked as a general tradesman and stored work tools as well as personal items in his vehicle. One day, Long was driving to an appointment when the truck began making “grinding” noises. On July 5, 2016, Long parked in a gravel lot owned by the city of Seattle. Long stayed on the property for the next three months.

¶3 On October 5, 2016, police alerted Long that he was violating the SMC by parking in one location for more than 72 hours. SMC 11.72.440(B). Long claims he told the officers that he lived in the truck. Later that day, a parking enforcement officer posted a 72-hour notice on the truck, noting it would be impounded if not moved at least one city block. SMC 11.30.060. Long did not move the truck. While Long was at work on October 12, 2016, a city-contracted company towed his truck. Without it, Long slept outside on the ground before seeking shelter nearby to escape the rain and wind.

¶4 Long requested a hearing to contest the parking infraction. SMC 11.30.120 (vehicle owner may request a hearing in municipal court to contest an impoundment). At the November 2, 2016 impoundment hearing, Long reiterated that he lived in his truck and kept all of his work tools in it. The magistrate found that Long had parked illegally, but the magistrate waived the $44.00 ticket, reduced the impoundment charges from $946.61 to $547.12, and added a $10.00 administrative fee. SMC 11.31.121 (violating the 72-hour rule is a “parking infraction” subject to $44.00 fine).1 The magistrate drafted a payment plan requiring Long to pay $50.00 per month.2 Long felt “forced” to agree or risk losing his truck at a public auction. Clerk’s Papers (CP) at 109.

1

The parties do not dispute that the impound charges for Long’s truck totaled $946.61. In municipal court, however, the fee was stated as $917.57. Regardless of this total, Long was ordered to pay $547.12, which he argues is unconstitutionally excessive.

2

Default under the payment plan would not have subjected the vehicle to forfeiture but could result in late charges and collection efforts.

<<*144>> ¶5 Long appealed the magistrate’s findings. Though he did not contest that the truck was parked illegally, Long argued that the impoundment violated the state and federal excessive fines clauses, substantive due process, and the homestead act. Long moved for summary judgment, which the municipal court denied.

¶6 On a RALJ appeal, the superior court affirmed and reversed in part: it rejected the substantive due process claim, and it held that the impoundment costs were unconstitutionally excessive under the federal constitution and that the payment plan violated the homestead act. The court concluded that the impoundment itself did not violate the Eighth Amendment to the United States Constitution.

¶7 The parties then sought review at the Court of Appeals. In a published decision, the court concluded that the payment plan was invalid under the homestead act and rejected the constitutional argument that the impoundment and associated costs were excessive. City of Seattle v. Long, 13 Wash. App. 2d 709, 467 P.3d 979 (2020). The court also held that Long failed to show the impoundment was unlawful pursuant to article I, section 7 of the Washington State Constitution, <<**100>> declining to review it for the first time on appeal. Id. at 733-35, 467 P.3d 979.

¶8 Long sought review here of the excessive fines and the article I, section 7 issues. Pet. for Review at 4-5, 8-18. Seattle cross petitioned, raising the homestead act as a contingent issue. Answer to Pet. for Review at 16-20. We granted review of all three.3 Order, <<*145>> No. 98824-2 (Wash. Dec. 2, 2020). Numerous amici curiae have filed briefs in support of Long, including the Institute for Justice, Public Justice, the American Civil Liberties Union (ACLU) of Washington, Northwest Justice Project, Juvenile Law Center, and Professors Alexes Harris and Mary Pattillo. Two amici contributed briefs in support of Seattle: the International Municipal Lawyers Association and the Washington Association of Municipal Attorneys.4

3

Seattle argues that Long is not an aggrieved party and that the case is moot because he retrieved his truck and the Court of Appeals affirmed the voided payment plan. Answer to Pet. for Review at 5; RAP 3.1. Long counters that Seattle can still impose towing costs because the Court of Appeals eliminated only the storage costs; it did not preclude the city from “charging a vehicle owner for costs associated with the towing and impounding of a vehicle.” Long, 13 Wash. App. 2d at 715, 467 P.3d 979; Pet’r’s Reply Br. at 8. Further, Long contends the case meets the exception to mootness due to the public nature of the issue, the need to provide future guidance, and the likelihood that the issue will reoccur. Pet’r’s Reply Br. at 8-9 (citing In re Eaton, 110 Wash.2d 892, 895, 757 P.2d 961 (1988)). Long is correct that the excessive fines clause issue is public, arising in other jurisdictions, e.g., Pimentel v. City of Los Angeles, 966 F.3d 934 (9th Cir. 2020) (remanding case to determine whether parking fines were constitutionally excessive), and likely to reoccur considering the large population of persons living in vehicles. See Mem. of Amici Curiae in Supp. of Review at 3 (close to 12,000 people are homeless in Seattle/King County with more than 2,700 living in their vehicles). As a technical matter, we did not grant review of the standing issue. Our order grants Long’s petition and the “issue contingently raised in the answer,” that is, the homestead act. See Order, No. 98824-2 (Wash. Dec. 2, 2020) (emphasis added); Answer to Pet. for Review at 16-20. Even assuming the case is moot, Long persuasively shows the issues should be considered.

4

This list does not include all amici curiae that have submitted briefing in this court. We refer only to first amici author listed on the briefing.

*** ANALYSIS

[1] <<1: 30-k-3555>>¶9 We review a summary judgment order de novo, engaging in the same inquiry as the trial court. Highline Sch. Dist. No. 401 v. Port of Seattle, 87 Wash.2d 6, 15, 548 P.2d 1085 (1976). Summary judgment is proper if the record shows “no genuine issue as to any material fact” and the “moving party is entitled to a judgment as a matter of law.” CR 56(c). The parties do not appear to contest the facts in this case.

**** I. The Homestead Act

¶10 A “uniquely American contribution” to real property law, homestead exemptions are based on the notion that citizens should have a home where family is sheltered and living beyond the reach of financial misfortune and the demands of certain classes of creditors. George L. Haskins, Homestead Exemptions, 63 HARV. L. REV. 1289, 1289 (1950); Charless & Blow v. Lamberson, 1 Iowa 435, 439 (1855); see  <<*146>> also Paul Goodman, The Emergence of Homestead Exemption in the United States: Accommodation and Resistance to the Market Revolution, 1840-1880, 80 J. AM. HIST. 470, 470 (1993). States began enacting homestead laws in the 19th century in order to provide security in an increasingly volatile American economy. Goodman, supra, at 470. Prior to these laws, the United States experienced financial panics that caused unemployment, bankruptcy, and loss of the family home. Id. at 471.

¶11 Texas enacted the first homestead exemption in 1839. MacKenzie Breitenstein, Note, The Ideal Homestead Exemption: Avoiding Asset Conversion & Fraud but Still Protecting Dependents, 58 DRAKE L. REV. 1121, 1123 (2010). Today, 48 states have homestead exemption laws. Id. at 1126. All such laws require the claimed “homestead” to be the primary residence of the debtor or his or her dependents, and only one homestead may be claimed. Id. at 1127. Relevant here, the homestead exemption does not protect the full value of a homestead but protects up to “the sum of fifteen thousand dollars in the case of other personal property <<**101>> described in RCW 6.13.010.” Former RCW 6.13.030(2) (2007).

[2] <<2: 202-k-1>> [3] <<3: 202-k-5>>¶12 Washington’s constitution provides,

The legislature shall protect by law from forced sale a certain portion of the homestead and other property of all heads of families.

WASH. CONST. art. XIX, § 1. The legislature fulfilled this mandate by passing the homestead act in 1895. LAWS OF 1895, ch. 64, § 1; Felton v. Citizens Fed. Sav. & Loan Ass’n of Seattle, 101 Wash.2d 416, 418, 679 P.2d 928 (1984). Like all homestead acts, Washington’s statute “ ‘implements the policy that each citizen have a home where [the] family may be sheltered and live beyond the reach of financial misfortune.’ ” In re Dependency of Schermer, 161 Wash.2d 927, 953, 169 P.3d 452 (2007) (alteration in original) (internal quotation marks omitted) (quoting Pinebrook Homeowners Ass’n v. Owen, 48 Wash. App. 424, 427, 739 P.2d 110 (1987)). The act <<*147>> is favored in law, and courts construe it liberally so it may achieve its purpose of protecting family homes. Id.

¶13 Under the homestead act some residences are automatically protected while others require an owner to file a declaration. RCW 6.13.040(1), (2); In re Tr.’s Sale of Real Property of Sweet, 88 Wash. App. 199, 201, 944 P.2d 414 (1997) (“Since 1981, homestead protection is ‘automatic.’ ”). Qualifying homes are protected from attachment and execution or forced sale for the debts of the owner up to the amount specified in the statute. Former RCW 6.13.070 (1987). The homestead exemption does not protect the full value of a homestead, but it protects up to “the sum of fifteen thousand dollars in the case of other personal property described in RCW 6.13.010.” Former RCW 6.13.030(2).

¶14 Here, we must determine whether the homestead act applies and whether any violation occurred. First, Seattle agrees that Long’s truck may qualify as a homestead but contends that additional procedural steps are necessary—namely, that RCW 6.13.040(1) requires Long to file a declaration, which he did not. Long responds that because he occupied the truck as his principal residence, it automatically qualifies. Second, Seattle argues that no attachment, execution, or forced sale occurred; Long disagrees.

¶15 For the following reasons, we agree with Long. RCW 6.13.040(1) automatically protects occupied personal property as a homestead, and no declaration is required. Long’s truck therefore constitutes a homestead. However, we agree with Seattle that no attachment, execution, or forced sale occurred. The homestead act protections were not triggered at this point in Long’s case because no party sought to collect on Long’s debt.

***** A. RCW 6.13.040(1) Automatically Protects Personal Property Occupied as a Principal Residence

[4] <<4: 30-k-3173>> [5] <<5: 361-k-1071>> [6] [7] <<7: 361-k-1082>>¶16 The meaning of a statute is a question of law we review de novo. <<*148>> State v. Mitchell, 169 Wash.2d 437, 442, 237 P.3d 282 (2010). “ ‘The court’s fundamental objective in construing a statute is to ascertain and carry out the legislature’s intent.’ ” Lake v. Woodcreek Homeowners Ass’n, 169 Wash.2d 516, 526, 243 P.3d 1283 (2010) (quoting Arborwood Idaho, LLC v. City of Kennewick, 151 Wash.2d 359, 367, 89 P.3d 217 (2004)). If a statute’s meaning is plain on its face, we must follow that plain meaning. Dep’t of Ecology v. Campbell & Gwinn, LLC, 146 Wash.2d 1, 9-10, 43 P.3d 4 (2002). A statute’s plain meaning is discerned from the ordinary meaning of the language, the context of the statute, related provisions, and the statutory scheme as a whole. Udall v. T.D. Escrow Servs., Inc., 159 Wash.2d 903, 909, 154 P.3d 882 (2007).

[8] <<8: 361-k-1156>> [9] <<9: 361-k-1105>>¶17 Whenever possible, statutes are to be construed so “ ‘no clause, sentence or word shall be superfluous, void, or insignificant.’ ” Kasper v. City of Edmonds, 69 Wash.2d 799, 804, 420 P.2d 346 (1966) (quoting Groves v. Meyers, 35 Wash.2d 403, 407, 213 P.2d 483 (1950)). “If a statute is ambiguous, we ‘may look to the legislative history of the statute and the circumstances surrounding its enactment to determine legislative intent.’ ” Five Corners Family Farmers v. State, 173 Wash.2d 296, 305-06, 268 P.3d 892 (2011) (quoting <<**102>> Rest. Dev., Inc. v. Cananwill, Inc., 150 Wash.2d 674, 682, 80 P.3d 598 (2003)).

¶18 RCW 6.13.040(1) provides,

Property described in RCW 6.13.010 constitutes a homestead and is automatically protected by the exemption described in RCW 6.13.070 from and after the time the real or personal property is occupied as a principal residence by the owner or, if the homestead is unimproved or improved land that is not yet occupied as a homestead, from and after the declaration or declarations required by the following subsections are filed for record or, if the homestead is a mobile home not yet occupied as a homestead and located on land not owned by the owner of the mobile home, from and after delivery of a declaration as prescribed in RCW 6.15.060(3)(c) or, if the homestead is any other personal property, from and after the delivery of a declaration as prescribed in RCW 6.15.060(3)(d).

<<*149>> (Emphasis added.) Much of the emphasized language above was added in a 1993 amendment. LAWS OF 1993, ch. 200, § 3. The amendment also included a section requiring a debtor claiming as a homestead “any other personal property” under RCW 6.13.040 to file a declaration stating they reside on the personal property. Id. § 5 (codified as RCW 6.15.060(3)(d)). Former RCW 6.13.010(1) (1999) defines a “homestead” as “real or personal property that the owner uses as a residence.”

[10] <<10: 202-k-42>>¶19 The parties essentially dispute whether the final clause of RCW 6.13.040(1) contemplates occupied or unoccupied personal property. Seattle argues that if occupied personal property is automatically exempt via the first clause of RCW 6.13.040(1), then “any other personal property” in the final clause must be unoccupied—yet lawmakers did not include that qualifier in the provision. City of Seattle’s Suppl. Br. (Seattle’s Suppl. Br.) at 3-4. Further, Seattle notes RCW 6.15.060(3)(d) requires a declaration for “any other personal property” to state that “ ‘the debtor resides thereon as a homestead.’ ” Id. at 2-3 (emphasis omitted) (quoting RCW 6.15.060(3)(d)). This requirement would be unnecessary if RCW 6.13.040(1) meant all personal property was occupied personal property. Id. at 2-3 (quoting RCW 6.15.060(3)(d)).

[11] <<11: 361-k-1366>>¶20 We conclude that RCW 6.13.040(1)’s final clause refers to unoccupied property. RCW 6.13.040(1) states explicitly that automatic protections occur when “real or personal property is occupied as a principal residence.” (Emphasis added.) The first and final clauses of RCW 6.13.040 were added to the homestead act in a 1993 amendment. LAWS OF 1993, ch. 200, § 3. The decision to add both clauses to the act in the same amendment indicates that they apply to different situations. “[W]e presume the legislature says what it means and means what it says.” State v. Costich, 152 Wash.2d 463, 470, 98 P.3d 795 (2004).

[12] <<12: 361-k-1375>>¶21 If lawmakers intended for the final clause to refer to occupied property, they could have included the term as they did in the first clause; they did not. Indeed, the final <<*150>> clause uses different words from the first clause: “any other personal property.” RCW 6.13.040(1) (emphasis added). When the legislature uses two different terms in the same statute, we presume the legislature intends the terms to have different meanings. Densley v. Dep’t of Ret. Sys., 162 Wash.2d 210, 219, 173 P.3d 885 (2007). Thus, under the plain language of RCW 6.13.040(1), automatically protected real or personal property must be occupied while any other personal property does not.

¶22 The statutory history of RCW 6.13.040 supports this reading. In 1881, a homestead could be created by mere occupancy. Davies v. Metro. Life Ins. Co., 191 Wash. 459, 465, 71 P.2d 552 (1937). With the passage of the homestead act in 1895, a homestead could be created only by filing a declaration. Id. Homestead by declaration persisted until 1981, where the legislature changed course. It reintroduced automatic protection, which was ultimately codified in RCW 6.13.040. See LAWS OF 1981, ch. 329, § 9; see also In re Wenner, 61 B.R. 634, 635 (1985) (“The 1981 amendments [to the homestead act] provided that a homestead was automatically created in the debtor’s permanent residence beginning, ‘at the time the property is occupied as a permanent residence by the owner.’ ” (quoting RCW 6.12.080)). As a result, declarations have been used in instances where <<**103>> property was not yet occupied. The 1981 amendment added a section requiring a declaration for homesteads on unimproved land purchased with the intention of residing thereon. LAWS OF 1981, ch. 329, § 9. In 1987, the legislature added qualifying language to unimproved land and required a declaration for mobile homes: “if the homestead is unimproved or improved land that is not yet occupied as a homestead, from and after the declaration ... or, if the homestead is a mobile home not yet occupied as a homestead and located on land not owned by the owner of the mobile home, from and after delivery of a declaration.” LAWS OF 1987, ch. 442, § 204(1)-(2).

¶23 Lawmakers further evidenced their intent to automatically protect personal property, such as Long’s truck, in <<*151>> the 1993 amendment. “Because some Washington citizens reside on their boats or in their cars or vans, it has been recommended that the homestead exemption’s scope be expanded to include any personal or real property that the owner uses as a residence.” FINAL B. REP. ON SUBSTITUTE S.B. 5068, 53d Leg. Reg. Sess. (Wash. 1993) (emphasis added). Admittedly, expanding the definition of homestead does not directly answer the question of whether a declaration is required for a nontraditional residence. But, when combined with the plain language and statutory history of RCW 6.13.040, it is evident that the legislature intended occupied personal property to be automatically protected as homesteads and other, unoccupied personal property to qualify upon declaration.

¶24 In addition to the plain language and history of .040(1), we reject Seattle’s reading because it would render the first clause of .040(1) meaningless. See G-P Gypsum Corp. v. Dep’t of Revenue, 169 Wash.2d 304, 309, 237 P.3d 256 (2010) (“ ‘Statutes must be interpreted and construed so that all the language used is given effect, with no portion rendered meaningless or superfluous.’ ” (internal quotation marks omitted) (quoting State v. J.P., 149 Wash.2d 444, 450, 69 P.3d 318 (2003))). The first clause refers to occupied personal or real property; the last clause refers to “any other personal property,” that is, property other than that already mentioned.

[13] <<13: 202-k-42>>¶25 Long’s truck qualifies as a homestead because it was occupied personal property. RCW 6.13.040(1). The homestead act does not require him to file a declaration in addition to occupying the vehicle as his primary residence.

***** B. The Homestead Act Does Not Apply at This Point in Long’s Case

¶26 We next consider the homestead act’s protections against “attachment and ... execution or forced sale for the debts of the owner up to the amount specified in RCW 6.13.030.” Former RCW 6.13.070. Long argues his truck was <<*152>> under threat of a forced sale by public auction unless he agreed to the payment plan and was unlawfully attached under a possessory lien when the truck was towed. Suppl. Br. of Pet’r/Cross-Resp’t Long (Suppl. Br. of Long) at 20-25. Seattle contends that its conduct fell short of all three enumerated actions because Long indirectly consented to the sale when he parked illegally and that no lien attached to the truck because its $4,000 value fell below the homestead act’s $15,000 protection. See former RCW 6.13.030.

[14] <<14: 202-k-197>>¶27 Seattle is partially correct. No attachment and execution or forced sale occurred here, but not for the reasons the city offers. Rather, the homestead act’s protections do not apply because Seattle has not sought to collect on Long’s debt. Thus, his homestead act claim is premature.

[15] [16] <<16: 108H-k-322>>¶28 Former RCW 6.13.070 protects debtors against specific creditor actions. An “attachment” is the physical “seizing of ... property to secure a judgment or to be sold in satisfaction of a judgment.” BLACK’S LAW DICTIONARY 157 (11th ed. 2019); see, e.g., Weber v. Laidler, 26 Wash. 144, 146, 66 P. 400 (1901) (noting that attachment involves seizure). An “execution” is a judicial “ ‘mode of obtaining the debt recovered by judgment’ ” such as a lien. Pinebrook Homeowners, 48 Wash. App. at 431, 739 P.2d 110 (quoting First Nat’l Bank v. Tiffany, 40 Wash.2d 193, 196, 242 P.2d 169 (1952)); BLACK’S, supra, at 714 (defining “execution” as <<**104>> a “[j]udicial enforcement of a money judgment, usu. by seizing and selling the judgment debtor’s property”). A “forced sale” is a nonconsensual sale to recover a debt. Felton, 101 Wash.2d at 422-23, 679 P.2d 928; BLACK’S, supra, at 1604 (defining “forced sale” as “[a] hurried sale by a debtor because of financial hardship or a creditor’s action. Cf. voluntary sale” (emphasis omitted)).

[17] <<17: 202-k-5>>¶29 As these definitions illustrate, former RCW 6.13.070 protects against actions taken to secure a debtor’s judgment. The homestead act does not specify a procedure for asserting and determining the validity of a homestead, leaving courts to formulate the remedy. Traverso v. Cerini, 146 Wash. 273, 277, 263 P. 184 (1928). The Court of Appeals has held that the <<*153>> validity of a homestead claim should be determined whenever it is asserted as a defense to execution of judgment against property. Enyart v. Humble, 17 Wash. App. 181, 184, 562 P.2d 648 (1977); see also City of Algona v. Sharp, 30 Wash. App. 837, 638 P.2d 627 (1982) (homeowner moved to quash an order and notice of foreclosure for failure to pay an assessment for sewer installation). Where property claimed as a homestead was sold under execution, owners properly brought a quiet title action against a purchase for the purpose of asserting the homestead exemption. Domke v. Beck, 18 Wash.2d 568, 573, 139 P.2d 1017 (1943). The homestead act operates as a shield to protect against creditors’ actions; it is not a sword to prevent such actions in the first instance. Christensen v. Christgard, Inc., 35 Wash. App. 626, 631, 668 P.2d 1301 (1983) (citing Webster v. Rodrick, 64 Wash.2d 814, 816, 394 P.2d 689 (1964)).

[18] <<18: 202-k-61>>¶30 As a legal matter, a debt is determined at adjudication. See Shaffer v. Heitner, 433 U.S. 186, 210 n.36, 97 S. Ct. 2569, 53 L. Ed. 2d 683 (1977). Similarly, former RCW 6.13.070(2) leaves it to courts to determine whether an exemption from the consequences of a debt applies. See Enyart, 17 Wash. App. at 184, 562 P.2d 648 (“The legislature has provided that homesteads should be identified and protected by the courts.”).

¶31 Further, the homestead act’s monetary exemption is not a complete one. A homestead is protected for debts “up to the amount specified in RCW 6.13.030.” Former RCW 6.13.070. This limited exemption cannot exceed the lesser of, among other things, the total net value of homestead lands, manufactured homes, and a mobile home as described in former RCW 6.13.010; or the sum of $125,000 in the case of lands, manufactured homes, and a mobile home or the sum of $15,000 in the case of other personal property described in former RCW 6.13.010. Former RCW 6.13.030. When an owner’s equity in property exceeds these exemption amounts, creditors seeking the excess value of the homestead must record a judgment pursuant to RCW 6.13.090 to obtain <<*154>> a lien.5 For a homestead vehicle exceeding the $15,000 exemption, creditors would follow the same statutory procedure. Former RCW 6.13.030; RCW 6.13.090. If the homestead exemption applies as the concurrence contends to prevent attachment by means of towing, the process of determining a vehicle’s value would occur on the streets —bypassing adjudication and falling to parking enforcement officers. See concurrence at 177-78. In sum, the homestead act protects only up to a certain amount and at least some portion of the value of the homestead will likely be available to pay the debt. Accordingly, the act operates a shield to preclude debtors from initially incurring a debt.6

5

RCW 6.13.100 allows a creditor to apply for the appointment of an appraiser when a judgment is executed on property. Once appointed, the appraiser submits a report on the value of the homestead, and the superior court will order either (1) a division of the property allowing the owner to retain a homestead and the creditor to seek enforcement of the execution on the remainder of the land or (2) sale of the property under the execution with no bid to be received unless it exceeds the amount of the homestead exemption. RCW 6.13.150, .160.

6

We understand the concurrence’s interest in protecting individuals who find themselves living in their vehicles, facing the towing and impoundment of their homes. See concurrence at 177-78. Nevertheless, towing a vehicle is not a debt protected under the homestead act until that debt is adjudicated. The practical consequences of the concurrence’s interpretation would also improperly shift the burden of determining the value of a homestead away from a court and onto parking enforcement officers. Such an interpretation transforms the act from a shield into a sword and would, at the very least, frustrate the statutory procedure for creditors pursuing the value of property exceeding the exemptions under former RCW 6.13.030. See RCW 6.13.090.

<<**105>> ¶32 The Washington State Association of Municipal Attorneys (WSAMA) urges us to conclude, as a threshold matter, that the impoundment and payment plan are not “debts” contemplated by former RCW 6.13.070. Br. of Amicus Curiae WSAMA at 12. For support, WSAMA points to Tellevik v. 6717 100th Street S.W., 83 Wash. App. 366, 376-77, 921 P.2d 1088 (1996). In that case, the Court of Appeals held that civil asset forfeiture is not subject to homestead protection because it is not based on such debts. Id. WSAMA argues that as in Tellevik, Long’s impoundment and assessed costs arose from an offense rather than a debt. See Br. of Amicus Curiae WSAMA at 12, 14-16. WSAMA is incorrect. *155 The impoundment and associated costs are not analogous to civil forfeiture. Long did not commit a criminal offense and his property was not seized pursuant to a forfeiture statute unlike Tellevik, 83 Wash. App. at 375, 921 P.2d 1088 (citing RCW 69.50.505).

¶33 Here, Long’s parking infraction gave rise to his debt. After contesting the infraction in municipal court, the magistrate imposed, and Long agreed to, a payment plan to reimburse the city for the impoundment costs. SMC 11.30.160(B) (upon imposition of a payment plan, “the City shall be responsible for paying the costs of impoundment to the towing company”). Seattle is Long’s creditor to whom he owes a $547.12 debt. See BLACK’S, supra, at 506 (defining “debt” as “[l]iability on a claim; a specific sum of money due by agreement or otherwise”). At this point, however, there is no evidence that the city has attempted to collect on Long’s debt. Therefore, the homestead act’s shield against attachment, execution, or forced sale is unnecessary because none of these actions has occurred.

**** II. Article I, Section 7

[19] <<19: 30-k-169>>¶34 Long also contends the impoundment of his truck violated article I, section 7. He first raised this issue in a reply brief at the Court of Appeals. See Resp’t Long’s Reply Br. (No. 78230-4-I May 13, 2019) at 23-24; see also Suppl. Br. of Resp’t/Cross-Pet’r (No. 78230-4-I Oct. 21, 2019) at 1-2, 5. Generally a party waives the right to raise an issue on appeal that was not raised before the trial court. See Seattle’s Suppl. Br. at 19 (citing Brundridge v. Fluor Fed. Servs., Inc., 164 Wash.2d 432, 441, 191 P.3d 879 (2008)). RAP 2.5(a)(3) permits a party to raise a manifest error affecting a constitutional right for the first time on appeal. The Court of Appeals declined to address the issue pursuant to RAP 2.5(a) because Long did not make this showing. RAP 2.5(a)(3); Long, 13 Wash. App. 2d at 733-34, 467 P.3d 979 (citing State v. A.M., 194 Wash.2d 33, 38, 448 P.3d 35 (2019)).

[20] <<20: 30-k-170(2)>> [21] <<21: 30-k-170(2)>> [22] <<22: 30-k-170(2)>>¶35 To meet RAP 2.5(a) and raise an error for the first time on appeal, an appellant must show (1) the error is manifest <<*156>> and (2) the error is truly of constitutional dimension. State v. O’Hara, 167 Wash.2d 91, 98, 217 P.3d 756 (2009) (citing State v. Kirkman, 159 Wash.2d 918, 926, 155 P.3d 125 (2007)). Reviewing courts look to the asserted claim and assess whether, if correct, it implicates a constitutional interest. Id. (citing State v. Scott, 110 Wash.2d 682, 687, 757 P.2d 492 (1988)). Whether an error is manifest requires a showing of actual prejudice. Id. at 99, 217 P.3d 756 (citing Kirkman, 159 Wash.2d at 935, 155 P.3d 125).

¶36 Here, Long relies on State v. Villela, 194 Wash.2d 451, 460, 450 P.3d 170 (2019), to argue that the city’s failure to consider alternatives to impoundment was unreasonable under article I, section 7. Long’s claim implicates a constitutional privacy interest, but he does not show prejudice.

[23] <<23: 349-k-488>> [24] <<24: 349-k-1767>> [25] <<25: 349-k-1767>> [26] <<26: 349-k-445>>¶37 Article I, section 7 provides, “No person shall be disturbed in his private affairs, or his home invaded, without authority of law.” Courts use a two-step analysis to determine whether this provision has been violated. State v. Puapuaga, 164 Wash.2d 515, 521-22, 192 P.3d 360 (2008) (citing State v. Surge, 160 Wash.2d 65, 71, 156 P.3d 208 (2007) (plurality opinion)). First, we determine whether the action complained of disturbs one’s private affairs. Id. at 522, 192 P.3d 360. If so, we look to the second inquiry: <<**106>> whether authority of law justifies the intrusion. Id. “[W]arrantless seizures are per se unreasonable, and the State bears the burden of demonstrating that a warrantless seizure falls into a narrow exception to the rule.” State v. Doughty, 170 Wash.2d 57, 61, 239 P.3d 573 (2010) (citing State v. Williams, 102 Wash.2d 733, 736, 689 P.2d 1065 (1984)). Impounding a car is a seizure under our state constitution. State v. Reynoso, 41 Wash. App. 113, 116, 702 P.2d 1222 (1985) (citing State v. Davis, 29 Wash. App. 691, 697, 630 P.2d 938 (1981)).

[27] <<27: 349-k-661>> [28] <<28: 349-k-661>> [29] <<29: 349-k-555>> [30] <<30: 349-k-661>>¶38 Most relevant to this case, a vehicle may be lawfully impounded in the course of enforcing traffic regulations if the driver committed a traffic offense for which the legislature has expressly authorized impoundment. Villela, 194 Wash.2d at 459, 450 P.3d 170 (quoting  <<*157>> State v. Tyler, 177 Wash.2d 690, 699, 302 P.3d 165 (2013)). If no probable cause exists to seize the vehicle and a reasonable alternative to impoundment exists, it is unreasonable to impound the vehicle. Id. Reasonableness of a search or seizure is decided in light of the facts of the case, and a police officer must consider reasonable alternatives. State v. Houser, 95 Wash.2d 143, 148, 622 P.2d 1218 (1980); Tyler, 177 Wash.2d at 699, 302 P.3d 165. Pursuant to Villela, an impoundment is lawful under article I, section 7 only if, in the judgment of the impounding officer, it is reasonable under the circumstances and there are no reasonable alternatives. 194 Wash.2d at 460, 450 P.3d 170.

[31] <<31: 48A-k-12>>¶39 The impoundment was reasonable under the circumstances, and no alternatives existed in this case. The Court of Appeals correctly noted that Long told the officers his truck was in need of repairs and could not be driven. Long, 13 Wash. App. 2d at 735, 467 P.3d 979; see also CP at 301-02 (“OFFICER 1: So I’m assuming this [the truck] runs? ... MR. LONG: No, it doesn’t. It’s got a broken (inaudible).... OFFICER 1: You need to get that thing fixed as soon as possible ... and get it moving because somebody’s going to come through here, probably a parking enforcement officer.”). The parking enforcement officer knew of this. CP at 306 (parking enforcement officer arrived at the location where Long’s truck is parked and was told Long “can’t move it”). When Long’s truck was towed, there appeared to be no other alternative to move it.

¶40 Furthermore, the officers had authority of law to seize Long’s truck. Long violated the city’s 72-hour parking ordinance. SMC 11.72.440. He had no right to park on a public right of way. See Galvis v. Dep’t of Transp., 140 Wash. App. 693, 706, 167 P.3d 584 (2007) (parking on a public right of way is a privilege); SMC 11.30.060 (a “vehicle ... may be impounded after notice of such proposed impoundment has been securely attached”).

¶41 Finally, Long contends that even if the initial impoundment was reasonable, holding his truck for an additional 21 days was unreasonable because the impoundment <<*158>> violated the homestead act. Suppl. Br. of Long at 19-21. We reject this argument. While it is far from acceptable that Long was deprived of his home for three weeks, Long does not argue that it violated due process. At the Court of Appeals, Long claimed the city violated his substantive due process rights with deliberate indifference by depriving him of shelter and exposing him to inclement weather. Long, 13 Wash. App. 2d at 731-33, 467 P.3d 979. The court rejected this argument in part because Long offered no case considering the doctrine outside the context of a 42 U.S.C. § 1983 claim. Id. at 732-33, 467 P.3d 979. Long did not seek review of the issue here.

[32] <<32: 202-k-5>> [33] <<33: 202-k-197>>¶42 We note that our decision on the homestead act does not call into question the city’s independent authority to impound a vehicle. The Seattle Municipal Code provides this mechanism to enforce parking infractions. SMC 11.72.440. A vehicle owner can object to the impoundment and payment of fees, but the homestead act is not a sword to prevent impoundment. Christensen, 35 Wash. App. at 631, 668 P.2d 1301. Homestead protections are resolved upon enforcement, not issuance, of a parking ticket or impoundment of a vehicle. See Enyart, 17 Wash. App. at 184, 562 P.2d 648; Domke, 18 Wash.2d at 573, 139 P.2d 1017; Sharp, 30 Wash. App. at 839, 638 P.2d 627.

**** <<**107>> III. Excessive Fines

¶43 Long also seeks relief under the state and federal excessive fines clauses. Pet. for Review at 17; WASH. CONST. art. I, § 14; U.S. CONST. amend. VIII. Washington’s constitution states, “Excessive bail shall not be required, excessive fines imposed, nor cruel punishment inflicted.” WASH. CONST. art. I, § 14. The federal constitution provides, “Excessive bail shall not be required, nor excessive fines imposed, nor cruel and unusual punishments inflicted.” U.S. CONST. amend. VIII.

[34] <<34: 30-k-755>>¶44 This court has stated that article I, section 14 provides greater protection than the Eighth Amendment for the purposes of cruel punishment. E.g., State v. Roberts, 142 Wash.2d 471, 506, 14 P.3d 713 (2000) (recognizing that the <<*159>> “Washington State Constitution’s cruel punishment clause often provides greater protection than the Eighth Amendment”); accord State v. Manussier, 129 Wash.2d 652, 674, 921 P.2d 473 (1996) (citing State v. Fain, 94 Wash.2d 387, 392-93, 617 P.2d 720 (1980)). Long has failed to provide an analysis under State v. Gunwall, 106 Wash.2d 54, 720 P.2d 808 (1986), in support of his argument that the excessive fines prohibition under our state constitution should be evaluated differently from the parallel provision in the United States Constitution. A Gunwall analysis is not a talisman but an interpretive tool. When a party urges a different or more protective interpretation under our state constitution for the first time, we expect supportive briefing, particularly when the language of that provision is identical to the United States constitutional provision. Absent support for an independent analysis, we view article I, section 14 and the Eighth Amendment as coextensive for the purposes of excessive fines.

[35] <<35: 174-k-1.3>> [36] <<36: 174-k-1.3>>¶45 The excessive fines clause “limits the government’s power to extract payments, whether in cash or in kind, ‘as punishment for some offense.’ ” Austin v. United States, 509 U.S. 602, 609-10, 113 S. Ct. 2801, 125 L. Ed. 2d 488 (1993) (emphasis omitted) (quoting Browning-Ferris Indus. of Vt., Inc. v. Kelco Disposal, Inc., 492 U.S. 257, 265, 109 S. Ct. 2909, 106 L. Ed. 2d 219 (1989)). Thus, a qualifying “fine” is a payment to a sovereign as punishment for some offense. United States v. Bajakajian, 524 U.S. 321, 327-28, 118 S. Ct. 2028, 141 L. Ed. 2d 314 (1998); Browning-Ferris, 492 U.S. at 265, 109 S.Ct. 2909. The Supreme Court recently concluded that the clause is applicable to the states. Timbs v. Indiana, ––– U.S. ––––, 139 S. Ct. 682, 687, 203 L. Ed. 2d 11 (2019).

***** A. Historical Considerations

¶46 The excessive fines clause was taken “verbatim” from the English Bill of Rights and the Magna Carta, which <<*160>> guaranteed that a “ ‘[f]ree-man shall not be amerced[7] for a small fault, but after the manner of the fault; and for a great fault after the greatness thereof, saving to him his contenement.’ ”8 Id. at 687-88 (quoting Magna Carta). The Magna Carta required monetary sanctions to be “ ‘proportioned to the wrong’ ” and “ ‘not be so large as to deprive [an offender] of his livelihood.’ ” Id. at 688 (alteration in original) (quoting Browning-Ferris, 492 U.S. at 271, 109 S.Ct. 2909).

7

Black’s defines “amerce” as “[t]o impose a fine or penalty that is not fixed but is left to the court’s discretion” or “[t]o fine or punish in any manner.” BLACK’S, supra, at 103; see also Timbs, 139 S. Ct. at 693 (Thomas, J., concurring in judgment) (noting that “amercements” are the medieval predecessors of fines).

8

“Contenement” is defined as “[f]reehold land held by a feudal tenant, [especially] land used to support the tenant. ●Magna Carta (1215) exempted this property from seizure.” BLACK’S, supra, at 398.

¶47 Despite these guaranties, Stuart kings continued to impose large fines on English subjects in order to raise revenue, harass political rivals, and detain those unable to pay. Id. at 688 (majority), 694 (Thomas, J., concurring in judgment) (reviewing the heavy fines imposed on the critics of the crown during the 17th century, such as a £100,000 levy against the sheriff of London for speaking against the Duke of York). After the last Stuart king was overthrown, the English Bill of Rights reaffirmed the Magna Carta’s excessive fines protection. Id. at 688. Virginia was the first to adopt the familiar <<**108>> language from the English Bill of Rights, and the Eighth Amendment was based directly on article I, section 9 of the Virginia Declaration of Rights of 1776. Id.; see also Browning-Ferris, 492 U.S. at 294, 109 S.Ct. 2909 (O’Connor, J., concurring in part and dissenting in part).9 All 50 states now include constitutional provisions against excessive fines. Timbs, 139 S. Ct. at 689.

9

Sadly, in spite of our vaunted independence, America followed our English forebears’ history of economic abuse. See Timbs, 139 S. Ct. at 688. After the Civil War, Southern states enacted “Black Codes,” imposing “draconian fines” for violations of vagrancy and recreating the system of involuntary servitude. Id. at 688-89.

***** <<*161>> B. The Excessive Fines Cases

¶48 The Supreme Court largely ignored the excessive fines clause for two centuries. Beth A. Colgan, Reviving the Excessive Fines Clause, 102 CAL. L. REV. 277, 297 (2014) (“Though the Excessive Fines Clause was ratified in 1791, nearly two centuries passed before the Supreme Court undertook its first meaningful foray into analyzing the Clause.”). 1993 marked the Court’s first substantial engagement with excessive fines in Austin. See Dep’t of Revenue v. Kurth Ranch, 511 U.S. 767, 803 n.2, 114 S. Ct. 1937, 128 L. Ed. 2d 767 (1994) (Scalia, J., dissenting) (stating that Austin “rescued” the excessive fines clause “from obscurity”). Austin held that civil and criminal forfeitures are subject to the excessive fines clause if they are at least partially punitive. 509 U.S. at 609-10, 113 S.Ct. 2801. In that case, a defendant pleaded guilty to a drug offense and forfeited his automobile body shop and mobile home. Id. at 604-05, 113 S. Ct. 2801. The government argued on appeal that civil forfeiture was not “punishment” and could not be excessive under the Eighth Amendment. Id. 607, 113 S. Ct. 2801. The Court disagreed, concluding that punishment “ ‘cuts across the division between the civil and criminal law.’ ” Id. at 610, 113 S. Ct. 2801 (quoting United States v. Halper, 490 U.S. 435, 447-48, 109 S. Ct. 1892, 104 L. Ed. 2d 487 (1989)). Civil proceedings “ ‘may advance punitive [and] remedial goals.’ ” Id. (quoting Halper, 490 U.S. at 447, 109 S.Ct. 1892). The relevant question, according to the Court, was whether a sanction is “simply” or “purely” remedial or whether it has any punitive characteristics, in which case it “must be considered a punishment for the purpose of the excessive fines clause.” State v. McClendon, 131 Wash.2d 853, 883, 935 P.2d 1334 (1997) (plurality opinion); see also Austin, 509 U.S. at 621, 113 S.Ct. 2801.

¶49 Five years later, the Court returned to excessive fines in Bajakajian, in which a defendant was arrested at an airport for failing to declare that he and his family were transporting over $350,000 in currency out of <<*162>> the country. 524 U.S. at 324, 118 S.Ct. 2028. Federal law required persons to forfeit to the government any property involved in such an offense. 18 U.S.C. § 982(a)(1) (2012). The Supreme Court explained that proportionality was the appropriate standard to assess excessive fines and, specifically, that a punitive fine violates the Eighth Amendment if it is “grossly disproportional to the gravity of the offense.” Bajakajian, 524 U.S. at 324, 118 S.Ct. 2028. The Court found the forfeiture of the entire sum was unconstitutionally excessive after considering that among other things, it was not an egregious infraction and the money was not connected to any illegal activities. Id. at 337-40, 344, 118 S. Ct. 2028. Both Austin and Bajakajian remain the seminal cases in the Court’s excessive fines jurisprudence.

¶50 In 2019, the Court once more examined the excessive fines clause in Timbs. There, a defendant pleaded guilty to dealing a controlled substance and conspiracy to commit theft. Timbs, 139 S. Ct. at 686. The police seized the defendant’s Land Rover SUV (sport utility vehicle) purchased for $42,000. Id. At the civil forfeiture hearing, the trial court found the vehicle had been used to facilitate a criminal offense but its value constituted four times the maximum monetary fine for the drug conviction ($10,000); thus, forfeiting the vehicle would be grossly disproportionate to the gravity of the offense. Id. The Indiana Supreme Court did not examine excessiveness and instead held the excessive fines clause did not apply to state action. The Supreme Court granted review to answer this narrow question and <<**109>> held that the clause is an incorporated protection applicable to the states under the Fourteenth Amendment. Id.

***** C. Legal Principles

[37] <<37: 174-k-1.3>> [38] <<38: 174-k-1.3>> [39] <<39: 174-k-1.3>> [40] <<40: 30-k-3722>>¶51 It is self-evident that to trigger the Eighth Amendment’s excessive fines clause, a sanction must be a “fine” and it must be “excessive.” Because the clause limits the government’s power to extract payments as “punishment <<*163>> for some offense,” Browning-Ferris, 492 U.S. at 265, 109 S.Ct. 2909, qualifying fines must be at least “partially punitive.” Timbs, 139 S. Ct. at 689. Therefore, the first step in an excessive fines inquiry is whether the state action is “punishment.” State v. Clark, 124 Wash.2d 90, 102, 875 P.2d 613 (1994), overruled in part on other grounds by State v. Catlett, 133 Wash.2d 355, 945 P.2d 700 (1997); Austin, 509 U.S. at 610, 113 S.Ct. 2801. The second inquiry is whether the fine is constitutionally excessive. Clark, 124 Wash.2d at 102-03, 875 P.2d 613; Bajakajian, 524 U.S. at 334, 118 S.Ct. 2028. Courts engage in this inquiry de novo. Bajakajian, 524 U.S. at 336-37, 118 S.Ct. 2028; State v. Chenoweth, 160 Wash.2d 454, 462, 158 P.3d 595 (2007) (interpreting the constitution is a question of law we review de novo).

****** i. “Punishment”

[41] <<41: 48A-k-12>>¶52 The Court of Appeals assumed without deciding that the impoundment of Long’s truck and the associated costs constitute a fine. Long, 13 Wash. App. 2d at 730, 467 P.3d 979. Here, the parties disagree that either is a punishment and consequently a fine. Long argues that SMC 11.72.440(E) characterizes the impoundment and payment plan as a “penalty” for violating the 72-hour law, making them partially punitive. Suppl. Br. of Long at 7; see also Consol. Br. of Resp’t/Cross-Pet’r Long (No. 78230-4-I Jan. 4, 2019) at 28-29. Seattle responds that the impoundment is not a fine because “ ‘deprivation by the government must be intended to be permanent.’ ” Seattle’s Suppl. Br. at 11 (quoting Coleman v. Watt, 40 F.3d 255, 263 (8th Cir. 1994)). Long retrieved his truck, thus the impoundment was not permanent. Id. Regarding the associated costs, Seattle contends the payment plan is remedial rather than punitive because it was meant to recoup the towing and storage fees that the city paid on Long’s behalf. We agree with Long that the impoundment and associated costs are partially punitive and constitute fines. Austin, 509 U.S. at 610, 113 S.Ct. 2801.

¶53 If a sanction is partially punitive, it falls within the excessive fines clause. Id.; see also  <<*164>> Tellevik, 83 Wash. App. at 372, 921 P.2d 1088 (“If the statutory provision has any purpose not solely remedial, the forfeiture is punishment within the meaning of the Eighth Amendment.”). SMC 11.72.440(E) states, “Vehicles in violation of this section are subject to impound as provided for in Chapter 11.30 SMC, in addition to any other penalty provided for by law.” (Emphasis added.) As the municipal and superior courts recognized, the plain language shows that one purpose of the ordinance is to penalize violators. See Hr’g (Mar. 2, 2018) at 50.

¶54 The associated costs were intended to reimburse the city for towing and storage fees, but they did not exist in isolation. The fees were imposed only as a result of the impoundment, which SMC 11.72.440(E) characterizes as a “penalty.” While the costs may be remedial, they are also punitive. See Bajakajian, 524 U.S. at 329, 118 S.Ct. 2028 (citing BLACK’S LAW DICTIONARY 1293 (6th ed. 1990) (“Remedial action” is one “brought to obtain compensation or indemnity.”); One Lot Emerald Cut Stones v. United States, 409 U.S. 232, 237, 93 S. Ct. 489, 34 L. Ed. 2d 438 (1972) (monetary penalty provides a “reasonable form of liquidated damages” and thus a “remedial” sanction for compensating the government for lost revenue)). We hold the impoundment and associated costs are both partially punitive.

¶55 Seattle does not meaningfully dispute the remedial versus punitive nature of the impoundment. Instead, the city argues that a fine must be a permanent loss as required by Coleman. Seattle’s Suppl. Br. at 11; Answer to Pet. for Review at 6-7. In that case, the Eighth Circuit Court of Appeals stated that a government deprivation “must be intended to be permanent to constitute a fine, as in the case of civil forfeitures.” Coleman, 40 F.3d at 263 (citing  <<**110>> Austin, 509 U.S. at 602, 113 S.Ct. 2801; Alexander v. United States, 509 U.S. 544, 113 S. Ct. 2766, 125 L. Ed. 2d 441 (1993)). While Austin and Alexander concerned the permanent loss of property via forfeiture, neither requires it. 509 U.S. at 604, 606-22, 113 S.Ct. 2801; 509 U.S. at 547-48, 558-60, 113 S.Ct. 2766.

¶56 Additionally, Coleman devoted “little discussion” to the argument that a temporary deprivation is an excessive <<*165>> fine. 40 F.3d at 263. Instead, the opinion focused on the subject of Austin and Alexander rather than their underlying reasoning. See id. The Austin Court explained that a forfeiture may serve a remedial purpose and still be subject to the excessive fines clause if it also serves “in part to punish.” 509 U.S. at 610, 113 S.Ct. 2801; see also Browning-Ferris, 492 U.S. at 265, 109 S.Ct. 2909. This inquiry looks to the function of a specific sanction, not its form or duration. See Benjamin Gillig, Note, Nexus Rethought: Toward a Rational Factual Standard for Federal Criminal Forfeitures, 102 IOWA L. REV. 289, 297 (2016) (Austin “emphasized the function that a forfeiture plays in a particular case”). It advances a categorical analysis rather than a bright line rule as suggested by Seattle’s interpretation. See Tellevik, 83 Wash. App. at 372, 921 P.2d 1088 (interpreting Supreme Court excessive fines precedent as applying a “categorical” approach that examines whether a forfeiture constitutes a punishment depending on the purposes of the provision).

¶57 Though Austin took no direct position on whether a temporary deprivation may still be partially punitive, its reasoning supports this conclusion. Outside the parking infraction context, temporary vehicle deprivation is punitive. For example, former RCW 46.55.350-.360 (2019), also known as “Hailey’s Law,” required officers to impound a vehicle when arresting drivers for DUIs (driving under the influence). LAWS OF 2011, ch. 167, § 3. The law also precluded drivers from redeeming their vehicles until 12 hours after it arrived at the tow truck operator’s storage facility. Id. Hailey’s Law was meant to “deter those arrested for driving or controlling a vehicle while under the influence of alcohol or drugs.” Id. § 2(1)(c) (emphasis added). Deterrence has traditionally been viewed as a goal of punishment. Bajakajian, 524 U.S. at 329, 118 S.Ct. 2028.

¶58 This court held that Hailey’s Law violated article I, section 7 and found the statute unconstitutional in Villela, 194 Wash.2d at 462, 450 P.3d 170. See also LAWS OF 2020, ch. 117, § 4 (repealing Hailey’s Law). While in effect, however, Hailey’s <<*166>> Law required temporary deprivation of a car for DUI arrest as a deterrent. This temporary deprivation was plainly a punishment. See Bajakajian, 524 U.S. at 329, 118 S.Ct. 2028; Tellevik, 83 Wash. App. at 372, 921 P.2d 1088. Under Austin, 509 U.S. at 610, 113 S.Ct. 2801, and Bajakajian, 524 U.S. at 329, 118 S.Ct. 2028, the law would qualify as partially punitive. Similarly, the temporary impoundment of Long’s is a penalty, and so, it is partially punitive. SMC 11.72.440(E); Austin, 509 U.S. at 610, 113 S.Ct. 2801; Bajakajian, 524 U.S. at 329, 118 S.Ct. 2028.

[42] <<42: 106-k-97>>¶59 Moreover, we are not bound by Coleman’s rather conclusory treatment of the Eighth Amendment. See 40 F.3d at 263 (devoting “little discussion” to the argument that a temporary deprivation is an excessive fine). On federal constitutional questions, we are bound only by decisions of the Supreme Court of the United States. State v. Vance, 168 Wash.2d 754, 762 n.7, 230 P.3d 1055 (2010) (citing State v. Radcliffe, 164 Wash.2d 900, 906, 194 P.3d 250 (2008); Tricon, Inc. v. King County, 60 Wash.2d 392, 394, 374 P.2d 174 (1962)). We therefore anchor our interpretation on the Supreme Court’s reasoning in Austin and Bajakajian rather than the Eighth Circuit’s interpretation of those cases. Under the Court’s precedent, the impoundment of Long’s truck was partially punitive and constitutes a fine.

****** ii. “Excessive”

[43] <<43: 174-k-1.3>> [44] <<44: 174-k-1.3>>¶60 Next, we consider whether the fines were excessive. Bajakajian, 524 U.S. at 333, 118 S.Ct. 2028; Tellevik, 83 Wash. App. at 372, 921 P.2d 1088. “The touchstone of the constitutional inquiry under the Excessive Fines Clause is the principle of proportionality: The amount of the forfeiture must bear some relationship to the gravity of the offense that it is designed to punish.” Bajakajian, 524 U.S. at 334, 118 S.Ct. 2028 <<**111>> (citing Austin, 509 U.S. at 622-23, 113 S.Ct. 2801; Alexander, 509 U.S. at 559, 113 S.Ct. 2766). A fine violates the excessive fines clause if it is grossly disproportional to the gravity of a defendant’s offense. Id. at 336, 118 S. Ct. 2028.

¶61 Despite mandating a proportionality inquiry, the Court has not yet articulated a test to carry it out. See  <<*167>> id. at 337-40, 118 S. Ct. 2028; David Pimentel, Forfeitures and the Eighth Amendment: A Practical Approach to the Excessive Fines Clause as a Check on Government Seizures, 11 HARV. L. & POL’Y REV. 541, 542 (2017) (“[T]he Supreme Court ... has not given clear or meaningful guidance for when a forfeiture should be deemed ‘excessive.’ ”). In lieu of such direction, lower courts have looked to Bajakajian for factors that the Court found persuasive.10 This has resulted in a “patchwork” of tests in the federal circuits. Pimentel, supra, at 543-44. For example, the Eleventh Circuit applies a three-factor test11 and the Tenth Circuit a nine-factor test.12 Id. at 544. Regardless of the factors, the various tests are consistent in their “general permissiveness.” Id.

10

Nicholas M. McLean, Livelihood, Ability to Pay, and the Original Meaning of the Excessive Fines Clause, 40 HASTINGS CONST. L.Q. 833, 845-46 (2013) (“[E]ach circuit has had to develop its own version of the Bajakajian[ ] multi-factor ‘gross disproportionalit’y test, with the ‘gross disproportionality’ determination often characterized as an inherently fact-intensive inquiry.”).

11

United States v. Browne, 505 F.3d 1229, 1281 (11th Cir. 2007).

12

United States v. Wagoner County Real Estate, 278 F.3d 1091, 1101 (10th Cir. 2002).

[45] <<45: 174-k-1.3>>¶62 This court adopted the Ninth Circuit’s test to determine whether a fine is grossly disproportional. The test includes but is not limited to “ ‘(1) the nature and extent of the crime, (2) whether the violation was related to other illegal activities, (3) the other penalties that may be imposed for the violation, and (4) the extent of the harm caused.’ ” State v. Grocery Mfrs. Ass’n, 195 Wash.2d 442, 476, 461 P.3d 334 (2020) (quoting United States v. $100,348.00 in U.S. Currency, 354 F.3d 1110, 1122 (9th Cir. 2004) (citing Bajakajian, 524 U.S. at 337-40, 118 S.Ct. 2028)); see also Tellevik, 83 Wash. App. at 374-75, 921 P.2d 1088 (listing similar factors). Bajakajian does not require the consideration of “any rigid set of factors in deciding whether a punitive fee is” proportional to the offense. United States v. Mackby, 339 F.3d 1013, 1016 (9th Cir. 2003).

<<*168>> ¶63 Critical to the present case is whether this proportionality inquiry can or should include consideration of a person’s ability to pay. Timbs notes that Bajakajian took “no position on ... whether a person’s income and wealth are relevant considerations in judging the excessiveness of a fine,” 139 S. Ct at 688, yet Bajakajian also observed that no argument was presented on the issue: “[r]espondent does not argue that his wealth or income are relevant to the proportionality determination or that full forfeiture would deprive him of his livelihood and the District Court made no factual findings in this respect.” 524 U.S. at 340 n.15, 118 S.Ct. 2028 (citation omitted). While the Court has not yet decided whether ability to pay is required, the history of the Eighth Amendment suggests it is.

¶64 The Magna Carta—from which the Eighth Amendment descended—limited the government’s power to impose punitive fines by, in part, forbidding penalties “so large as to deprive [a person] of his livelihood.” Browning-Ferris, 492 U.S. at 271, 109 S.Ct. 2909. English freemen could be amerced only in such a way as to save “ ‘to him his contenement,’ ” a merchant “his merchandise,’ ” and a serf his “wainage.”13 Bajakajian, 524 U.S. at 335-36, 118 S.Ct. 2028 (quoting Magna Carta); see also Timbs, 139 S. Ct. at 694 (Thomas, J., concurring in judgment) (quoting 2 HENRY HALLAM, THE CONSTITUTIONAL HISTORY OF ENGLAND: FROM THE ACCESSION OF HENRY VII TO THE DEATH OF GEORGE II 34 (8th ed. 1867) (noting the Magna Carta’s provision that no person be amerced to the <<**112>> “ ‘full extent of his means’ ”)). Blackstone’s Commentaries echo this notion: no one “shall have a larger amercement imposed ... than his circumstances or personal estate will bear.” 4 WILLIAM BLACKSTONE, COMMENTARIES ON THE LAWS OF ENGLAND *372 (1769).

13

For the definition of “contenement,” see supra note 8. Black’s defines “wainage” as “[t]he plow, team, and other implements used by a person ([especially] a villein) to cultivate the soil” or the “[c]ultivated land or the profits from it.” BLACK’S, supra, at 1894.

¶65 Across the pond, the Virginia Supreme Court of Appeals explained that its excessive fines clause reflected <<*169>> the traditional understanding that any “fine or amercement ought to be according to the degree of the fault and the estate of the defendant.” Jones v. Commonwealth, 5 Va. 555, 558 (1799) (emphasis added). Thomas Cooley’s esteemed constitutional treatise stated that the excessive fines provision requires a fine to “have some reference to the party’s ability to pay it.” THOMAS M. COOLEY, A TREATISE ON THE CONSTITUTIONAL LIMITATIONS WHICH REST UPON THE LEGISLATIVE POWER OF THE STATES OF THE AMERICAN UNION 328 (1868).

¶66 Nineteenth century lawmakers appear to have accepted this traditional understanding. See Nicholas M. McLean, Livelihood, Ability to Pay, and the Original Meaning of the Excessive Fines Clause, 40 HASTINGS CONST. L.Q. 833, 883-84 (2013). In an 1864 speech to the United States Senate, one Pennsylvania Republican noted that an excessive fine “ ‘is a technical term’ ” and must “ ‘be determined from the condition of the man how much he could pay without touching the sustenance of his wife and children.’ ” Id. at 884 (quoting CONG. GLOBE, 38th Cong., 1st Sess. 561 (1864) (statement of Sen. Edgar Cowan)). Though not uniformly accepted, many state courts applied this understanding of the excessive fines clause.14 For example, the <<*170>> Florida Supreme Court concluded that “[t]he duration and quantity of each [fine]” depends on the “aggravation, or otherwise, of the offense, [and] the quality and condition of the parties ... the quantum, in particular, of pecuniary fines neither can nor ought to be ascertained by an invariable.” Id. (second alteration in original) (citing Frese v. State, 23 Fla. 267, 270-71, 2 So. 1 (1887)).

14

See McLean, supra, at 885 & n.195 (citing State v. Staub, 182 La. 1040, 1044-45, 162 So. 766 (1935) (“What constitutes an excessive fine for the violation of a penal statute depends in part ... upon the ability of the defendant to pay. A fine which in one case would be only slight punishment, because easily paid, might in another case be excessive, because its payment would be ruinous to the convict.”); People v. Hershey Farms, Inc., 175 Misc. 641, 643, 24 N.Y.S.2d 163 (N.Y.Gen.Sess. 1941) (quoting 15 AM. JUR. Criminal Law § 551 (1938)) (“ ‘A fine is excessive if it seriously impairs his ability to gain a livelihood.’ ”) (quoting 15 AM. JUR. Criminal Law § 551 (1938))); Cohen v. State, 173 Md. 216, 232, 195 A. 532 (Ct. App. 1937) (“[W]hen a fine is imposed, it should be done with due regard to the ability of the defendant to pay.”); cf. State v. Ross, 55 Or. 450, 474, 104 P. 596, 106 P. 1022 (1909) (“[I]mprisonment ... for life, for the nonpayment of [a] fine, ... is a cruel and unusual punishment.”). Not all state courts, however, agreed on this point. See, e.g., Poindexter v. State, 137 Tenn. 386, 392, 193 S.W. 126 (1917) (“A fine is proportioned to the gravity of the offense punished, and the financial ability of a defendant to pay is not ordinarily considered.”); Conley v. State, 85 Ga. 348, 11 S.E. 659 (1890); State v. Little, 42 Iowa 51, 56 (1875) (“It seems to us that this is one of the cases which call for severe punishment. In view of the fact that the extent of the punishment in such cases is fixed by law at one thousand dollars, we think a fine of half that sum is far from being excessive in this case.”)).

¶67 A number of modern state and federal courts have joined the chorus of legal scholars to conclude that the history of the clause and the reasoning of the Supreme Court strongly suggest that considering ability to pay is constitutionally required. E.g., Oregon v. Goodenow, 251 Or. App. 139, 153, 282 P.3d 8 (2012) (“When assessing the severity of a defendant’s forfeiture, courts consider the amount of the forfeiture and the effect of the forfeiture on the defendant.” (citing United States v. Levesque, 546 F.3d 78 (1st Cir. 2008); Browning-Ferris, 492 U.S. at 266-67, 109 S.Ct. 2909)); Commonwealth v. 1997 Chevrolet, 106 A.3d 836, 871 (Pa. Cmwlth.2014) (“the excessive fines analysis ... requires ... a thorough examination of every property owner’s circumstances”); Rachel J. Weiss, The Forfeiture Forecast After Timbs: Cloudy with a Chance of Offender Ability to Pay, 61 B.C. L. REV. 3073, 3108 (2020); Suppl. Br. of Long at 9 n.19 (citing law review articles in support). Federal circuit courts are split on the issue. United States v. Lippert, 148 F.3d 974, 978 (8th Cir. 1998) (“[I]n the case of fines, as opposed to forfeitures, the defendant’s ability to pay is a factor under the Excessive Fines Clause.”). But see United States v. Smith, 656 F.3d 821, 828 (8th Cir. 2011) (deeming a “ ‘defendant’s <<**113>> inability to satisfy a forfeiture at the time of conviction’ ” is not relevant to constitutional analysis (quoting Levesque, 546 F.3d 78, 85 (1st. Cir. 2008))); accord United States v. Seher, 562 F.3d 1344, 1371 (11th Cir. 2009).

¶68 The Colorado Supreme Court recently observed that history and precedent constitute “persuasive evidence that a fine that is more than a person can pay may be ‘excessive’ within the meaning of the Eighth Amendment.”  <<*171>> Dep’t of Labor & Emp’t v. Dami Hosp., LLC, 2019 CO 47M, ¶ 30, 442 P.3d 94, 101. In addition to historical considerations, the Colorado court found that the “concept of ‘proportionality’ itself” supported considering ability to pay. Id. ¶ 31. A fine that would bankrupt one person would be a substantially more burdensome fine than one that did not. Id.

[46] <<46: 174-k-1.3>> [47] <<47: 174-k-1.3>>¶69 The weight of history and the reasoning of the Supreme Court demonstrate that excessiveness concerns more than just an offense itself; it also includes consideration of an offender’s circumstances. The central tenet of the excessive fines clause is to protect individuals against fines so oppressive as to deprive them of their livelihood. Timbs, 139 S. Ct. at 688. Inherent in this safeguard is the recognition that “ ‘what is ruin to one man’s fortune, may be a matter of indifference to another’s.’ ” Browning-Ferris, 492 U.S. at 300, 109 S.Ct. 2909 (O’Connor, J., concurring in part and dissenting in part) (quoting 4 BLACKSTONE, supra, at <<*371>>). As one Pennsylvania court astutely noted, “[T]he excessive fines analysis under the Eighth Amendment requires more than ‘lip service.’ ... This requires a thorough examination of every property owner’s circumstances.” 1997 Chevrolet, 106 A.3d at 871.

¶70 The homelessness crisis and widespread use of fines to fund the criminal justice system also fully support an ability to pay inquiry. Amici have demonstrated what any casual observer of the news already knows: America is facing a severe housing crisis. E.g., Br. of Amici Curiae ACLU of Wash. et al. at 1; Benjamin Schneider, CityLab University: Understanding Homelessness in America, BLOOMBERG CITYLAB (July 6, 2020), https://www.bloomberg.com/news/features/2020-07-06/why-is-homelessness-such-a-problem-in-u-s-cities (reviewing a brief history, geographic and demographic trends, and the effect of COVID-19 on homelessness in America). In King County, nearly 12,000 people are experiencing homelessness, and over 2,000 of those individuals live in their vehicles. Homelessness in King County 2019, ALL HOME, http://allhomekc.org/wp-content/uploads/2019/05/All-Homes-Infographic-V04.pdf <<*172>> [http://perma.cc/5LQX-ZCQE]; Amicus Br. of Nw. Justice Project et al. at 2-3.

¶71 Many factors have contributed to this emergency: volatile housing markets, uncertain social safety nets, colonialism, slavery, and discriminative housing practices—all exacerbated by the global COVID-19 pandemic. Br. of Amici Curiae ACLU of Wash. et al. at 1-7 (examining the effects of the seizure of Seattle and surrounding lands from indigenous peoples and racially restrictive covenants on communities of color); see also RICHARD ROTHSTEIN, THE COLOR OF LAW: A FORGOTTEN HISTORY OF HOW OUR GOVERNMENT SEGREGATED AMERICA 64, 97-99 (2017) (reviewing federal, state, and local housing policies that supported segregation such as redlining, that is, the refusal to insure mortgages in black neighborhoods). The excessive fines clause descended from English law that sought to protect individuals from fines that would deprive them of their ability to live. This concern is directly related to an offender’s circumstances—in this case, homelessness and the circumstances forcing individuals into it.

¶72 Further, this court has recognized that punitive fines should not be sought or imposed as “ ‘ “a source of revenue.” ’ ” Grocery Mfrs. Ass’n, 195 Wash.2d at 476, 461 P.3d 334 (quoting Timbs, 139 S. Ct. at 689 (quoting Harmelin v. Michigan, 501 U.S. 957, 979 n.9, 111 S. Ct. 2680, 115 L. Ed. 2d 836 (1991) (plurality opinion))). It has been said that “offender-funded justice” comprises much of the funding for criminal justice across the country, including traffic and parking violation fines. E.g., Bryan L. Adamson, <<**114>> Debt Bondage: How Private Collection Agencies Keep the Formerly Incarcerated Tethered to the Criminal Justice System, 15 NW. J.L. & SOC. POL’Y 305, 315 (2020); Suppl. Br. of Long at 13. Courts scrutinize “governmental action more closely when the State stands to benefit.” Harmelin, 501 U.S. at 979 n.9, 111 S.Ct. 2680 (lead opinion). Including an ability to pay inquiry for an excessive fines claim allows courts to do just that.

<<*173>> [48] <<48: 174-k-1.3>>¶73 We pay more than “lip service” to the excessive fines clause and instead hew to its history. We conclude, as did the Colorado Supreme Court, that courts considering whether a fine is constitutionally excessive should also consider a person’s ability to pay. See Dami Hosp., 2019 CO 47M, ¶ 31, 442 P.3d 94.

***** D. Application to Long

[49] <<49: 48A-k-12>>¶74 Our gross disproportionality test considers “ ‘(1) the nature and extent of the crime, (2) whether the violation was related to other illegal activities, (3) the other penalties that may be imposed for the violation, and (4) the extent of the harm caused,’ ” as well as a person’s ability to pay the fine. See Grocery Mfrs. Ass’n, 195 Wash.2d at 476, 461 P.3d 334; Dami Hosp., 442 P.3d at 101. In light of these factors, we conclude that the impoundment and $547.12 payment plan were unconstitutionally excessive.

¶75 First, the nature of the offense at issue is a civil parking infraction that carries a $44 fine. SMC 11.31.121 (“Monetary penalties—Parking infractions”). The city certainly has an interest in keeping its streets clear and free of traffic, but the offense of overstaying one’s welcome in a specific location is not particularly egregious. See Seattle’s Suppl. Br. at 13. Moreover, the city has suspended enforcement of the 72-hour parking violation during COVID-19, signaling that the city views it as a relatively minor offense. See Amici Br. of Pub. Justice et al. at 8. Second, there is no evidence that the infraction was related to any other criminal activity. Third, the only penalty identified is the $44 ticket and towing/storage costs. In this case, the magistrate waived the ticket and reduced the associated costs from approximately $900 to $550. If Long fell behind on payments, he would be subject to additional penalties in the form of late charges and collection efforts. Fourth, the extent of the harm caused was minimal. As the superior court noted, Long was not parked in an area of “very hot <<*174>> demand for city vehicles or otherwise.” Hr’g at 54. He was not parked in a residential neighborhood, and as noted, he was not cited for blocking or obstructing a roadway.

¶76 On the other hand, the city was harmed when it paid the costs of towing and impoundment. See SMC 11.30.160(B) (allowing a payment plan requires that “the City shall be responsible for paying the costs of impoundment to the towing company”). Seattle leans heavily on the notion of reimbursement as evidence that the payment plan is not excessive because “[t]he government is entitled to rough remedial justice.” Clark, 124 Wash.2d at 103, 875 P.2d 613; Seattle’s Suppl. Br. at 15. Clark reasoned that the value of the forfeited property in that case was equivalent to the cost of prosecution, thus the government received rough remedial justice, and the court declined to consider the forfeiture as an excessive fine. 124 Wash.2d at 103-04, 875 P.2d 613. But Seattle overlooks a critical caveat: Clark also explicitly acknowledged that “rough equivalence of the value of the property forfeited and the amount spent on prosecution may not always insulate a forfeiture from a finding that the forfeiture is ‘excessive.’ ” Id. at 104, 875 P.2d 613 (emphasis added). Reimbursement is but one factor courts may consider in a proportionality inquiry.

¶77 Fifth, LONG’s circumstances were such that he had little ability to pay $547.12. When his vehicle was impounded, Long earned between $300.00 and $600.00 in addition to $100.00 in tribal fees per month. He told the magistrate at his impoundment hearing that he lived in his truck and had only $50.00 to his name. Long was attempting to move himself out of homelessness by saving for an apartment. During that time, LONG’s truck held his clothes, food, bedding, and various work tools essential to his job as a general tradesman. After the truck was towed, Long slept outside before seeking shelter from the cold weather, and he contracted influenza. These facts indicate Long could not afford to pay the $547.12 assessment. From October 13 until November 3, Long did not have his truck and could not <<*175>> access his tools; thus he **115 could not find skilled labor jobs. During that period, he was homeless and sick, likely making very little money. The impoundment severely compromised Long’s ability to work—in other words, his livelihood. See Bajakajian, 524 U.S. at 335, 118 S.Ct. 2028; Timbs, 139 S. Ct. at 688 (“ ‘[N]o man shall have a larger amercement imposed upon him, than his circumstances or personal estate will bear.’ ” (alteration in original) (quoting 4 BLACKSTONE, supra, at *372)).

¶78 Moreover, paying $50 per month when Long made at most $700, would leave him $650 with which to live. Cf. Hr’g at 57 (the superior court stated that LONG’s “income per month is something like $300 at best”); see also Amici Br. of Pub. Justice et al. at 18 & n.12 (the self-sufficiency standard or minimum amount of money to adequately meet one’s needs for a Seattle resident is $2,270 per month). It is difficult to conceive how Long would be able to save money for an apartment and lift himself out of homelessness while paying the fine and affording the expenses of daily life. See Amici Br. of Pub. Justice et al. at 17-19 (noting poor offenders facing large financial penalties routinely forgo basic needs, miss bills, and borrow at high interest rates); Professors Amicus Curiae Br. in Supp. of Resp’t at 9-16 (reviewing the “dramatically different type of justice” poor people face than “defendants with financial means,” including automatic license suspensions for failure to pay court fines, longer periods of homelessness, and persistent mental health concerns). Seattle asserts that treating the payment plan as excessive punishment is to “trivialize the Eighth Amendment.” Seattle’s Suppl. Br. at 14. Yet to do what the city asks is to ignore the Eighth Amendment entirely. This we cannot do.

¶79 Finally, though not referenced in our proportionality test, the Court of Appeals below considered the legislative approval of the fines. Long, 13 Wash. App. 2d at 731, 467 P.3d 979. Pursuant to Seher, 562 F.3d at 1371, if the value of the fine is within the range prescribed by a legislative body, a strong presumption exists that a forfeiture is constitutional. The Court of <<*176>> Appeals found that towing and requiring a vehicle owner to pay the associated costs are the “exact penalties” authorized by the city council for violating the 72-hour rule. Long, 13 Wash. App. 2d at 731, 467 P.3d 979. While the Seattle City Council likely contemplated impoundment when enacting the parking ordinance at hand, it did not approve the related costs. Long points out that the fees here were set by a contract negotiated with the towing company. Seattle responds that the towing company went through the city’s competitive bidding process, indicating legislative approval for towing and storage costs. See Seattle’s Suppl. Br. at 16. But the process of competitive bidding shows only that Lincoln Towing won the contract; it does not explain how the company determines towing and storage costs. See Hr’g at 20-21 (superior court oral ruling). Nor does the record contain this information. This is far from the congressionally approved maximum financial penalty set out in Bajakajian. As such, it does not indicate a strong presumption of constitutionality.

¶80 For these reasons, the impoundment and associated costs deprived Long of his means of living and violated the excessive fines clause.

¶81 This decision is not intended to suggest that Seattle can never impound vehicles or impose costs associated with towing. Nor does it require city parking enforcement officers to determine a vehicle owner’s ability to pay at the issuance of a parking infraction, contrary to amicus International Municipal Lawyers Association’s assertion. See Amicus Br. of Int’l Mun. Lawyers Ass’n at 13. The above analysis focuses only on enforcement. See State v. Catling, 193 Wash.2d 252, 264, 438 P.3d 1174 (2019) (noting that federal law does not preclude the imposition of a legal financial obligation but does restrict the use of Social Security for payment of the debt). The excessive fines clause prohibits the extraction of payment as a punishment for some offenses that would deprive a person of his or her livelihood. See Bajakajian, 524 U.S. at 335, 118 S.Ct. 2028; Timbs, 139 S. Ct. at 688. A <<*177>> natural venue for this inquiry is an impoundment hearing in municipal court. See SMC 11.30.120(D) (vehicle owner entitled to a hearing in municipal court to contest an impoundment).

*** CONCLUSION

¶82 We affirm the superior court’s conclusion that LONG’s truck automatically qualifies <<**116>> as a homestead and that no declaration is required. RCW 6.13.040(1). However, because Seattle has not yet attempted to collect on LONG’s debt, former RCW 6.13.070 does not apply, and LONG’s homestead act claim is premature. Thus, we reverse the superior court’s decision that Seattle violated the act.

¶83 As to LONG’s excessive fines claim, we hold that the impoundment and associated costs are fines and that an ability to pay inquiry is necessary. Long has shown that he lacks the ability to pay the imposed costs.

¶84 Finally, we conclude that the payment plan as imposed was excessive. However, a reasonable fine may still be constitutional and appropriate. Accordingly, we remand the case to the trial court for further proceedings consistent with this opinion.

Johnson, Owens, Stephens, Gordon McCloud, and Montoya-Lewis, JJ., concur.

** González, C.J. (concurring)

¶85 I largely concur with the well-reasoned majority. I particularly agree that Steven Long’s truck automatically qualified as his homestead because he obviously lived in it. In my view, though, the homestead act, ch. 6.13 RCW, also protected Long’s home both from being towed and from being subject to forced sale, regardless of whether the sale was ultimately avoided.

¶86 By operation of law, as soon as the truck was towed, a lien was placed on it. RCW 46.55.140(1). This lien effectively <<*178>> attached the home as security for the impound debts. This violates the homestead act and never should have happened.15 See former RCW 6.13.070 (1987). If a home is automatically protected as a principal residence under former RCW 6.13.010 (1999), it cannot be simply towed by an agent of the state and attached as security for the cost of that tow.16 Even if that were permissible, requiring Long to consent to a fine for the privilege of redeeming his home was not. Under threat of forced sale, Long was forced to accede to a payment plan even though the magistrate knew that the vehicle was Long’s primary residence. This, too, violates the clear protections of former RCW 6.13.070.

15

Homesteads are not protected against debts secured by “mechanic’s, laborer’s, construction, maritime, automobile repair, material supplier’s, or vendor’s liens arising out of and against the particular property claimed as a homestead.” Former RCW 6.13.080(1) (2019). These exceptions are strictly construed and do not include an operator’s lien that arises from the towing of a vehicle. See Pinebrook Homeowners Ass’n v. Owen, 48 Wash. App. 424, 428-29, 739 P.2d 110 (1987) (holding that an assessment lien does not qualify as one of the statutory homestead exceptions); see also City of Algona v. Sharp, 30 Wash. App. 837, 842-43, 638 P.2d 627 (1982) (stating that “[a]n inference must therefore be made that the legislature intended the omission” of lien types not listed in the statute).

16

Amici curiae Northwest Justice Project and Northwest Consumer Law Center note that impoundment and auction of a vehicle is an expedited process with minimal due process protections. Amicus Br. of Nw. Justice Project et al. at 15. In fact, “[t]here is a high likelihood that vehicle-sheltered individuals will not even receive the [towing] notice, since it is mailed to the registered owner’s physical address, at which the homeless individual likely does not reside.” Id. at 15-16 (citing RCW 46.55.110(a)). This provides additional support for an automatic homestead protection that prevents towing in the first instance, as it “may be the only meaningful protection” prior to impound and auction. Id. at 16.

¶87 The homestead act protects “ ‘a home where [the] family may be sheltered and live beyond the reach of financial misfortune,’ ” and the act is construed “liberally so it may achieve its purpose of protecting family homes.” In re Dependency of Schermer, 161 Wash.2d 927, 953, 169 P.3d 452 (2007) (alteration in original) (internal quotation marks omitted) (quoting Pinebrook Homeowners Ass’n v. Owen, 48 Wash. App. 424, 427, 739 P.2d 110 (1987)). These protections would be gutted if the homeowner had to wait until their home is seized and a forced sale scheduled before invoking the act’s protections. The impoundment hearing is the very <<*179>> latest time the homestead act’s protections could be meaningfully raised. See RCW 46.55.120(2)(b).

¶88 The city contends that the homestead act does not apply because a forced sale was <<**117>> merely contemplated and because Long impliedly consented to having his home impounded by failing to move it. See City of Seattle’s Suppl. Br. at 9-10. But Long could not move his truck because he could not afford a new part. That is not consent. Long did not violate the parking ordinance willingly; he simply had no other option. Nor did Long willingly enter into an arrangement that provided him a benefit with some possible risk. See Felton v. Citizens Fed. Sav. & Loan Ass’n of Seattle, 101 Wash.2d 416, 421, 679 P.2d 928 (1984).

¶89 Simply put, the homestead act was intended to provide shelter for families. Macumber v. Shafer, 96 Wash.2d 568, 570, 637 P.2d 645 (1981) (citing Clark v. Davis, 37 Wash.2d 850, 226 P.2d 904 (1951)). The act bars the city from towing a vehicle that is occupied as a primary residence and from forcing an individual to agree to a payment plan to prevent that vehicle from being sold at a public auction. With these observations, I respectfully concur.

** Yu and Whitener, JJ., concur with González, C.J.
