#+title:      How To Interpret Court Rules
#+date:       [2023-12-23 Sat 07:47]
#+filetags:   :construction:interpretation:rules:
#+identifier: 20231223T074757

As with all court rules, we interpret the arbitration rules “as though
they were drafted  by the Legislature.” Nevers v.  Fireside, Inc., 133
Wn.2d 804, 809, 947 P.2d 721 (1997) (citing State v. Wittenbarger, 124
Wn.2d 467, 484,  880 P.2d 517 (1994)). “Our review  of the application
of  a court  rule or  law to  the facts  is de  novo.” Malted  Mousse,
Inc. v. Steinmetz, 150 Wn.2d 518, 525, 79 P.3d 1154 (2003).  Issues of
statutory interpretation are  also reviewed de novo.  Dep’t of Ecology
v.  Campbell & Gwinn, LLC, 146 Wn.2d  1, 9, 43 P.3d 4 (2002). The goal
of statutory interpretation is to  carry out the legislature’s intent,
and we begin with the plain language of the statute. Id. at 9-10.

Supreme Court of the State of Washington
Opinion Information Sheet

Docket Number:	101,329-9
Title of Case:	Crossroads Mgmt., LLC v. Ridgway
File Date:	12/21/2023
Oral Argument Date:	05/09/2023

SOURCE OF APPEAL
----------------
Appeal from Pierce County Superior Court
Docket No:	18-2-10533-7
Judgment or order under review
Date filed:	03/26/2021
Judge signing:	Honorable Elizabeth P. Martin
