#+title:      Washington State Bar Family Law Website wafls
#+date:       [2023-12-19 Tue 13:28]
#+filetags:   :familylaw:section:wsba:
#+identifier: 20231219T132811

December 19, 2023



Launch of Washington State Bar Association’s Family Law Section Website!



Dear WSBA Family Law Section Members,



We are proud to announce the official launch of the new Washington State Bar Family Law Section website. It is designed to enhance communication and engagement within our family law community, and to serve as a valuable tool for staying informed.



We invite you to visit the website regularly at wafls.org and explore all that it has to offer.



Key Features:



1. Events Calendar: Stay informed about upcoming Family Law Section seminars, workshops, and networking events. Connect with fellow members and expand your professional network.

2. Around Washington: Navigate the complexities of family law proceedings through our dedicated Washington State Court Information Center. Access up-to-date court rules, procedural guidelines, and essential resources to bolster your practice.

3. Family Law Resources: Access legal resources and publications to stay informed and enhance your professional expertise.

4. Legislative Activity: Stay at the forefront of legislative activity and legal developments with our comprehensive page dedicated to current legislative activity. Watch for updates and links to family law bills of interest throughout the legislative session.

5. Family Law Section Committee: Stay informed about your Executive Committee’s activities and advocacy efforts on key family law policies affecting our community.

6. Podcasts: Insightful discussions with family law professionals, experts, and judicial officers on topics and issues relevant to your practice and your clients.



The new website is – and will be – a valuable resource for our section members.



Sincerely,



Tamara Garrison Chairperson

WSBA Family Law Executive Committee (FLEC)
