#+title:      The Tort of Intentionally Inflicting Emotional Distress by Outrageous Conduct
#+date:       [2023-12-18 Mon 08:03]
#+filetags:   :iied:tort:
#+identifier: 20231218T080307

* Main

The tort of intentionally inflicting emotional distress by outrageous conduct was first recognized in this jurisdiction in Grimsby v. Samson, supra. In that case, the Supreme Court adopted Restatement (Second) of Torts s 46 (1965):
#+begin_quote
Outrageous Conduct Causing Severe Emotional Distress
(1) One who by extreme and outrageous conduct intentionally or recklessly causes severe emotional distress to another is subject to liability for such emotional distress, and if bodily harm to the other results from it, for such bodily harm.
#+end_quote
The court went on to quote the Restatement's definition of extreme and outrageous conduct:
#+begin_quote
Liability exists “only where the conduct has been so outrageous in character, and so extreme in degree, as to go beyond all possible bounds of decency, and to be regarded as atrocious, and utterly intolerable in a civilized community.”
#+end_quote
(Italics omitted.) Grimsby v. Samson, supra 85 Wash.2d at 59, 530 P.2d 291.


/Phillips v. Hardwick/, 29 Wn. App. 382, 387, 628 P.2d 506, 510 (1981)

** Factors

The question of whether certain conduct is sufficiently outrageous is ordinarily a question for a jury. Jackson v. Peoples Federal Credit Union, 25 Wash.App. 81, 604 P.2d 1025 (1979). It is, however, for this court to determine in the first instance that reasonable minds could differ on whether the conduct has been sufficiently extreme and outrageous to result in liability. Bowe v. Eaton, 17 Wash.App. 840, 565 P.2d 826 (1977). Restatement (Second) of Torts s *388 46, Comment h (1965). Paraphrasing the factors considered by the court in Jackson v. Peoples Federal Credit Union, supra 25 Wash.App. at 86-87, 604 P.2d 1025, this court must consider
- (a) the position occupied by the defendant;
- (b) whether plaintiff was peculiarly susceptible to emotional distress, and if defendant knew this fact;
- (c) whether defendant's conduct may have been privileged under the circumstances;
- (d) the degree of emotional distress caused by a party must be severe as opposed to constituting mere annoyance, inconvenience or the embarrassment which normally occur in a confrontation of the parties; and,
  (e) the actor must be aware that there is a high probability that his conduct will cause severe emotional distress and he must proceed in a conscious disregard of it.

Restatement (Second) of Torts s 46, Comments e, f, and g.


/Phillips v. Hardwick/, 29 Wn. App. 382, 387–88, 628 P.2d 506, 510 (1981)
