#+title:      28 Wash. App. 2d 335 (2023) Housing Authority of Grant County v. Parker
#+date:       [2024-06-28 Fri 18:19]
#+filetags:   :old:rlta:
#+identifier: 20240628T181916

                          28 Wash.App.2d 335
             Court of Appeals of Washington, Division 3.
HOUSING AUTHORITY OF GRANT COUNTY, a Washington municipal corporation, Respondent,
                                  v.
                     Christina PARKER, Appellant.
                           No. 39089-6-III
                                  |
                       Filed September 21, 2023

* BRIEF

** Facts
- The Defendant was evicted, and several years later requested the TC to enter an OLD.
- The Def submitted testimony explaining why it felt there was good cause to enter an OLD.  It explained extenuating circumstances leading to the eviction, and that it had paid the rent owed.  It also explained that it was finding it impossible to become housed again due to the eviction showing up on every application.
- The TC refused, not finding good cause
- The Def appealed, and the CofA issues a ruling explaining that the TC could find good cause even when the PL's case was justified by facts and law, and the T was not reinstated.
- The case was remanded for the TC to conduct a meaningful analysis of whether good cause existed in this case.

** Issues
- Could "good cause" exist even though the PL had legitimate facts and law to support the eviction, and the Def was not reinstated to its tenancy?

** Rules
- RCW 59.18.367(1)
  - Under the statute, an OLD may be predicated on one of three circumstances: (a) the landlord’s case was factually or legally flawed, (b) the tenancy was restored, or (c) “other good cause.”
  - Issuance of an order for limited dissemination (OLD) is committed to the superior court’s discretion.
- Our fundamental objective in interpreting statutory text is to ascertain and carry out the legislature’s intent.
- As worded, it appears the legislature recognized that the circumstances set forth in subsections (a) and (b) of RCW 59.18.367(1) would generally constitute per se good cause for the issuance of an OLD. See Bauer, 22 Wash. App. 2d at 938 n.2, 514 P.3d 710 (opining an OLD should “ordinarily” be granted where subsection (a) is satisfied).

** Analysis
In **518 addition, statutory context indicates the legislature intended the good cause determination to be guided by an assessment of whether the prior unlawful detainer action fairly represents the risk a prior tenant poses to potential future landlords.

¶19 As previously explained, the legislature has indicated it seeks to limit the automatic dissemination of misleading, inaccurate, or incomplete information about unlawful detainer proceedings.
Our assessment is that subsections (a) and (b) of the OLD statute further this goal because both subsections describe circumstances where the existence of a prior unlawful **521 detainer action usually would not fairly reflect the risk that a given tenant poses to future landlords.
An unlawful detainer proceeding that was “without basis in fact or law,” RCW 59.18.367(1)(a), may reflect poorly on the prior landlord, but says nothing about the qualifications of the tenant.
And where a tenancy was “reinstated,” RCW 59.18.367(1)(b), it would appear that the conflict giving rise to the unlawful detainer action has been resolved.

** Conclusion
We therefore interpret RCW 59.18.367(1)(c) to allow issuance of an OLD upon a judicial finding of good cause to believe that a prior eviction does not fairly reflect *344 the risk a prior tenant poses to future landlords. Because subsection (c) is an alternative to subsections (a) and (b), a court may find good cause even if the prior eviction was lawful and the tenancy has not been reinstated.

* Case
Housing Authority of Grant County v. Parker
Court of Appeals of Washington, Division 3. | September 21, 2023 | 28 Wash.App.2d 335 | 535 P.3d 516

PUBLISHED OPINION

Hous. Auth. of Grant Cnty. v. Parker, 28 Wn. App. 2d 335, 535 P.3d 516 (2023)

** Synopsis

*** Background:
County housing authority brought unlawful detainer action against tenant. The Superior Court, Grant County, granted writ of restitution, Anna L. Gigliotti, J., denied tenant’s motion for order prohibiting tenant screening service providers from disclosing to prospective landlords existence of unlawful detainer action, and denied tenant’s motion for reconsideration. Tenant appealed, and Court of Appeals accepted review.

*** Holdings:
The Court of Appeals, Pennell, J., held that:

[1] court may find good cause for order limiting dissemination even if the prior unlawful detainer action was lawful and the tenancy has not been reinstated, and

[2] trial court abused its discretion in denying motion.

Reversed and remanded.

*** Procedural Posture(s):
On Appeal; Motion for Attorney’s Fees; Other.

** West Headnotes (13)

[1]

Landlord and TenantReview


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1805Review


Court of Appeals reviews a trial court’s ultimate decision to grant or deny a former tenant’s motion for an order limiting dissemination in a tenant screening report of a prior unlawful detainer action for abuse of discretion. Wash. Rev. Code Ann. § 59.18.367(1).




[2]

StatutesConstruction based on multiple factors


361Statutes
361IIIConstruction
361III(A)In General
361k1082Construction based on multiple factors


Statutory interpretation begins with the statute’s plain meaning, which is discerned from the ordinary meaning of the language at issue, the context of the statute in which the provision is found, related provisions, and the overall statutory scheme.




[3]

Landlord and TenantJudgment and enforcement thereof


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1804Judgment and enforcement thereof


Court may find good cause for an order limiting dissemination in a tenant screening report of a prior unlawful detainer action even if the prior unlawful detainer action was lawful and the tenancy has not been reinstated. Wash. Rev. Code Ann. § 59.18.367(1)(c).




[4]

StatutesAssociated terms and provisions;  noscitur a sociis
StatutesGeneral and specific terms and provisions;  ejusdem generis


361Statutes
361IIIConstruction
361III(E)Statute as a Whole;  Relation of Parts to Whole and to One Another
361k1159Associated terms and provisions;  noscitur a sociis
361Statutes
361IIIConstruction
361III(E)Statute as a Whole;  Relation of Parts to Whole and to One Another
361k1160General and specific terms and provisions;  ejusdem generis


Under canons of noscitur a sociis and ejusdem generis, use of word “other” to modify general statutory term can signify legislative intent that general term shares some sort of attribute with preceding, more specific terms.




[5]

Landlord and TenantJudgment and enforcement thereof


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1804Judgment and enforcement thereof


A court has discretion to find good cause for an order limiting dissemination in a tenant screening report of a prior unlawful detainer action separate from the two other grounds enumerated in the governing statute, namely finding the action was sufficiently without basis in fact or law or that the tenancy was reinstated, but the good cause inquiry should address concerns similar to those addressed by the other two enumerated grounds. Wash. Rev. Code Ann. § 59.18.367(1).




[6]

Landlord and TenantJudgment and enforcement thereof


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1804Judgment and enforcement thereof


“Other good cause,” as ground for a court order limiting dissemination in a tenant screening report of a prior unlawful detainer action, is not limited to situations where the tenant ameliorated the legal relationship with their former landlord. Wash. Rev. Code Ann. § 59.18.367(1)(c).




[7]

Landlord and TenantJudgment and enforcement thereof


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1804Judgment and enforcement thereof


A court order limiting dissemination in a tenant screening report of a prior unlawful detainer action may be issued upon a judicial finding of good cause to believe that a prior eviction does not fairly reflect the risk a prior tenant poses to future landlord. Wash. Rev. Code Ann. § 59.18.367(1)(c).




[8]

Landlord and TenantJudgment and enforcement thereof


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1804Judgment and enforcement thereof


A court order limiting dissemination in a tenant screening report of a prior unlawful detainer action provides only a narrow form of relief, as it does not vacate any prior court orders or seal from public view the contents of prior unlawful detainer proceedings; it merely operates to limit the use of prior unlawful detainer information in a tenant screening report. Wash. Rev. Code Ann. § 59.18.367(3).




[9]

Landlord and TenantJudgment and enforcement thereof


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1804Judgment and enforcement thereof


The statute governing a court order limiting dissemination in a tenant screening report of a prior unlawful detainer action does not limit a landlord’s ability to ask prospective tenants about whether they have ever been the subject of an unlawful detainer action. Wash. Rev. Code Ann. § 59.18.367.




[10]

Landlord and TenantJudgment and enforcement thereof


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1804Judgment and enforcement thereof


Trial court abused its discretion in denying motion by prospective tenant for order prohibiting tenant screening service providers from disclosing to prospective landlords existence of unlawful detainer action; trial court conflated good cause standards for different grounds for order, and comments in trial court’s oral ruling suggested it declined to issue order because there was not some sort of legal deficiency in unlawful detainer action that would have caused confusion to tenant, but an eviction premised on a misleading notice to vacate would be an eviction of dubious legality. Wash. Rev. Code Ann. § 59.18.367(1)(c).




[11]

Landlord and TenantJudgment and enforcement thereof


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1804Judgment and enforcement thereof


A finding of good cause for an order limiting dissemination in a tenant screening report of a prior unlawful detainer action does not require relief. Wash. Rev. Code Ann. § 59.18.367(1)(c).




[12]

Landlord and TenantReview


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1805Review


When reviewing an order for limited dissemination of a tenant screening report for abuse of discretion, the only role of the appellate tribunal is to mandate that the superior court correctly interpret the law and that its record be sufficiently detailed to allow for meaningful appellate review.




[13]

Landlord and TenantReview


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1805Review


Court of Appeals would not limit evidence on remand to information tenant supplied with her initial motion for order prohibiting tenant screening service providers from disclosing to prospective landlords existence of unlawful detainer action; superior court had discretion to decide scope of evidence relevant to assessment of good cause for requested order and whether prior unlawful detainer action was fair indicator of risk tenant may present to future landlords. Wash. Rev. Code Ann. § 59.18.367(1)(c).




**517 Appeal from Grant Superior Court, Docket No: 19-2-01695-3, Honorable Anna L. Gigliotti, Judge.
Attorneys and Law Firms
Scott Crain, Northwest Justice Project, 401 2nd Ave. S Ste. 407, Seattle, WA, 98104-3811, Seth A. Sivinski, Northwest Justice Project, 300 Okanogan Ave. Ste. 3a, Wenatchee, WA, 98801-6940, for Appellant.
Julie Katherine Norton, Ogden Murphy Wallace PLLC, 1 5th St. Ste. 200, Wenatchee, WA, 98801-6650, for Respondent.

* PUBLISHED OPINION
Pennell, J.

*337 ¶1 Under RCW 59.18.367, a former tenant who was the defendant in an unlawful detainer action may move for a court order prohibiting tenant screening service providers from disclosing the existence of that action to prospective landlords. Issuance of an order for limited dissemination (OLD) is committed to the superior court’s discretion. Under the statute, an OLD may be predicated on one of three circumstances: (a) the landlord’s case was factually or legally flawed, (b) the tenancy was restored, or (c) “other good cause.” RCW 59.18.367(1).

¶2 This case concerns “other good cause” as identified in subsection (c) of RCW 59.18.367(1). There is no statutory definition for “good cause” in this context. But the language adopted by the legislature makes plain that good cause for an OLD may be found regardless of the applicability of the other two circumstances specified in subsections (a) and (b). That is, there might be good cause for an OLD even when the prior unlawful detainer action had legal merit and even when the tenancy was not restored. *In **518 addition, statutory context indicates the legislature intended the good cause determination to be guided by an assessment of whether the prior unlawful detainer action fairly represents the risk a prior tenant poses to potential future landlords.*

¶3 The superior court’s decision to deny Christina Parker’s motion for an OLD was made without the benefit of case law interpreting “good cause” under RCW 59.18.367(1)(c). The court’s oral rulings indicate it may have denied an OLD for reasons that are not consistent with the standards set forth in this opinion. We therefore remand this matter for the court to consider whether good cause exists, and whether an OLD should be issued, according to the guidance provided by this opinion.

** FACTS
¶4 Beginning in 2013, the Housing Authority of Grant County rented an apartment to Christina Parker. In 2019, *338 the Housing Authority initiated an action against Ms. Parker for unlawful detainer, alleging she had violated her obligation to pay for utilities under the parties’ lease agreement. The superior court granted a writ of restitution and Ms. Parker was forcibly ousted in 2020.

¶5 In March 2022, Ms. Parker filed a motion in the unlawful detainer action for an OLD, citing RCW 59.18.367(1)(c). Under this statute, a court “may” order tenant screening service providers not to disclose a prior unlawful detainer action to prospective landlords if the tenant shows “good cause.” RCW 59.18.367(1)(c). When a tenant obtains an OLD, screening providers are forbidden from disclosing the existence of the prior unlawful detainer action in subsequent tenant screening reports or from using the prior action in determining any recommendations to be included in a tenant screening report. See RCW 59.18.367(3).

¶6 In support of her motion for an OLD, Ms. Parker submitted a sworn declaration setting forth her case for good cause. Ms. Parker explained there were mitigating circumstances surrounding the reasons for her eviction and failure to pay her utilities, including a loss of transportation that resulted in her losing her job. Ms. Parker asserted she had paid off the debt that led to her eviction, as well as the Housing Authority’s legal fees. She attached screenshots purportedly showing proof of payment. Ms. Parker also declared she and her children have continued to be negatively impacted by the 2020 eviction. According to Ms. Parker, the family lives in temporary housing as Ms. Parker has been turned down from five housing opportunities as a result of tenant screening providers’ automatic reporting of her prior eviction.

¶7 The Housing Authority filed only one responsive document: a sworn declaration from its director, Carol Anderson. Ms. Parker objected to the declaration, which was undisputedly untimely under the relevant local court rule. The Anderson declaration accused Ms. Parker of a litany of breaches that were not litigated under the prior unlawful *339 detainer complaint, allegations that Ms. Parker contended were irrelevant to the discrete issue of whether an OLD should be issued.

¶8 The superior court orally denied Ms. Parker’s motion for an OLD, explaining:
... Okay. I did have a chance to review all of the documents. I did look at the RCW. There is, unfortunately, not any real specific case law on what good cause is. However, in just looking at the terms of what good cause is, I just don’t find that this is good cause to order the limited dissemination.
This wasn’t good cause where there was a confusion of maybe possibly not realizing you do have to, you know, leave the home because the homeowner is going to move in and so they think they have a right to stay. This is just, I just can’t find sufficient good cause to order the limited dissemination. So, I am going to deny the motion at this time.
1 Rep. of Proc. (RP) (Apr. 1, 2022) at 4-5. The superior court subsequently issued a written order denying Ms. Parker’s motion, without any elaboration or analysis. The court’s order acknowledged “having reviewed” the untimely declaration from Carol Anderson over Ms. Parker’s objection. Clerk’s Papers at 59-60.

¶9 Ms. Parker moved for reconsideration, arguing the superior court erroneously relied **519 on Ms. Anderson’s untimely declaration. The court orally denied Ms. Parker’s motion for reconsideration, explaining:
... I’m gonna deny it. ... I did not make it clear what I took into consideration. I did not take into consideration the [Anderson] declaration. ...
I just—I can’t find based on the information that now there’s ramifications for this that it equals good cause. I did, as I said before in the previous hearing, I looked and attempted to determine good cause. I don’t think arguing the other court rules ... is [sic] equivalent to good cause in this case. The statute does have the (a)[,] (b) and (c) prongs. I just can’t find that based on the information that is provided and the facts in this case that there is good cause for limiting the dissemination *340 of this unlawful detainer action. So, I am gonna deny the motion to reconsider.
1 RP (May 20, 2022) at 18. The court subsequently entered a written order denying reconsideration, without any additional explanation or analysis.

¶10 Ms. Parker appeals.1

#+BEGIN_QUOTE
FN-1 A commissioner of this court ruled the superior court’s orders were not appealable as a matter of right, but a panel of this court modified the commissioner’s ruling and accepted review. See Order Granting Motion to Modify Commissioner’s Ruling, Hous. Auth. v. Parker, No. 39089-6-III (Wash. Ct. App. Nov. 8, 2022).
#+END_QUOTE

** ANALYSIS
¶11 Enacted in 2016, the OLD statute provides as follows:
A court may order an unlawful detainer action to be of limited dissemination for one or more persons if: (a) The court finds that the plaintiff’s case was sufficiently without basis in fact or law;
(b) the tenancy was reinstated under RCW 59.18.410 or other law; or (c) other good cause exists for limiting dissemination of the unlawful detainer action.
RCW 59.18.367(1).

[1]¶12 Because the statute uses the permissive word “ ‘may,’ ” we review a trial court’s ultimate decision to grant or deny an OLD for abuse of discretion. See Seattle’s Union Gospel Mission v. Bauer, 22 Wash. App. 2d 934, 938-39, 514 P.3d 710 (2022). However, the primary issue on appeal concerns whether the superior court properly construed the phrase “other good cause” as used in RCW 59.18.367(1)(c). We review questions of statutory interpretation de novo. See State v. Eaton, 168 Wash.2d 476, 480, 229 P.3d 704 (2010).

[2]¶13 Our fundamental objective in interpreting statutory text is to ascertain and carry out the legislature’s intent. Lake v. Woodcreek Homeowners Ass’n, 169 Wash.2d 516, 526, 243 P.3d 1283 (2010). “Statutory interpretation begins with the statute’s plain meaning,” which is discerned from the *341 ordinary meaning of the language at issue, the context of the statute in which the provision is found, related provisions, and the overall statutory scheme. Id.

[3]¶14 As set forth above, the OLD statute provides three bases for relief. Under subsection (a), an OLD may issue if the landlord’s case in the prior unlawful detainer action was “sufficiently without basis in fact or law.” RCW 59.18.367(1). Subsection (b) allows the court to issue an OLD if the tenancy was reinstated. Id. And subsection (c) allows for relief based on “other good cause.” Id. The use of the disjunctive term “or” to connect the three subsections signifies the legislature’s intent that relief may be awarded under subsection (c) even if the circumstances described in subsections (a) or (b) are not present. See Ski Acres, Inc. v. Kittitas County, 118 Wash.2d 852, 856, 827 P.2d 1000 (1992) (“The [l]egislature would have used the word ‘or’ if it had intended to convey a disjunctive meaning.”). In other words, the court may find good cause for an OLD even if a prior unlawful detainer action was lawful and the tenancy has not been reinstated.

[4] [5]¶15 The legislature provided additional guidance through its use of the word “other.” Under the canons of noscitur a sociis and ejusdem generis, the use of the word “other” to modify a general term can signify legislative intent that the general term shares some sort of attribute with preceding, **520 more specific terms. See Wash. State Dep’t of Soc. & Health Servs. v. Guardianship Estate of Keffeler, 537 U.S. 371, 375, 384-85, 123 S. Ct. 1017, 154 L. Ed. 2d 972 (2003). The structure of the OLD statute supports application of this principle here. As worded, it appears the legislature recognized that the circumstances set forth in subsections (a) and (b) of RCW 59.18.367(1) would generally constitute per se good cause for the issuance of an OLD. See Bauer, 22 Wash. App. 2d at 938 n.2, 514 P.3d 710 (opining an OLD should “ordinarily” be granted where subsection (a) is satisfied). But subsection (c) indicates there may be “other good cause” that the legislature could not anticipate. The placement of the word “other” *342 before “good cause” indicates a court has discretion to find good cause separate from the circumstances identified in subsections (a) and (b), but that the good cause inquiry should address concerns similar to those addressed by (a) and (b).

¶16 Legislative history provides insight into policy concerns that are relevant to our interpretive process. In enacting the fair tenant screening act, the legislature found that “tenant screening reports purchased from tenant screening companies may contain misleading, incomplete, or inaccurate information, such as information relating to eviction or other court records.” LAWS OF 2012, ch. 41 § 1.2 As recognized by RCW 59.18.367(1)(a), an unlawful detainer action that lacked a legal or factual basis would be an inaccurate indicator of a tenant’s history. And consistent with subsection (b) of the statute, an unlawful detainer action where the tenancy was ultimately restored would provide an incomplete picture of a tenant’s relationship with their former landlord. It stands to reason that subsection (c) indicates there are other situations where a prior unlawful detainer action—even a meritorious one—might provide misleading insight into an applicant’s desirability as a renter.

#+BEGIN_QUOTE
FN-2 The legislature also found it is often impossible for a prospective tenant to provide an explanation of red flags that show up in these reports until after they have already been rejected by a landlord, “at which point lodging disputes are seldom worthwhile.” Id. As Division One of this court has recognized, “[r]enters may be ‘disqualified from the rental market almost entirely’ ” on the basis of reports furnished by tenant screening providers. Bauer, 22 Wash. App. 2d at 937, 514 P.3d 710 (quoting Eric Dunn & Marina Grabchuk, Background Checks and Social Effects: Contemporary Residential Tenant-Screening Problems in Washington State, 9 SEATTLE J. SOC. JUST. 319, 320 (2010)).
#+END_QUOTE

¶17 The Housing Authority appears to agree with much of the foregoing analysis. It concurs that we should look at subsections (a) and (b) in discerning the meaning of subsection (c). And it agrees the aforementioned 2012 legislative findings are relevant to interpreting the meaning of “good cause” under the OLD statute. But the Housing Authority submits we must limit “other good cause” to situations *343 where a tenant ameliorated the legal relationship with their former landlord. As an example, the Housing Authority claims there would be good cause for issuance of an OLD under RCW 59.18.367(1)(c) if the landlord and a tenant settled a pending unlawful detainer case with the tenant agreeing to vacate the premises and the landlord agreeing to not oppose the tenant’s request for an OLD. Wash. Court of Appeals oral argument, Hous. Auth. v. Parker, No. 39089-6-III (Sept. 5, 2023), at 21 min., 1 sec. through 22 min., 31 sec., video recording by TVW, Washington State’s Public Affairs Network, http://www.tvw.org.

[6]¶18 The Housing Authority’s proposed interpretation fails because it is too narrow and too rigid. The legislature’s decision not to define “good cause” is indicative of an intent that RCW 59.18.367(1)(c) be an “open-ended basis” for relief. Bauer, 22 Wash. App. 2d at 938 n.2, 514 P.3d 710. Restricting good cause to a narrow set of legal circumstances between the tenant and landlord would be inconsistent with the statutory text.

¶19 As previously explained, the legislature has indicated it seeks to limit the automatic dissemination of misleading, inaccurate, or incomplete information about unlawful detainer proceedings. Our assessment is that subsections (a) and (b) of the OLD statute further this goal because both subsections describe circumstances where the existence of a prior unlawful **521 detainer action usually would not fairly reflect the risk that a given tenant poses to future landlords. An unlawful detainer proceeding that was “without basis in fact or law,” RCW 59.18.367(1)(a), may reflect poorly on the prior landlord, but says nothing about the qualifications of the tenant. And where a tenancy was “reinstated,” RCW 59.18.367(1)(b), it would appear that the conflict giving rise to the unlawful detainer action has been resolved.

[7] [8] [9]¶20 We therefore interpret RCW 59.18.367(1)(c) to allow issuance of an OLD upon a judicial finding of good cause to believe that a prior eviction does not fairly reflect *344 the risk a prior tenant poses to future landlords. Because subsection (c) is an alternative to subsections (a) and (b), a court may find good cause even if the prior eviction was lawful and the tenancy has not been reinstated.3

#+BEGIN_QUOTE
FN-3 It is worth noting that an OLD provides only a narrow form of relief. An OLD does not vacate any prior court orders. Nor does it seal from public view the contents of prior unlawful detainer proceedings. Nothing in the OLD statute limits a landlord’s ability to ask prospective tenants about whether they have ever been the subject of an unlawful detainer action. The statute merely operates to limit the use of prior unlawful detainer information in a service provider’s tenant screening report. See RCW 59.18.367(3). The limited impact of an OLD allows trial judges space to grant relief to a tenant without infringing on a prospective landlord’s right to information. Cf. Hundtofte v. Encarnación, 181 Wash.2d 1, 4, 330 P.3d 168 (2014) (plurality opinion) (prohibiting superior court from redacting the names of defendants in meritless unlawful detainer action given the public’s interest in the open administration of the courts).
#+END_QUOTE

[10]¶21 Having set forth the meaning of “other good cause” under subsection (c) of RCW 59.18.367(1), we turn to Ms. Parker’s claim that the superior court abused its discretion in denying her motion for relief under the OLD statute. The record on review provides very limited information regarding the superior court’s reasons for denying Ms. Parker’s motion. There are no written findings. In its oral ruling, the court indicated an OLD might be available if “there was a confusion of maybe possibly not realizing [the tenant] do[es] have to, you know, leave the home.” 1 RP (Apr. 1, 2022) at 5.

¶22 The superior court’s comments suggest it declined to issue an OLD because there was not some sort of legal deficiency in the unlawful detainer action that would have caused confusion to Ms. Parker. But an eviction premised on a misleading notice to vacate would be an eviction of dubious legality. See Christensen v. Ellsworth, 162 Wash.2d 365, 372, 173 P.3d 228 (2007) (Proper notice to a tenant is a condition precedent to the superior court’s exercise of jurisdiction in an unlawful detainer case.); IBF, LLC v. Heuft, 141 Wash. App. 624, 632, 174 P.3d 95 (2007) (Notice is improper if it “deceive[s] or mislead[s]” [a] tenant.). This would implicate subsection (a) of the OLD statute, which allows for an order of limited dissemination when an eviction was issued “without basis in fact or law.” RCW 59.18.367(1)(a). *345 But Ms. Parker sought relief under subsection (c) of the statute, not subsection (a).

¶23 By apparently conflating the good cause standards of subsections (a) and (c), the superior court committed legal error. While we recognize the court lacked any interpretive guidance in assessing Ms. Parker’s claim for relief under subsection (c), the court’s legal error still amounts to an abuse of discretion. See Cook v. Tarbert Logging, Inc., 190 Wash. App. 448, 461, 360 P.3d 855 (2015). Remand is therefore required so the superior court can consider Ms. Parker’s motion under the appropriate standard.

[11] [12]¶24 Ms. Parker objects to a full remand, arguing this court should direct entry of an OLD based on her unrefuted evidence of good cause. We are unpersuaded. The assessment of good cause has been allocated to the superior court, not this reviewing court. Furthermore, even though a finding of good cause should “ordinarily” result in an OLD, even this circumstance does not invariably require relief. Bauer, 22 Wash. App. 2d at 938 n.2, 514 P.3d 710. The only role of our appellate tribunal is to mandate that the superior court correctly interpret the law and that its record be sufficiently detailed to allow for meaningful appellate review. See, e.g., Maldonado v. Maldonado, 197 Wash. App. 779, 790-92, 391 P.3d 546 (2017) (finding abuse of discretion where superior **522 court’s failure to adequately explain its reasoning hampered appellate review).

[13]¶25 Ms. Parker alternatively claims that the evidence on remand should be limited to the information supplied with her initial motion for an OLD. Again, we disagree. On remand, the superior court has discretion to decide the scope of evidence relevant to its assessment of good cause and whether Ms. Parker’s prior unlawful detainer action is a fair indicator of the risk Ms. Parker may present to future landlords. To the extent Ms. Parker argues that she should receive an OLD based on information outside the scope of what was presented in the prior unlawful detainer proceeding, *346 the Housing Authority may respond in kind. Evidence presented by both parties should comply with applicable court rules.

** CONCLUSION
¶26 The order denying Ms. Parker’s request for an OLD is reversed and we remand for further proceedings. We deny both parties’ unsupported requests for attorney fees.4 As the substantially prevailing party, Ms. Parker is entitled to costs under RAP 14.2.

#+begin_quote
FN-4 Ms. Parker has cited RCW 4.84.040 in support of her request for attorney fees. However, this provision has no application to this case.
#+end_quote

* WE CONCUR:
Lawrence-Berrey, A.C.J.
Staab, J.

** All Citations
28 Wash.App.2d 335, 535 P.3d 516

* End of Document

© 2024 Thomson Reuters. No claim to original U.S. Government Works.
