#+title:      245 Cal.App.4th 75 (2016) Boston LLC v. Juarez
#+date:       [2024-07-03 Wed 15:14]
#+filetags:   :breach:insurance:material:
#+identifier: 20240703T151408

* Case

Boston LLC v. Juarez
Court of Appeal, Second District, Division 1, California. | February 25, 2016 | 245 Cal.App.4th 75 | 199 Cal.Rptr.3d 452

KeyCite Yellow Flag - Negative Treatment

 Distinguished by 510pacificave v. Weiss, Cal.App. 2 Dist., June 29, 2021

Boston LLC v. Juarez, 245 Cal. App. 4th 75, 199 Cal. Rptr. 3d 452 (2016)

245 Cal.App.4th 75, 199 Cal.Rptr.3d 452, 16 Cal. Daily Op. Serv. 2159, 2016 Daily Journal D.A.R. 1927

KeyCite Yellow Flag - Negative Treatment
 	Distinguished by 510pacificave v. Weiss, Cal.App. 2 Dist., June 29, 2021

                          245 Cal.App.4th 75

      Court of Appeal, Second District, Division 1, California.

                BOSTON LLC, Plaintiff and Respondent,
                                  v.
                Juan JUAREZ, Defendant and Appellant.

                               B267267
|
Filed February 25, 2016
|
Petition for Rehearing March 18, 2016
|
Petition for Review Denied May 11, 2016

** Synopsis
Background: Landlord sued tenant, who rented apartment under Los Angeles Rent Stabilization Ordinance (LARSO), for unlawful detainer, stemming from tenant’s failure to obtain renter’s insurance pursuant to rental agreement and landlord’s three-day notice to perform or quit. Following bench trial, the Superior Court, Los Angeles County, No. 14U02675, Leland B. Harris, J., ruled in favor of landlord. Tenant appealed. The Superior Court, Appellate Division, No. BV030948, Ricciardulli, J., 240 Cal.App.4th Supp. 28, 93 Cal.Rptr.3d 521, affirmed. The Court of Appeal asserted jurisdiction over the matter pursuant to rule governing transfer authority.


** Holdings: The Court of Appeal, Lui, J., held that:

[1] unlawful detainer statute did not create substantive forfeiture right;

[2] forfeiture clause in rental agreement did not foreclose materiality argument or defense;

[3] LARSO’s public policy goals outweighed free market and freedom of contract principles allowing landlord to include unilateral forfeiture clause in agreement;

[4] nature of insurance clause weighed against enforcing it; and

[5] tenant’s delay in obtaining renter’s insurance was not a material breach sufficient to justify forfeiture.

Reversed.


** Procedural Posture(s): On Appeal; Judgment.


** West Headnotes (11)


[1]

Landlord and TenantScope and standards of review


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(C)Actions for Recovery of Possession
233k1758Actions
233k1771Appeal
233k1771(4)Scope and standards of review


Whether the law requires material breach to enforce forfeiture clause in residential lease is a question of law which Court of Appeals reviews de novo in the absence of disputed facts.
1 Case that cites this headnote



[2]

Landlord and TenantNature and form


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1781Nature and form


Unlawful detainer statute did not create substantive forfeiture right, but rather statute governed forfeiture procedure; purpose of statute was procedural, statute implemented landlord’s property rights by permitting him to recover possession once consensual basis of tenant’s occupancy was at an end, and statute did not speak to what kinds of substantive neglect or failure to perform conditions or covenants of lease allowed statute to take effect. Cal. Civ. Proc. Code § 1161(3).




[3]

Landlord and TenantDefenses and grounds of opposition in general
Landlord and TenantViolation of Tenancy


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1783Right of Action and Defenses
233k1787Defenses and grounds of opposition in general
233Landlord and Tenant
233IXRegulated Rents
233IX(D)Recovery of Possession
233IX(D)3Grounds for Recovery or Non-Recovery
233k1992Violation of Tenancy
233k1993In general


Forfeiture clause in tenant’s rental agreement pursuant to Los Angeles Rent Stabilization Ordinance (LARSO), which provided that any failure of compliance or performance under agreement by tenant allowed landlord to forfeit agreement and terminate tenant’s right to possession, did not foreclose argument or defense by tenant that breach of agreement must be material to justify forfeiture in landlord’s unlawful detainer action, stemming from tenant’s failure to obtain renter’s insurance, as required under agreement and landlord’s three-day notice to perform or quit; despite such clause, materiality requirement still applied, especially where landlord had ability to detect and cure breach far in advance of bringing suit, but chose not to do so. Cal. Civ. Proc. Code § 1161(3).
5 Cases that cite this headnote



[4]

Landlord and TenantBreach by lessor
Landlord and TenantGrounds of action


233Landlord and Tenant
233IVParticular Kinds of Tenancies and Attributes Thereof
233IV(F)Termination
233IV(F)2Breach of Covenant or Condition
233k913Breach by lessor
233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1783Right of Action and Defenses
233k1786Grounds of action


Whether a particular breach of rental contract will give landlord the right to declare a forfeiture in unlawful detainer action is based on whether breach is material because law sensibly recognizes that, although every instance of noncompliance with a contract’s terms constitutes a breach, not every breach justifies treating contract as terminated. Cal. Civ. Proc. Code § 1161(3).
5 Cases that cite this headnote



[5]

Landlord and TenantBreach of Covenant or Condition
Landlord and TenantGrounds of action


233Landlord and Tenant
233IVParticular Kinds of Tenancies and Attributes Thereof
233IV(F)Termination
233IV(F)2Breach of Covenant or Condition
233k910In general
233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1783Right of Action and Defenses
233k1786Grounds of action


Courts allow termination of rental agreement under unlawful detainer statute only if breach can be classified as material, substantial, or total. Cal. Civ. Proc. Code § 1161(3).
5 Cases that cite this headnote



[6]

Landlord and TenantStatutes and Municipal Regulations in General


233Landlord and Tenant
233IXRegulated Rents
233IX(A)Regulation of Rents in General
233IX(A)1In General
233k1832Statutes and Municipal Regulations in General
233k1833In general


Courts are bound to uphold Los Angeles Rent Stabilization Ordinance’s (LARSO) objectives unless they are patently unenforceable.




[7]

Landlord and TenantBreach of Covenant or Condition
Landlord and TenantPurpose


233Landlord and Tenant
233IVParticular Kinds of Tenancies and Attributes Thereof
233IV(F)Termination
233IV(F)2Breach of Covenant or Condition
233k910In general
233Landlord and Tenant
233IXRegulated Rents
233IX(A)Regulation of Rents in General
233IX(A)1In General
233k1832Statutes and Municipal Regulations in General
233k1835Purpose


Los Angeles Rent Stabilization Ordinance’s (LARSO) public policy goals of providing stable affordable housing to low-income residents and preventing pretext evictions outweighed free market and freedom of contract principles allowing landlord to include unilateral forfeiture clause in an urban residential rental contract; unilateral forfeiture clause entirely benefited landlord, and permitting landlords with superior bargaining power to forfeit leases based on minor or trivial breaches would have allowed landlords to strategically circumvent LARSO’s good cause eviction requirements and disguise pretext evictions under cloak of contract provisions.
6 Cases that cite this headnote



[8]

Landlord and TenantConditions


233Landlord and Tenant
233IILeases and Agreements in General
233II(B)Construction and Operation
233k606Conditions


Because lease condition involving a forfeiture must be strictly interpreted against the party for whose benefit it is created, if lease agreement can be reasonably interpreted so as to avoid forfeiture, it is court’s duty to do so. Cal. Civ. Code § 1442.
3 Cases that cite this headnote



[9]

Landlord and TenantProperty of tenants
Landlord and TenantViolation of Tenancy


233Landlord and Tenant
233VEnjoyment and Use of Premises
233V(J)Liability for Dangerous or Defective Conditions
233V(J)6Particular Conditions
233k1323Injuries to Property
233k1325Property of tenants
233Landlord and Tenant
233IXRegulated Rents
233IX(D)Recovery of Possession
233IX(D)3Grounds for Recovery or Non-Recovery
233k1992Violation of Tenancy
233k1993In general


Insurance clause in tenant’s rental agreement pursuant to Los Angeles Rent Stabilization Ordinance (LARSO), which provided that landlord did not insure tenant for any personal injury or property damage and that tenant was required to obtain and pay for any insurance coverage necessary to protect him from such damage, was overreaching and unrealistic, and thus nature of clause weighed against enforcing it, especially where enforcing clause would have benefited landlord, the party for whose benefit clause was created, as ground for forfeiting agreement; landlord was precluded from absolving itself for any property damage to tenant by demanding that tenant obtain insurance when that damage could have been caused by landlord or could have been damage landlord was liable for as landlord. Cal. Civ. Code § 1442.
1 Case that cites this headnote



[10]

ContractsQuestions for Jury


95Contracts
95VPerformance or Breach
95k323Questions for Jury
95k323(1)In general


Normally, question of whether a breach of an obligation is a material breach is a question of fact, however, if reasonable minds cannot differ on issue of materiality, issue may be resolved as a matter of law.
6 Cases that cite this headnote



[11]

Landlord and TenantViolation of Tenancy


233Landlord and Tenant
233IXRegulated Rents
233IX(D)Recovery of Possession
233IX(D)3Grounds for Recovery or Non-Recovery
233k1992Violation of Tenancy
233k1993In general


Tenant’s slight delay in obtaining renter’s insurance pursuant to rental agreement under Los Angeles Rent Stabilization Ordinance (LARSO) and landlord’s three-day notice to obtain insurance or quit was not a material breach sufficient to justify forfeiture of agreement; chance that tenant’s temporary noncompliance with agreement’s insurance clause incited other tenants to not comply with their insurance obligations was insufficient to demonstrate harm justifying forfeiture, tenant’s lack of insurance for a mere handful of days after he was noticed did not harm landlord, and giving tenant three-day notice to obtain insurance on the Friday preceding a three-day weekend suggested gamesmanship or retaliatory motives.
See 12 Witkin, Summary of Cal. Law (10th ed. 2005) Real Property, § 703 et seq.
1 Case that cites this headnote



**454 APPEAL from a judgment the Superior Court of Los Angeles County, Leland B. Harris, Judge. Reversed. (Los Angeles County Super. Ct. No. 14U02675; App. Div. No. BV030948)
Attorneys and Law Firms
Public Counsel, Lisa R. Jaskol and Robert J. Reed for Defendant and Appellant.
Neighborhood Legal Services of Los Angeles County, Los Angeles, Alexander Prieto, Eliza Schafler, Lena Silver; Western Center on Law and Poverty, Los Angeles, and Maria Palomares as Amici Curiae on behalf of Defendant and Appellant.
Legal Aid Foundation of Los Angeles, Anna Levine–Gronningsater; Inner City Law Center and Lorraine Lopez as Amici Curiae on behalf of Defendant and Appellant.
Allen R. King, Los Angeles, for Plaintiff and Respondent.

* Opinion

LUI, J.

*78 Plaintiff and respondent Boston LLC (Boston) rented defendant and appellant Juan Juarez an apartment under the Rent Stabilization Ordinance of the City of Los Angeles (LARSO) (L.A. Mun. Code, § 151.00 et seq.). Their rental agreement contained a forfeiture clause stating that “any failure of compliance or performance by Renter shall allow Owner to forfeit this agreement and terminate Renter’s right to possession.” (Italics added.) The agreement also contained an insurance clause stating that Juarez “shall obtain and pay for any insurance coverage necessary to protect Renter” “for any personal injury or property damage.” (Italics added.) After 15 years of Juarez failing to obtain this insurance, Boston gave Juarez a three-day notice to perform or quit. Juarez obtained insurance shortly after the three-day period expired.

Boston then sued Juarez for unlawful detainer. (Super. Ct. L.A. County, No. 14U02675.) The trial court ruled for Boston. Juarez appealed to the *79 appellate division of the superior court. (Super. Ct. L.A. County, App. Div., No. BV030948.) The appellate division affirmed, holding **455 that because of the forfeiture clause, Juarez was properly precluded at trial from defending himself on a materiality ground or raising certain affirmative defenses. (Boston LLC v. Juarez (2015) 240 Cal.App.4th Supp. 28, 193 Cal.Rptr.3d 521 (Boston I ).)

We asserted jurisdiction over the matter pursuant to California Rules of Court, rule 8.1002,1 to settle an important question of law: Whether a tenant’s breach of an LARSO rental contract, regardless of the breach’s materiality or impact on the landlord, justifies the landlord forfeiting the agreement and terminating tenancy. We hold a tenant’s breach must be material to justify forfeiture. Here, the tenant’s obligation to obtain and pay for insurance protected the tenant’s interest, not the landlord’s; accordingly, the tenant’s failure to obtain a policy could not have harmed the landlord and therefore was not a material breach of the agreement constituting grounds for forfeiture.

1

Undesignated rule references are to the California Rules of Court.



BACKGROUND
Juarez rented an apartment in Los Angeles from Boston for more than 15 years under LARSO. Juarez and Boston’s rental agreement called for Juarez to obtain renter’s insurance. Juarez did not obtain renter’s insurance, however. On February 14, 2014, Boston gave Juarez a three-day notice to perform by obtaining renter’s insurance or quit.2 February 14th was a Friday and began a three-day weekend for Presidents’ Day, a legal holiday, which was on Monday, February 17th. Likely due to the holiday weekend, Juarez failed to obtain renter’s insurance within the three-day period; he did, however, obtain it by February 21st.

2

Juarez, a monolingual Spanish speaker, could not read the notice because it was written in only English.


Boston then sued Juarez for unlawful detainer. Boston argued the rental contract contained a forfeiture clause which allowed it to terminate Juarez’s tenancy for any breach, regardless of the breach’s materiality. Juarez countered that the law requires a material breach to justify forfeiture. Juarez argued he should therefore be allowed to present evidence that his breach was immaterial and, in any event, he was in substantial compliance with the insurance clause. He also asserted a number of affirmative defenses, including retaliation and waiver. The trial court, however, agreed with Boston that the forfeiture clause made any breach by Juarez, regardless of materiality, grounds for Boston to terminate Juarez’s tenancy. Juarez agreed to a bench *80 trial upon the parties stipulating to undisputed facts. The court ruled Juarez had breached the rental agreement by failing to obtain renter’s insurance within the three-day notice period and Boston could thereby forfeit the lease. The trial court did not make a determination about the breach’s materiality. Juarez appealed to the appellate division, but it affirmed, two to one. We review this matter under rule 8.1002.


DISCUSSION
On appeal, Juarez argues the law demands that a tenant’s breach must be material to justify a landlord’s forfeiture of a rental contract. We agree. Because we agree, we do not reach his argument that the forfeiture clause constituted an unlawful penalty or whether he should have been allowed to present certain affirmative defenses.

[1]Whether the law requires a material breach to enforce a forfeiture clause in a **456 residential lease is a question of law which we review de novo in the absence of disputed facts. (Cohn v. Corinthian Colleges, Inc. (2008) 169 Cal.App.4th 523, 527, 86 Cal.Rptr.3d 401 [appellate courts exercise “independent judgment” on “pure question[s] of law” where “the facts are not disputed”].)



1. Code of Civil Procedure section 1161, subdivision 3 governs forfeiture procedure and does not create substantive rights
[2]Boston brought its unlawful detainer action under Code of Civil Procedure section 1161, subdivision 3.3 Section 1161, subdivision 3 establishes that a “tenant of real property ... is guilty of unlawful detainer: [¶] ... [¶] 3. When he or she continues in possession ... after a neglect or failure to perform other conditions or covenants of the lease or agreement under which the property is held ... than the one for the payment of rent, and three days’ notice, in writing, requiring the performance of such conditions or covenants, or the possession of the property shall have been served upon him or her ....’’ On appeal, Boston argues that section 1161, subdivision 3 provides for statutory forfeiture, as opposed to contractual forfeiture, and, therefore, Boston was permitted to forfeit the contract as a matter of law after Juarez failed to obtain insurance within the notice period.

3

Undesignated statutory references are to the Code of Civil Procedure.


Boston is incorrect. Section 1161, subdivision 3 does not create a substantive forfeiture right. Rather, “ ‘[t]he purpose of the unlawful detainer statutes is procedural. The statutes implement the landlord’s property rights by permitting him to recover possession once the consensual basis for the *81 tenant’s occupancy is at an end.’ ” (Foster v. Britton (2015) 242 Cal.App.4th 920, 930, 195 Cal.Rptr.3d 800, quoting Birkenfeld v. City of Berkeley (1976) 17 Cal.3d 129, 149, 130 Cal.Rptr. 465, 550 P.2d 1001.) This procedural statute does not speak to what kinds of substantive “neglect or failure to perform ... conditions or covenants of the lease” allow the statute to take effect. In the absence of such a statutory directive, we look to case law for the substance of what kinds of breaches allow the procedural statute to take effect.



2. Case law dictates a breach must be material to justify forfeiture
Case law is clear as to what kinds of “failure to perform” justify forfeiture. Courts have consistently concluded that “a lease may be terminated only for a substantial breach thereof, and not for a mere technical or trivial violation.” (Keating v. Preston (1940) 42 Cal.App.2d 110, 118, 108 P.2d 479 (Keating ) [discussing breach of implied covenants].) This materiality limitation even extends to leases which contain clauses purporting to dispense with the materiality limitation. For example, in Randol v. Scott, a forfeiture clause provided “that ‘if default shall be made **457 in any of the covenants herein contained, then it shall be lawful for the lessor to re-enter the said premises.’ ” (Randol v. Scott (1895) 110 Cal. 590, 593, 42 P. 976 (Randol ); id. at pp. 597–598, 42 P. 976.) Despite the forfeiture clause’s language that any breach permitted forfeiture, the court refused to allow forfeiture for an “entirely ... trivial” matter, especially when the lessor had permission to enter and inspect the premises at any time, which would have given the lessor the chance to detect, and demand remedy for, the complained-of breach. (Id. at pp. 597–598, 42 P. 976.) Similarly, in Keating, the lease contained a clause authorizing the lessor “to re-enter the premises ... ‘if default shall be made in any of the covenants herein contained.’ ” (Keating, supra, 42 Cal.App.2d at p. 114, 108 P.2d 479, italics omitted.) The court held that even if the offending behavior could be considered a breach, “it was so slight and trivial a violation ... that it [did] not constitute ground for terminating the lease on that account.” (Id. at p. 117, 108 P.2d 479.)4

4

That cases have not specifically spoken on a materiality requirement for forfeiture of residential leases does not mean the well-established materiality requirement does not apply to such leases. On the contrary, residential leases especially should be protected by the materiality requirement due to the parties’ unequal bargaining power, as explained further in part 4.a., post.


[3]Juarez and Boston’s agreement contained a forfeiture clause stating: “Renter’s performance of and compliance with each of the terms hereof ... constitute a condition on Renter’s right to occupy the Premises and any failure of compliance or performance by Renter shall allow Owner to forfeit this agreement and terminate Renter’s right to possession.” Boston argues this clause forecloses any materiality argument or defense by Juarez. The above *82 cases, however, demonstrate that despite such a clause, the materiality requirement still applies. (Accord, Medico–Dental etc. Co. v. Horton & Converse (1942) 21 Cal.2d 411, 433, 132 P.2d 457 [“a breach of contractual right in a trivial or inappreciable respect will not justify rescission of the agreement by the party entitled to the benefit in question...”].) This is especially so when, as in Randol, Boston had the ability to detect and cure the breach far in advance of bringing suit, but chose to not do so.



3. The substantive law requiring a materiality limitation underlies, and therefore applies to, section 1161, subdivision 3
[4] [5]“Although not expressly set forth in Code of Civil Procedure section 1161, subdivision 3,” the “requirement” that a “ ‘breach be substantial’ ” “is set forth in case law.” (NIVO 1 LLC v. Antunez (2013) 217 Cal.App.4th Supp. 1, 5, 159 Cal.Rptr.3d 922 (NIVO 1, ), citing Keating, supra, 42 Cal.App.2d at p. 115, 108 P.2d 479.) That is, “[w]hether a particular breach will give a plaintiff landlord the right to declare a forfeiture is based on whether the breach is material.” (NIVO 1, at p. Supp. 5, 159 Cal.Rptr.3d 922.) This is because “ ‘[t]he law sensibly recognizes that although every instance of noncompliance with a contract’s terms constitutes a breach, not every breach justifies treating the contract as terminated. [Citations.] Following the lead of the Restatements of Contracts, California courts allow termination only if the breach can be classified as “material,” “substantial,” or “total.” [Citations.]’ ” (Ibid. quoting Superior Motels, Inc. v. Rinn Motor Hotels, Inc. (1987) 195 Cal.App.3d 1032, 1051, 241 Cal.Rptr. 487.)

Although not binding on us, NIVO 1 demonstrates how courts apply the materiality requirement in section 1161 cases. In NIVO 1, a rental agreement required a tenant to obtain renter’s insurance. (NIVO 1, supra, 217 Cal.App.4th at p. Supp. 3, 159 Cal.Rptr.3d 922.) Under the original contract, the tenant’s violation of the insurance clause would result only “in a waiver of the tenant’s rights to seek damages against the landlord” (id. at p. Supp. 4, 241 Cal.Rptr. 487) in the case of “ ‘personal property damage or loss’ ” (id. at p. Supp. 3, 241 Cal.Rptr. 487). The landlord attempted to unilaterally modify the rental agreement, however, by adding a forfeiture clause stating: “ ‘Any failure of compliance or performance by Renter **458 shall allow Owner to declare a forfeiture of this agreement and terminate Renter’s right to possession. Any breach of the contract is a material breach.’ ” (Id. at p. Supp. 4, 241 Cal.Rptr. 487, italics omitted.) The appellate division held that the landlord’s attempted unilateral modification in adding the forfeiture clause was illegal under LARSO and consequently disregarded it. (Ibid. citing L.A. Mun. Code, § 151.09, subd. A.2(c).) Then, recognizing the materiality requirement, the appellate division upheld the trial court’s determination that the tenant’s failure to obtain renter’s insurance was immaterial. (NIVO 1, at pp. Supp. 4–6, 159 Cal.Rptr.3d 922.) The court reasoned “that the failure *83 to comply with [the] lease provision was a ‘trivial breach’ because the ‘provision benefits the tenant, not the landlord.’ ” (Id. at p. Supp. 5, 241 Cal.Rptr. 487.) Although NIVO 1 did not analyze the materiality requirement in light of a forfeiture clause, Randol, supra, 110 Cal. 590, 42 P. 976, and other cases establish that a materiality requirement would apply even in the face of a forfeiture clause.

Other California authorities recognize a materiality requirement as well. For example, Miller and Starr admonishes that a “landlord cannot terminate the lease unless the tenant’s breach of the condition is material or substantial.” (10 Miller & Starr, Cal. Real Estate (4th ed. 2015) § 34:181, p. 34-566, citing NIVO 1, supra, 217 Cal.App.4th Supp. 1, 159 Cal.Rptr.3d 922.) It continues, “Every default by a tenant does not necessarily justify the landlord’s termination of the tenancy,” and this “is especially true when the breach involves a nonmonetary covenant in the lease.” (10 Miller & Starr, supra, § 34:181, p. 34–565.) Witkin concurs that a “[s]ubstantial [b]reach [i]s [r]equired” to invoke a “forfeiture clause.” (12 Witkin, Summary of Cal. Law (10th ed. 2005) Real Property, § 668, p. 784–785, italics omitted; id. (2015 Supp.) § 668, p. 159, citing NIVO 1, at p. Supp. 4, 159 Cal.Rptr.3d 922.) Likewise, the California Practice Guide comments that a “ ‘trivial’ or ‘de minimis’ breach is not sufficient ground for termination and may be raised an as ‘equitable defense’ to unlawful detainer.” (Friedman et al., Cal. Practice Guide: Landlord-Tenant (The Rutter Group 2015) ¶ 7:130, p. 7-80, citing NIVO 1, at p. Supp. 5, 159 Cal.Rptr.3d 922.)

Others states, including Arizona, Illinois, Massachusetts, South Carolina, and Utah, likewise recognize a materiality requirement. (See, e.g., Foundation Dev. Corp. v. Loehmann’s (1990) 163 Ariz. 438, 443, 788 P.2d 1189, 1194 (Loehmann’s ) [in a commercial lease context, it was unlikely that the Arizona Legislature “intended to permit forfeitures under any and all circumstances, no matter how trivial, inadvertent, non-prejudicial, or technical the breach,” given the “important interplay of property and contract law that preceded the enactment of the statute”]; Wolfram Partnership v. LaSalle Nat. Bank (2001) 328 Ill.App.3d 207, 262 Ill.Dec. 404, 765 N.E.2d 1012, 1025 [“Regardless of the language used by the parties, a breach, to justify a ... forfeiture of a lease agreement, must have been material or substantial”]; Banco do Brasil v. 275 Washington Street Corp. (D.Mass. 2010) 750 F.Supp.2d 279, 292 [quoting and agreeing with Loehmann’s materiality requirement]; Kiriakides v. United Artists Communications, Inc. (1994) 312 S.C. 271, 275, 440 S.E.2d 364, 366 [agreeing with Loehmann’s after finding that a “majority of courts have concluded that a lease may not be forfeited for a trivial or technical breach even when the parties have specifically agreed that ‘any breach’ gives rise to the right of termination”]; Cache County v. Beus (Utah Ct. App. 1999) 978 P.2d 1043, 1049–1050 [quoting and agreeing with Loehmann’s ].)



**459 *84 4. Public policy and other considerations favor a materiality requirement, especially for an LARSO lease

a. LARSO’s public policy goals outweigh freedom to contract and free market rationales in this context
[6]LARSO was born out of the shortage of affordable housing, especially for low-income individuals, in Los Angeles. (L.A. Mun. Code, § 151.01.) It seeks to “safeguard tenants from excessive rent increases” by imposing certain statutory limitations and obligations on landlords which landlords would otherwise not be subject to under normal freedom to contract principles. (Ibid.) For example, LARSO prohibits landlords from terminating leases without one of 14 enumerated “good causes.” (Id., § 151.09.) We are bound to uphold LARSO’s objectives unless they are patently unenforceable. (People v. Otto (2001) 26 Cal.4th 200, 209–210, 109 Cal.Rptr.2d 327, 26 P.3d 1061 [“Courts have a ‘ “duty to uphold a statute unless its unconstitutionality clearly, positively, and unmistakably appears....” ’ ”].)

In its decision upholding the forfeiture clause, the appellate division focused on Juarez’s and Boston’s general freedom to contract and held, notwithstanding NIVO 1 ‘s and other cases’ materiality requirement, “ ‘[i]f contractual language is clear and explicit, it governs ... [citation]’ (Bank of the West v. Superior Court (1992) 2 Cal.4th 1254, 1264 [10 Cal.Rptr.2d 538, 833 P.2d 545]).” (Boston I, supra, 240 Cal.App.4th at p. Supp. 34, 193 Cal.Rptr.3d 521.) It reasoned that in Juarez and Boston’s case, “[t]he clear and unambiguous terms of [the forfeiture] clause permitted forfeiture of the agreement and termination of the defendant’s right to possession based on any breach, regardless of the breach’s importance in relation to the entire agreement.” (Id. at p. Supp. 35, 193 Cal.Rptr.3d 521.)

While the freedom to contract is important, as the appellate division noted, the California Supreme Court has recognized in Green v. Superior Court that free market principles, which justify, in part, the freedom to contract, do not apply to urban residential leases, such as Juarez’s LARSO lease. (Green v. Superior Court (1974) 10 Cal.3d 616, 625, 111 Cal.Rptr. 704, 517 P.2d 1168 (Green ).) This is because “the severe shortage of low and moderate cost housing has left tenants with little bargaining power ... and thus the mechanism of the ‘free market’ no longer serves as a viable means for fairly allocating” rights and duties between landlords and tenants. (Ibid.) Citing Green, courts acknowledge that due to the “unequal bargaining power [between] landlord and tenant resulting from the scarcity of adequate housing in urban areas,” tenants in urban residential leases are treated more favorably by courts than lessees in commercial leases where the “parties are more likely to have equal bargaining power.” ( *85 Schulman v. Vera (1980) 108 Cal.App.3d 552, 561, 166 Cal.Rptr. 620; Henrioulle v. Marin Ventures, Inc. (1978) 20 Cal.3d 512, 519, 143 Cal.Rptr. 247, 573 P.2d 465 [“tenants are likely to be in a poor position to bargain with landlords”].)5 Here, Juarez and Boston’s **460 lease reflects the unequal bargaining power recognized by Green and other courts in that the unilateral forfeiture clause entirely benefits Boston as the landlord. The forfeiture clause makes any breach by Juarez grounds for Boston to forfeit the lease and imposes not only no reciprocal obligation on Boston, it imposes no obligations at all on Boston. Granted, Boston would be restricted by general contract principles permitting punishment for Boston’s breaches. Under these general contract principles, however, a trivial breach by Boston would likely result in either nominal or negligible damages, which would be of little value to Juarez. (Avina v. Spurlock (1972) 28 Cal.App.3d 1086, 1088, 105 Cal.Rptr. 198 [nominal damages are awarded when “there is no loss or injury to be compensated but where the law still recognizes a technical ... breach”].)

5

In addition to unequal bargaining power, tenants often sign form leases without understanding the full import of their terms, and consequently unknowingly sign away important rights. The Legislature has acknowledged in a related context that tenants need protection from “ ‘unknowing[ly] signing away [such] valuable rights.’ ” (Jaramillo v. JH Real Estate Partners, Inc. (2003) 111 Cal.App.4th 394, 403, 3 Cal.Rptr.3d 525 [referring to Civ. Code, § 1953].)


[7]Permitting landlords like Boston with superior bargaining power to forfeit leases based on minor or trivial breaches would allow them to strategically circumvent LARSO’s “good cause” eviction requirements and disguise pretext evictions under the cloak of contract provisions. Such provisions, which enable pretext evictions, are “ ‘unenforceable on grounds of public policy if ... the interest in its enforcement is clearly outweighed in the circumstances by a public policy against the enforcement of such terms.’ ” (Bovard v. American Horse Enterprises, Inc. (1988) 201 Cal.App.3d 832, 840, 247 Cal.Rptr. 340, quoting Rest.2d Contracts, § 178.) Here, LARSO’s public policy goals of providing stable affordable housing to low-income Angelenos and preventing pretext evictions outweigh the free market and freedom to contract principles allowing a landlord to include a unilateral forfeiture clause in an urban residential rental contract.



b. Forfeiture is avoided where possible and forfeiture clauses are strictly construed against the party they benefit
[8]“A condition involving a forfeiture must be strictly interpreted against the party for whose benefit it is created.” (Civ. Code, § 1442.) Courts recognize the full import of this rule, reasoning that “[i]f the agreement can be reasonably interpreted so as to avoid the forfeiture, it is our duty to do so.” (Quatman v. McCray (1900) 128 Cal. 285, 289, 60 P. 855; see also McNeece v. Wood (1928) 204 Cal. 280, 284, 267 P. 877, quoting  *86 Cleary v. Folger (1890) 84 Cal. 316, 321, 24 P. 280 [“ ‘Forfeitures ... are not favored by the courts....’ ”].) Because the forfeiture clause allegedly made any breach by Juarez grounds for Boston to forfeit the contract, all the agreement’s clauses, including the insurance clause, should be “strictly interpreted” against Boston.

[9]The insurance clause provides that Boston “does not insure Renter for any personal injury or property damage” (italics added) and that Juarez “shall obtain and pay for any insurance coverage necessary to protect Renter” from such damage. This provision is overreaching. Boston cannot absolve itself of liability for “any ... property damage” to Juarez by demanding that Juarez obtain insurance when that damage could be caused by Boston itself or could be damage Boston is liable for as a landlord. (Italics added.) In the balance of our analysis, the overreaching and unrealistic nature of the clause weighs against enforcing it, especially when enforcing it would benefit Boston, “the party for whose benefit it [was] created.” (Civ. Code, § 1442.)



**461 c. A materiality requirement potentially prevents unmeritorious litigation
Permitting forfeiture for trivial breaches could unleash a torrent of unmeritorious unlawful detainer litigation.6 Without the protection of a materiality requirement, tenants potentially are in jeopardy of defending frivolous unlawful detainer actions for trivial breaches. For example, Juarez’s lease prevents him from even bringing a musical instrument on the premises, “unless noted in ... Owner’s copy of this Agreement.” If we upheld the forfeiture clause as Boston argues, Juarez could risk forfeiture of the rental agreement, and eviction, for absurdly trivial reasons, e.g., if he hung a violin with no strings on his wall for decoration because it was a family heirloom or if for a few days he had in his apartment a gift-wrapped plastic piano for a niece’s upcoming birthday. Litigation over these types of trivial breaches is not a proper or efficient use of court resources.7

6

Bilateral forfeiture clauses, although more favorable to the tenant, also potentially open the floodgates and perhaps to an even greater degree.


7

In addition, an eviction for such a trivial matter would almost certainly be pretext, as no rational landlord would expend the time or resources litigating such a frivolous issue; again, we will not legally provide the basis for pretext evictions.


The appellate division attempted to refute this argument, holding that “[i]n evictions based on three-day notices to perform or quit ... breaches would only constitute valid grounds for eviction if they [a]re not cured within the notice period, meaning tenants could not be evicted based on single incidents....” (Boston I, supra, 240 Cal.App.4th at p. Supp. 36, 193 Cal.Rptr.3d 521.) Even if that were true, Juarez would still be subject to the risk of eviction if he refused to *87 take the decorative, heirloom violin out of his home or if he were out of town, say for a three-day weekend, when a notice about the piano gift was posted. This court will not uphold clauses which could result in such frivolous litigation.



5. Given the facts, Juarez’s failure to obtain renter’s insurance within the three-day notice period was not a material breach
[10]“Normally the question of whether a breach of an obligation is a material breach ... is a question of fact,” however “ ‘if reasonable minds cannot differ on the issue of materiality, the issue may be resolved as a matter of law.’ ” (Brown v. Grimes (2011) 192 Cal.App.4th 265, 277–278, 120 Cal.Rptr.3d 893, quoting Insurance Underwriters Clearing House, Inc. v. Natomas Co. (1986) 184 Cal.App.3d 1520, 1526–1527, 228 Cal.Rptr. 449.)

[11]The primary purpose of renter’s insurance is to protect the tenant, not the landlord. As such, Boston has little ground to argue that Juarez’s failure to obtain insurance harmed it. For example, Boston does not argue Juarez made claims against it that should have been covered by renter’s insurance but were not because Juarez lacked it. Instead, Boston argues it was harmed because there was a chance Juarez’s noncompliance encouraged other tenants’ noncompliance. In the absence of evidence of actual harm, the chance Juarez’s temporary noncompliance incited other tenants to not comply with their insurance obligations is insufficient to demonstrate harm justifying forfeiture. (See Feder v. Wreden etc. Co., Inc. (1928) 89 Cal.App. 665, 673, 265 P. 386 [a court cannot “overlook[ ]” when a complaint fails to allege actionable harm]; Rest.2d Contracts, supra, ch. 16, Introductory Note, **462 [“The initial assumption” in awarding damages “is that the injured party is entitled to full compensation for his actual loss” (italics added)].) Boston also fails to explain how Juarez lacking insurance for a mere handful of days after he was noticed harmed Boston, given the 15 years Juarez lacked insurance, a defect which Boston could have easily discovered at any time and demanded Juarez remedy. Also, although technically permissible, Boston giving Juarez the three-day notice to obtain insurance on the Friday preceding a three-day weekend which encompassed a widely celebrated legal holiday smacks of gamesmanship, or possibly even retaliatory motives, in light of the 15 years Boston failed to enforce the insurance clause. Given the facts of this case, Juarez’s slight delay in obtaining renter’s insurance was not a material breach sufficient to justify forfeiture.

Because Juarez’s breach was immaterial, we need not address his arguments that the forfeiture clause constituted an unlawful penalty or that he should have been allowed to present certain affirmative defenses.


*88 DISPOSITION
The judgment is reversed. Juarez is awarded his costs on appeal under California Rules of Court, rule 8.278.

We concur:
CHANEY, Acting P.J.
JOHNSON, J.
All Citations
245 Cal.App.4th 75, 199 Cal.Rptr.3d 452, 16 Cal. Daily Op. Serv. 2159, 2016 Daily Journal D.A.R. 1927
End of Document

© 2024 Thomson Reuters. No claim to original U.S. Government Works.
