#+title:      149 Wash. App. 757 Commonwealth Real Estate Services v. Padilla (2009)
#+date:       [2024-02-13 Tue 08:57]
#+filetags:   :compliance:mhlta:strict:waiver:
#+identifier: 20240213T085728

* BRIEF


* LAW


[9]

Landlord and TenantAcceptance of rent


233Landlord and Tenant
233IVParticular Kinds of Tenancies and Attributes Thereof
233IV(F)Termination
233IV(F)4Waiver of Forfeiture
233k941Acceptance of rent
(Formerly 233k112(2))


If a landlord accepts rent with knowledge of a prior breach of a lease covenant, the landlord waives the right to evict based on that breach.


* CASE

Commonwealth Real Estate Services v. Padilla
Court of Appeals of Washington, Division 3. | April 16, 2009 | 149 Wash.App. 757 | 205 P.3d 937

Document Details

Outline
Synopsis
West Headnotes
Attorneys and Law Firms
Opinion
All Citations

KeyCite:

KeyCite Yellow Flag - Negative Treatment
 Distinguished by Triune Family Charitable Remainder Unitrust v. Pfeifer, Wash.App. Div. 3, August 24, 2010

washington Citation:

Commonwealth Real Estate Servs. v. Padilla, 149 Wn. App. 757, 205 P.3d 937 (2009)

All Citations:

149 Wash.App. 757, 205 P.3d 937

Search Details

Search Query:

Commonwealth v. Padilla

Jurisdiction:

Washington

Delivery Details

Date:

February 13, 2024 at 10:54 AM

Delivered By:

Lincoln Harvey

Client ID:

DISMISSAL

Status Icons:



Inline KeyCite:

Inline KeyCite completed successfully.





KeyCite Yellow Flag - Negative Treatment
 	Distinguished by Triune Family Charitable Remainder Unitrust v. Pfeifer, Wash.App. Div. 3, August 24, 2010
149 Wash.App. 757
Court of Appeals of Washington,
Division 3.
COMMONWEALTH REAL ESTATE SERVICES d/b/a Harvest Manor Estates, a Washington Corporation, Appellant,
v.
Rick PADILLA, a single person, et al, Respondent.
No. 27324–5–III.
|
April 16, 2009.
Synopsis
Background: Mobile home park brought action for unlawful detainer, alleging it had served resident with more than three notices to comply with alleged rule violations during a 12 month period. The Superior Court, Grant County, John Michael Antosz, J., dismissed the action on grounds park waived its statutory right to evict under the Manufactured/Mobile Home Landlord-Tenant Act (MHLTA). Park appealed.

[Holding:] The Court of Appeals, Kulik, A.C.J., held that park waived right to file unlawful detainer action by accepting rent after third notice to comply or vacate.

Affirmed.

Procedural Posture(s): On Appeal; Motion to Dismiss.


West Headnotes (10)


[1]

TrialDismissal or nonsuit


388Trial
388XTrial by Court
388X(A)Hearing and Determination of Cause
388k381Rulings on Weight and Sufficiency of Evidence
388k384Dismissal or nonsuit


Under the Rule of Civil Procedure which provides that in a bench trial, the court may grant a motion to dismiss at the close of the plaintiff’s case either as a matter of law or a matter of fact, a dismissal is proper if there is no evidence, or reasonable inferences therefrom, that would support a verdict for the plaintiff. CR 41(b)(3).
9 Cases that cite this headnote



[2]

Appeal and ErrorTaking Case or Question from Jury;  Judgment as a Matter of Law
Appeal and ErrorDismissal and nonsuit in general


30Appeal and Error
30XVIReview
30XVI(D)Scope and Extent of Review
30XVI(D)14Taking Case or Question from Jury;  Judgment as a Matter of Law
30k3561In general
(Formerly 30k893(1))
30Appeal and Error
30XVIReview
30XVI(F)Presumptions and Burdens on Review
30XVI(F)2Particular Matters and Rulings
30k3889Dismissal and nonsuit in general
(Formerly 30k895(2))


If the trial court dismisses the case as a matter of law after the plaintiff rests, under the Rule of Civil Procedure which provides that in a bench trial, the court may grant a motion to dismiss at the close of the plaintiff’s case either as a matter of law or a matter of fact, review is de novo and the question on appeal is whether the plaintiff presented a prima facie case, viewing the evidence in the light most favorable to the plaintiff. CR 41(b)(3).
12 Cases that cite this headnote



[3]

Appeal and ErrorTaking Case or Question from Jury;  Judgment as a Matter of Law


30Appeal and Error
30XVIReview
30XVI(D)Scope and Extent of Review
30XVI(D)14Taking Case or Question from Jury;  Judgment as a Matter of Law
30k3561In general
(Formerly 30k866(1))


If the trial court acts as a fact-finder, in dismissing a case under the Rule of Civil Procedure which provides that in a bench trial, the court may grant a motion to dismiss at the close of the plaintiff’s case either as a matter of law or a matter of fact, appellate review is limited to whether substantial evidence supports the trial court’s findings and whether the findings support its conclusions of law.
10 Cases that cite this headnote



[4]

Landlord and TenantNature and extent of tenancy


233Landlord and Tenant
233XIMobile Homes and Mobile Home Parks
233k2103Nature and extent of tenancy
(Formerly 233k371)


The Manufactured/Mobile Home Landlord-Tenant Act (MHLTA), governs the legal rights, remedies, and obligations between mobile home park landlords and tenants. West’s RCWA 59.20.080.
1 Case that cites this headnote



[5]

Landlord and TenantPurpose
Landlord and TenantGrounds in general


233Landlord and Tenant
233XIMobile Homes and Mobile Home Parks
233k2091Constitutions, Statutes, and Ordinances
233k2093Purpose
(Formerly 233k371)
233Landlord and Tenant
233XIMobile Homes and Mobile Home Parks
233k2121Reentry and Recovery of Possession;  Termination
233k2123Grounds in general
(Formerly 233k389)


The legislative purpose in enacting the Manufactured/Mobile Home Landlord-Tenant Act (MHLTA) was to regulate and protect mobile home owners by providing a stable, long-term tenancy for home owners living in a mobile home park; accordingly, the MHLTA modifies and limits the grounds upon which a landlord may terminate a mobile home park tenancy. West’s RCWA 59.20.080.
1 Case that cites this headnote



[6]

Landlord and TenantStatutory provisions


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1782Statutory provisions
(Formerly 233k289)


While the unlawful detainer statute is designed to provide expeditious, summary proceedings, it is in derogation of the common law and must be strictly construed in favor of the tenant. West’s RCWA 59.12.010 et seq.




[7]

Forcible Entry and DetainerPresumptions and burden of proof


179Forcible Entry and Detainer
179ICivil Liability
179k29Evidence
179k29(1)Presumptions and burden of proof


The burden is upon the plaintiff in an unlawful detainer action to prove his or her right to possession by a preponderance of the evidence, because the possession of a tenant is originally lawful, and is so presumed until the contrary appears. West’s RCWA 59.12.010 et seq.




[8]

Landlord and TenantReentry and Recovery of Possession;  Termination


233Landlord and Tenant
233XIMobile Homes and Mobile Home Parks
233k2121Reentry and Recovery of Possession;  Termination
233k2122In general
(Formerly 233k388.1)


Provisions of the Manufactured/Mobile Home Landlord-Tenant Act (MHLTA) that are the functional equivalent of an unlawful detainer statute must be construed strictly in favor of the tenant. West’s RCWA 59.12.010 et seq., 59.20.080(1)(h).
1 Case that cites this headnote



[9]

Landlord and TenantAcceptance of rent


233Landlord and Tenant
233IVParticular Kinds of Tenancies and Attributes Thereof
233IV(F)Termination
233IV(F)4Waiver of Forfeiture
233k941Acceptance of rent
(Formerly 233k112(2))


If a landlord accepts rent with knowledge of a prior breach of a lease covenant, the landlord waives the right to evict based on that breach.




[10]

Landlord and TenantReentry and Recovery of Possession;  Termination
Landlord and TenantDefenses;  retaliatory eviction


233Landlord and Tenant
233XIMobile Homes and Mobile Home Parks
233k2121Reentry and Recovery of Possession;  Termination
233k2122In general
(Formerly 233k388.1)
233Landlord and Tenant
233XIMobile Homes and Mobile Home Parks
233k2121Reentry and Recovery of Possession;  Termination
233k2125Defenses;  retaliatory eviction
(Formerly 233k391)


Mobile home park waived its right as a landlord to declare a lease forfeiture and to file an unlawful detainer action against a tenant, as authorized by the Manufactured/Mobile Home Landlord-Tenant Act (MHLTA), where it accepted rent in full from the tenant after service of its third 15 day notice within 12 months to tenant to comply with park rules or vacate. West’s RCWA 59.12.010 et seq., 59.20.080(1)(h).
1 Case that cites this headnote



Attorneys and Law Firms
**938 Carl Nathan Warring, Warring Law Firm PS, Moses Lake, WA, for Appellant.
Judith A. Lurie, Northwest Justice Project, Wenatchee, WA, for Respondent.
Opinion

KULIK, A.C.J.

*759 ¶ 1 Harvest Manor Estates, a mobile home park, filed this unlawful detainer action in September 2007, alleging it had served Rick Padilla with more than three notices, during a 12-month period, to comply with park rules or to vacate because of alleged rule violations. We affirm the trial court’s dismissal of the action because Harvest Manor waived its statutory right to evict Mr. Padilla under the Manufactured/Mobile Home Landlord–Tenant Act (MHLTA), chapter 59.20 RCW, by continuing to accept rent from Mr. Padilla after serving three 15–day notices.



**939 FACTS
¶ 2 Commonwealth Real Estate Services doing business as Harvest Manor Estates owns a manufactured/mobile home park located in Moses Lake, Grant County, Washington.

¶ 3 Rick Padilla began residing at Harvest Manor in 1984. After residing on lot 153 for approximately 14 years, Mr. Padilla purchased an older, single-wide mobile home installed on lot 5 and moved there. Mr. Padilla alleged that when he purchased the home on lot 5, both the home and lot were in poor condition. Mr. Padilla claims that over the *760 years, he made significant improvements to his home and the lot, including repairing and replacing the roof, the siding, and the decks.

¶ 4 On September 6, 2007, Harvest Manor filed this unlawful detainer action, seeking to terminate Mr. Padilla’s tenancy under RCW 59.20.080(1)(h), a provision of the MHLTA. Under RCW 59.20.080(1)(h), it is grounds for termination of a mobile home park tenancy: “[i]f the landlord serves a tenant three fifteen-day notices within a twelve-month period to comply or vacate for failure to comply with the material terms of the rental agreement or park rules.”

¶ 5 Harvest Manor alleged in the complaint that it was entitled to evict Mr. Padilla because in a 12–month period it had served him with three 15–day notices to comply with park rules or to vacate the premises.

¶ 6 The unlawful detainer action was based on three specific notices, each of which was attached to the complaint. The notices were provided to Mr. Padilla on November 20, 2006, June 21, 2007, and July 23, 2007.1 Each notice demanded that Mr. Padilla comply with the park rules and regulations to properly maintain the mobile home and to comply with the rules with regard to a shed and proper storage of items around the mobile home site. Mr. Padilla denied he was in violation of the park rules, and, in the alternative, he denied that he failed to comply with the park rules within 15 days of the receipt of each notice.

1

Although it was not mentioned in the complaint, the record shows that a fourth 15–day notice within the 12–month period was served on Mr. Padilla on September 5, 2006. For purposes of this action, the July 23, 2007 notice to comply or vacate is treated as the third notice.


¶ 7 Harvest Manor concedes that it continued to accept rent from Mr. Padilla when it became due each month after service of the three 15–day notices, including August 2007. Further, Harvest Manor admits it accepted rent on September 5, 2007, one day before it filed the unlawful detainer action, and each month thereafter.

*761 ¶ 8 At trial on April 25, 2008, Harvest Manor presented and rested its case, but before Mr. Padilla concluded his case, the trial was continued to a later date. On May 21, Mr. Padilla filed a motion for involuntary dismissal pursuant to CR 41(b)(3). Mr. Padilla argued that the matter should be dismissed because Harvest Manor waived its right to evict under RCW 59.20.080(1)(h) by continuing to accept rent after issuing the third 15–day notice to comply or vacate.

¶ 9 The court concluded as a matter of law that “by continuing to accept rental payments in full from [Mr. Padilla] after service of the July 23, 2007 notice to comply or vacate, [Harvest Manor] waived its right to declare a lease forfeiture, and waived its right to file an unlawful detainer action.” Clerk’s Papers (CP) at 46. Consequently, the trial court granted Mr. Padilla’s motion and dismissed Harvest Manor’s action with prejudice. This appeal followed.



ANALYSIS
¶ 10 This appeal involves the application of the waiver doctrine to the MHLTA. The single issue raised by this appeal is whether the trial court erred by ruling that Harvest Manor waived its right to seek termination of Mr. Padilla’s tenancy under RCW 59.20.080(1)(h) by accepting rent after service of the July 23, 2007 notice to comply or vacate. Harvest Manor argues that the court’s application of the waiver doctrine to this case was error and interferes with a landlord’s ability to terminate the tenancy of a mobile home tenant who repeatedly violates **940 the terms of his or her lease and/or the park rules and regulations.

¶ 11 Prior to the close of trial, Mr. Padilla brought a motion for involuntary dismissal pursuant to CR 41(b)(3), arguing that upon the facts and the law, Harvest Manor could not show a right to relief. Mr. Padilla argued that Harvest Manor waived its right to evict him through the unlawful detainer procedure because it continued to accept full monthly rental payments from him after service of the third of the three notices supporting eviction action. The *762 trial court agreed, and an order of involuntary dismissal was entered on July 24, 2008.

[1] [2] [3] ¶ 12 CR 41(b)(3) provides that in a bench trial, the court may grant a motion to dismiss at the close of the plaintiff’s case either as a matter of law or a matter of fact. Under CR 41(b)(3), dismissal is proper “if there is no evidence, or reasonable inferences therefrom, that would support a verdict for the plaintiff.” Willis v. Simpson Inv. Co., 79 Wash.App. 405, 410, 902 P.2d 1263 (1995). If the trial court dismisses the case as a matter of law after the plaintiff rests, “review is de novo and the question on appeal is whether the plaintiff presented a prima facie case, viewing the evidence in the light most favorable to the plaintiff. But if the trial court acts as a fact-finder, appellate review is limited to whether substantial evidence supports the trial court’s findings and whether the findings support its conclusions of law.” In re Dependency of Schermer, 161 Wash.2d 927, 939–40, 169 P.3d 452 (2007).

[4] [5] ¶ 13 In Washington, the MHLTA, governs the legal rights, remedies, and obligations between mobile home park landlords and tenants. Little Mountain Estates Tenants Ass’n v. Little Mountain Estates MHC, LLC, 146 Wash.App. 546, 550, 192 P.3d 378 (2008). “The legislative purpose in enacting the MHLTA was to regulate and protect mobile home owners by providing a stable, long-term tenancy for home owners living in a mobile home park.” Id. at 558, 192 P.3d 378. Accordingly, the MHLTA modifies and limits the grounds upon which a landlord may terminate a mobile home park tenancy.

¶ 14 Specifically, the MHLTA provides that a “landlord shall not terminate or fail to renew a tenancy of a tenant or the occupancy of an occupant, of whatever duration” except for one or more of the 13 reasons set forth in RCW 59.20.080(1)(a)-(m). RCW 59.20.080(1). Under subsection (1)(h), a landlord may terminate a mobile home tenancy “[i]f the landlord serves a tenant three fifteen-day notices within a twelve-month period to comply or vacate for failure *763 to comply with the material terms of the rental agreement or park rules.”

¶ 15 Once the tenant is served with three 15–day notices to comply or vacate within one year, a landlord may commence an unlawful detainer action. The general unlawful detainer statute, chapter 59.12 RCW, provides a landlord with a statutory means to terminate a tenancy before the end of the rental term. The purpose of unlawful detainer under chapter 59.12 RCW is to provide landlords with a speedy, efficient procedure by which to evict a tenant and obtain possession of the premises after a breach by the tenant or for certain activities on the premises. Christensen v. Ellsworth, 162 Wash.2d 365, 375–76, 173 P.3d 228 (2007).

[6] [7] ¶ 16 “While chapter 59.12[RCW] is designed to provide expeditious, summary proceedings, it is in derogation of the common law and must be strictly construed in favor of the tenant.” Laffranchi v. Lim, 146 Wash.App. 376, 383, 190 P.3d 97 (2008) (footnote omitted). Moreover, the burden is upon the plaintiff in an unlawful detainer action to prove his or her right to possession by a preponderance of the evidence. Hous. Auth. of City of Pasco & Franklin County v. Pleasant, 126 Wash.App. 382, 392, 109 P.3d 422 (2005). “The possession of a tenant is originally lawful, and is so presumed until the contrary appears.” Duprey v. Donahoe, 52 Wash.2d 129, 135, 323 P.2d 903 (1958).

[8] ¶ 17 Initially, we reject Harvest Manor’s contention that RCW 59.20.080(1)(h) should be interpreted in a manner favorable to the landlord. Division One of this court explained that the provisions of RCW 59.20.080 are “the functional equivalent of an unlawful detainer statute” which courts “must construe ... strictly in favor of the tenant.” **941 Hartson P’ship v. Goodwin, 99 Wash.App. 227, 235–36, 991 P.2d 1211 (2000). It follows that the same rules of strict construction in favor of tenants that apply to chapter 59.12 RCW unlawful detainer actions also apply to mobile home tenancies governed by the MHLTA.

[9] ¶ 18 “Certain rules of law with relation to the right of forfeiture under a lease are well established.” Wilson v. *764 Daniels, 31 Wash.2d 633, 639, 198 P.2d 496 (1948). “The well established rule in Washington is that if a landlord accepts rent with knowledge of a prior breach of a lease covenant, the landlord waives the right to evict based on that breach.” Hous. Res. Group v. Price, 92 Wash.App. 394, 401–02, 958 P.2d 327 (1998) (citing Signal Oil Co. v. Stebick, 40 Wash.2d 599, 603–04, 245 P.2d 217 (1952)).

¶ 19 Harvest Manor argues that to apply the doctrine of waiver to the MHLTA makes it impossible for a landlord to evict a tenant pursuant to RCW 59.20.080(1)(h) because the landlord would have to stop accepting rent from the tenant once the first notice is served. Harvest Manor contends that applying the waiver principle to RCW 59.20.080(1)(h) “effectively removes it from the MHLTA.” Br. of Appellant at 6. Harvest Manor claims that the concept of requiring an accumulation of violations to support a termination of the tenancy is “contrary to the theory of a waiver of the very violations that must be accumulated. Id. consequently, Harvest Manor argues that the legislature did not intend for it to forgo rent for one year on the off chance Mr. Padilla might again violate some provision of the lease or the park rules or risk waiver.

¶ 20 Harvest Manor’s argument is unpersuasive and misconstrues the trial court’s ruling. The issue of whether or not Harvest Manor waived its right to evict Mr. Padilla by accepting rent after service of the first and/or the second notices is not before this court. The trial court did not decide that in order to avoid waiving its right to evict Mr. Padilla, Harvest Manor would have had to forgo accepting rent after service of the first notice, and again after service of the second notice, as Harvest Manor appears to argue.

[10] ¶ 21 Rather, the order for involuntary dismissal was entered specifically on the undisputed fact that Harvest Manor accepted rent in full after service of the July 23, 2007 notice to comply or vacate, which was the third notice served within a 12–month period. The trial court made a narrow ruling, holding “as a matter of law that by continuing to accept rental payments in full from [Mr. Padilla] after *765 service of the July 23, 2007 notice to comply or vacate, [Harvest Manor] waived its right to declare a lease forfeiture, and waived its right to file an unlawful detainer action.” CP at 46.

¶ 22 Because it is undisputed that Harvest Manor continued to accept Mr. Padilla’s rent after service of the third of three 15–day notices, judgment was properly granted dismissing the unlawful detainer action as a matter of law. Wilson, 31 Wash.2d at 639, 198 P.2d 496. Accordingly, we affirm the trial court.

¶ 23 Attorney Fees. Harvest Manor seeks attorney fees on appeal pursuant to RAP 18.1 and RCW 59.20.110. A party is entitled to attorney fees on appeal if a contract, statute, or recognized ground of equity permits recovery of attorney fees at trial and the party is the substantially prevailing party. Dayton v. Farmers Ins. Group, 124 Wash.2d 277, 280, 876 P.2d 896 (1994). Because Harvest Manor is not a prevailing party, we deny its request for attorney fees.

WE CONCUR: BROWN and KORSMO, JJ.
All Citations
149 Wash.App. 757, 205 P.3d 937
End of Document

© 2024 Thomson Reuters. No claim to original U.S. Government Works.
