#+title:      Chapter 03.01: The Rules of the Game
#+date:       [2024-08-20 Tue 18:47]
#+filetags:   :er611:evidence:evidlaw:objections:
#+identifier: 20240820T184712

* 3.01: The Rules of the Game

Objections to the FORM of the question or answer are *rules about the conduct of the trial*

They relate to how things are done (not the validity of evidence)

Most good trial lawyers avoid making such objections, unless they believe that the objection will influence the effectiveness with which either the examiner or the witness is able to relate to the jurors.

The trial lawyer uses the objections to the form of the question to influence the flow of the information to the jurors.

"How" the information is presented can be as influential as "what" the information is.

Trial results come from what is heard and seen.

** Rule 611
:PROPERTIES:
:CUSTOM_ID: h:278B53FF-D791-4410-8B12-21AA215D1B34
:END:
Objections to the form of the question or answer ask the judge to exercise discretion provided by Rule 611 to control the mode of questioning witnesses.

*** (a) Control by Court.

The court shall exercise reasonable control over the mode and order of
interrogating witnesses and presenting evidence so as to (1) make the
interrogation and presentation effective for the ascertainment of the
truth, (2) avoid needless consumption of time, and (3) protect
witnesses from harassment or undue embarrassment.

*** (b) Scope of Cross Examination.

Cross examination should be limited to the subject matter of the
direct examination and matters affecting the credibility of the
witness. The court may, in the exercise of discretion, permit inquiry
into additional matters as if on direct examination.

*** (c) Leading Questions

Leading questions should not be used on the direct examination of a
witness except as may be necessary to develop the witness'
testimony. Ordinarily leading questions should be permitted on cross
examination. When a party calls a hostile witness, an adverse party,
or a witness identified with an adverse party, interrogation may be by
leading questions.
