#+title:      Unlawful Detainer Measure of Damages for Wrongful Eviction
#+date:       [2024-02-13 Tue 10:37]
#+filetags:   :damages:eviction:measure:rlta:ud:wrongful:
#+identifier: 20240213T103748

* Measure of Damages for Wrongful Eviction

** Propriety of Court's Damages Award.
A wrongfully evicted tenant is entitled to recover all damages that
reasonably flowed from the landlord's wrongful act, including the
expenses of moving.
- Iverson v. Marine Bancorporation, 86 Wash.2d 562, 565, 546 P.2d 454 (1976).


The party seeking damages must prove loss as a result of the other
party's conduct by competent evidence in the record.
- Id.; ESCA Corp. v. KPMG Peat Marwick, 86 Wash.App. 628, 639, 939
  P.2d 1228 (1997), aff'd, 135 Wash.2d 820, 959 P.2d 651 (1998).


- Triune Family Charitable Remainder Unitrust v. Pfeifer, 157 Wn. App. 1045 (2010) [NOT PUBLISHED]


** Amount of Damages for Wrongful Eviciton

The parties stipulated to Ms. Pfeifer's damages in the amount of
$1,311 for her security deposit and moving and storage expenses—after
a $286 offset to Triune for the unsubsidized portion of her rent for
July and August 2008. The court also awarded Ms. Pfeifer costs of
$522.19, and $120.12 in prejudgment interest. None of these amounts
are challenged on appeal.


- Triune Family Charitable Remainder Unitrust v. Pfeifer, 157 Wn. App. 1045 (2010) [NOT PUBLISHED]

** Requirement of a Bond Prior to Eviction

Here, the trial court cited RCW 59.18.380 as a basis for awarding
damages to Ms. Pfeifer. The statute requires the landlord to post bond
to secure payment of the tenant's costs and damages sustained by
reason of a wrongful writ of restitution:

#+begin_quote
[B]efore any writ shall issue prior to final judgment the plaintiff
shall execute to the defendant and file in the court a bond in such
sum as the court may order, with sufficient surety to be approved by
the clerk, conditioned that the plaintiff will prosecute his action
without delay, and will pay all costs that may be adjudged to the
defendant, and all damages which he may sustain by reason of the writ
of restitution having been issued, should the same be wrongfully sued
out.
#+end_quote
- Former RCW 59.18.380 (1973) (emphasis added).


- Triune Family Charitable Remainder Unitrust v. Pfeifer, 157 Wn. App. 1045 (2010) [NOT PUBLISHED]
