#+title:      Wrongful Eviction
#+date:       [2024-02-13 Tue 11:14]
#+filetags:   :eviction:rlta:ud:wrongful:
#+identifier: 20240213T111455

* Wrongful Eviction

RCW 59.18.650(4)

(4) A landlord who removes a tenant or causes a tenant to be removed
from a dwelling in any way in violation of this section is liable to
the tenant for wrongful eviction, and the tenant prevailing in such an
action is entitled to the greater of their economic and noneconomic
damages or three times the monthly rent of the dwelling at issue, and
reasonable attorneys' fees and court costs.

* Cause of Action for Wrongful Eviction

And an illegally evicted tenant can recover money damages. See, e.g.,
RCW 59.18.650(4); RCW 59.18.380; RCW 59.18.290(1).

- Hernandez v. Francis No. 39548-1-III [UNPUBLISHED]

* WAIT Self-Help Eviction                                                       :ATTACH:
SCHEDULED: <2026-03-31 Tue>
:PROPERTIES:
:DIR:      ~/.local/share/notes/law/documents/training/Tactics to Respond to Self-Help Eviction 2026-03-05/
:WATCHED:  [2026-03-16 10:00]
:CLE-CREDIT: Pending
:END:
:LOGBOOK:
- State "WAIT"       from              [2026-03-16 Mon 11:06] \\
  Waiting for CLE credit to be approved on the WSBA CLE website.  Got back and check.
:END:

[HTF] HTF - Tactics to Respond to Self-Help Eviction

Laura Parmenter via groups.nwjustice.org <laura.parmenter=nwjustice.org@groups.nwjustice.org>
Attachments
Thu, Mar 12, 2:52 PM (4 days ago)
to Housing, NJP

Hello, everyone,

The recording of our recent training, “Tactics to Respond to Self‑Help
Evictions,” is now available on both SharePoint and Vimeo. You can
access the session using the links provided below.  All training
materials are also attached to this email.

If you attended the live training, please make sure to submit your attendance using this link: Attendance Link.

For those who will be viewing the training after the fact, the instructions for submitting your attendance will be included in the video’s description on Vimeo. Please note that those instructions are not yet updated; I will revise them as soon as I receive the activity ID from WSBA.

Thank you for your patience, and please let me know if you have any questions or need assistance accessing the materials.

Vimeo: https://vimeo.com/1173077863?share=copy&fl=sv&fe=ci

SharePoint:  ​Clipchamp icon HTF Tactics to Respond to Self-help Evictions.mp4
