#+title:      TITLE 9 - Record on Review
#+date:       [2024-08-01 Thu 10:46]
#+filetags:   :rap:record:review:
#+identifier: 20240801T104634

* RAP 9.1 - COMPOSITION OF RECORD ON REVIEW

** (a) Generally

The "record on review" may consist of
- (1) a "report of proceedings",
- (2) "clerk's papers",
- (3) exhibits, and
- (4) a certified record of administrative adjudicative proceedings.


** (b) Report of Proceedings.

The report of any oral proceeding *MUST* be transcribed in the form of a
typewritten report of proceedings.

The report of proceedings may take the form of
- a "verbatim report of proceedings" as provided in rule 9.2,
- a "narrative report of proceedings" as provided in rule 9.3, or
- an "agreed report of proceedings" as provided in rule 9.4.


** (c) Clerk's Papers.

The clerk's papers include the

- pleadings,
- orders, and
- other papers

filed with the clerk of the trial court.


** (d) Avoid Duplication.

Material appearing in one part of the record on review should not be
duplicated in another part of the record on review.


** (e)  Review of Superior Court Decision on Review of Decision of Court of Limited Jurisdiction.

Upon review of a superior court decision reviewing a decision of a
court of limited jurisdiction pursuant to rule 2.3(d), the record
shall consist of the record of proceedings and the transcript of
electronic record as defined in RALJ 6.1 and 6.3.1. When requested by
the appellate court, the superior court shall transmit the original
record of proceedings and transcript of electronic record as was
considered by the superior court on the appeal from the decision of
the court of limited jurisdiction.

* RAP 9.2 - VERBATIM REPORT OF PROCEEDINGS

** (a) Transcription and Statement of Arrangements.
:PROPERTIES:
:CUSTOM_ID: h:E02408B6-FC22-4DFC-AD66-5698CBC45806
:END:

If the party seeking review intends to provide a verbatim report of
proceedings,
- the party SHOULD arrange for
  - transcription of
  - and
  - payment for
  - an original and one copy
  - of
    - the verbatim report of proceedings
  - _within 30 days_
  - /after/
  - the notice of appeal was filed or discretionary review was granted.

The party seeking review *MUST* file with the appellate court and serve
on all parties of record and all named court reporters or authorized
transcriptionists a statement that arrangements have been made for the
transcription of the report and file proof of service with the
appellate court.

The statement *MUST* be filed
- _within 30 days_
- /after/
- the notice of appeal was filed or discretionary review was granted.

The party *MUST* indicate
- the date that the report of proceedings was ordered,
- the financial arrangements which have been made for payment of transcription costs,
- the name of each court reporter or authorized transcriptionist preparing a verbatim report of proceedings,
- the hearing dates, and
- the trial court judge.

If the party seeking review does not intend to provide a verbatim
report of proceedings,
- a statement to that effect *SHOULD* be filed
- *in lieu of a statement of arrangements*
- _within 30 days_
- /after/
- the notice of appeal was filed or discretionary review was granted and served on all parties of record.

** (b) Content.

A party should arrange for the transcription of all those portions of
the verbatim report of proceedings necessary to present the issues
raised on review.

A verbatim report of proceedings provided at public expense should not
include the voir dire examination or opening statements unless
appellate counsel has reason to believe those sections are relevant to
the appeal or they are requested by the client for preparing a
statement of additional grounds.

If the party seeking review intends to urge that a verdict or finding
of fact is not supported by the evidence, the party should include in
the record all evidence relevant to the disputed verdict or
finding.

If the party seeking review intends to urge that the court erred in
giving or failing to give an instruction, the party should include in
the record all of the instructions given, the relevant instructions
proposed, the party's objections to the instructions given, and the
court's ruling on the objections.

Unless the parties agree that a cost bill will not be filed under RAP
14.2, the party claiming indigency on appeal should include in the
record all portions of the trial court proceedings relating to all
trial court decisions on indigency and relating to any trial court
decisions on the offender’s current or likely future ability to pay
discretionary legal financial obligations.

** (c) Notice of Partial Report of Proceedings and Issues.

If a party seeking review arranges for less than all of the verbatim
report of proceedings, the party should include in the statement of
arrangements a statement of the issues the party intends to present on
review.

Any other party who wishes to add to the verbatim report of
proceedings should within 10 days after service of the statement of
arrangements file and serve on all other parties and the court
reporter or authorized transcriptionist a supplemental statement of
arrangements which designates the additional parts of the verbatim
report of proceedings and file proof of service with the appellate
court.

If the party seeking review refuses to provide the additional parts of
the verbatim report of proceedings, the party seeking the additional
parts may provide them at the party's own expense or apply to the
trial court for an order requiring the party seeking review to pay for
the additional parts of the verbatim report of proceedings.

** (d) Payment of Expenses.

If a party either fails to make arrangements for payment of the costs
of the verbatim report of proceedings at the time the verbatim report
of proceedings is ordered or fails to make payment of completed
verbatim report of proceedings and causes case delay, the party may be
subject to sanctions as provided in rule 18.9.

** (e) Title Page and Table of Contents.

The court reporter or other authorized transcriber shall include at
the beginning of each volume of the verbatim report of proceedings a
title page and a table of contents.

- (1) The *title page* should include the following:

  - (A) Case name,
  - (B) Trial court and appellate cause numbers,
  - (C) Date(s) of hearings,
  - (D) Trial court judge(s),
  - (E) Names of attorneys at trial,
  - (F) Name, business address and telephone number of each court reporter or other authorized transcriber.

- (2) The *table of contents* shall follow the title page and shall indicate, under the headings listed below, the pages where the following appear:

  - (A) Proceedings. The beginning of each proceeding and the nature of that proceeding;
  - (B) Testimony. The testimony of each witness, the page where it begins, and the type of examination, i.e., direct, cross, re-direct, re-cross, and the page where the plaintiff rests and the defendant rests;
  - (C) Exhibits. The admission into evidence of exhibits and depositions;
  - (D) Argument. The pages where opening statements occur, except as otherwise provided in rule 9.2(b) for verbatim reports of proceedings provided at public expense, and the pages where closing arguments occur;
  - (E) Instructions. All instructions proposed and given. Any other events should be listed under a suitable heading which would help the reviewing court locate separate parts of the verbatim report of proceedings.
  - (F) Multiple Days. If a volume includes hearings from more than one day, there shall be a separate table of contents for each day.

** (f) Form.

*** (1) Generally

The verbatim report of proceedings shall be on 8 1/2- by 11-inch
paper.  Margins shall be lined 1 3/8 inches from the left and 5/8
inches from the right side of each page.  Indentations from the left
lined margin should be: 1 space for "Q" and "A"; 5 spaces for the body
of the testimony; 8 spaces for commencement of a paragraph; and 10
spaces for quoted authority.  Typing should be double spaced except
that comments by the reporter should be single spaced.  The page
should have 25 lines of type. Type must be pica type or its equivalent
with no more than 10 characters an inch.

**** (A) Witnesses Designated/Examination.

Indicate at the top or bottom of each page the name of the witness and
whether the examination is on direct, cross, re-direct, re-cross, or
rebuttal.

**** (B) Jury In/Out.

Indicate when the jury is present, when the jury leaves, and when the
jury returns.

**** (C) Bench/Side Bar Conferences.

Designate whether a bench/side bar conference is on or off the record.

**** (D) Chamber Conferences.

If the conference is recorded, note the presence or absence of persons
participating in chamber conferences.

**** (E) Speaker/Event Identification.

Identify speakers and events that occur throughout the proceedings in
capital letters centered on the appropriate line. For example:
recess/court reconvene; direct examination, cross examination,
re-direct examination, re-cross examination, plaintiff rests;
defendant’s evidence: direct examination, cross examination, re-direct
examination, re-cross examination, defense rests; instructions,
conference, closing arguments: for plaintiff, for defense, and
rebuttal.

*** (2) Volume and Pages

**** (A) [Pages numbered]

Pages in each volume of the verbatim report of proceedings shall be
numbered consecutively and be arranged in chronologic order by date of
hearing(s) requested in the statement of arrangements.

**** (B) [Page limit]

 Each volume of the verbatim report of proceedings shall include no
more than 250 pages. The page numbers in the first volume should start
with page 1 and continue to 250, as needed, regardless of how many
hearing dates are included in the volume. In the second volume of the
verbatim report of proceedings and subsequent volumes page numbers
should start with the next page number in sequence where the previous
volume ended. The volumes shall be either bound or fastened securely.

*** (3) Copies

The verbatim report of proceedings should be legible, clean and
reproducible.

* RAP 9.3 - NARRATIVE REPORT OF PROCEEDINGS

The party seeking review *MAY* prepare a *narrative report of
proceedings*.

A party preparing a narrative report *MUST* exercise the party's best
efforts to include
- a fair and accurate statement of
  - the occurrences in
- and
  - evidence introduced in
- the trial court material to the issues on review.

A /narrative report/ *SHOULD* be in the same form as a verbatim report, as
provided in rule 9.2(e) and (f).

If *any party* prepares a verbatim report of proceedings, that report
will be used as the report of proceedings for the review.

A narrative report of proceedings may be prepared if the court
reporter's notes or the electronic recording of the proceeding being
reviewed is lost or damaged.

* RAP 9.4 - AGREED REPORT OF PROCEEDINGS

The parties may prepare and sign an agreed report of proceedings
setting forth only so many of the facts averred and proved or sought
to be proved as are essential to the decision of the issues presented
for review.

The agreed report of proceedings must include only matters which were
actually before the trial court.

An agreed report of proceedings should be in the same form as a
verbatim report, as provided in rule 9.2(e) and (f).

An agreed report of proceedings may be prepared if the court
reporter's notes or the electronic recording of the proceeding being
reviewed is lost or damaged.

* RAP 9.5 - FILING AND SERVICE OF REPORT OF PROCEEDINGS—OBJECTIONS

** (a) Generally.
:PROPERTIES:
:CUSTOM_ID: h:7CA98895-F70B-42CB-ACE2-2D8F847037B9
:END:

The party seeking review *MUST* file *an agreed or narrative* report of
proceedings with the appellate court
- _within 60 days_
- after
- the *statement of arrangements* is _filed_.

The court reporter or authorized transcriptionist preparing a verbatim
report of proceedings MUST file it in the appellate court
- _within 60 days_
- after
  - the *statement of arrangements* is filed
- and
  - all named court reporters or authorized transcriptionists are served.

The court reporter or authorized transcriptionist SHALL promptly
notify all parties that the report of proceedings has been filed with
the appellate court, and shall provide a copy of the report of
proceedings to the party who arranged for the transcript.

*** (1) [A party filing a brief]

_A party filing a brief_ *MUST* promptly forward a copy of the verbatim
report of proceedings with a copy of the brief to the party with the
right to file the next brief. If more than one party has the right to
file the next brief, the parties must cooperate in the use of the
report of proceedings. The party who files the last brief should
return the copy of the report of proceedings to the party who paid for
it.

*** (2) [A searchable PDF electronic copy]

A searchable PDF electronic copy of the verbatim report of proceedings
shall be filed with the original verbatim report of proceedings, with
a copy provided to the party who caused the verbatim report of
proceedings to be filed. The report of proceedings may be
electronically filed with the appellate court in accordance with the
court’s filing procedures.

** (b) Additional Time for Filing and Service of Verbatim Report of Proceedings.

If a verbatim report of proceedings cannot be completed within 60 days
after the statement of arrangements is filed and served, the court
reporter or authorized transcriptionist shall, no later than 10 days
before the report of proceedings is due to be filed, submit an
affidavit to the party who ordered the report of proceedings stating
the reasons for the delay.

The party who requested the verbatim report of proceedings should move
for an extension of time from the appellate court.

The clerk will notify the parties of the action taken on the
motion.

Failure to timely file the verbatim report of proceedings and notice
of service may subject the court reporter or video transcriber or
authorized transcriptionist to sanctions as provided in rule 18.9.

** (c) Objections to Report of Proceedings

A party MAY serve and file *objections* to, and propose *amendments* to, a
/narrative report of proceedings/ or a /verbatim report of proceedings/
- within 10 days
- after
  - receipt of the report of proceedings
- or
  - receipt of the notice of filing of the report of proceedings with the
    appellate court.

If objections or amendments to the report of proceedings are served
and filed, any objections or proposed amendments must be heard by the
trial court judge before whom the proceedings were held for settlement
and approval, except objections to the form of a report of
proceedings, which shall be heard by motion in the appellate
court.

The court may direct court reporters or authorized transcriptionists
to pay for the expense of any modifications of the proposed report of
proceedings.

The motion procedure of the court deciding any objections shall be
used in settling the report of proceedings.

** (d) Substitute Judge May Settle Report of Proceedings

If the judge before whom the proceedings were held is for any reason
unable to promptly settle questions as provided in section (c),
another judge may act in the place of the judge before whom the
proceedings were held.

* RAP 9.6 - DESIGNATION OF CLERK'S PAPERS AND EXHIBITS

** (a) Generally.
:PROPERTIES:
:CUSTOM_ID: h:671D5AAB-FF3A-428A-82ED-9034375CDE4B
:END:

The party seeking review should, within *30 days* after the notice of
appeal is filed or discretionary review is granted,

- _serve_ on all other parties and
- _file_ with the trial court clerk

*a designation of those clerk's papers and exhibits*

the party wants the trial court clerk to transmit to the appellate court.

- A copy of the designation shall also be _filed with the appellate court clerk_.

Any party may supplement the designation of clerk's papers and
exhibits prior to or with the filing of the party's last
brief.

Thereafter, a party may supplement the designation only by order of
the appellate court, upon motion.

Each party is encouraged to designate only clerk's papers and exhibits
needed to review the issues presented to the appellate court

** (b) Designation and Contents.

*** (1)
The clerk's papers shall include, at a minimum:

**** (A) [Notice of Appeal]
the notice of appeal or the notice for discretionary review;

**** (B) [Complaint}]
the indictment, information, or complaint in a criminal case;

**** (C) [Complaint}]
the summons and complaint or case initiating petition in a civil case;

**** (D) [Order}]
any written order or ruling not attached to the notice of appeal, of
which a party seeks review;

**** (E) [Answer]
the final pretrial order, or the final complaint and answer or other
pleadings setting out the issues to be tried if the final pretrial
order does not set out those issues;

**** (F) [Written Opinion | Findings and Conclusions]
 any written opinion, findings of fact, or conclusions of law;

**** (G) [Jury Instructions]
 any jury instruction given or refused that presents an issue on
 appeal; and

**** (H) [Order Sealing Documents]
any order sealing documents if sealed documents have been designated;

**** (I) [Order of Indigency]
in a criminal case where a cost bill may be filed, any order
concerning the defendant’s indigency and current or likely future
ability to pay discretionary legal financial obligations.

*** (2) [Identification Required]
Each designation or supplement shall specify the full title of the
pleading, the date filed, and, in counties where subnumbers are used,
the clerk's subnumber.

*** (3) [List of Exhibits]
Each designation of exhibits shall include the trial court clerk's
list of exhibits and shall specify the exhibit number and the
description of the exhibit to be transmitted.

** (c) Format

*** (1) [Full Copies]
Full copies of all designated pleadings shall be included, unless the
trial court orders otherwise.

*** (2) [Sequential Numbering]
The trial court clerk shall number the papers sequentially from
beginning to end, including any supplemental clerk's papers,
regardless of which party designated them.

*** (3) [Reasonable Expenses]
The trial court clerk shall make available a copy of the clerk’s
papers transmitted to the appellate court to any party, upon payment
of the trial court clerk’s reasonable expenses. If the trial court
clerk generates the clerk’s papers in electronic format, the trial
court clerk shall make available to any party a copy of the clerk’s
papers in electronic format, upon payment of the trial court clerk’s
reasonable expenses.

*** [Form]

**** Caption
CLARK COUNTY NO.:
COURT OF APPEALS NO.:
THIS IS SUPPLEMENTAL [ ] YES [ ] NO

DESIGNATION OF CLERK'S PAPERS
(Clerk's Action Required)

**** Body
TO: Superior Court Clerk

Pursuant to RAP 9.6,.7, and .8, please prepare and transmit to the
Court of Appeals, Division II, the following Clerk’s Papers and
Exhibits:

|------------+-------------------+----------------|
| Sub Number | Title of Document | Date of Filing |
|------------+-------------------+----------------|
| .          |                   |                |
| .          |                   |                |
| .          |                   |                |
|------------+-------------------+----------------|
| Exhibit #  | Description       | Trial Date     |
| .          |                   |                |
| .          |                   |                |
| .          |                   |                |
|------------+-------------------+----------------|

A copy of this document has been filed with the Court of Appeals and
served on all parties of record.

**** Signature
DATED: _________________________________

________________________________________
Signature WSB NO.

**** Certificat of Service
I certify that on the _____ day of _______________, 20 ___, I
caused a true and correct copy of this Designation of Clerk’s
Papers to be served on the following in the manner indicated
below:

Counsel for [Party]
Name: [Name]
Address: [Address]
[ ] U.S Mail
[ ] Hand Delivery
[ ] Other:

By: _________________________________-
    Signature WSB NO.
* RAP 9.10 - CORRECTING OR SUPPLEMENTING RECORD

_If a party has made a good faith effort_ to provide those portions of
the record required by rule 9.2(b), the appellate court will not
ordinarily dismiss a review proceeding or affirm, reverse, or modify a
trial court decision or administrative adjudicative order certified
for direct review by the superior court because of the failure of the
party to provide the appellate court with a complete record of the
proceedings below.

_If the record is NOT sufficiently complete_ to permit a decision on the
merits of the issues presented for review, the appellate court may, on
its own initiative or on the motion of a party

- (1) direct the transmittal of additional clerk's papers and exhibits or administrative records and exhibits certified by the administrative agency, or

- (2) correct, or direct the supplementation or correction of, the
  report of proceedings.

The appellate court or trial court may impose sanctions as provided in
rule 18.9(a) as a condition to correcting or supplementing the record
on review.

The party directed or permitted to supplement the record on review
must file either a designation of clerk’s papers as provided in rule
9.6 or a statement of arrangements as provided in rule 9.2 within the
time set by the appellate court.

* RAP 9.11 - ADDITIONAL EVIDENCE ON REVIEW

** (a) Remedy Limited.

The appellate court may direct that additional evidence on the merits
of the case be taken before the decision of a case on review if:

- (1) additional proof of facts is needed to fairly resolve the issues
  on review,

- (2) the additional evidence would probably change the decision being
  reviewed,

- (3) it is equitable to excuse a party's failure to present the
  evidence to the trial court,

- (4) the remedy available to a party through postjudgment motions in
  the trial court is inadequate or unnecessarily expensive,

- (5) the appellate court remedy of granting a new trial is inadequate
  or unnecessarily expensive, and

- (6) it would be inequitable to decide the case solely on the
  evidence already taken in the trial court.

** (b) Where Taken.

The appellate court will ordinarily direct the trial court to take
additional evidence and find the facts based on that evidence.

* RAP 9.12 - SPECIAL RULE FOR ORDER ON SUMMARY JUDGMENT

On review of an order granting or denying a motion for summary
judgment the appellate court will consider only evidence and issues
called to the attention of the trial court.

The order granting or denying the motion for summary judgment shall
designate the documents and other evidence called to the attention of
the trial court before the order on summary judgment was
entered.

Documents or other evidence called to the attention of the trial court
but not designated in the order shall be made a part of the record by
supplemental order of the trial court or by stipulation of counsel.

* RAP 9.13 - REVIEW OF DECISION RELATING TO RECORD

A party may object to a trial court decision relating to the record by
motion in the appellate court.
