#+title:      Subject Jurisdiction in Unlawful Detainer Cases
#+date:       [2024-08-30 Fri 11:44]
#+filetags:   :jurisdiction:subject:ud:
#+identifier: 20240830T114434

* MHM & F, LLC v. Pryor, 168 Wash.App. 451 (2012)
¶ 18 We recognize our previous decisions support Prior Junior's argument that a properly worded summons is necessary to “confer” subject matter jurisdiction upon a superior court. See, e.g., Truly v. Heuft, 138 Wash.App. 913, 918–23, 158 P.3d 1276 (2007). We also acknowledge a previous decision holding that a superior court lacks subject matter jurisdiction in an unlawful detainer action where a necessary party is not joined as a party. Laffranchi v. Lim, 146 Wash.App. 376, 383–84, 190 P.3d 97 (2008). By characterizing these issues as jurisdictional, Truly and Laffranchi permit them to be raised for the first time on appeal. But those cases are incorrectly reasoned on that point. Those cases did not consider article IV, section 6 of our constitution.
- MHM & F, LLC v. Pryor, 168 Wn. App. 451, 459, 277 P.3d 62, 66 (2012)


¶ 19 In recent cases where our appellate courts have considered the constitutional grant of subject matter jurisdiction to the superior courts, they have accorded it the centrality that it deserves. Our Supreme Court has held that article IV, section 6 is dispositive and has overruled precedents that erroneously classify the superior court's jurisdiction as statutory. See State v. Posey, 174 Wash.2d 131, 272 P.3d 840, 842–45 (2012); ZDI Gaming, Inc. v. State ex rel. Washington State Gambling Comm'n, 173 Wash.2d 608, 616–18, 268 P.3d 929 (2012); Williams v. Leone & Keeble, Inc., 171 Wash.2d 726, 730, 734, 254 P.3d 818 (2011); Dougherty v. Dep't of Labor & Indus., 150 Wash.2d 310, 316–20, 76 P.3d 1183 (2003); *460 Young v. Clark, 149 Wash.2d 130, 133–34, 65 P.3d 1192 (2003); Shoop v. Kittitas County, 149 Wash.2d 29, 38, 65 P.3d 1194 (2003); Marley v. Dep't of Labor & Indus., 125 Wash.2d 533, 541, 886 P.2d 189 (1994). Truly and Laffranchi exemplify the problem **67 identified by our Supreme Court in Marley, where the court observed that the improvident and inconsistent use of the term “subject matter jurisdiction” has caused it to be confused with a court's authority to rule in a particular manner. Marley, 125 Wash.2d at 539, 886 P.2d 189.
- MHM & F, LLC v. Pryor, 168 Wn. App. 451, 459–60, 277 P.3d 62, 66–67 (2012)


¶ 20 Whether the superior court ruled correctly or incorrectly in this particular case, it did not lack subject matter jurisdiction. The court's subject matter jurisdiction in cases involving the title or possession of real property is expressly granted by the state constitution and has not been “vested exclusively in some other court.” WASH. CONST. art. IV, sec. 6. We narrowly construe exceptions to the constitution's jurisdictional grant. Cole v. Harveyland, LLC, 163 Wash.App. 199, 206, 258 P.3d 70, (2011). Thus, it is incorrect to say that the court acquires subject matter jurisdiction from an action taken by a party or that it loses subject matter jurisdiction as the result of a party's failure to act. Bin, 163 Wash.App. at 376, 260 P.3d 900.
- MHM & F, LLC v. Pryor, 168 Wn. App. 451, 460, 277 P.3d 62, 67 (2012)


¶ 21 If the type of controversy is within the superior court's subject matter jurisdiction, as it is here, “ ‘then all other defects or errors go to something other than subject matter jurisdiction.” ’ Marley, 125 Wash.2d at 539, 886 P.2d 189 (quoting ROBERT J. MARTINEAU, Subject Matter Jurisdiction as a New Issue on Appeal: Reining in an Unruly Horse, 1988 B.Y.U. L.REV. 1, 28. Here, the alleged errors go to statutory interpretation (_Does an applicable statute require that the summons refer to a facsimile number, and if so, does the absence of such a reference require that the action be dismissed?_) and to matters of procedure (Was the Association a necessary party, and if so, could the case proceed in its absence?). Pryor Junior could have litigated these issues in the trial court, but he failed to do so. Because the trial court's subject matter jurisdiction did not depend on the wording of the summons or the joinder of parties, Pryor *461 Junior may not assert lack of subject matter jurisdiction as an excuse for avoiding his responsibility to preserve error. These are issues on which the trial court was not asked to make a ruling, and we decline to address them.14
- MHM & F, LLC v. Pryor, 168 Wn. App. 451, 460–61, 277 P.3d 62, 67 (2012)
