#+title:      4 Wash. App. 2d 8 Castellon v. Rodriguez (2018)
#+date:       [2024-02-03 Sat 12:39]
#+filetags:   :case:jurisdiction:rlta:service:
#+identifier: 20240203T123942

* BRIEF

* CASE

Castellon v. Rodriguez
Court of Appeals of Washington, Division 3. | June 5, 2018 | 4 Wash.App.2d 8 | 418 P.3d 804

Document Details

Outline
Synopsis
West Headnotes
Attorneys and Law Firms
PUBLISHED OPINION
All Citations

washington Citation:

Castellon v. Rodriguez, 4 Wn. App. 2d 8, 418 P.3d 804 (2018)

All Citations:

4 Wash.App.2d 8, 418 P.3d 804

Search Details

Jurisdiction:

Washington

Delivery Details

Date:

February 3, 2024 at 2:33 PM

Delivered By:

Lincoln Harvey

Client ID:

DISMISSAL

Status Icons:



Inline KeyCite:

Inline KeyCite completed successfully.




4 Wash.App.2d 8
Court of Appeals of Washington, Division 3.
Luz CASTELLON and Juan Castellon, Respondents,
v.
Sergio RODRIGUEZ, Appellant,
Jane Doe Rodriguez, and All Other Occupants, Defendants.
No. 35137-8-III
|
FILED JUNE 5, 2018
Synopsis
Background: Landlords brought an unlawful detainer action against tenant and tenant’s wife. The Superior Court, Walla Walla County, M. Scott Wolfram, J., entered judgment for landlords and subsequently denied tenant’s motion to vacate the judgment, quash writ of garnishment, and dismiss landlords’ complaint. Tenant appealed.

Holdings: The Court of Appeals, Pennell, J., held that:

[1] tenant did not waive his personal jurisdiction defense;

[2] trial court did not have personal jurisdiction over tenant;

[3] trial court had personal jurisdiction of tenant’s marital community; but

[4] trial court lacked subject matter jurisdiction to enter money judgment and issue writ of garnishment.

Vacated and remanded with instructions.

Procedural Posture(s): On Appeal; Judgment; Motion to Set Aside or Vacate Order or Judgment; Motion to Quash; Motion to Dismiss.


West Headnotes (23)


[1]

Appeal and ErrorDenial of relief in general


30Appeal and Error
30XVIReview
30XVI(D)Scope and Extent of Review
30XVI(D)17Relief from Judgment or Order
30k3633Denial of relief in general


Court of Appeals generally reviews a trial court’s decision to deny a motion to vacate judgment for abuse of discretion.
4 Cases that cite this headnote



[2]

JudgmentInvalidity of judgment in general


228Judgment
228IXOpening or Vacating
228k346Invalidity of judgment in general


Trial court has a nondiscretionary duty to vacate a void judgment.
3 Cases that cite this headnote



[3]

JudgmentJurisdiction of the person and subject-matter


228Judgment
228INature and Essentials in General
228k16Jurisdiction of the person and subject-matter


A judgment is void if it is entered without personal jurisdiction or subject matter jurisdiction.
2 Cases that cite this headnote



[4]

Appeal and ErrorJudgment in General


30Appeal and Error
30XVIReview
30XVI(D)Scope and Extent of Review
30XVI(D)12Judgment in General
30k3541In general


Court of Appeals reviews de novo whether a judgment is void.
5 Cases that cite this headnote



[5]

CourtsWaiver of Objections


106Courts
106INature, Extent, and Exercise of Jurisdiction in General
106I(A)In General
106k37Waiver of Objections
106k37(1)In general


A defendant will waive the defense of personal jurisdiction if it is not raised in a responsive motion or pleading. Wash. Super. Ct. Civ. R. 12(h)(1).
1 Case that cites this headnote



[6]

AppearanceWaiver of Objections


31Appearance
31k21Waiver of Objections
31k22In general


Waiver of the defense of personal jurisdiction does not occur merely by virtue of a defendant’s voluntary appearance in court. Wash. Super. Ct. Civ. R. 4(d)(5).




[7]

CourtsWaiver of Objections


106Courts
106INature, Extent, and Exercise of Jurisdiction in General
106I(A)In General
106k37Waiver of Objections
106k37(1)In general


Washington courts recognize common law waiver of the defense of personal jurisdiction if a defendant acts in a manner inconsistent with a jurisdictional defense or is dilatory in asserting the defense.
1 Case that cites this headnote



[8]

Appeal and ErrorPersonal jurisdiction


30Appeal and Error
30XVIReview
30XVI(D)Scope and Extent of Review
30XVI(D)3Procedural Matters in General
30k3210Jurisdiction
30k3213Personal jurisdiction


So long as there are no disputed facts, the Court of Appeals’ review of a claim of waiver of the defense of personal jurisdiction is de novo.




[9]

AppearanceWaiver of Objections


31Appearance
31k21Waiver of Objections
31k22In general


Tenant did not waive his personal jurisdiction defense under court rules governing such waiver in landlords’ unlawful detainer action, despite tenant’s two court appearances prior to entry of judgment, where tenant never filed a responsive pleading or motion or sought any form of substantive relief before eventually filing a motion to vacate judgment against him, in which motion tenant raised his personal jurisdiction defense for the first time. Wash. Super. Ct. Civ. R. 4(d)(5), 12(h)(1).




[10]

AppearanceWaiver of Objections
CourtsEstoppel arising from submitting to or invoking jurisdiction


31Appearance
31k21Waiver of Objections
31k22In general
106Courts
106INature, Extent, and Exercise of Jurisdiction in General
106I(A)In General
106k37Waiver of Objections
106k37(3)Estoppel arising from submitting to or invoking jurisdiction


Tenant did not waive his personal jurisdiction defense under common law waiver rule, in landlords’ unlawful detainer action; tenant never took an action inconsistent with his personal jurisdiction defense, such as making a request for affirmative relief, tenant merely requested an interpreter and responded to court’s inquiries during his first appearance in court, and tenant was not dilatory in raising the defense in a motion to vacate judgment against tenant.




[11]

CourtsTime of making objection
ProcessTime for objection


106Courts
106INature, Extent, and Exercise of Jurisdiction in General
106I(A)In General
106k37Waiver of Objections
106k37(2)Time of making objection
313Process
313IIIDefects, Objections, and Amendment
313k156Time for objection


Concern regarding dilatory conduct, as ground for common law waiver of the defense of personal jurisdiction, is that a defendant will lie in wait and mask the problems with service of process until after expiration of the statute of limitations.




[12]

Landlord and TenantReview


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1805Review


Court of Appeals would review de novo a tenant’s claim that he was not adequately served with landlords’ unlawful detainer summons and complaint.




[13]

ProcessPresumptions and burden of proof


313Process
313IIService
313II(E)Return and Proof of Service
313k144Evidence as to Service
313k145Presumptions and burden of proof


The party attacking the sufficiency of service of process carries the burden to show by clear and convincing proof that it was improper.




[14]

Landlord and TenantSummons or other process


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1797Summons or other process


Trial court lacked personal jurisdiction over tenant in landlords’ unlawful detainer action, where tenant was never personally served with process, and copies of summons and complaint were never left at tenant’s usual abode with a person of suitable age and discretion. Wash. Rev. Code Ann. § 4.28.080(16).




[15]

Landlord and TenantSummons or other process


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1797Summons or other process


Trial court had personal jurisdiction of tenant’s marital community in landlords’ unlawful detainer action, where landlords’ process server personally served tenant’s wife.




[16]

Marriage and CohabitationProcess and appearance


253Marriage and Cohabitation
253VCommunity Property
253V(I)Proceedings
253k1015Process and appearance


Personal service as to one spouse permits a creditor to proceed with legal action against a marital community.




[17]

Landlord and TenantNature and form


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1781Nature and form


An unlawful detainer action is a summary statutory proceeding to determine the right of possession as between landlord and tenant. Wash. Rev. Code Ann. § 59.12.030.




[18]

Landlord and TenantNature and form


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1781Nature and form


An unlawful detainer action is a narrow one, limited to the question of possession and related issues such as restitution of the premises and rent. Wash. Rev. Code Ann. § 59.12.030.




[19]

Forcible Entry and DetainerScope of inquiry and powers of court


179Forcible Entry and Detainer
179ICivil Liability
179k31Trial
179k32Scope of inquiry and powers of court


A court presiding over an unlawful detainer action sits as a special statutory tribunal, not as a court of general jurisdiction; as such, the court lacks authority to address disputes unrelated to possession.




[20]

ActionChange of character or form
Forcible Entry and DetainerScope of inquiry and powers of court


13Action
13IINature and Form
13k36Change of character or form
179Forcible Entry and Detainer
179ICivil Liability
179k31Trial
179k32Scope of inquiry and powers of court


Although a judge presiding over an unlawful detainer action lacks authority to consider general civil claims, this limitation does not apply in perpetuity; once the right to possession ceases to be at issue, the proceeding may be converted into an ordinary civil suit for damages, and the parties may then properly assert any cross claims, counterclaims, and affirmative defenses.
2 Cases that cite this headnote



[21]

ActionChange of character or form
Forcible Entry and DetainerScope of inquiry and powers of court


13Action
13IINature and Form
13k36Change of character or form
179Forcible Entry and Detainer
179ICivil Liability
179k31Trial
179k32Scope of inquiry and powers of court


The power to convert an unlawful detainer action into a general action for damages lies exclusively with the trial court.
1 Case that cites this headnote



[22]

ActionChange of character or form
Forcible Entry and DetainerScope of inquiry and powers of court


13Action
13IINature and Form
13k36Change of character or form
179Forcible Entry and Detainer
179ICivil Liability
179k31Trial
179k32Scope of inquiry and powers of court


No particular method exists for the trial court to exercise its power to convert an unlawful detainer action into a general action for damages, but the court must do something to effect conversion, and merely granting a party’s request for general civil damages is insufficient.




[23]

Landlord and TenantJurisdiction


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1792Jurisdiction


Trial court lacked subject matter jurisdiction to enter a civil money judgment against tenant and issue a writ of garnishment, in landlords’ unlawful detainer action, where trial court took no action to convert the unlawful detainer action into a general action for damages prior to issuing judgment.
1 Case that cites this headnote



**806 Appeal from Walla Walla Superior Court, Docket No: 16-2-00602-8, Honorable M. Scott Wolfram, Judge
Attorneys and Law Firms
Tyler William Graber, Northwest Justice Project, 38 E Main St. Ste. 207, Walla Walla, WA, 99362-1939 for Appellant.
Mona Jane Geidl Gonzales, Attorney at Law, 249 W Alder St., Walla Walla, WA, 99362-2809 for Respondents.




PUBLISHED OPINION
Pennell, J.
*10 ¶ 1 Sergio Rodriguez appeals a superior court order denying his motion to (1) vacate a CR 56 *11 judgment for money damages entered in favor of his former landlords, Luz and Juan Castellon, (2) quash a writ of garnishment, and (3) dismiss his landlords’ unlawful detainer complaint. Because the judgment and writ were issued in the context of an unlawful detainer proceeding that had never been converted into a general civil action, we agree with Mr. Rodriguez that the trial court’s actions are void for lack of subject matter jurisdiction. In addition, because Mr. Rodriguez was never served with the unlawful detainer summons and complaint, the trial court lacked personal jurisdiction over Mr. Rodriguez as an individual. However, given that service of process was completed as to Mr. Rodriguez’s wife, the court properly held jurisdiction over the Rodriguez marital community.

¶ 2 Because the CR 56 order and judgment, and writ of garnishment, are void for lack of subject matter jurisdiction, the trial court should have granted Mr. Rodriguez’s motion to vacate the judgment and quash the writ of garnishment. This matter is therefore reversed and remanded for further proceedings.


FACTS
¶ 3 Sergio and Angela Rodriguez rented property on 8th Avenue in Walla Walla, Washington, from Luz and Juan Castellon pursuant to a verbal month-to-month agreement. For the bulk of the tenancy, Mr. Rodriguez lived at the property with Angela Rodriguez and the couple’s children. Mr. Rodriguez paid Mr. Castellon rent at the beginning of each month.

**807 ¶ 4 In April 2016, Sergio and Angela Rodriguez informally separated and Mr. Rodriguez moved out of the 8th Avenue property. Mr. Rodriguez claims he advised Mr. Castellon of this development and provided a new mailing address. After he moved out, Mr. Rodriguez continued to pay rent to Mr. Castellon as part of an informal separation agreement with Angela Rodriguez. However, Mr. Rodriguez *12 claims he informed Mr. Castellon that after August he would no longer pay rent, and that Mr. Castellon and Angela Rodriguez would then need to work something out between themselves.

¶ 5 On August 8, 2016, Mr. Castellon posted a 20-day notice to vacate, terminating the month-to-month tenancy as of August 31. This notice was served by affixing it to the front door of the rental property and mailing it to the property’s address. Because Mr. Rodriguez was no longer living at the property, he claims he never received the notice. Ultimately, Angela Rodriguez did not timely vacate.

¶ 6 On September 1, 2016, the Castellons filed a complaint for unlawful detainer against Sergio Rodriguez and Angela Rodriguez. A show cause hearing was scheduled for September 12.

¶ 7 The Castellons’ process server went to the 8th Avenue property on September 1 to attempt service. The Rodriguez’s daughter answered the door and advised the process server that her mother was at a neighbor’s house. The daughter took the process server to the neighbor’s residence, a couple of doors down the street. While at the neighbor’s house, the process server personally served Angela Rodriguez with the summons and complaint. When Angela Rodriguez advised the process server that she was married to Sergio Rodriguez, he indicated on the certificate of service that Mr. Rodriguez was served via substitute service on Angela Rodriguez. Mr. Rodriguez claims he never received a copy of the summons and complaint. Instead, he found out about the show cause hearing from Angela Rodriguez after she called and told him there was a court action against him that he should go to.

¶ 8 Mr. Rodriguez was present for the September 12 show cause hearing. Although Mr. Rodriguez did not respond when the case was originally called, he stepped forward when the court commissioner specifically asked whether Mr. Rodriguez was present. The commissioner asked Mr. Rodriguez if he intended to file a response to the summons *13 and complaint. Mr. Rodriguez instead asked for a Spanish-language interpreter and the case was set over for the following day.

¶ 9 The following morning, a court-certified Spanish interpreter was present in the courtroom to assist Mr. Rodriguez. As the hearing began, the court commissioner had to call Mr. Rodriguez up again because he was unaware his case had been announced. Counsel for the Castellons acknowledged that Sergio Rodriguez and Angela Rodriguez were in the process of separating and divorcing and that Angela and their children had finally vacated the property before the weekend prior to the hearing. The commissioner asked if Mr. Rodriguez had moved out, and he responded that he moved out “like three months ago.” Report of Proceedings (Sept. 13, 2016) at 5. Mr. Rodriguez went on to answer the commissioner’s questions and stated that he had cleaned up the outside of the 8th Avenue property as the owner requested and that he was working at the Taqueria Mi Pueblito, and he provided the address for his workplace. The commissioner stated to counsel for the Castellons that the workplace address was Mr. Rodriguez’s forwarding address and that since the family had moved out there was nothing to do, to which counsel for the Castellons agreed no writ of restitution was necessary.

¶ 10 At some point after the September 13, 2016 hearing, the Castellons discovered damage to the 8th Avenue property. On October 31, the Castellons filed a CR 56 motion for entry of judgment against Sergio Rodriguez and Angela Rodriguez, a supporting declaration with documentation, a cost bill, and a notice of hearing. In this motion, the Castellons specifically alleged that back rent was due and owing under the verbal lease agreement and that there was damage to the property. On October 31, Mr. Rodriguez was served with the motion and supporting documents, and notice of the hearing set for December 12.

**808 ¶ 11 Neither of the Rodriguezes made an appearance at the December 12 hearing. Counsel for the Castellons indicated *14 she had not received a response from either defendant and she did not know if they were present in the courtroom. No inquiry was made to determine whether Sergio Rodriguez or Angela Rodriquez were in the courtroom.1 Instead, the trial court asked if counsel for the Castellons had an order prepared. The court then signed the order and judgment as presented. The judgment included $5,335.04 in damages, $277.00 in costs, $800.00 in attorney fees, and $1,000.00 in rent for an unspecified month.

1

Mr. Rodriguez claims he was in the courtroom on December 12, but was unaware his case had been called. No Spanish-language interpreter was present on December 12.


¶ 12 A writ of garnishment was obtained on December 21, 2016, for Mr. Rodriguez’s earnings. After receiving the garnishment documents, Mr. Rodriguez secured counsel who filed a motion to vacate the judgment, quash the writ of garnishment, and dismiss the complaint for unlawful detainer. The trial court denied Mr. Rodriguez’s motion. Mr. Rodriguez appeals.


ANALYSIS

Standard of review
[1] [2] [3] [4]¶ 13 This court generally reviews a trial court’s decision to deny a motion to vacate judgment for abuse of discretion. Graves v. Dep’t of Game, 76 Wash. App. 705, 718, 887 P.2d 424 (1994). However, there is a nondiscretionary duty on the trial court to vacate a void judgment. Servatron, Inc. v. Intelligent Wireless Prod., Inc., 186 Wash. App. 666, 679, 346 P.3d 831 (2015). A judgment is void if it is entered without personal jurisdiction or subject matter jurisdiction. Prof’l Marine Co. v. Certain Underwriters at Lloyd’s, 118 Wash. App. 694, 703-04, 77 P.3d 658 (2003). We review de novo whether a judgment is void. ShareBuilder Sec. Corp. v. Hoang, 137 Wash. App. 330, 334, 153 P.3d 222 (2007).



*15 Personal jurisdiction
¶ 14 The parties dispute whether Mr. Rodriguez was validly served with the summons and complaint alleging unlawful detainer. If service of process was improper, then the trial court would have failed to gain personal jurisdiction over Mr. Rodriguez.



*Waiver*
[5] [6] [7] [8]¶ 15 The Castellons argue that regardless of the validity of service, Mr. Rodriguez has waived this issue. Under the Superior Court Civil Rules, a defendant will waive the defense of personal jurisdiction if it is not raised in a responsive motion or pleading. CR 12(h)(1). However, waiver does not occur merely by virtue of a defendant’s voluntary appearance in court. CR 4(d)(5); Kuhlman Equip. Co. v. Tammermatic, 29 Wash. App. 419, 422, 628 P.2d 851 (1981) (court rules “have abolished the distinction between special and general appearances”). In addition to the waiver standards set by court rule, Washington courts recognize common law waiver if a defendant acts in a manner inconsistent with a jurisdictional defense or is dilatory in asserting the defense. Lybbert v. Grant County, 141 Wash.2d 29, 39, 1 P.3d 1124 (2000). So long as there are no disputed facts, our review of a waiver claim is de novo. See id. at 40, 1 P.3d 1124.
[See => [[denote:20240203T125535][1c  Waiver of Defenses]]]

[9]¶ 16 Here, Mr. Rodriguez never waived his personal jurisdiction defense pursuant to the terms of the court rules. Although Mr. Rodriguez made two court appearances prior to entry of judgment, he never filed a responsive pleading or motion. Mr. Rodriguez first raised his personal jurisdiction defense in his motion to vacate judgment. Prior to that time, Mr. Rodriguez never sought any form of substantive relief from the court or any other party. Given these circumstances, the court rules permit Mr. Rodriguez to assert a personal jurisdiction defense.

[10] [11]¶ 17 The record also lacks evidence of common law waiver. Mr. Rodriguez never took any action inconsistent *16 with his personal jurisdiction defense, such as making a request for affirmative relief. When Mr. Rodriguez appeared in court in September 2016, he merely requested an interpreter and responded to the court’s inquiries. This conduct **809 was responsive, not affirmative. Waiver does not occur in such circumstances. French v. Gabriel, 116 Wash.2d 584, 806 P.2d 1234 (1991) (memorandum filed in response to motion for summary judgment in which defendant claimed to be entitled to dismissal was insufficient to waive personal jurisdiction); Negash v. Sawyer, 131 Wash. App. 822, 826-27, 129 P.3d 824 (2006) (limited appearance with no request for affirmative relief was insufficient to waive personal jurisdiction defense). Nor was Mr. Rodriguez particularly dilatory in asserting his personal jurisdiction defense. The concern regarding dilatory conduct is that a defendant will lie in wait and mask the problems with service of process until after expiration of the statute of limitations. Lybbert, 141 Wash.2d at 40, 1 P.3d 1124. Such concerns are not present here. Mr. Rodriguez is a monolingual Spanish speaker. During the period prior to his assertion of lack of personal jurisdiction, Mr. Rodriguez was unrepresented by counsel. The Castellons have not pointed to any tactical advantage Mr. Rodriguez could have gained by delaying his personal jurisdiction defense. Given these circumstances, Mr. Rodriguez should not be prohibited from raising his personal jurisdiction claims by the doctrine of common law waiver.



Sufficiency of service of process
[12] [13]¶ 18 Because the defense of personal jurisdiction was not waived, we confront Mr. Rodriguez’s claim that he was not adequately served with the Castellons’ unlawful detainer summons and complaint. Our review is de novo. Scanlan v. Townsend, 181 Wash.2d 838, 847, 336 P.3d 1155 (2014); Northwick v. Long, 192 Wash. App. 256, 260, 364 P.3d 1067 (2015). The party attacking the sufficiency of the service carries the burden to show by clear and convincing *17 proof that it was improper. Allen v. Starr, 104 Wash. 246, 247, 176 P. 2 (1918); Leen v. Demopolis, 62 Wash. App. 473, 478, 815 P.2d 269 (1991).

[14]¶ 19 We first note that Mr. Rodriguez was never personally served with process in accordance with the terms of RCW 4.28.080(16). The Castellons’ process server never provided Mr. Rodriguez a copy of the summons and complaint. Nor were copies ever left at Mr. Rodriguez’s “usual abode with some [resident] of suitable age and discretion.” RCW 4.28.080(16). For purposes of our analysis, it does not matter whether Mr. Rodriguez’s usual abode was the 8th Avenue property. No service ever took place at the 8th Avenue property. Instead, Angela Rodriguez was served at a location a few doors away. Given this circumstance, it is apparent the Castellons never personally served Mr. Rodriguez with the summons and complaint as contemplated by statute.

[15] [16]¶ 20 The real question is not whether Mr. Rodriguez was personally served as required by RCW 4.28.080(16); it is whether service on Angela Rodriguez was sufficient to obtain jurisdiction over the Rodriguez marital community because the two remained legally married. The rule in Washington is that personal service as to one spouse permits a creditor to proceed with legal action against a marital community. Oil Heat Co. of Port Angeles, Inc. v. Sweeney, 26 Wash. App. 351, 356, 613 P.2d 169 (1980); Komm v. Dep’t of Social & Health Servs., 23 Wash. App. 593, 598-99, 597 P.2d 1372 (1979). Because the Castellons’ process server personally served Angela Rodriguez, the service of process was valid as to the Rodriguez marital community. Thus, even though personal jurisdiction was never obtained against Mr. Rodriguez individually, the court had jurisdiction over Mr. Rodriguez’s marital community.



Subject matter jurisdiction
¶ 21 In addition to his personal jurisdiction challenge, Mr. Rodriguez claims the trial court lacked subject matter *18 jurisdiction over his case because the Castellons’ unlawful detainer action was never converted into an ordinary action for damages as required by Munden v. Hazelrigg, 105 Wash.2d 39, 711 P.2d 295 (1985).

[17] [18] [19]¶ 22 An unlawful detainer action is a summary statutory proceeding, brought under RCW 59.12.030, “to determine the right of possession as between landlord and tenant.” Munden, 105 Wash.2d at 45, 711 P.2d 295. “The action is a narrow one, limited to the question of possession and related **810 issues such as restitution of the premises and rent.” Id. A court presiding over an unlawful detainer action sits as a special statutory tribunal, not as a court of general jurisdiction. Granat v. Keasler, 99 Wash.2d 564, 570-71, 663 P.2d 830 (1983). As such, the court lacks authority to address disputes unrelated to possession. Id.

[20]¶ 23 Although a judge presiding over an unlawful detainer action lacks authority to consider general civil claims, this limitation does not apply in perpetuity. Once “the right to possession ceases to be at issue ..., the proceeding may be converted into an ordinary civil suit for damages, and the parties may then properly assert any cross claims, counterclaims, and affirmative defenses.” Munden, 105 Wash.2d at 45-46, 711 P.2d 295.

[21] [22]¶ 24 The power to convert an unlawful detainer action into a general action for damages lies exclusively with the trial court. Id. at 47, 711 P.2d 295 (“[T]he trial court has inherent power to fashion the method by which an unlawful detainer action is converted to an ordinary civil action.”) (emphasis added). “No particular method exists for the trial court to” exercise its conversion powers. Barr v. Young, 187 Wash. App. 105, 109, 347 P.3d 947 (2015). But the court must do something. Merely granting a party’s request for general civil damages is insufficient. See Angelo Prop. Co. v. Hafiz, 167 Wash. App. 789, 818, 274 P.3d 1075 (2012) (no subject matter jurisdiction when court could have converted unlawful detainer action to general action for damages but did not do so).

*19 [23]¶ 25 Nothing in the record indicates the trial court took any action to convert the Castellons’ unlawful detainer action into a general action for damages prior to issuing judgment. As a result, the court lacked jurisdiction to enter a civil money judgment and issue the writ of garnishment. The court’s actions were therefore void, and Mr. Rodriguez is entitled to relief on his motion to vacate. Allstate Ins. Co. v. Khani, 75 Wash. App. 317, 325, 327-28, 877 P.2d 724 (1994); see generally RCW 6.27.060, .070.



Remaining contentions
¶ 26 Apart from their jurisdictional dispute, the parties disagree over whether and to what extent (1) the Rodriguez marital community is liable for the damages claimed by the Castellons and (2) the Walla Walla County Superior Court adhered to its own language assistance plan. These remaining issues involve unresolved factual issues that cannot be addressed in this appeal. Any claims regarding community liability, language assistance plan violations, or other matters may be raised on remand, if appropriate.


APPELLATE FEES AND COSTS
¶ 27 Mr. Rodriguez has asked for attorney fees and costs pursuant to RAP 18.1 and RCW 6.27.230 (regarding attorney fees in garnishment proceedings). This request is premature, as Mr. Rodriguez has not yet prevailed. It remains possible that, after remand, a writ of garnishment will be reissued against Mr. Rodriguez based on his responsibility for marital community liabilities. Nevertheless, should Mr. Rodriguez ultimately escape a writ of garnishment on remand, he should be deemed a prevailing party as to the Castellons’ garnishment proceeding and awarded attorney fees under RCW 6.27.230, including fees generated during this appeal.


CONCLUSION
¶ 28 The trial court’s order denying Mr. Rodriguez’s motion to vacate is reversed. This matter is remanded to the *20 trial court with instructions to vacate the December 12, 2016, judgment and all subsequent writs of garnishment. Further proceedings may occur on remand, consistent with the terms of this opinion.

Lawrence-Berrey, C.J., and Korsmo, J., concur.
All Citations
4 Wash.App.2d 8, 418 P.3d 804
End of Document

© 2024 Thomson Reuters. No claim to original U.S. Government Works.
