#+title:      Satisfaction of Judgment
#+date:       [2024-07-17 Wed 15:48]
#+filetags:   :judgment:satisfaction:
#+identifier: 20240717T154813

* RCW 4.56.100 - Satisfaction of Judgments for Payment of Money
1) When any judgment for the payment of money only shall have been paid or satisfied, the clerk of the court in which such judgment was rendered shall note upon the record in the execution docket satisfaction thereof giving the date of such satisfaction upon either the payment to such clerk of the amount of such judgment, costs and interest and any accrued costs by reason of the issuance of any execution, or the filing with such clerk of a satisfaction entitled in such action and identifying the same executed by the judgment creditor or his or her attorney of record in such action or his or her assignee acknowledged as deeds are acknowledged. The clerk has the authority to note the satisfaction of judgments for criminal and juvenile legal financial obligations when the clerk's record indicates payment in full or as directed by the court. Every satisfaction of judgment and every partial satisfaction of judgment which provides for the payment of money shall clearly designate the judgment creditor and his or her attorney if any, the judgment debtor, the amount or type of satisfaction, whether the satisfaction is full or partial, the cause number, and the date of entry of the judgment. A certificate by such clerk of the entry of such satisfaction by him or her may be filed in the office of the clerk of any county in which an abstract of such judgment has been filed. When so satisfied by the clerk or the filing of such certificate the lien of such judgment shall be discharged.

2) The department of social and health services shall file a satisfaction of judgment for welfare fraud conviction if a person does not pay money through the clerk as required under subsection (1) of this section.

* Proceedings to compel satisfaction of record
- 228 Judgment - Key 874 :: Persons to Whom Payments May Be Made
- 228 Judgment - Key 894 :: No WA cases
- 228 Judgment - Key 896 :: No WA cases
