#+title:      75 Wash.App. 317 Allstate Co. v. Khani (1994)
#+date:       [2024-02-03 Sat 14:31]
#+filetags:   :case:judgment:pj:vacate:void:
#+identifier: 20240203T143130

* BRIEF

Court has nondiscretionary duty to vacate void judgment.

Void judgments may be vacated regardless of lapse of time; consequently, not even doctrine of laches bars party from attacking void judgment.

Default judgment entered upon defective service of process was void and could be vacated regardless of lapse of time, and regardless of whether defendant had actual notice of the judgment before statute of limitations expired. CR 60(b)(5).



* CASE

Allstate Ins. Co. v. Khani
Court of Appeals of Washington, Division 1. | August 8, 1994 | 75 Wash.App. 317 | 877 P.2d 724

Document Details

Outline
West Headnotes
Attorneys and Law Firms
Opinion
All Citations

KeyCite:

KeyCite Yellow Flag - Negative Treatment
 Distinguished by Watkins v. Peterson Enterprises, Inc., Wash., April 1, 1999

washington Citation:

Allstate Ins. Co. v. Khani, 75 Wn. App. 317, 877 P.2d 724 (1994)

All Citations:

75 Wash.App. 317, 877 P.2d 724

Search Details

Jurisdiction:

Washington

Delivery Details

Date:

February 3, 2024 at 4:29 PM

Delivered By:

Lincoln Harvey

Client ID:

DISMISSAL

Status Icons:



Inline KeyCite:

Inline KeyCite completed successfully.





KeyCite Yellow Flag - Negative Treatment
 	Distinguished by Watkins v. Peterson Enterprises, Inc., Wash., April 1, 1999
75 Wash.App. 317
Court of Appeals of Washington,
Division 1.
ALLSTATE INSURANCE COMPANY, a foreign corporation, Respondent,
v.
Mohamad Amar KHANI and Jane Doe Khani, husband and wife, and their marital community, Appellants.
No. 33337–2–I.
|
Aug. 8, 1994.
Synopsis
In response to writ of garnishment, defendant moved to vacate default judgment, quash service of process and quash writ of garnishment. The Superior Court, King County, Maurice Epstein, Commissioner, denied motion, and defendant appealed. The Court of Appeals, Scholfield, J., held that: (1) default judgment entered upon defective service of process was void and could be vacated regardless of lapse of time, and (2) defendant was entitled to attorney fees and costs.

Reversed and remanded with instructions.

Procedural Posture(s): On Appeal.


West Headnotes (6)


[1]

JudgmentInvalidity of judgment in general


228Judgment
228IXOpening or Vacating
228k346Invalidity of judgment in general


Court has nondiscretionary duty to vacate void judgment.
25 Cases that cite this headnote



[2]

JudgmentTime for Application


228Judgment
228IXOpening or Vacating
228k386Time for Application
228k386(1)In general


Motion to vacate on ground that judgment has been satisfied, released or discharged, or prior judgment upon which it is based has been reversed or otherwise vacated, or it is no longer equitable that judgment should have prospective application may be brought at any time after entry of judgment. CR 60(b)(5).
1 Case that cites this headnote



[3]

JudgmentInvalid or unauthorized judgments


228Judgment
228IXOpening or Vacating
228k386Time for Application
228k386(3)Invalid or unauthorized judgments


Void judgments may be vacated regardless of lapse of time; consequently, not even doctrine of laches bars party from attacking void judgment.
14 Cases that cite this headnote



[4]

JudgmentTime for Application


228Judgment
228IVBy Default
228IV(B)Opening or Setting Aside Default
228k153Time for Application
228k153(1)In general


Default judgment entered upon defective service of process was void and could be vacated regardless of lapse of time, and regardless of whether defendant had actual notice of the judgment before statute of limitations expired. CR 60(b)(5).
19 Cases that cite this headnote



[5]

JudgmentInvalidity of judgment
JudgmentTime for Application


228Judgment
228IVBy Default
228IV(B)Opening or Setting Aside Default
228k141Invalidity of judgment
228Judgment
228IVBy Default
228IV(B)Opening or Setting Aside Default
228k153Time for Application
228k153(1)In general


Party will not be deemed to have waived right to challenge default judgment void for lack of personal jurisdiction merely because time has passed since judgment was entered; under such circumstances, trial court must vacate that judgment and has no discretion to do otherwise.
35 Cases that cite this headnote



[6]

Creditors’ RemediesAttorney fees


108HCreditors’ Remedies
108HVIIParticular Remedies––Garnishment
108HVII(C)Proceedings
108HVII(C)9Costs and Fees
108Hk842Attorney fees
(Formerly 189k191 Garnishment)


When party must vacate default judgment before successfully challenging writ of garnishment, that party may recover attorney fees and costs for both proceedings. West’s RCWA 6.27.230.
7 Cases that cite this headnote



Attorneys and Law Firms
**725 *318 Jeri–Beth Bowman, Seattle, for appellants.
William P. Harris, Seattle, for respondent.
Opinion

SCHOLFIELD, Judge.

Allstate Insurance Company obtained a default judgment against Mohamad Amar Khani and his wife (collectively, Khani) in 1988. In 1993, the trial court denied Khani’s motion to vacate the judgment, quash service of process, and quash a writ of garnishment. Khani appeals the trial court’s order, arguing that the default judgment was void for lack of jurisdiction. Khani also contends the trial court erred by finding that he was required to bring the CR 60(b)(5) motion within a reasonable time and that he failed to do so despite having actual notice of the default judgment. Alternatively, Khani argues that under CR 60(b)(11) he did bring the motion within a reasonable time given the peculiarities of this case. Finally, Khani seeks *319 attorney fees and costs for the proceedings before the trial court and on appeal. We reverse.

On February 21, 1987, Mohamad Amar Khani was involved in a car accident with Deborah Head, who was insured by Allstate Insurance Company. According to a police officer’s report of the incident, the brakes on Khani’s car “did not work per Khani”. The report also gave Khani’s phone number and listed his address as 30602 Pacific Highway South, E–105, in Federal Way, Washington. He lived there at that time with his brother, who was supporting him.

According to Khani’s affidavit, he received a letter from Allstate on March 11, 1987 indicating that the insurance company had determined the accident was his fault. Khani, a native of Syria who arrived in the United States in 1985 pursuant to a student visa, did not know he could contest Allstate’s conclusion. Allstate asked him to verify his insurance coverage or make payment arrangements. He wrote to Allstate offering to pay $10 per month, as that was all he could afford given the work restrictions of his visa.1

1

Khani previously applied to the Immigration and Naturalization Service of the U.S. Department of Justice for permission to engage in employment, but that application was denied in 1986. It was not until July 12, 1988, that Khani received authorization to work in the United States.


On April 1, 1987, Khani received correspondence through his post office box from an Allstate agent in Anchorage, Alaska. The agent asked him to sign a “Confession of Judgment Without Action” form, indicating it would be filed in an Alaska state court, and a form stating he agreed to pay Allstate $100 each month until the sum of $2,495.55 was paid. The agent wrote that if he did not receive the signed documents within 10 days, he would file a lawsuit and “[t]hat way will cost you much, much more money.” Khani wrote to Allstate and again explained he could pay only $10 each month but he would willingly renegotiate payments if his employment status changed. Allstate mailed its written rejection of that offer to Khani’s post office box on April 9, 1987.

*320 Khani subsequently married and moved from his brother’s apartment in Federal Way to his mother-in-law’s home in Seattle on September 10, 1987. Khani notified the **726 Washington Department of Licensing (DOL) of his address change within 10 days of moving, and the Khanis lived at that Seattle address until December 1988. Khani kept his original post office box for his mail. In October 1987, Khani’s brother also moved out of the Federal Way apartment.

On January 12, 1988, Allstate attempted to serve a summons and complaint on Khani in an effort to recover the amount it had paid its insured. Allstate hired a professional process server to accomplish service. An affidavit of service signed by R. Davis states that he served the documents on January 12, 1988 at 30602 Pacific Highway South, E–105, in Federal Way, by giving them to a man named Matthew Welton. Davis also stated the following in another affidavit:
At 6:20 am, I went to 30602 Pacific Highway South # E–105, Federal Way. A man answered the door. I asked for Mohamad Khani, he told me that he was sleeping. I asked him if he was a resident and what his name was. He told me that his name is Ma[t]thew Welton and that he was a resident. I served Mat [t]hew Welton the documents and he signed for them. He is: Caucasian male, 6′ 170 lbs, with Brown hair.

According to an affidavit of the apartment manager, the business records of the complex show that no one named Matthew Welton or Mohamad Amar Khani was ever named as a tenant. However, the records show that on November 30, 1987, Don McDonough moved into apartment E–105. McDonough’s affidavit states that Matthew Welton was living with him on the date service of process on Khani was attempted, and Welton’s affidavit confirms that fact. Welton’s affidavit also states he has never known or lived with anyone named Mohamad Khani.

Without Khani’s knowledge, a default judgment was entered against him in favor of Allstate on October 28, 1988 for $2,853.55 plus attorney fees and costs. On December 9, 1988, Khani received a notice from DOL stating that his driving privilege would be suspended because the October 1988 default judgment against him had not been satisfied. *321 Khani “was shocked and completely unaware of any such judgment”. The notice advised Khani he could request a hearing on the matter because the record of judgment did not indicate he had been personally served with process before the judgment was entered.

Khani requested a hearing, and the DOL hearing officer found that Khani had not received actual and timely notice of Allstate’s suit against him when process was served on Matthew Welton. The hearing officer also found that Khani had notified DOL of his address change on September 23, 1987. Thus, on May 24, 1989, the hearing officer reversed the notice of suspension. According to Khani’s affidavit, he believed the hearing officer’s decision disposed of the matter completely.

In June 1990, Khani received a copy of his credit report and saw that it included the 1988 judgment. After sending a copy of the hearing officer’s decision to the company that prepared the report, the company deleted the judgment. In October 1990, DOL sent Khani a second notice of suspension based on the October 1988 default judgment. However, when Khani referred a DOL employee to the hearing officer’s 1989 decision, the employee told Khani to disregard the second notice because the decision resolved the matter. Khani again believed that the matter was finally resolved, and the default judgment never reappeared on his subsequent credit reports.

In December 1992, Khani and his wife attempted to obtain financing to purchase a home and were informed by a real estate agent that the title insurance report listed the unsatisfied 1988 default judgment. That report also identified Allstate’s attorney as William P. Harris. The real estate agent contacted Harris and attempted to reach an agreement where the Khanis would pay $75 each month until the judgment was paid in full. Allstate, through Harris, rejected that offer on January 15, 1993, and responded that it would only agree to a $300 deposit and monthly payments of $100 thereafter. The Khanis felt that arrangement was unacceptable in light of the DOL hearing officer’s decision and their *322 belief that the matter had been resolved years earlier. Allstate subsequently sent a copy of the default judgment **727 to DOL. In February 1993, DOL wrote to Allstate’s counsel, explaining that the hearing officer had reversed the previous suspension order and DOL was “unable to initiate suspension action against Mr. Khani.”

On April 5, 1993, Khani received notice that a writ of garnishment had been served on his employer, Alaska Airlines.2 On that same day, Khani obtained counsel. He thereafter moved to vacate the default judgment and quash the service of process and the writ of garnishment. The trial court entered the following findings with regard to that motion:

2

Khani also learned that Allstate had begun garnishment proceedings in November 1990 against his earnings from his prior employer, the Red Lion Hotel, but had never served the hotel with the garnishment papers. According to the affidavit of Allstate’s counsel, Allstate halted those earlier proceedings because it believed Khani no longer worked for the hotel. However, a letter from the Director of Human Resources at the Red Lion indicates Khani worked for the hotel from May 7, 1990 to March 16, 1992.


(1) The Defendant has provided convincing evidence that Defendant did not reside at the location the documents were served (# E–105) and that said substituted service is thus defective;
(2) The Defendant did not bring this motion within a reasonable time; and Plaintiff would be prejudiced if the motion is granted; and
(3) Attorney fees and costs were denied to both parties.
The court also made the additional finding that
prior to the running of the statute of limitations the defendant had actual notice that a lawsuit had been started against him and a judgment had been entered. Non[e]theless he waited for over four years before doing anything about it or taking any action to have it set aside. That the plaintiff was prejudiced by this unreasonable delay.
The court consequently denied Khani’s motion and the parties’ respective requests for attorney fees and costs. Khani appeals.


I.
We first decide whether the trial court erred by denying Khani’s motion to vacate the default judgment and quash *323 service of process and the writ of garnishment, given the court’s finding that service of process was defective.3 Khani argues that because service of process was defective, the default judgment is void for lack of personal jurisdiction, and thus, the trial court erred by denying his motion. Allstate contends that the trial court did not abuse its discretion by denying the motion or by finding Khani failed to bring the motion within a reasonable time and Allstate would be prejudiced if the motion were granted.

3

Because Allstate has not assigned error to the trial court’s finding that service was defective, we must treat that finding as a verity on appeal. See Hayes v. Trulock, 51 Wash.App. 795, 800, 755 P.2d 830, review denied, 111 Wash.2d 1015 (1988).


[1] A trial court’s decision to grant or deny a motion to vacate a default judgment is generally reviewed for an abuse of discretion. Leen v. Demopolis, 62 Wash.App. 473, 478, 815 P.2d 269 (1991), review denied, 118 Wash.2d 1022, 827 P.2d 1393 (1992). However, a court has a nondiscretionary duty to vacate a void judgment. Leen, 62 Wash.App. at 478, 815 P.2d 269; In re Marriage of Markowski, 50 Wash.App. 633, 635, 749 P.2d 754 (1988); Brickum Inv. Co. v. Vernham Corp., 46 Wash.App. 517, 520, 731 P.2d 533 (1987).

[2] [3] A motion to vacate under CR 60(b)(5)4 “may be brought at any time” after entry of judgment. Lindgren v. Lindgren, 58 Wash.App. 588, 596, 794 P.2d 526 (1990), review denied, **728 116 Wash.2d 1009, 805 P.2d 813 (1991); see also Brenner v. Port of Bellingham, 53 Wash.App. 182, 188, 765 P.2d 1333 (1989) (“motions to vacate under CR 60(b)(5) are not barred by the ‘reasonable time’ or the 1–year requirement of CR 60(b)”). Void judgments may be vacated regardless *324 of the lapse of time. In re Marriage of Leslie, 112 Wash.2d 612, 618–19, 772 P.2d 1013 (1989). Consequently, not even the doctrine of laches bars a party from attacking a void judgment. Leslie, 112 Wash.2d at 619–20, 772 P.2d 1013.

4

CR 60(b) states:
On motion and upon such terms as are just, the court may relieve a party or his legal representative from a final judgment, order, or proceeding for the following reasons:
. . . . .
(5) The judgment is void[.]
. . . . .
The motion shall be made within a reasonable time and for reasons (1), (2) or (3) not more than 1 year after the judgment, order, or proceeding was entered or taken.


Brenner provides a striking example of how meaningless the passage of time is in the context of a void judgment. There, a default judgment was entered in 1969 condemning all interests in certain real property and vesting title in the Port of Bellingham. In 1985, Brenner sued the Port for damages resulting from the condemnation action and alleged in part that the Port had failed to satisfy the statutory requirements of service by publication. The trial court denied Brenner’s motion for summary judgment, ruling that the Port’s error was merely an irregularity and, thus, voidable under CR 60(b)(1) rather than void under CR 60(b)(5). The trial court also found that Brenner had failed to move to vacate the judgment within a reasonable time as required by CR 60(b)(1). 53 Wash.App. at 185, 765 P.2d 1333. The Court of Appeals reversed, holding that the Port’s failure to strictly comply with the requirements of service by publication meant the court had no jurisdiction over Brenner when it entered the 1969 judgment condemning her interest in the property. Recognizing that a default judgment entered without valid service is void and may be vacated at any time, the court remanded the case to the trial court with instructions to vacate the 16–year–old judgment. 53 Wash.App. at 188, 765 P.2d 1333.

[4] In the present case, the trial court expressly found Allstate’s service of process was defective. “Proper service of the summons and complaint is essential to invoke personal jurisdiction over a party, and a default judgment entered without proper jurisdiction is void.” Markowski, 50 Wash.App. at 635–36, 749 P.2d 754; see also Mid–City Materials, Inc. v. Heater Beaters Custom Fireplaces, 36 Wash.App. 480, 486, 674 P.2d 1271 (1984). Because a party may move to vacate a void judgment at any time (Leslie, 112 Wash.2d at 618–19, 772 P.2d 1013), the trial court erred by finding that Khani failed to bring his motion within a reasonable time. Further, as discussed in detail below, the trial court’s finding that Khani had actual notice of the *325 default judgment through the DOL notice is irrelevant on these facts. More significantly, the trial court erred by denying Khani’s motion because it failed to fulfill its nondiscretionary duty to vacate a void judgment. See Leen, 62 Wash.App. at 478, 815 P.2d 269; Markowski, 50 Wash.App. at 635, 749 P.2d 754. Thus, the trial court’s order must be reversed and the case remanded with instructions to vacate the default judgment and quash the writ of garnishment. See Leslie, 112 Wash.2d at 618, 772 P.2d 1013 (a vacated judgment has no effect, and the parties’ rights are left as though the judgment had never been entered).5

5

Khani also makes the alternative argument that he brought his motion to vacate within a reasonable time under CR 60(b)(11), which allows a trial court to relieve a party from a final judgment for “[a]ny other reason justifying relief from the operation of the judgment.” Khani, however, has made no showing of a meritorious defense which is a critical prerequisite to vacating a judgment under CR 60(b)(11). See Calhoun v. Merritt, 46 Wash.App. 616, 619, 731 P.2d 1094 (1986). Regardless, “[t]he customary CR 60 meritorious defense requirement is immaterial where the court entering an in personam judgment had no jurisdiction of the defendants in the first instance.” Mid–City Materials, 36 Wash.App. at 486, 674 P.2d 1271.




II.
As discussed above, a void judgment may be vacated at any time. Nonetheless, Allstate argues that under Romjue v. Fairchild, 60 Wash.App. 278, 803 P.2d 57, review denied, 116 Wash.2d 1026, 812 P.2d 102 (1991), Khani waived the defense of insufficient service of process.

In Romjue, a Division Three opinion, Romjue filed suit against Fairchild for damages resulting from a car accident. Romjue served process on “Mrs. Fairchild” at a Kennewick address and believed that service **729 was effective. That address, however, was not where Fairchild lived. He resided in Ellensburg. Defense counsel nevertheless filed a notice of appearance, and Romjue’s counsel sent him a copy of an affidavit of service stating that service had been made at the Kennewick address. In addition, before the statute of limitation had run, defense counsel was aware from the parties’ correspondence that Romjue’s counsel believed service on Mrs. Fairchild was effective and was relying on that belief. Defense counsel subsequently engaged in discovery. After *326 the statute of limitation for Romjue’s cause of action had run, defense counsel moved to dismiss on the ground that service was insufficient. The trial court granted that motion. 60 Wash.App. at 279, 803 P.2d 57.

On appeal, the court framed the issue as whether Fairchild waived the defense of insufficient service because he engaged in discovery before he moved to dismiss. The court concluded he had waived that defense because the type of discovery he conducted was inconsistent with the defense of insufficient service. 60 Wash.App. at 281, 803 P.2d 57. The court also reached its conclusion because defense counsel knew before the statute of limitation ran that Romjue’s counsel was unwittingly relying on the ineffective service, yet defense counsel chose not to correct that misapprehension until after the statute of limitation had expired. 60 Wash.App. at 281–82, 803 P.2d 57.

A critical distinction between Romjue and the present case is that the defendant in Romjue brought a pretrial motion to dismiss, not a motion to vacate a void default judgment. Under CR 12, a party must comply with specific requirements to move for dismissal based on the defense of lack of personal jurisdiction. CR 12(b). If a party fails to properly raise that defense under CR 12 when he has an opportunity to do so, the party may be deemed to have waived it. CR 12(h)(1); see also French v. Gabriel, 116 Wash.2d 584, 588–89, 806 P.2d 1234 (1991).

Where a defendant appears in a case and files responsive pleadings or engages in discovery prior to the entry of a final judgment, that defendant is subject to the requirements of CR 12(b) and (h)(1).

[5] In contrast, when a default judgment is entered against a defendant and is void for lack of personal jurisdiction over him, he may challenge the void default judgment at any time. A party will not be deemed to have waived the right to challenge a default judgment void for lack of personal jurisdiction merely because time has passed since the judgment was entered. See Leslie, 112 Wash.2d at 619, 772 P.2d 1013. Under such circumstances, the trial court must vacate that judgment *327 and has no discretion to do otherwise. See, e.g., Leen, 62 Wash.App. at 478, 815 P.2d 269.

The facts of Romjue are entirely different from the facts here. Khani never received service of process and had no knowledge of Allstate’s proceedings against him until after the default judgment was entered. Romjue’s active participation in the case prior to judgment made him subject to the requirements of CR 12. There is no evidence that Khani knew about the statute of limitation for Allstate’s claim or that he strategically waited to vacate the judgment until after the limitation expired. Even if Khani had known about the limitation period, Allstate offers no authority to support its contention that when a defendant learns about a void default judgment against him and knows the statute of limitation for the plaintiff’s claim has not expired, he must try to vacate that judgment before the limitation does expire. Thus, in this context, the trial court’s finding that Khani had actual notice of the judgment before the statute of limitation expired is irrelevant.



III.
[6] Finally, we must decide whether Khani is entitled to attorney fees and costs under RCW 6.27.230 for the proceedings before the trial court and those on appeal. The statute provides in part that when a garnishee’s answer to a writ of garnishment is controverted, “the costs of the proceeding, including a reasonable compensation for attorney’s fees, shall be awarded to the prevailing party”. Further, when a party must vacate a default judgment before successfully challenging a writ of garnishment, RCW 6.27.230 **730 allows that party to recover attorney fees and costs for both proceedings. Lindgren v. Lindgren, 58 Wash.App. 588, 598, 794 P.2d 526 (1990), review denied, 116 Wash.2d 1009, 805 P.2d 813 (1991). Because Khani had to vacate the default judgment before he could oppose the writ of garnishment, he is entitled under RCW 6.27.230 to his attorney fees and costs both in the trial court and on appeal. Allstate’s request for fees under RAP 14.2 is denied.

*328 We reverse the trial court’s order denying Khani’s motion to vacate the default judgment and remand the case with instructions to vacate the default judgment, quash the service of process and the writ of garnishment, and award reasonable attorney fees for services rendered in the trial court.

WEBSTER, C.J., and BAKER, J., concur.
All Citations
75 Wash.App. 317, 877 P.2d 724
End of Document

© 2024 Thomson Reuters. No claim to original U.S. Government Works.
