#+title:      94 Wash.2d 291 State v. Petrich (1980)
#+date:       [2024-02-08 Thu 08:23]
#+filetags:   :case:nuncprotunc:
#+identifier: 20240208T082310

* Caption

94 Wn.2d 291, STATE v. PETRICH

CITE:          94 Wn.2d 291, 616 P.2d 1219

               STATE v. PETRICH

CAUSE NUMBER: 46030

FILE DATE:     September 18, 1980

CASE TITLE: The State of Washington, Respondent, v. Kurt                Konrad Petrich, Petitioner.

* Headnotes

[1] Judgment - Entry Nunc Pro Tunc - Power of Court. Courts have discretionary power to enter judgments nunc pro tunc for the purpose of recording judicial actions previously taken.

[2] Appeal and Error - Notice of Appeal - Timeliness - Judgment Entered Nunc Pro Tunc - Effect. A party who proposes and agrees to the entry of a judgment nunc pro tunc may not later assert that the period for bringing an appeal commenced on the date the nunc pro tunc order was entered.

* Summary

NATURE OF ACTION: Prosecution for assault in the second degree committed with a firearm and deadly weapon. The defendant fired a pistol at the driver of an automobile who had been following and harassing the defendant and his fiancee.

Superior Court: The Superior Court for King County, No. 76647, Herbert M. Stephens, J., at the conclusion of the trial orally dismissed the firearm and deadly weapon allegations; on April 1, 1977, rendered an oral judgment of guilty; on April 15, 1977, entered a written judgment, including dismissal of the weapons allegations, which was labeled nunc pro tunc so as to appear of record as of April 1, 1977; and on April 25, 1977, entered written findings, conclusions, and dismissal of the weapons allegations.

Court of Appeals: The court REVERSED the dismissal of the weapons allegations at 21 Wn. App. 100, holding that the State's appeal was timely and that the trial court had no power to dismiss the weapons allegations under CrR 8.3(b).

Supreme Court: Holding that the April 25 dismissal of the weapons allegations was surplusage which could not be the basis for review, that the State was bound by the nunc pro tunc effect of the April 15 judgment, and that the appeal was untimely, the court REVERSES the decision of the Court of Appeals.

COUNSEL:      LAURENCE B. FINEGOLD, SHARON A. FINEGOLD, and HARVEY H. CHAMBERLIN, for petitioner.

NORM MALENG, PROSECUTING ATTORNEY, and MARC A. BOMAN, DEPUTY, for respondent.

AUTHOR OF MAJORITY OPINION: Williams, J. -

* Opinion

** Facts

MAJORITY OPINION: Petitioner Kurt Konrad Petrich was charged with assault in the second degree while armed with a deadly weapon and firearm: to wit, a pistol. He was convicted after a nonjury trial, but the court dismissed the deadly weapon and firearm allegations pursuant to CrR 8.3(b). The State appealed the dismissal of these sentence enhancement provisions, and the Court of Appeals reversed the trial court. STATE v. PETRICH, 21 Wn. App. 100, 583 P.2d 674 (1978). We now reverse the Court of Appeals.

On April 11, 1976, between 12:30 and 1:30 a.m., petitioner and his fiancee, Colleen Ingram, were leaving a dance at the Legion Hall in Redmond, Washington, when they were observed embracing by Michael Hill, age 16, and Nina Heyes, age 15. Hill and Heyes mistook the couple for male homosexuals and decided to follow them to "hassle them" and "see where they lived and maybe for Halloween maybe just - ".

As the Petrich-Ingram vehicle, driven by Ingram, traveled the 12 miles toward the couple's home in Stillwater, Washington, Hill intermittently flashed his high-beam headlights and drew close behind the other car, accelerating up to a high rate of speed on the poorly lit country roads. Both petitioner and Ingram testified they were frightened, having no idea how many people were in the other car or "what they were trying to prove." Upon reaching their residence in Stillwater, Ingram pulled to the side of the road to speak to two persons standing in a neighbor's driveway. Petitioner exited the vehicle, obtained his pistol from his home, and returned to the roadside. Meanwhile, Hill passed the parked vehicle, stopped farther down the road, and shut off the lights. After a few minutes, Hill turned the car around and drove back toward the Petrich-Ingram vehicle, at which time petitioner aimed the pistol and fired the weapon. The bullet passed through the passenger side of the automobile hitting Hill in the arm. Petitioner and Ingram immediately called the police and notified them of the incident.

Prior to his trial for second degree assault, petitioner moved under CrR 8.3(b) to dismiss the deadly weapon and firearm allegations in the information. The parties agreed that it would be appropriate for the court to hear the evidence in the case before ruling on the motion. At the conclusion of the trial, the court found that petitioner had "overreacted and used excessive force." Finding of fact No. 11. Petitioner had never previously been arrested or convicted of a crime, however, and the judge was convinced that the incident would not have occurred but for the misbehavior of the victim. Therefore, pursuant to CrR 8.3(b), the judge dismissed the mandatory sentencing allegations, stating his act to be "in the furtherance of justice" and the alternative to be cruel and unusual punishment. «1»

«1» Petitioner was charged with second degree assault under former RCW 9.11.020 (now RCW 9A.36.020), while armed with a deadly weapon under RCW 9.95.040(1) and a firearm under RCW 9.41.025. The firearm charge, if substantiated, would preclude the trial judge from suspending the sentence or granting probation, and petitioner would therefore receive a mandatory minimum sentence of at least 5 years in prison. The victim who instigated this sequence of events was not charged with any offense.

Conclusion of law No. 1.

On April 1, 1977, the trial court orally rendered its judgment, deferring imposition of sentence for 2 years on condition petitioner serve 60 days in the King County jail, make restitution to the victim, and pay a fine of $250 to the Washington State Crime Victims Compensation program. After pronouncing sentence, the court, in compliance with CrR 7.1, said to petitioner:

"     Mr. Petrich, since you have been found guilty of assault in the second degree, the Court should advise you YOU HAVE A RIGHT TO APPEAL, AND YOU HAVE THIRTY DAYS TO GIVE NOTICE and take appropriate steps. Your counsel, Mr. Finegold, can certainly advise you along those lines, and the Court can also advise you, if you do not have funds with which to employ counsel, the State will employ or appoint counsel for you or retain counsel for you.
(Italics ours.)

Subsequently, the following colloquy took place between the prosecuting attorney and the court:

"     MR. HAMILTON: I am afraid I don't recall whether Your Honor indicated he would have THIRTY DAYS FROM TODAY in which to enter notice of appeal. THE COURT: Yes, the rule says he must do it WITHIN THIRTY DAYS. MR. HAMILTON:
Yes, that was my understanding, although, I haven't thoroughly read the new rules on appeal, but I haven't read recently the new rules, but I think that is still the case. THE COURT: Yes. And Mr. Petrich, you do have a right of appeal, AND NOTICE SHOULD BE GIVEN IN THIRTY DAYS.
(Italics ours.)

On April 13, 1977, counsel for petitioner and counsel for the State reappeared before the trial judge. The prosecutor stated at the outset:

"The purpose of the hearing is simply to present findings of fact, conclusions of law as they relate to the judgment entered in this case, and also the order indicated by the Court orally, that it would dismiss pursuant to the rules, Criminal Rule 8.3(b), the provisions relating to the deadly weapon and firearms.
After the parties took their exceptions to the findings of fact, conclusions of law, and verdict, petitioner's counsel inquired about the judgment and sentence which had been rendered April 1:

"     MR. FINEGOLD: How about the judgment and sentence?

MR. HAMILTON: Counsel has reminded me I haven't typed in the judgment and sentence. I believe your Honor was not here last week, or I was under the impression that you were not. THE COURT: No, that's right. You are right. MR. HAMILTON: So I AM GOING TO HAVE TO DO THE JUDGMENT AND SENTENCE AS A NUNC PRO TUNC ORDER, and I don't have the proper nunc pro tunc phraseology on it there. I will bring that up this afternoon, indicating that the JUDGMENT RELATES TO THE DATE WHEN THE COURT PRONOUNCED JUDGMENT. We had this week before last, wasn't it? MR. FINEGOLD: I believe it was on Friday, April 1. THE COURT: April 1. MR. FINEGOLD: If it reflects an April 1 date, it can wait until he brings up the other papers tomorrow.

MR. HAMILTON: THAT WAS MY INTENTION . . .

(Italics ours.)

On April 14, 1977, the State presented and the judge signed an "Order Deferring Imposition of Sentence (Probation)", which was filed the next day, April 15. The caption included the phrase "NUNC PRO TUNC", and at the bottom of the first page appeared the following typewritten sentence: "This judgment entered so as to appear of record as of April 1, 1977." The order also reflected the dismissal of the sentence enhancement allegations in the following language:

"the defendant entered a plea of "Not Guilty" and the subsequent finding of guilty by the court on the 17th day of December, 1976, "guilty as to both counts," and the court having heard evidence and HAVING ORDERED DISMISSAL OF THE DEADLY WEAPON AND FIREARM PROVISIONS pursuant to CrR 8.3(b).
(Italics ours.)

Because the State's proposed findings of facts and conclusions of law were not satisfactory to the court at the April 13 hearing, those matters were not submitted until April 25, 1977, along with an included "Order of Dismissal under CrR 8.3(b)". The findings, conclusions, and order were signed by the judge and entered that same day.
On May 16, 1977, the State filed an appeal from the April 25 order of dismissal under CrR 8.3(b), contending that the trial judge lacked authority to dismiss the sentence enhancement allegations. On May 23, 1977, petitioner filed a notice of appeal and cross appeal, and later moved to dismiss the State's appeal as not timely filed. The Court of Appeals, holding the State's appeal was timely, concluded the trial court was without the authority to dismiss the deadly weapon and firearm allegations.

The State argues that its appeal was timely because it challenged the April 25 "Order of Dismissal under CrR 8.3(b)" and was therefore clearly within the period required by RAP 5.2(a). It is our view, however, that the April 25 order was not a proper order and thus it could not be challenged by the State either by direct appeal (RAP 2.2(b)) or by discretionary review (RAP 2.3).

In the judgment and order deferring imposition of sentence entered on April 15, the court specifically stated that it had previously ordered dismissal of the sentence enhancement provisions. Moreover, the sentence does not impose a mandatory 5-year term, as would have been required under RCW 9.41.025(1). Thus, even had there been no express dismissal, the court impliedly ordered the dismissal of the provisions at the time it signed the judgment and sentence. It follows that the purported "order" of April 25 was mere surplusage and a nullity and could not be the basis for an appeal or discretionary review. Thus, the only order the State could challenge was the April 15, 1977 "Order Deferring Imposition of Sentence (Probation)", which, as we have stated, incorporated the dismissal under CrR 8.3(b).

Petitioner urges that April 1, 1977, is the operative date from which the State could take an appeal under the 30-day rule of RAP 5.2(a). He asserts that the nunc pro tunc sentencing order of April 15 relates both the sentencing and any appeals therefrom back to April 1. If this analysis is correct, the State's May 15 notice of appeal was clearly untimely. The Court of Appeals did not reach this issue because it concluded the April 25 ruling was a properly appealable order.

** Legal Analysis

[1] An order nunc pro tunc records judicial acts done at a former time which were not then carried into the record. STATE v. MELHORN, 195 Wash. 690, 692, 82 P.2d 158 (1938). Washington courts have inherent power to enter judgments nunc pro tunc. GARRETT v. BYERLY, 155 Wash. 351, 284 P. 343, 68 A.L.R. 254 (1930). The power is discretionary and is to be exercised "'as justice may require . . .'" in a particular case. IN RE ESTATE OF CARTER, 14 Wn. App. 271, 274, 540 P.2d 474 (1975); GARRETT, at 359. Judgments will not be rendered nunc pro tunc when in the view of the trial court an injustice will result thereby. STATE EX REL. TUFTON v. SUPERIOR COURT, 46 Wash. 395, 397, 90 P. 258 (1907).

[2] In the present case, both the trial court and the prosecutor advised petitioner and his counsel that any appeal must be taken within 30 days of April 1, the day the trial judge orally pronounced the judgment and sentence. Because of the State's delay in preparing the papers, they were not presented for the court's signature until April 14, a day after defense counsel reminded the prosecutor in open court that the judgment had not yet been signed and entered. The prosecutor OFFERED to prepare the judgment and sentence nunc pro tunc; defense counsel agreed, and the final order reflects the agreement. In effect, the State now asks the court to ignore its stipulation as to the effective date of the judgment and its apparent concurrence in the court's advice to petitioner that the time for appeal started running from April 1.

It is uncontradicted that the State was responsible for the delay in entry of the judgment, that the State proposed it should relate back to April 1, and that the court, the State, and the petitioner accepted and relied on the nunc pro tunc effect of the judgment. Accordingly, we hold that the State is bound by its proposed judgment and that in the unusual
situation here presented, the effective date of the judgment and sentence was April 1, 1977, and the State's May 15, 1977, appeal was therefore untimely. Under these circumstances, we think it manifestly unfair to permit the State to disavow its own conduct and prevail on its claim that the nunc pro tunc language should now be declared ineffective.

We thus do not reach the merits of the State's appeal, and this disposition makes it likewise unnecessary to consider petitioner's appeal of his conviction, which, as the Court of Appeals observed, was tardy in any event. STATE v. PETRICH, 21 Wn. App. 100, 106 n.2, 583 P.2d 674 (1978).

The judgment of the Court of Appeals is reversed.

CONCURRING JUDGES: Utter, C.J., and Rosellini, Stafford, Wright, Brachtenbach, Horowitz, Dolliver, and Hicks, JJ., concur.

POST-OPINION INFORMATION:
