#+title:      72 Wash.App. 380 Bar K Land Co. v. Webb (1993)
#+date:       [2024-02-08 Thu 07:54]
#+filetags:   :case:ejectment:
#+identifier: 20240208T075454

72 Wn. App. 380, 864 P.2d 435, BAR K LAND CO. v. WEBB

Dec. 1993

[No. 12186-1-III. Division Three. December 9, 1993.]

BAR K LAND CO. v. WEBB BAR K LAND COMPANY, Respondent, v. SHIRLEY WEBB, Appellant.

[1] Ejectment – Right of Action – Purchaser Under Earnest Money Agreement – Early Possession – Holding Over. When a prospective purchaser of residential real estate takes possession under the terms of an early possession agreement, pays for permanent improvements under an earnest money agreement far in excess of the amount a tenant would pay to improve rented property, and continues to occupy the premises without making payments after the expiration of the earnest money agreement, the relationship between the parties is that of vendor and purchaser. The owner's proper cause of action for obtaining possession is ejectment, not unlawful detainer, at which the prospective purchaser may counterclaim for the reasonable value of the improvements made to the premises.
Nature of Action: The owner of a house brought an unlawful detainer action against a person who had taken possession of the premises under the terms of an early possession agreement. The sale had never closed and the defendant stopped making payments.
Superior Court: The Superior Court for Spokane County, No. 91-2-00548-1, Kathleen M. O'Connor, J., on January 29, 1992, entered a judgment in favor of the owner.
Court of Appeals: Holding that the owner had a right of action for ejectment but not for unlawful detainer, the court reverses the judgment and remands the case for further proceedings.

Howard K. Michaelsen, for appellant.

Thomas R. McGarry and Olson, Loeffler & Landis, for respondent.

MUNSON, J. – Shirley Webb appeals her eviction and a judgment for Bar K Land Company in the amount of $13,946.83. She contends the court erred in: (1) finding this was an unlawful detainer action rather than an ejectment action; and (2) finding the earnest money agreement was not a bona fide agreement.
In the fall of 1989 Bar K Land Company advertised for sale a house located at 718 West Glass, Spokane, Washington. Shirley Webb responded to the advertisement and expressed an interest in purchasing the property. Ms. Webb told Bar K she could not qualify for financing, but Neil R. Cowley would cosign the loan with Ms. Webb.
On February 13, 1990, Bar K and Ms. Webb entered into an "Early Possession Agreement" under which Ms. Webb would pay $16.67 per day as rent for the property. An "Earnest Money Agreement", dated March 5, 1990, was signed by Neil Cowley and Bar K. The "Earnest Money Agreement" provided for $500 earnest money and a sale price on the property of $65,000; $10,150 of the sale price was to go toward remodeling the house. The sale was to close on or before June 1, 1990.

On April 18, 1990, Ms. Webb and Bar K signed another agreement which explained the remodeling more fully. Ms. Webb was to pay the first $3,600 of remodeling expenses, to be considered a down payment. Bar K agreed to provide labor and materials at its cost for purposes of the remodeling.
Remodeling of the house began sometime in March or April 1990. Ms. Webb spent more than $15,000 on remodeling expenses. Bar K purportedly spent a substantial amount, but how much was not established in the record. Ms. Webb stopped paying rent on July 1, 1990, but continued to pay remodeling expenses. The sale of the house did not close and remodeling stopped in November 1990.

On January 31, 1991, a 3-day notice to pay rent or vacate was served on Ms. Webb. On February 5, Bar K commenced this action for unlawful detainer. Ms. Webb posted a $1,000 bond with the court on February 13. In addition, she paid $510 monthly to the court beginning in March.
On December 30, 1991, the trial court entered judgment for Bar K in the amount of $13,946.83, directed the clerk to pay $5,590 over to Bar K (from the rent paid into the court registry), and directed the issuance of a writ of restitution.

On January 3, 1992, Ms. Webb moved for an order to set a supersedeas bond. On January 7, a supersedeas bond was set in the amount of $8,356.83 ($13,946.83 judgment amount less $5,590 paid to Bar K). On the same day, the Spokane County Sheriff evicted Ms. Webb from the premises. Ms. Webb appealed the supersedeas order. On January 15, the Court of Appeals commissioner remanded the matter back to the trial court (Court of Appeals cause 12135-6-III). On January 29, the trial court fixed the supersedeas bond in the amount of $8,300. That bond was never posted and the judgment remains unsatisfied.
Since Ms. Webb's eviction, Bar K has refurbished and re-rented the property.

UNLAWFUL DETAINER

Ms. Webb contends the trial court erred in applying the law of unlawful detainer rather than the law of ejectment. She argues her relationship with Bar K was that of vendor and purchaser, not landlord and tenant.

Both ejectment and unlawful detainer are recognized as legal methods of evicting tenants who do not pay their rent. Honan v. Ristorante Italia, Inc., 66 Wn. App. 262, 269, 832 P.2d 89, review denied, 120 Wn.2d 1009 (1992).

Unlawful detainer actions under RCW 59.18 are special statutory proceedings with the limited purpose of hastening recovery of possession of rental property. Unlawful detainer is limited to cases involving landlords and tenants when the only questions are possession and rent. The superior court's jurisdiction in such actions is limited to the primary issue of possession and incidental issues such as restitution and rent, or damages. Phillips v. Hardwick, 29 Wn. App. 382, 386, 628 P.2d 506 (1981). It is well settled that additional claims cannot be joined in an unlawful detainer action. Honan, at 269. Any issue not incident to the right of possession within the specific terms of RCW 59.18 must be raised in an ordinary civil action. The landlord-tenant act specifically excludes from the act relationships involving earnest money agreements. RCW 59.18.040.

Ejectment is a remedy for one who, claiming a paramount title, is out of possession. Ejectment is a mixed action, and damages for the ouster or wrong can be simultaneously recovered. 28 C.J.S. Ejectment § 1, at 848 (1941). When permanent improvements have been made upon the property by the defendant, in good faith, the value thereof may be allowed as a setoff, or as a counterclaim, against damages for withholding the property. RCW 7.28.150, .160.

Ms. Webb asserts the early possession agreement was part of the sale and not a separate agreement for rent. Reeves v. McClain, 56 Wn. App. 301, 310, 783 P.2d 606 (1989). As a result, Ms. Webb contends she had greater property interests than those of a tenant. Therefore, this should have been an action for ejectment rather than unlawful detainer, allowing her counterclaims and interests to be decided.

Ms. Webb cites two cases, Snarski v. Washington State Colonization Co., 53 Wash. 221, 101 P. 839 (1909) and Reeves v. McClain, supra, as authority for her contention that this should be an action for ejectment. Snarski can be distinguished in that it involved the purchase of real estate for which the buyer had paid all but a very small portion of the purchase price. When the seller could not convey a clear title, the court allowed the purchaser to recover the purchase price and the value of improvements. Ms. Webb made a small earnest money payment of $500 and improvements of $3,600 or, as she contends, $15,000.
In Reeves, the purchaser fully performed under the sale agreement, rescinding only when she discovered the seller had not delivered an insured clear title. Here, Ms. Webb did not complete the purchase of the house.

Aldrich v. Forbes, 237 Or. 559, 391 P.2d 748 (1964) is very similar to this case. In Aldrich, the purchasers paid earnest money under a purchase agreement. In a supplemental agreement, the purchasers agreed to pay rent on the property until they obtained a loan. In addition, they agreed to make certain repairs to the home, which they did. When the purchasers did not obtain their loan by the specified time, the seller brought an unlawful detainer action. The court found that the earnest money agreement created a vendor-purchaser relationship and the supplemental agreement continued this relationship because of the expense involved in making the repairs. The court stated:

[T]he . . . agreement required the purchasers to make repairs and to paint the premises. This obligation imposed upon the purchasers with its concomitant expense would not be inconsistent with a lease if the lease were for a period long enough to enable the lessees to reap some benefit from the improvements during the tenancy. But the improvements which the purchasers here agreed to make would be of little use to them unless they could get a loan and continue to occupy the premises as purchasers of the property rather than as lessees.

It is our conclusion that the . . . agreement was intended to continue the relationship of vendor and purchaser initially created by the earnest money agreement. This being so, an action of forcible entry and detainer does not lie.
Aldrich, at 572.

[1] Similarly here, the amount Ms. Webb was required to pay for improvements under the earnest money agreement was far in excess of an amount a renter would pay to improve rental property. Ms. Webb continued to make payments on improvements even after the earnest money agreement expired. Although Ms. Webb did execute the early possession agreement slightly before the earnest money agreement, the early possession agreement was done with the understanding that she, through Mr. Cowley, was to be the purchaser of the property. Clearly, she was treated by both parties as a purchaser rather than a tenant.

The trial court found that when the earnest money agreement expired, the relationship became one of landlord-tenant and an action for unlawful detainer was proper. However, the excessive amount spent by Ms. Webb for improvements continued the relationship as that of vendor-purchaser, and an action did not lie in unlawful detainer.
Bar K asserts that even if the court finds that unlawful detainer is not the appropriate remedy, the issue of possession is moot because Ms. Webb has moved out and the house has been rented. The issue is not moot because the house has not been sold and if this action is brought for ejectment, Ms. Webb still has a counterclaim for her improvements.
Since we find this should not have been an unlawful detainer action, Ms. Webb's remaining issues need not be addressed.

ATTORNEY FEES

The earnest money agreement provides: "In the event that Buyer, Seller or Agent shall commence proceedings or institute suit to enforce any rights hereunder, the prevailing party shall be entitled to costs and a reasonable attorney's fee."

Ms. Webb is awarded costs and attorney fees for this appeal.

Reversed and remanded for trial as an action for ejectment.

THOMPSON, C.J., and SPERLINE, J. Pro Tem., concur.
