#+title:      3 Wash.App. 120 Kessler v. Nielsen (1970)
#+date:       [2024-02-03 Sat 14:42]
#+filetags:   :jurisdiction:possession:ud:
#+identifier: 20240203T144250

* BRIEF

** PROCEDURE

1. PL LL owned the premises at issue, and entered into a sale
   agreement with the DEF T, which stated that if the sale did not
   close as anticipated, then the DEF T would owe rent at a certain
   amount per month for the time of occupancy.

2. DEF T filed an action for rescission of contract and damages
   against PL LL, which was ultimately determined in PL LL's favor.

3. PL LL served DEF T with a statutory 3-day notice demanding rent or
   surrender of the premises.

4. PL LL brought the currrent detainer action.

5. Sale of the premises was consumated before a judgment was rendered
   in the detainer action.

6. A judgment for double rent was entered in the detainer action.

7. The DEF T filed an appeal, alleging errors with various findings
   and fact and conclusions of law that resulted in the judgment of
   double rent.

8. DEF T argued that upon the sale of the premises the unlawful
   detainer action became moot since there was no longer any
   controversy.


** LAW

1. The statutory action for unlawful detainer is a creation of the
   legislature and is a procedure unknown to the common law.

2. The statutory action is summary.

3. the plaintiff must strictly adhere to the statutory procedure.

4. Failure to follow the statute defeats the court's jurisdiction,
   which is limited.

* CASE

Kessler v. Nielsen
Court of Appeals of Washington, Division 1, Panel One. | July 27, 1970 | 3 Wash.App. 120 | 472 P.2d 616

Document Details

Outline
West Headnotes
Attorneys and Law Firms
Opinion
All Citations

washington Citation:

Kessler v. Nielsen, 3 Wn. App. 120, 472 P.2d 616 (1970)

All Citations:

3 Wash.App. 120, 472 P.2d 616

Search Details

Jurisdiction:

Washington

Delivery Details

Date:

February 3, 2024 at 4:39 PM

Delivered By:

Lincoln Harvey

Client ID:

DISMISSAL

Status Icons:



Inline KeyCite:

Inline KeyCite completed successfully.




3 Wash.App. 120
Court of Appeals of Washington, Division 1,
Panel One.
Edgar J. KESSLER, individually and as Administrator of the Estate of Laura Kessler, deceased, Appellant,
v.
Hans E. NIELSEN and Mildred Nielsen, his wife, Respondents.
Hans E. NIELSEN and Mildred Nielsen, his wife, Respondents,
v.
Edgar J. KESSLER, Appellant.
No. 384—I.
|
July 27, 1970.
Synopsis
Consolidated actions by purchaser of realty against vendors for rescission, and by vendors against purchaser for unlawful detainer. The Superior Court, Snohomish County, Paul D. Hansen, J., dismissed purchaser’s complaint and entered judgment for vendors in unlawful detainer action for double the reasonable rent of the property, and purchaser appealed from judgment of double rent. The Court of Appeals, Swanson, J., held that unlawful detainer action by vendors against purchaser for double rent due during time purchaser was in possession of property prior to completion of sale became moot when sale was closed prior to trial of action in that vendors no longer had right to possession and there was no longer issue for judicial determination.

Reversed in part.

Procedural Posture(s): On Appeal.


West Headnotes (6)


[1]

EjectmentForm of action
EjectmentExistence of other remedy


142Ejectment
142IRight of Action and Defenses
142k4Form of action
142Ejectment
142IRight of Action and Defenses
142k5Existence of other remedy


Common-law action of ejectment is separate from and in addition to action for unlawful detainer. RCWA 59.12.030(3).
1 Case that cites this headnote



[2]

Forcible Entry and DetainerNature and Form of Remedy


179Forcible Entry and Detainer
179ICivil Liability
179k6Nature and Form of Remedy
179k6(1)In general


Statutory action for unlawful detainer is summary, and plaintiff must strictly adhere to statutory procedure, and failure to follow statute defeats court’s jurisdiction which is in any event limited. RCWA 59.12.030(3).
7 Cases that cite this headnote



[3]

Forcible Entry and DetainerNature and Form of Remedy


179Forcible Entry and Detainer
179ICivil Liability
179k6Nature and Form of Remedy
179k6(1)In general


Purpose of statutory action for unlawful detainer is to preserve peace by limiting common-law right of personal reentry. RCWA 59.12.030(3).




[4]

Forcible Entry and DetainerIssues, proof, and variance


179Forcible Entry and Detainer
179ICivil Liability
179k22Pleading
179k28Issues, proof, and variance


In forcible entry and detainer action, only issue before court is right to possession, and statutory incidents are dependent on such right. RCWA 59.12.030(3), 59.12.170.
3 Cases that cite this headnote



[5]

Forcible Entry and DetainerDamages
Landlord and TenantDamages and amount of recovery


179Forcible Entry and Detainer
179ICivil Liability
179k30Damages
179k30(1)In general
233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1806Damages and amount of recovery
(Formerly 233k291(14))


Rent or damages may only be recovered under unlawful detainer statute when there is right to possession, and when such right is not present, damages or rent must be recovered in ordinary civil action. RCWA 59.12.030(3), 59.12.170.
14 Cases that cite this headnote



[6]

ActionMoot, hypothetical or abstract questions


13Action
13IGrounds and Conditions Precedent
13k6Moot, hypothetical or abstract questions


Unlawful detainer action brought by vendors of real estate against purchaser for double rent due during time purchaser was in possession of property prior to completion of sale became moot when sale was closed prior to trial of action in that vendors no longer had right to possession and there was no longer issue for judicial determination. RCWA 59.12.030(3), 59.12.170.
5 Cases that cite this headnote



Attorneys and Law Firms
*120 **617 Dailey & Brinster, A. E. Dailey, Everett, for appellant.
Westmoreland, French & Meagher, Benj. L. Westmoreland, Everett, for respondents.
Opinion

SWANSON, Judge.

Hans and Florence Nielsen brought an action against Edgar J. Kessler under the unlawful detainer statute, RCW 59.12.030(3).1 The Nielsens claimed Kessler *121 occupied their premises from January 24, 1969, until August 6, 1969, without the payment of rent. The Nielsens received judgment for unpaid rent computed at the rate of $150 per month. The total, $965, was doubled pursuant to RCW 59.12.170,2 so that the judgment aggregated $1,930.
1

‘A tenant of real property for a term less than life is guilty of unlawful detainer either:
‘(3) When he continues in possession in person or by sub-tenant after a default in the payment of rent, and after notice in writing requiring in the alternative the payment of the rent or the surrender of the detained premises, served (in manner in RCW 59.12.040 provided) in behalf of the person entitled to the rent upon the person owing it, has remained uncomplied with for the period of three days after service thereof. The notice may be served at any time after the rent becomes due; * * *’


2

‘* * * The jury, or the court, if the proceedings be tried without a jury, shall also assess the damages occasioned to the plaintiff by any forcible entry, or by any forcible or unlawful detainer, alleged in the complaint and proved on the trial, and, if the alleged unlawful detainer be after default in the payment of rent, find the amount of any rent due, and the judgment shall be rendered against the defendant guilty of the forcible entry, forcible detainer or unlawful detainer for twice the amount of damages thus assessed and of the rent, if any, found due.’


**618 In a prior lawsuit brought by Kessler, the amended complaint asked for damages equaling the difference in interest rates over the life of an FHA loan. Kessler said he suffered this damage because the Nielsens improperly delayed signing the closing papers in a real estate sale between the parties. The Nielsens cross-claimed for the reasonable rental of the property, alleging the same facts as in the unlawful detainer action. The cases were consolidated for trial, and Kessler’s suit was dismissed for want of proof. The Nielsens received a judgment for $965 which was set off against their judgment in the unlawful detainer action.
These cases had their genesis in the sale to the Kesslers of a home owned by the Nielsens. An earnest money receipt and agreement was signed on December 17, 1968, and the Kesslers took immediate possession. The earnest money receipt and agreement provided in part:
Should the loan fail the purchaser shall be liable for rental of $150 per month during the time he occupies the property.

The parties met in Seattle on January 24, 1969, to close the sale. At this time the Nielsens were told that the mortgage placement fee (discount) would be 9 per cent of the mortgage. Mr. Nielsen learned the same service could be *122 obtained elsewhere at a rate of 5 1/2 per cent, and thus declined to sign the papers. The trial court held that the Nielsens had no legal duty to sign the closing papers on this date. The situation was further complicated by the fact that the FHA loan rate was increased from 6 3/4 per cent to 7 1/2 per cent effective January 24. The Kesslers were obligated to pay this increased rate.
On February 13, 1969, prior to the closing of the sale, Mrs. Kessler died. Mr. Kessler then proceeded to have her estate probated and her interest in the property set aside in lieu of homestead. Prior to the close of probate in July, 1969, the Nielsens made demands on Kessler to close the sale. Failing in this, on May 16, 1969, the Nielsens served on Kessler a statutory 3-day notice demanding past and future rental or surrender of the premises. Kessler answered the notice with a suit for rescission, and the Nielsens brought their detainer action. The sale was consummated on August 6, 1969, before the suits were heard or the judgment rendered.
Kessler neither specifically appeals from, nor assigns error to, the dismissal of his complaint in accordance with CAROA 43. He does assign error to the various findings of fact and conclusions of law which resulted in the judgment for double rent in the unlawful detainer action. Kessler’s argument is that on August 6, 1969, and before the trial, when the sale was closed, the unlawful detainer action became moot, since there was no longer any controversy. See MacRae v. Way, 64 Wash.2d 544, 392 P.2d 827 (1964). The Nielsens argue to the contrary:
To hold that at any time the right to possession is either surrendered to the landlord or given up by the landlord After commencement of the action renders it moot, would be to defeat the very purpose of the statute and encourage defiance of the policy of the law to persuade quick surrender of possession.

[1] [2] The statutory action for unlawful detainer is a creation of the legislature and is a procedure unknown to the common law. Indeed, the common law action of enjectment *123 is separate from and in addition to the action for unlawful detainer. Petsch v. Willman, 29 Wash.2d 136, 185 P.2d 992 (1947); 1 H. Tiffany, Real Property s 180 (B. Jones 3d ed. 1939). The statutory action is summary, MacRae v. Way, Supra; Young v. Riley, 59 Wash.2d 50, 365 P.2d 769 (1961); Petsch v. Willman, Supra, and the plaintiff must strictly adhere to the statutory procedure. Failure to follow the statute defeats the court’s jurisdiction, Sowers v. Lewis, 49 Wash.2d 891, 307 P.2d 1064 (1957); 33 Wash.L.Rev. 165 (1958), which is in any event limited. Little v. Catania, 48 Wash.2d 890, 297 P.2d 255 (1956); Young v. Riley,59 Wash.2d at 52, 365 P.2d at 771:
The right and remedy alike are statutory, and the procedural remedy is an integral **619 part of the right itself. RCW 59.12. In an unlawful detainer action, the court sits as a special statutory tribunal to summarily decide the issues authorized by statute and not as a court of general jurisdiction with the power to hear and determine other issues.

(Footnote omitted.)

[3] [4] [5] The purpose of the statutory action is to preserve the peace, Young v. Riley, Supra, by limiting the common law right of personal reentry. Woodward v. Blanchett, 36 Wash.2d 27, 216 P.2d 228 (1950). In such an action there is only one issue before the court—the right to possession. The statutory incidents are dependent on this right. MacRae v. Way, 64 Wash.2d at 546, 392 P.2d at 829:
In such proceedings the superior court sits as a special statutory tribunal, limited to deciding the primary issue of right to possession together with the statutorily designated incidents thereto, I.e., restitution and rent or damages.

Accord, Motoda v. Donohoe, 1 Wash.App. 174, 459 P.2d 654 (1969); Muscatel v. Storey, 56 Wash.2d 635, 354 P.2d 931 (1960); Petsch v. Willman, Supra; Stevens v. Jones, 40 Wash. 484, 82 P. 754 (1905). Rent or damages may only be recovered under the statute when there is a right to possession. When this right is not present, the damages or rent *124 must be recovered in an ordinary civil action. Stevens v. Jones, Supra.

This discursive preamble brings us to the primary issue of this case—whether or not the Nielsens could receive a judgment for double rent in their unlawful detainer action. As shown above, the right to receive double rent is dependent upon the right to possession. It is undisputed that this property was sold to Kessler on August 6, 1969, and that the action was not tried until September 12, 1969, nor the judgment entered until October 28, 1969. The Nielsens had no right to possession after August 6, 1969. Does this defeat their recovery?
Our research and the parties’ briefs have unearthed no identical Washington case. In Stevens v. Jones, Supra, and MacRae v. Way, Supra, cited by Kessler, the plaintiffs had relinquished their right to possession prior to the commencement of the unlawful detainer actions. The court in both cases ordered dismissal of the actions.
Any claim she may have had for damages could be waged in this summary action only as an incident to her right to possession. The right to damages is a personal one, and when unaccompanied with the right to recover possession must be waged in an ordinary civil action.

Stevens v. Jones, 40 Wash. at 486, 82 P. at 755. Relying on Shannon v. Loeb, 65 Wash. 640, 118 P. 823 (1911); Lochridge v. Natshuhara, 114 Wash. 326, 194 P. 974 (1921); and Sowers v. Lewis, Supra, Nielsens say they are entitled to double rental because they did not relinquish the right to possession until after the action had been started.
The results in these cases appear to support the Nielsens’ contention. Shannon was an action brought under the then equivalent of RCW 59.12.030(1), I.e., holding-over after end of term. The defendant claimed his possession was pursuant to an agreement for a month-to-month tenancy following the expiration of a 3-year term. The defendant occupied the premises for 1 month past the end of the 3-year term and then moved out. Plaintiff was allowed double damages for *125 that month. Possession was relinquished to the plaintiff prior to the trial.
Lochridge was also an action under the holding-over portion of the unlawful detainer statute. Both parties agreed the lease was given an oral extension. The plaintiffs said the extension was for 60 days; the defendants said it was for 1 year. The defendants remained in possession of the property until after the trial under a redelivery bond. The court found the extension was for 60 days and awarded plaintiffs double damages for the period of time between the end of the extension and the cessation of possession.
In Sowers, the complaint stated two causes of action. The first under the failure-to-pay-rent provision, and the second **620 under the breach-of-covenant provision. The defendant moved to quash the proceedings on jurisdictional grounds. A demurrer was entered to the complaint. The trial court entered an order of default. Prior to the default the defendant surrendered possession although a writ of restitution had issued. On appeal it was held the motion to quash and demurrer were good as to the second cause of action.
These cases do not support the Nielsens’ contention. In each one of them the defendants were claiming a right to possession during the period of time subsequently held to constitute unlawful detainer. In Shannon, the defendants asserted their possession was under a month-to-month lease. In Lochridge, the right to possession was claimed under a 1-year extension to the lease. The motion to quash and demurrer in Sowers raised the issue of whether the plaintiff could bring the action, and this included plaintiff’s right to possession. See RCW 4.40.020. Thus, when each of these cases came on for trial, the parties were disputing, and were in a position to dispute, the right to possession.
There is a significant factual difference between those three cases and the case at bar. In those cases the landlords were using right of possession as a sword to oust the tenants. The tenants in turn attempted to establish a contrary right as a shield. Here, the positions are reversed. The sword is in the hand of the tenant Kessler. We are concerned *126 whether the former landlords can assert a legal right on the specter of that sword. The Nielsens, before trial, compromised the right they were attempting to assert by intentionally and unequivocally vesting that right in the person they sought to preclude from possession. On the date the Nielsens sold their property, Kessler’s possession, which was theretofore arguably wrongful, became rightful.
The distinction, then, is between possession and right of possession.
The expression ‘right of possession’ obviously involves an idea different from that of possession. One having the possession quite usually has the right of possession, in the sense that there is no other person able to show a better right, and when the possession and right of possession thus concur, it is ordinarily unnecessary to refer to the right. But one may have a right to the possession as against another who has the possession, as in the simple case of one who has been ousted from the land by another.

1 H. Tiffany, Real Property s 20 (B. Jones 3d ed. 1939). This distinction was used by the court in the Lochridge case relied on by the Nielsens. The plaintiffs-respondents moved to dismiss the appeal on the ground that the question of right of possession was moot. The court answered the motion:
It may be true that at the time of the hearing here the appellants had surrendered possession of the premises and that the question of restitution at this time is not involved, but the appellants’ right to possession is involved, as is also the question of damage which they must pay for any wrongful possession. There is no merit in the motion to dismiss.

114 Wash. at 330, 194 P. at 975. Thus, even though the plaintiffs were in possession at the time of the appeal, the defendants who were still asserting their possessory right had to be precluded as to this right. The action was not moot until this issue had been determined vis-a-vis the parties.
[6] In this statutory action for unlawful detainer, the primary issue, as shown above, is the right to possession. Once *127 the action is brought the defendant, who has not conceded the plaintiff’s right to possession, has the right to have this issue determined. But where, as here, the plaintiff, prior to trial, acts inconsistently with the assertion of right to possession, there is no longer an issue for judicial determination. MacRae v. Way, 64 Wash.2d 544, 392 P.2d 827 (1964). And, where the plaintiff is in no position to litigate this right, no recovery may be had for the statutory incidents.

**621 The statute itself supports this analysis. RCW 59.12.170 provides in part:
If upon the trial the verdict of the jury or, if the case be tried without a jury, the finding of the court be in favor of the plaintiff and against the defendant, judgment shall be entered for the restitution of the premises; * * *

It is incomprehensible that the legislature would order that the courts restore possession to one who could legally assert no right to possession. The unambiguous language of the statute and the rationale of the cases compel us to strike the judgment for double rent entered against Kessler.
As was pronounced in Stevens v. Jones, 40 Wash. at 486, 82 P. at 755:
The right to damages is a personal one, and when unaccompanied with the right to recover possession must be waged in an ordinary civil action.

The Nielsens’ right to recover rent was personal, and the rent was in fact recovered as a cross-claim in Kessler’s action. That judgment must stand. It is supported by the law and the facts. But the judgment for double rent must fall because it was not incident to a right to possession.
JAMES, C.J., and FARRIS, J., concur.
All Citations
3 Wash.App. 120, 472 P.2d 616
End of Document

© 2024 Thomson Reuters. No claim to original U.S. Government Works.
