#+title:      31 Wash.2d 633 Wilson v. Daniels (1948)
#+date:       [2024-02-03 Sat 17:34]
#+filetags:   :jurisdiction:statutory:ud:
#+identifier: 20240203T173419

* BRIEF

* CASE

Wilson v. Daniels
Supreme Court of Washington, Department 1. | October 15, 1948 | 31 Wash.2d 633 | 198 P.2d 496

Document Details

Outline
West Headnotes
Attorneys and Law Firms
Opinion
Concurring Opinion
Dissenting Opinion
All Citations

washington Citation:

Wilson v. Daniels, 31 Wn.2d 633, 198 P.2d 496 (1948)

All Citations:

31 Wash.2d 633, 198 P.2d 496

Search Details

Jurisdiction:

Washington

Delivery Details

Date:

February 3, 2024 at 7:33 PM

Delivered By:

Lincoln Harvey

Client ID:

DISMISSAL

Status Icons:



Inline KeyCite:

Inline KeyCite completed successfully.




31 Wash.2d 633
Supreme Court of Washington, Department 1.
WILSON et ux.
v.
DANIELS.
No. 30539.
|
Oct. 15, 1948.
|
Rehearing Denied Jan. 18, 1949.
Synopsis
Action of unlawful detainer by John Bruce Wilson and Phyllis Wilson, his wife, against Alfred Daniels. From a judgment dismissing the action, the plaintiffs appeal.

Judgment affirmed.

HILL. J., dissenting.



West Headnotes (10)


[1]

Landlord and TenantAcceptance of rent


233Landlord and Tenant
233IVParticular Kinds of Tenancies and Attributes Thereof
233IV(F)Termination
233IV(F)4Waiver of Forfeiture
233k941Acceptance of rent
(Formerly 233k112(2))


If the landlord accepts rent with full knowledge of a breach of terms of the lease, he waives his right to declare a forfeiture for such breach.
3 Cases that cite this headnote



[2]

Landlord and TenantAcceptance of rent


233Landlord and Tenant
233IVParticular Kinds of Tenancies and Attributes Thereof
233IV(F)Termination
233IV(F)4Waiver of Forfeiture
233k941Acceptance of rent
(Formerly 233k112(2))


If, under the provisions of the lease, rent is paid in advance, the landlord is not prevented from declaring a forfeiture for a breach occurring subsequent to the payment of rent and during the term for which the rent is paid.




[3]

Landlord and TenantBreach of Covenant or Condition
Landlord and TenantPayment


233Landlord and Tenant
233IVParticular Kinds of Tenancies and Attributes Thereof
233IV(F)Termination
233IV(F)2Breach of Covenant or Condition
233k910In general
(Formerly 233k103(1))
233Landlord and Tenant
233VIIRent
233VII(A)Rights and Liabilities
233VII(A)8Payment
233k1520In general
(Formerly 233k213(1))


The payment of rent merely gives the tenant the right of possession of the premises during the term, but it does not, during that term, give him the right to violate other provisions of the lease.




[4]

Landlord and TenantAcceptance of rent


233Landlord and Tenant
233IVParticular Kinds of Tenancies and Attributes Thereof
233IV(F)Termination
233IV(F)4Waiver of Forfeiture
233k941Acceptance of rent
(Formerly 233k112(2))


The acceptance of rent waives the right to declare a forfeiture for prior breaches, but it does not operate as a waiver of a continuance of the breaches or of any subsequent breaches.
2 Cases that cite this headnote



[5]

Landlord and TenantAcceptance of rent


233Landlord and Tenant
233IVParticular Kinds of Tenancies and Attributes Thereof
233IV(F)Termination
233IV(F)4Waiver of Forfeiture
233k941Acceptance of rent
(Formerly 233k112(2))


Where landlord was fully aware of all the breaches of lease relied on in notice when he accepted payment of rent, he thereby waived right to declare forfeiture because of such breaches notwithstanding general provision in lease against waiver of covenants, breaches, etc., but he did not thereby lose right to declare forfeiture if such breaches continued or if new ones occurred.
5 Cases that cite this headnote



[6]

Landlord and TenantGrounds of action


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1783Right of Action and Defenses
233k1786Grounds of action
(Formerly 233k290(2))


Under the unlawful detainer statute the tenant must be in default in the particulars enumerated in notice at time notice is served. Rem.Rev.Stat. § 812(4).
5 Cases that cite this headnote



[7]

Landlord and TenantGrounds of action
Landlord and TenantNecessity and sufficiency


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1783Right of Action and Defenses
233k1786Grounds of action
(Formerly 233k290(2))
233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1790Actions
233k1794Demand or Notice
233k1794(2)Necessity and sufficiency
(Formerly 233k291(1))


Under the unlawful detainer statute it is essential that there exist a breach or breaches of the covenants of the lease, that the landlord notify the tenant of the existence of such breach or breaches and give him ten days to correct them, and that the tenant must fail or neglect to correct such breach or breaches before the tenant is guilty of unlawful detainer and the landlord is entitled to possession. Rem.Rev.Stat. § 812(4).
7 Cases that cite this headnote



[8]

Landlord and TenantStatutory provisions


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1782Statutory provisions
(Formerly 233k289)


Unlawful detainer statutes are in derogation of the common law, and must be strictly construed in favor of the tenant. Rem.Rev.Stat. § 812(4).
7 Cases that cite this headnote



[9]

Landlord and TenantNature and form


233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1781Nature and form
(Formerly 233k288)


The proceedings under unlawful detainer statutes are summary in character, and were designed to hasten the recovery of possession and to eliminate the delays incident to common law action of ejectment. Rem.Rev.Stat. § 812(4).
10 Cases that cite this headnote



[10]

Landlord and TenantAcceptance of rent
Landlord and TenantGrounds of action


233Landlord and Tenant
233IVParticular Kinds of Tenancies and Attributes Thereof
233IV(F)Termination
233IV(F)4Waiver of Forfeiture
233k941Acceptance of rent
(Formerly 233k112(2))
233Landlord and Tenant
233VIIIReentry and Recovery of Possession by Landlord
233VIII(D)Actions for Unlawful Detainer
233k1783Right of Action and Defenses
233k1786Grounds of action
(Formerly 233k290(2))


Where landlord accepted rent with knowledge of prior breaches and thereby waived his right to declare a forfeiture of lease because of such prior breaches, he also waived his right to rely on such prior breaches as a basis for setting in motion his statutory remedy of unlawful detainer. Rem.Rev.Stat. § 812(4).
8 Cases that cite this headnote



*634 **497 Appeal from Superior Court, King County; James B. Kinne, judge.
Attorneys and Law Firms
Preston, Thorgrimson & Horowitz, of Seattle, for appellants.
Eggerman, Rosling & Williams and Joseph J. Lanza, all of Seattle, for respondent.
Opinion

SCHWELLENBACH, Justice.

This is an appeal from a judgment dismissing an action for unlawful detainer. We shall refer to appellant husband as the sole appellant.
Since October, 1942, plaintiff had owned and operated ‘The Oasis,’ a night club located at 13747 Aurora Avenue, on the outskirts of Seattle. It had a large dining room that could seat five hundred people. In the center of the room was a dance floor, about thirty feet by ninety feet, surrounded by tables.
On July 8, 1946, plaintiff Wilson entered into a three-year lease with defendant, at a rental of $1,500 a month. The lease contained twenty-eight clauses, Clause 24 of which was as follows:
‘24. The failure or delay of the Lessor to insist upon strict performance of any of the covenants, agreements, stipulations or conditions of this lease, or to exercise any option herein conferred, in any one or more instances, shall not be construed to be a waiver or relinquishment of any such, or any other covenants or agreements, stipulations **498 or conditions, but the same shall be and remain in full force and effect.
‘It is further mutually covenanted and agreed between the parties hereto that no waiver by Lessor of a breach by Lessee of any covenant, agreement, stipulation or condition of this lease shall be construed to be a waiver of any succeeding breach of the same covenant, agreement, stipulation or condition or of a breach of any other covenant, agreement, stipulation or condition.
*635 ‘None of the covenants, terms or provisions of this lease to be kept or performed by Lessee shall be in any manner altered, waived, modified or abandoned, except by written instrument, duly signed and acknowledged before a notary public, and delivered by Lessor, and nor otherwise.
‘Each and all of the various rights, remedies, elections and recourses of the Lessor provided for in this lease, or created by law, shall be construed as cumulative, and no one of them as exclusive of the others, or as exclusive of any rights, remedies, elections or recourses now or hereafter allowed or conferred by law or in equity.’
The defendant experienced difficulty in paying his rent, and on October 22, 1946 an agreement was entered into between the parties modifying the prior lease. Under the modification agreement, the rent was to be reduced to $1,200 for each of the months of November, and December, 1946 (of which $1,000 a month was to be then paid) and February, March, April, May June and July, of 1947. Defendant was to conduct a special New Year’s Eve celebration on the evening of December 31, 1946. Out of the net proceeds of this celebration the lessee was to pay $400 as the balance due for November and December, and $2,000 as rent for January. If the net proceeds exceeded $4,800, a further sum equal to fifty per cent of the excess was to be paid as additional rent for January.
The defendant did not pay his rent (under the terms of the lease, payable in advance on the first day of each month) due on November 1st. He was served with the statutory three-day notice to pay or vacate the premises, and he paid on November 8th or 9th.
About ten days prior to December 7th, plaintiff noticed that certain provisions of the lease were being violated. The dance floor was warped, due to seepage of water as the result of an ice carnival which had been there. The neon sign was in disrepair; the septic tank was overflowing; the carpeting was badly cut; the rubber matting at the entrance to the kitchen was cut to shreds; the kitchen walls were dirty; some dishes were broken. Perhaps the most *636 distressing part of the whole affair, to Mr. Wilson’s mind, was the deterioration of the clientele of this high-class night club. Mr. Wilson testified that he noticed men dancing without their coats, and that the ladies were of a different quality than when he operated it.
About this time he was advised by the office of the Collector of Internal Revenue that Daniels had not paid his taxes and that they were going to step in and take the proceeds of the New Year’s Eve celebration. It was proved that at this time Daniels was insolvent.
Daniels did not pay his rent due December 1st, and on December 2nd he was served with notice to pay the rent by midnight December 6th, or vacate. The rent was paid on the evening of December 6th. It was done by the payment of $250 cash and a check for $750. The next morning the check was cashed, immediately after which, the notice involved in this action, under the provisions of Rem.Rev.Stat. § 812(4), was served on him. Omitting the formal parts, that notice is as follows:
‘Notice Is Hereby Given that you have neglected and failed to keep and perform the conditions and covenants of said lease, and that you are in default for violation thereof in the following respects:
‘1. You have violated paragraph 5 of said lease in that you have failed to operate and conduct the restaurant, cafe and cabaret business required to be operated by you along the same standards and under the same policies as said business was operated by the lessor prior to the execution of said lease. You have failed to maintain or keep the staff of employees previously employed by the lessor, and have permitted the premises to be patronized by disreputable and **499 dissolute persons, with the result that the reputation of said business has been materially and irreparably damaged.
‘2. You have failed to carry on the business undertaking of operating said restaurant, cafe and cabaret business diligently, assiduously or energetically.
‘3. You have violated paragraph 12 of said lease in the following respects:
‘(a) You have permitted the spring dance floor to be materially and irreparably damaged, and have failed to *637 repair the same, although request has been made for such repairs by the lessor.
‘(b) You have failed to keep the exterior of said premises in a clean condition.
‘(c) You have permitted the Neon displays to go out of repair and you have failed to repair the same.
‘(d) You have neglected to repair the sewer connections.
‘(e) You have failed to repair the wall in the men’s rest room.
‘(f) You have caused undue wear upon the rugs and have failed to properly clean them, with the result that material and irreparable damage has been caused thereto.
‘(g) You have failed to replace the rubber matting at the entrance of the kitchen.
‘(h) You have failed to keep the kitchen walls in a clean and sanitary condition and have failed to take the proper steps to keep the same in a sanitary and efficient state of repair.
‘(i) You have failed to replace breakage in the glassware and dishes used in the operation of said business and you have further failed to replace silverware which has become damaged or which has been lost.
‘4. You have violated and have permitted yourself to become in default of the provisions of paragraph 20 of said lease wherein it is provided that ‘in the event lessee becomes insolvent * * * this lease shall be void if the lessor shall so elect.’ Such insolvency consists of the following matters:
‘(a) You have failed and refused to report and pay to the Collector of Internal Revenue of the United States sums due and payable to him covering withholding taxes on amounts withheld from employees for payment of income tax, and Federal Cabaret Taxs in an amount exceeding $9,000.
‘(b) You have failed and refused to pay amounts due to the County of King, State of Washington for County Cabaret Taxes covering such tax collected from patrons in an amount exceeding $500.
‘(c) You have failed to pay amounts due to the Puget Sound Power & Light Company for electricity furnished to said premises in an amount approximating $400.00.
‘(d) You have failed to pay amounts due for water and gas furnished to said premises, the exact amounts whereof are unknown to the undersigned.
*638 ‘5. By reason of the amounts owing by you to the Collector of Internal Revenue as aforesaid, it appears that you will be unable to perform the terms and conditions of the agreement modifying the lease, dated October 22, 1946, wherein it is provided that the undersigned is to receive the first $2,400 of the net proceeds received with respect to the business operated on said leased premises on New Year’s Eve, December 31, 1946, in that the Collector of Internal Revenue has indicated that he intends to impound all of the proceeds of said business on said occasion in the event that the amounts owing to the Collector of Internal Revenue as aforesaid shall not have been paid.
‘6. You are in default of the provisions of paragraph 28 of said lease in that you have failed to comply with the laws and regulations of the Government of the United States, the State of Washington, and the County of King, by failing to report and pay withholding taxes, Federal Cabaret Tax and County Carbaret Tax as provided by law.
‘The foregoing enumeration of defaults is not intended to exclude any other defaults there may be, and the existence of which defaults the undersigned lessor may not be aware of, and the failure to mention any such additional grounds of default shall not be deemed or construed to constitute a waiver of the lessor’s rights under this lease on account thereof.
‘Notice Is Further Given that you are hereby required to remove the foregoing **500 defaults and fully perform each of the covenants of said lease which have heretofore been broken by you as hereinabove set forth within ten (10) days after the service of this notice upon you, and you are further informed that in the event of your failure to correct said defaults and to perform said covenants within the said period of ten (10) days, you will be required to remove from and deliver up the possession of said premises to the undersigned within the said ten days, and in the event of your failure so to do the undersigned will institute legal proceedings against you to recover possession of the said premises, to declare a forfeiture of said lease, and to recover double damages and rents.
‘Dated at Seattle, Washington, this 7th day of December, 1946.
[signed] ‘John Bruce Wilson, Owner’
The plaintiff testified:
‘Q. Now, Mr. Wilson, did you have occasion to examine the premises shortly before you served this notice to remedy conditions or quit? A. Yes.
‘Q. Approximately when did *639 you examine the premises with relation to that notice? A. The latter part of November and the first part of December.’ and again:
‘Q. Will you fix the time which you’re testifying about at this time? A. Well, I did say, your Honor, that it was the latter part of November or the first part of December.
‘The Court: I understood you to say sometime after the notice was given.
‘Q. Let’s get it clear for the record. This was prior to the giving of the notice? A. It was prior to the giving of the notice.
‘Q. It was a week or ten days prior to the giving of the notice? A. That’s right.’
Under cross-examination he testified:
‘Q. Now, at the time you gave this notice to pay rent or surrender the premises, you knew of each and every one of these violations that you contended later were grounds for forfeiture of the lease, didn’t you? A. Yes and no. I knew of them, but the extent of the damage, I didn’t know how much it was, no.
‘Q. But, nevertheless, you knew everything that was in your notice as of December 2, didn’t you, when you gave this notice? A. Partially, yes.
‘Q. Well, is there any part of it you didn’t know? A. Well, as I said before, the extent of the damage.
‘Q. That’s the only thing? A. That’s right.’
As to cashing the check, he testified:
‘Q. You recall cashing it the next morning, didn’t you? A. Yes, sir.
‘Q. And was that before your attorneys had prepared this notice to forfeit the lease? A. I think the notice was being prepared at the time.
‘Q. At the time, yes. A. Yeah, starting in the morning, yes.
‘Q. You had advised them to go ahead and prepare the notice? A. I think I did, yes.
‘Q. Just before you cashed the check or after? A. I don’t remember whether it was before or after, to be honest with you.’
[1] [2] [3] [4] Certain rules of law with relation to the right of forfeiture under a lease are well established. If the landlord accepts rent with full knowledge of a breach of the terms of a lease, he waives his right to declare a forfeiture for such breach. If, under the provisions of the lease, rent is paid in advance, the landlord is not prevented from declaring a forfeiture for a breach occurring subsequent to *640 the payment of rent and during the term for which the rent is paid. The payment of rent merely gives the tenant the right of possession of the premises during the term, but it does not, during that term, give him the right to violate other provisions of the lease. Although the acceptance of rent waives the right to declare a forfeiture for prior breaches, it does not operate as a waiver of a continuance of the breaches or of any subsequent breaches. The rule is thus stated in 32 Am.Jur. 754,32 Am.Jur. 754, Landlord and Tenant, § 890: ‘If a covenant or condition for forfeiture is not a continuing one or is not **501 capable of a continuing or a subsequent breach, a waiver of forfeiture for breach of such covenant or happening of such condition will, of course, operate to prevent any future claim of forfeiture. In other words, the waiver of a forfeiture by acceptance of rent applies to past breaches, which are single and complete when the rent is accepted, and having been once waived the landlord’s rights are lost. But the general rule is that a waiver of a right of forfeiture for breach of a covenant in a lease does not operate as a waiver with respect to a continuance of the breach, where the breach is a continuing one, and it does not operate as a waiver of the right of forfeiture for a subsequent breach of the covenant.’

This court, in Schultz v. Cardwell, 142 Wash. 489, 253 P. 822, 824, said:
‘Appellants contend that by thus taking rent respondents kept the lease alive and waived all breaches, and that they are not in position to claim a termination of the lease. They cite a number of authorities tending to support their view. In Field v. Copping, Agnew & Scales, 65 Wash. 359, 118 P. 329, 36 L.R.A.,N.S., 488, we said:
“The acceptance of rent eo nomine is ordinarily a recognition of the continuance of the tenancy, and where it is accepted after and with knowledge of the act of forfeiture by the tenant, it is a waiver of the forfeiture.’
‘The general rule is well stated in 16 R.C.L. 1132, as follows:
“The most familiar instance of the waiver of the forfeiture of a lease arises from the acceptance of rent by the landlord after condition broken, and it is a universal rule that if the landlord accepts rent from his tenant after full notice or knowledge of a breach of a covenant or condition in his lease for which a forfeiture might have been demanded, *641 this constitutes a waiver of forfeiture which cannot afterward be asserted for that particular breach or any other breach which occurred prior to the acceptance of the rent. In other words, the acceptance by a landlord of the rents, with full knowledge of a breach in the conditions of the lease, and of all of the circumstances, is an affirmation by him that the contract of lease is still in force, and he is thereby estopped from setting up a breach in any of the conditions of the lease, and demanding a forfeiture thereof.’
‘On the other hand, respondents take the position that, while the foregoing authorities state the general rule, there is an exception to the effect that where the breach is a continuing one, no waiver or estoppel takes place because of the landlord taking rent. This exception to the rule is stated in 16 R.C.L. 1136, as follows:
“If the covenant or condition for forfeiture is not a continuing one and thus capable of a continuing breach, a waiver will of course operate to prevent any future claim of forfeiture. On the other hand, where it is of a continuing nature and a breach is waived, as by the acceptance of rent, this applies only as to past breaches, and the landlord is not thereby precluded from taking advantage of a forfeiture resulting from a subsequent or continued breach. Thus where a mining lease provides for its forfeiture for cessation of work for a specified time, the acceptance of rent after cessation for such time will not preclude the enforcement of a forfeiture for a continued cessation.”
Appellant contends that, because of the provisions of Clause 24 of the lease, hereinbefore quoted, the acceptance of the rent could not constitute a waiver of prior breaches. Appellant would be correct in his contention if the lease and contained an express stipulation between the parties that the lessor’s receipt of the rent should not prejudice his right to forfeiture because of any prior breaches. This was the situation in Re Wil-Low Cafeterias, 2 Cir., 95 F.2d 306, 308, 115 A.L.R. 1184, where the lease provided: “The consent of the lessor in any instance to any variation of the terms of this lease, or the receipt of rent with knowledge of any breach, shall not be deemed to be a waiver as to any breach of any covenant or condition herein contained, nor shall any waiver be claimed as to any provision of this lease unless the same be in writing, signed by the lessor or the lessor’s authorized agent.”
*642 In Vintaloro v. Pappas, 310 Ill. 115, 141 N.E. 377, the landlord, after serving a notice **502 of forfeiture, received the rent monthly until the trial a year later. The lease provided: “It is further agreed by the parties hereto that after the service of notice or the commencement of a suit, or after final judgment for the possession of said premises, the lessor may receive and collect rent due, and the payment of rent shall not waive or affect said notice of suit or judgment.”
It was held that, because of the express stipulation in the lease, the landlord did not waive his right of forfeiture.
In the case at bar, Clause 24 of the lease was general in its terms. There was no express stipulation by the parties that the acceptance of rent did not constitute a waiver of any prior breaches.
[5] When the rent was accepted on December 6, 1946, appellant was fully aware of all of the breaches alleged in his notice. By accepting the rent, he waived his right to declare a forfeiture because of the prior breaches. He did not thereby lose such right in the event that those breaches continued, or new ones occurred. However, he did not wait for the old breaches to continue or new ones to occur. He immediately served the notice. With his right hand he accepted the rent and with his left hand he served the notice. The two acts were practically simultaneous. At that time no old breach had continued, nor had any new breach occurred.

It must be remembered, however, in the case at bar, that appellant did not declare a forfeiture of the lease. Instead, he resorted to the statutory remedy of unlawful detainer under the provisions of Rem.Rev.Stat. § 812(4), P.P.C. 55–5, as follows: ‘When he continues in possession in person or by subtenant after a neglect or failure to keep or perform any other condition or covenant of the lease or agreement under which the property is held, including any covenant not to assign or sublet, than one for the payment of rent, and after notice in writing requiring * * * in the alternative the performance of such condition or covenant or the  *643 surrender of the property, served (in the manner provided in this act) upon him, and if there be a subtenant in actual possession of the premises, also upon such subtenant, shall remain uncomplied with for ten days after service thereof. Within ten days after the service of such notice the tenant, or any subtenant in actual occupation of the premises, or any mortgagee of the term, or other person interested in its continuance, may perform such condition or covenant and thereby save the lease from such forfeiture; * * *’
We are therefore confronted with the problem of determining whether or not the acceptance of the rent, which constituted a waiver of the right to declare an immediate forfeiture of the lease, also constituted a waiver of the right to serve the notice under the unlawful detainer statute, without waiting for the old breaches to continue or new ones to occur. By accepting the rent, the old breaches were not wiped out. The landlord merely waived his right to declare a forfeiture because of them.
[6] [7] However, under the statute, at the time the notice is served, the tenant must then be in violation of the provisions of the lease enumerated in the notice. We held in Thisius v. Sealander, 26 Wash.2d 810, 175 P.2d 619, that the purpose of the notice was to apprise the tenant of the defaults claimed in order to give him the opportunity to correct them within the time allowed in the notice. These things must occur before relief can be obtained under the statute: There must exist a breach or breaches of the covenants of the lease; the landlord must notify the tenant of the existence of such breach or breaches, and give him ten days to correct them; the tenant must fail or neglect to correct such breach or breaches. The tenant is then guilty of unlawful detainer, and the landlord is entitled to possession.

[8] [9] Since unlawful detainer statutes are in derogation of the common law, they must be strictly construed in favor of the tenant. The proceedings are summary in character. By reason of provisions designed to hasten the recovery of possession, the statutes creating it remove the necessity to which the landlord was subjected at common law, of bringing *644 an action of ejectent with its attendant delays and expenses. **503 52 C.J.S., Landlord and Tenant, § 752, pages 610, 611.

[10] Having in mind that these statutes are strictly construed, and that they are designed to hasten the recovery of possession, we are of the opinion that when the landlord accepts the rent, with knowledge of prior breaches, thereby waiving his right to declare a forfeiture of the lease because of such prior breaches, he also waives his right to rely on such prior breaches as a basis for setting in motion his statutory remedy of unlawful detainer. He must wait until the old breaches continue or new ones occur.

The judgment is affirmed.
MILLARD and SIMPSON, JJ., concur.


MALLERY, Chief Justice (concurring in result).

I concur with the result of the majority because I think that the acceptance of rent by a landlord waives all existing breaches (including continuing ones) for the period of occupancy for which the tenant has paid.


HILL, Justice (dissenting).

My sympathies are with the respondent Daniels and I should like to join with the majority in an affirmance, but I am much concerned lest we let a hard case make some bad law.
By the majority opinion, we add two new propositions to the law of landlord and tenant, and I am not in accord with either of them.
First: To the rule that the acceptance of rent with knowledge of the breach of covenants on which a forfeiture might be predicated is a waiver of the right of forfeiture for such breaches, we now add: even though there be a continuing breach of a continuing covenant, unless the breach continues for some substantial time subsequent to the acceptance of the rent.
There is a generally recognized exception to the rule that the acceptance of rent with knowledge of the breach of covenants is a waiver of the right of forfeiture for such breaches. The exception applies when the covenants breached are continuing covenants and the breaches are *645 continuing breaches. The majority recognizes this exception but says that the lessor must wait until the old breaches have continued beyond the time of the acceptance of the rent. The question which the majority does not attempt to determine is how long the old breaches must continue.
Among others, we have a covenant in the lease here under consideration to keep the premises ‘in good order, condition and repair.’ The authorities agree that a covenant to keep in repair is the best illustration of a continuing covenant, and that failure to keep in repair is a continuing breach. The majority says that, because the rent was paid one evening and notice to remedy the breach of the covenant to repair (among others) was given the following morning, the lessor was not entitled to insist that the breach of the covenant to keep in repair be remedied within ten days. Should he have waited two days, three days, a week, or ten days after accepting the rent before giving ten days’ notice to remedy the breach of the covenant to repair or to surrender possession of the premises? Unless we recognize that a continuing breach has continued when a second has passed after the payment of rent, we leave it to be determined in each individual case when a continuing breach begins to continue after the payment of rent.
It is true that in this case the interval between the payment of rent and the serving of notice that the continuing breach must be remedied was very brief. The reasoning that would say that it was not sufficient is like unto that of the lady who sought to excuse the fact that she had given birth to an illegitimate child by saying that, after all, it was such a little one. The fact that the breach of the covenant to repair continued after the rent was paid seems to me apparent and inescapable.
Second: To the rule that the acceptance of rent with knowledge of the breach of covenants on which a forfeiture might be predicated is a waiver of the right of forfeiture for such breaches, we now add: and it is likewise a waiver of the right, under the unlawful detainer statute ( **504 Rem.Rev.Stat. § 812(4)), to give ten days’ notice to *646 keep or perform a continuing covenant of which there is a continuing breach.
It must be noted that the continuing breach of a continuing covenant existed subsequent to the payment of the rent in this case, and that the lessor gave the lessee, by the notice he served under the provisions of Rem.Rev.Stat. § 812(4), ten days within which to remedy the breaches or to surrender possession of the premises. The breaches had continued during the interval of time, however short, between payment of the rent and the serving of the statutory notice or demand that they be remedied. They could have been remedied at any time within that ten-day period. I see no reason why a lessor may not insist, after an acceptance of rent, that the continuing covenants of a lease, such as a covenant to keep in repair, be enforced, or why he may not utilize the provisions of the unlawful detainer statute to secure that enforcement.
The judgment of dismissal with prejudice should be reversed, with direction to enter judgment in favor of the appellants. If there are such equities as to prevent a forfeiture, the respondent could then avail himself of the provisions of Rem.Rev.Stat. § 830.
All Citations
31 Wash.2d 633, 198 P.2d 496
End of Document

© 2024 Thomson Reuters. No claim to original U.S. Government Works.
