#+title:      Fair Credit Reporting Act - FCRA
#+date:       [2024-11-13 Wed 08:42]
#+filetags:   :credit:fcra:law:
#+identifier: 20241113T084226

* About the FCRA

The Fair Credit Reporting Act (FCRA for short) is a federal law that
protects consumers. The credit “bureaus,” aka credit reporting
agencies (CRAs for short) are required to have reasonable procedures
in place to ensure the maximum possible accuracy of the information
they keep and share about you.

The FCRA also obligates entities like banks and other furnishers of
information to reinvestigate in response to a consumer dispute. Keep
reading to find out more about disputes.

* FCRA Statutes

* FCRA Web Sites
** SaraEllen Hutchison
- [[https://saraellenhutchison.com/][Home on the Web]]
- [[https://saraellenhutchison.com/disputes/][Credit Report Disputes]]
** Consumer Financial Protection Bureau
[[https://www.consumerfinance.gov/][Link]]

We're the Consumer Financial Protection Bureau (CFPB), a
U.S. government agency that makes sure banks, lenders, and other
financial companies treat you fairly.

* Credit Report Disputes

** About Disputes

Inaccurate info on your credit report? The FCRA gives consumers the
right to dispute it.

In most situations, “inaccurate” means objectively wrong, such as
information that belongs to someone else, or information that is yours
but otherwise false.

For example, if your credit file is mixed up with someone else, you
might see a different name, or debts you don’t recognize. If you are a
victim of identity theft, it might be in your name, but there could be
addresses and accounts that are unfamiliar.

Inaccurate info also includes things like a mortgage or credit card
that is yours, but the status of it is messed up. For example, it
might report as 120 days late even though you did not miss any
payments.

The dispute process follows three basic steps.

** Steps

*** Consumer Disputes

The first step is a consumer dispute, by you, the consumer, to the
credit reporting agencies. It's best to do this in writing, and not by
phone or online, because then you can tell your whole story. It's also
best to do this yourself, and not pay someone else (like a credit
repair shop) because rarely will that be a thorough, detailed dispute.

**** How to Get a Credit Report

- Go to [[https://www.annualcreditreport.com/index.action][annualcreditreport.com]].

- When you go to annualcreditreport.com, do not sign up for any
  subscription, membership, service, or account with any of the big
  three credit reporting agencies (Equifax, Experian and Trans
  Union). They’re not necessary.

- It’s not necessary to purchase the FICO score.

- Save page of each of those three credit reports, saved as PDF files
  where all the text is contained within the page and is not cut off.

- You might need to adjust down to 85% or 90% before saving the file
  as a PDF from the print window so that the text isn’t cut off. I
  have seen this be an issue with Trans Union in particular, so
  eyeball it before you send it to me.

- If you have Credit Karma or some other kind of credit report, save
  those too, but it often isn’t enough. So, get your *current* credit
  reports at annualcreditreport.com.

- If you have trouble getting the credit reports or the screening
  questions are wholly unfamiliar to you, make note of that too,
  because there may be a legal right of yours that’s being violated.

- [[https://www.annualcreditreport.com/manualRequestForm.action][You can also get a mail-in form here]].

- And finally, if you have what’s called a “tri-merge” credit report
  (typically you get these from a mortgage lender) ask if they’ll give
  it to you. Sometimes mortgage lenders will claim they are not
  allowed to give you a copy of those. That’s not true. They are
  simply not required to give you a copy of the report, but it is
  permitted. In any event, they are required to send you disclosure of
  your credit score and the factors that led to the credit decision,
  called an *Adverse Action notice*.

**** How to Dispute

***** About

First let’s dispel some common misunderstandings about the
process. Contrary to popular belief, if there is false information on
your credit report, the last thing in the world you need is “credit
repair.”

One of the worst things you can do is pay someone else to dispute for
you, because a form letter sent by a credit repair shop is often
treated as frivolous or suspicious, which doesn’t help.

One of the best things you can do is do your own disputes IN WRITING,
on paper, (snail) MAILED, and not online or by phone, even though that
seems faster and like less work. (Trust me, it’s not.)

Disputes are appropriate under most circumstances before you should
sue a credit reporting agency, and are always necessary before you can
sue a furnisher under the Fair Credit Reporting Act.

If you’re reading this, you probably already know that there’s
something on your credit that is false. But it’s always best to get
your credit reports from the most official source for free and
complete credit reports, [[https:annualcreditreport.com][annualcreditreport.com]], so you can be fully
informed of the problem.

***** How to Do Dispute

- In WRITING, via CERTIFIED MAIL.

- The CFPB has more detailed instructions and a sample letter for
  disputing inaccurate info on your credit reports [[https://www.consumerfinance.gov/ask-cfpb/how-do-i-dispute-an-error-on-my-credit-report-en-314/][here]].

- The only advice CFPB offers that I disagree with is the advice to
  dispute by phone or online.

- Disputing by phone or online is actually a terrible idea when the
  circumstances surrounding your dispute don’t fit into the
  overly-basic categories the credit reporting agency has in its phone
  system or online dispute system.

- _Only a written letter sent via certified mail will permit you to
  explain how and why the information on your credit report is false_.

- The entities who report information to the credit reporting agencies
  (such as banks) are required to delete any unverifiable
  information. It is possible that they will cease credit reporting of
  the false information but still hold you responsible for repayment,
  but your consumer rights and contract defenses under state law would
  still apply to you.

- *But, if the entity reporting something on your credit keeps
  reporting it after you dispute to the credit reporting agencies*, you
  may have a Fair Credit Reporting Act claim against whoever is
  reporting it. And in most situations, these disputes are a
  necessary first step before it’s a wise idea to bring a lawsuit.

***** What Happens After Mailing Dispute?

The credit reporting agencies are generally obligated to reinvestigate
your dispute. If you are disputing a creditor's information, they are
required to send all relevant information you include with your
dispute to the creditor (called the "furnisher" in FCRA-speak).

***** False Information is Preventing Housing

I get it. It's a dumpster fire!  Very rarely, if a person is a victim
of a mixed credit file, and it's obvious (to me, after my analysis)
that the false information originated with the credit reporting agency
or background check company, it's okay to sue without first
disputing. You might have other claims that are ripe and ready to go
based on the conduct of some entity that's between you and a house or
job.  But, I only recommend this when people need their problem solved
urgently and it's like burning money to wait. Litigating these
situations with emergency strategies is not ideal. 99% of the time I'm
gonna tell you to dispute first.

***** Important Documents

Consumer protection and Fair Credit Reporting Act cases are document
heavy. Below is a list of the important kinds of documents you should
keep in a safe place, and well-organized, depending on the nature of
your issue.

****** Inaccurate Credit Report or Background Check

- Credit reports (every page!)
- Documents showing your credit score
- Written disputes to credit reporting agencies
- Responses from the credit reporting agencies explaining what they did with your dispute
- Mail receipts, showing mail tracking numbers
- Police report
- FTC identity theft affidavit
- Written documentation that you don't owe the debt
- Credit denial paperwork
- Text messages or emails with your lender stating why you won't be approved

****** Identity Theft

- Credit reports (every page!)
- Documents showing your credit score
- Written disputes to credit reporting agencies
- Responses from the credit reporting agencies explaining what they did with your dispute
- Mail receipts, showing mail tracking numbers
- Police report
- FTC identity theft affidavit
- Written documentation that you don't owe the debt or that you are a different person
- Credit denial paperwork
- Text messages or emails with your lender stating why you won't be approved

****** How to Organize Documents

- If I have invited you to do a consultation with me, I need all
  documents as PDF files, which you can email to me or I can send you
  a secure Sharefile link.  Do not give me a Google Drive or Microsoft
  One Drive link.
- I will not login to any account for you, and I’m not able to see
  your credit report or other document from just a URL. You need to
  save anything I’ve requested or that you want me to see as a PDF
  file.
- For multi-page documents (like credit reports), do not send me
  dozens of PNG files (screenshots) that then I have to figure out
  like a 1000-piece jumbo puzzle.
- I realize for some kinds of evidence or documentation, screenshots
  might be the only way to capture something. That’s ok, just clearly
  date and name the file so I know what it is and when it happened.
- Do not forward emails to me, because I do not want to become part of
  the email “chain.” Instead, save emails as PDF files.
- I also want to see each page of whatever document it is. Not just
  the page of the credit report with the inaccurate stuff; the entire
  credit report. I look for things that are not obvious.

****** How to Save a PDF of a Web Page?

Looking to save a copy of a web page? Your web browser can likely “print” the page to a PDF.

Both Windows 10 and macOS have the built-in ability to print to a PDF.

******* Windows users
- Open the print menu by pressing Ctrl+P.
- Under the “Printer” drop-down menu, select “Microsoft Print to PDF”
  or “Save as PDF”. (The exact wording may vary by browser.)
- Click “Print”.
- When prompted, choose where you want to save the file.
- If you're on an older version of Windows that does not have the
  built-in Microsoft Print to PDF printer, the Google Chrome browser
  provides its own “Save as PDF” option.

******* Mac users
- Open the print menu by pressing Command+P.
- From the PDF drop-down menu (in the lower-left corner), choose “Save
  as PDF”. (In Chrome you may be able to skip this step and select
  “Open PDF in Preview”.)
- When prompted, choose where you want to save the file.


****** How to make a PDF on iPhone

[[https://www.macworld.com/article/673649/how-to-create-a-pdf-on-iphone.html][Link]]

You can turn any type of document into a PDF on iPhone in seconds, and
since the functionality is built into the Share option you don’t need
third-party apps to get started. Here’s how to convert to PDF on
iPhone or iPad.

For most documents (web pages and more) you can chose the Markup
option:

- Tap the /Share/ button.
- Choose /Markup/.
- You can draw or write on the PDF, or just tap Done.
- Choose /Save File To…/ and select the location and filename for your
  PDF.


Some file types, like images, don’t give you the Markup option. For
those, you can use the print preview to create and save a PDF:

- Open the document or image file and tap the Share button.
- Choose Print.
- You’ll see an interface to select your printer and number of copies,
  with a preview at the bottom. Long-press on the preview.
- The preview will pop up on your screen. Tap it to select it and a
  PDF will be created.
- Use the Share button on the lower left of the PDF preview to copy,
  save as a file, or send it to someone.

****** How to scan documents on iPhone

Sometimes, you need to turn a piece of paper into a digital
file. Maybe you need to include a receipt, registration, or other form
of proof in an online form. Or, you want to keep copies of your
important documents in the cloud, so they’re always accessible and
safe from being lost or destroyed. Such documents are often digitized
as Portable Document Format files (or PDFs).

It used to be that you needed to use either dedicated hardware or a
third-party iPhone app to take a photo of a document and convert it to
PDF. That is no longer the case: Apple includes a very handy document
scanner in the iPhone’s Notes and Files apps, and it does a
surprisingly good job of capturing most documents and converting them
to PDF. Because it’s not very obvious, you’d be forgiven for not even
knowing it exists.

Here’s how you scan documents using an iPhone. We also cover how to
convert the scan into a PDF and how to autofill the PDF on an iPhone.

******* How to scan a document on iPhone using Notes

- Open the Notes app.
- Create a new Note or select an existing one.
- Tap the camera button and select Scan Documents.
- Hold your iPhone over your document until it is highlighted. Try to
  get it as level and square as possible.
- Either hold your iPhone (or iPad) still until the scan captures
  automatically or press the shutter.
- Depending on whether you are happy or not choose Retake or Keep Scan.
- Unhappy with the scan? There are two modes: if you use Auto (the
  word Auto appears in the upper-right corner), Notes captures a page
  whenever it detects a document. Most of the time the results are
  pretty accurate, but if they aren’t good enough you can switch to
  Manual by tapping Auto in the top right, then you can drag the
  corners to adjust the scan until you are happy. Keystoning will be
  applied. (Keystoning is the effect of a rectangle appearing to be a
  different shape when not captured—or projected as with a slide
  projector—absolutely squarely.)
- Once you are happy with the scan, tap Keep Scan.
- Continue scanning until all pages are captured, or tap Save.
- Notes will attempt to extract some text at the top of the document
  to use as its title.

******* How to turn a scan into a PDF on iPhone

The method above allows you to scan a document into Notes, which is
useful if you want to store your scans in Notes. But what if you’d
rather store it as a PDF?

Luckily if you save the scan it will automatically save as a PDF.

- Open a Note containing a scanned document.
- Beside the scanned document tap on the arrow.
- Choose Save to Files.
- Select a folder within Files in which to save a PDF of the scan.
- Give the file a name (and tags if you wish) at the bottom of the
  screen.

This will save the scan as a PDF.

******* How to scan a PDF on iPhone

You don’t have to save your scan in Notes, you can also scan directly
into Files, where your document will automatically be saved as a PDF.

- Open Files on your iPhone (or iPad).
- Choose a location to save your scan.
- Tap the more button (…) in the upper right, and choose Scan Documents.
- Line up your document and tap the shutter, or hold the iPhone still
  to automatically capture the image. If you use the shutter, you can
  drag the corners to adjust.
- Once you are happy tap Keep Scan.
- Add additional scans if required and tap Save when you’re done.
- The scan will be saved in your chosen location as a PDF, and likely
  named “Scanned Document.” The name will be highlighted so you can
  easily change it.


******* How to fill in a PDF on iPhone

Now that you have your PDF scanned onto your iPhone it is easy to fill
it in. In fact, your iPhone can even use AutoFill to complete some
parts of the PDF.

- Once scanned the PDF will invite you to AutoFill Form, this iOS 17
  feature means that details like your name, address and other
  information can be automatically filled in (as long as you have
  previously added it to your Contact Card. See how to autofill
  passwords, names and addresses.
- You can then fill in details by tapping on the fields. To add text
  tap on the pencil icon at the bottom right.
- When you tap in the signature box the software will recognize that a
  signature is required and you can easily add a signature if you have
  one saved, or you can add or remove a signature.


You might find it easier to fill in a PDF on a Mac, read:
[[https://www.macworld.com/article/672595/how-to-edit-a-pdf-on-mac.html][How to edit a PDF on Mac.]]

**** Identity Theft

If you are a victim of identity theft, it can be frightening and
overwhelming. You must act quickly to shore up your finances, dispute
unauthorized transactions, report the fraud and theft to law
enforcement, and freeze your credit reports so fraudsters can’t open
up more fake accounts in your name.

Even though your local law enforcement might not do anything to help
you, it’s vital that you file a report with them and then get a copy
of the report. Why? Because your willingness to report to the police
under risk of prosecution for filing a false report bolsters your
credibility when you are dealing with banks and the credit reporting
agencies.

Attaching a police report with your dispute to the credit reporting
agencies also triggers certain important rights that ID theft victims
have. When you send in a police report with your dispute, credit
reporting agencies are required to promptly block fraudulent accounts
from appearing on your credit reports, and notify the other credit
reporting agencies of the issue.

Here are some links to law enforcement agencies in Western Washington:

[[https://www.atg.wa.gov/guardit.aspx][Live elsewhere in Washington State? Check out the Attorney General’s
page]], and call your local police to be directed to the right place.

It can also be helpful to include an [[https://www.attorneygeneral.gov/wp-content/uploads/2017/12/pdf-0094-identity-theft-affidavit.pdf][FTC identity theft affidavit]]
along with your credit report dispute.

Again, just like I’ve said elsewhere on this page, it’s really
important to do your dispute in writing and not online or by phone.

Many banks and debt collectors will make you jump through the hoop of
giving them a police report or filling out a fraud packet. They might
still not decide in your favor, but it’s critical for your case
against them to have a good paper trail. So save copies of everything,
and save your mail receipts!

There is a comprehensive United States government educational resource
page outlining each step you are to take if you are a victim of
identity theft, which is [[https://www.identitytheft.gov/][identitytheft.gov]].

**** Mixed Credit File

Sometimes when somebody else’s information is on your credit report,
it isn’t identity theft at all. It’s not some random thief who took
out accounts in your name. It’s the fault of the credit reporting
agency, who may have combined your information with somebody else’s
information and threw it all in the proverbial blender.

How does this happen? The credit reporting agencies use algorithms —
fancy math based on probabilities where computers do the work behind
the scenes — to decide what information is attributed to you, and what
information gets published about you to creditors, insurance companies
and employers.

And because the computer looks for generalities and patterns, debt
belonging to someone with a similar social security number or name who
lives in a different town might wind up on your credit file.

What’s especially frustrating for consumers is that when you try to
get your credit report, if you are mixed up with another consumer, the
screening questions might be wholly unfamiliar to you. It can prevent
you from even seeing your own credit report (that’s another legal
claim, by the way).

If you are going in circles with what seems to be an identity theft
problem, but you’re seeing “variations” of your name or other people’s
names, addresses, telephone numbers and employers on your credit
report, you might have a mixed file. If you are only able to get your
credit report from one or two of the three big CRAs (Equifax, Experian
and Trans Union) and at least one of the credit reports has other
people blended with you, you might have a mixed file.

Not a lot of people, even attorneys, know how to look at credit
reports to see the telltale signs of a mixed file vs. identity theft,
so if you can relate to anything described above, contact an
experienced FCRA lawyer.

*** Reinvestigation

The credit reporting agency is supposed to "re"-investigate the
accuracy of the information that you say is incorrect. If there is a
"furnisher" (creditor or other source of info) reporting that
information to the credit reporting agency, the agency is supposed to
tell the furnisher about your dispute and include all relevant
information with it so the furnisher can look into it.

*** Dispute Results

Finally, after all that reinvestigation, the credit reporting agency
is supposed to notify you of the results, within 30 days. Sometimes
they get it right, your credit report is corrected and you ride off
into the sunset. But sometimes the false information persists. The
strength of your potential FCRA case can depend largely on how
thorough you were in your disputes. Keep reading.

** CFPB How do I dispute an error on my credit report?
[[https://www.consumerfinance.gov/ask-cfpb/how-do-i-dispute-an-error-on-my-credit-report-en-314/][Link]]

You have the right to dispute errors on your credit report. Fixing an
error generally means contacting both the credit reporting company and
the company that provided the information.

** First

First, dispute the information with the credit reporting company or companies

If you identify an error on your credit report, you should start by
disputing that information with the [[https://www.consumerfinance.gov/ask-cfpb/what-is-a-credit-reporting-company-en-1251/][credit reporting company]]
(Experian, Equifax, and/or Transunion). You should explain in writing
what you think is wrong, why, and include copies of documents that
support your dispute. You can also use our [[https://files.consumerfinance.gov/f/documents/092016_cfpb__CreditReportingSampleLetter.pdf][instructions]] and
[[https://files.consumerfinance.gov/f/documents/092016_cfpb_CreditReportingDisputeLetter.docx][template letter]] as a guide.

If you mail a dispute, your dispute letter should include:

- Contact information for you, including your complete name, address,
  and telephone number
- Credit report confirmation number, if available
- Each error you want fixed, including the account number for any
  account you may be disputing
- Clear explanation of why you are disputing the information
- Request that the information be removed or corrected
- A copy of the portion of your credit report that contains the
  disputed items, with the disputed items circled or highlighted
- Copies (not originals) of documents that support your position


You can choose to send your dispute letter by certified mail and ask
for a return receipt, so that you have a record that your letter was
received.

You can contact the nationwide credit reporting companies online, by
mail, or by phone:

*** Equifax
Online: www.equifax.com/personal/credit-report-services/credit-dispute/

By mail: Download the dispute form
Mail the dispute form with your letter to:

Equifax Information Services LLC
P.O. Box 740241
Atlanta, GA 30374

By phone: Call the phone number shown on your credit report or call (866) 349-5191

*** Experian

Online: www.experian.com/disputes/main.html

By mail: Use the address provided on your credit report or mail your letter to:

Experian
P.O. Box 4500
Allen, TX 75013

By phone: Call the phone number shown on your credit report or call (888) 397-3742

*** TransUnion

Online: dispute.transunion.com

By mail: Download the dispute form
Mail the dispute form with your letter to:

TransUnion Consumer Solutions
P.O. Box 2000
Chester, PA 19016-2000

By phone: (800) 916-8800, Monday – Friday 8 a.m. 11 p.m. ET, Saturday and Sunday 8 a.m. – 5 p.m. ET.

** Second

Then, dispute the information with the company that provided it to the
credit reporting companies


Credit reporting companies gather information about you from other
companies (called furnishers). Examples of furnishers include your
bank, your landlord, and your credit card company. To dispute the
information a company provided to the credit reporting company, you
can use our [[https://files.consumerfinance.gov/f/documents/092016_cfpb_FurnisherDisputeLetter.docx][sample letter]] as a guide.

** Third

What happens after you send in your dispute?

*** The credit reporting company investigates

The credit reporting company you sent the dispute letter to must
investigate your dispute, forward copies of relevant documents to the
company that provided the information about you, and report the
results back to you.

A credit reporting company is not required to take action about
disputes that are frivolous. The company must send you a notice
explaining that it has decided the dispute is frivolous, and the
notice must be sent within five business days after it made the
decision.

*** The information furnisher makes corrections and notifies all the credit reporting companies

After correcting information about you, the information furnisher is
responsible for notifying all the credit reporting companies about the
corrected information. Then, the credit reporting companies update
your credit reports.

The information furnisher might determine the information about you is
accurate and should not be updated or removed. In that case, you can
contact the credit reporting companies again and ask them to include a
statement explaining the dispute in your credit reports. The statement
is then added to your file and provided to whomever requests your
credit report in future.

** Submit a Complaint

If you have a problem with your credit report, you can also
[[https://www.consumerfinance.gov/complaint/][submit a complaint with the CFPB]].
