#+title:      RCW 59.18.257 Screening of prospective tenants -— Notice to prospective tenant -— Costs -— Adverse action notice -— Violation
#+date:       [2024-07-11 Thu 10:31]
#+filetags:   :rcw:rcw5918:screening:
#+identifier: 20240711T103144

* Screening of prospective tenants—Notice to prospective tenant—Costs—Adverse action notice—Violation.

1) (a) Prior to obtaining any information about a prospective tenant,
   the prospective landlord shall first notify the prospective tenant
   in writing, or by posting, of the following:

       (i) What types of information will be accessed to conduct the
   tenant screening;

       (ii) What criteria may result in denial of the application;

       (iii) If a consumer report is used, the name and address of the
   consumer reporting agency and the prospective tenant's rights to
   obtain a free copy of the consumer report in the event of a denial
   or other adverse action, and to dispute the accuracy of information
   appearing in the consumer report; and

       (iv) Whether or not the landlord will accept a comprehensive
   reusable tenant screening report made available to the landlord by
   a consumer reporting agency. If the landlord indicates its
   willingness to accept a comprehensive reusable tenant screening
   report, the landlord may access the landlord's own tenant screening
   report regarding a prospective tenant as long as the prospective
   tenant is not charged for the landlord's own tenant screening
   report.

   (b) (i) The landlord may charge a prospective tenant for costs
   incurred in obtaining a tenant screening report only if the
   prospective landlord provides the information as required in (a) of
   this subsection.

       (ii) If a prospective landlord conducts his or her own
   screening of tenants, the prospective landlord may charge his or
   her actual costs in obtaining the background information only if
   the prospective landlord provides the information as required in
   (a) of this subsection. The amount charged may not exceed the
   customary costs charged by a screening service in the general
   area. The prospective landlord's actual costs include costs
   incurred for long distance phone calls and for time spent calling
   landlords, employers, and financial institutions.

   (c) If a prospective landlord takes an adverse action, the
   prospective landlord shall provide a written notice of the adverse
   action to the prospective tenant that states the reasons for the
   adverse action. The adverse action notice must contain the
   following information in a substantially similar format, including
   additional information as may be required under chapter 19.182 RCW
   [Fair Credit Reporting Act]: [[denote:20240711T103641][rcw=59=18=257  Adverse Action Notice]]

2) Any landlord who maintains a website advertising the rental of a
   dwelling unit or as a source of information for current or
   prospective tenants must include a statement on the property's home
   page stating whether or not the landlord will accept a
   comprehensive reusable tenant screening report made available to
   the landlord by a consumer reporting agency. If the landlord
   indicates its willingness to accept a comprehensive reusable tenant
   screening report, the landlord may access the landlord's own tenant
   screening report regarding a prospective tenant as long as the
   prospective tenant is not charged for the landlord's own tenant
   screening report.

3) Any landlord or prospective landlord who violates subsection (1) of
   this section may be liable to the prospective tenant for an amount
   not to exceed one hundred dollars. The prevailing party may also
   recover court costs and reasonable attorneys' fees.

4) This section does not limit a prospective tenant's rights or the
   duties of a screening service as otherwise provided in chapter
   19.182 RCW.


[ 2016 c 66 § 2; 2012 c 41 § 3; 1991 c 194 § 3.]
