#+title:      Potential Damages in RLTA Retaliation Case RCW 59.18.240-.250
#+date:       [2025-01-27 Mon 09:30]
#+filetags:   :damages:distress:emotional:harassment:misrepresentation:outrage:rlta:
#+identifier: 20250127T093034
#+signature:  24a

* Email about Emotional Distress Damages

Alexander R. Reaganson via groups.nwjustice.org <alexander.reaganson=nwjustice.org@groups.nwjustice.org>
Jan 24, 2025, 5:10 PM (3 days ago)
to Elizabeth, HTF@groups.nwjustice.org, VOCA

Hey Elizabeth!

Thanks for the response. I totally agree with you on the lack of teeth to these arguments, per the statute.

Luckily, thanks to some previous advice from John Wolff (NJP-Pullman) in an old case of mine, I do have an answer on that front.

There's a case from '98, White River Estates v. Hiltbruner, 134 Wn.2d 761, Page cite 766, that addresses this in an MHLTA matter but held generally that emotional distress damages are available following a statutory violation if, A) the violation sounds in intentional tort, and; B) as long as the larger statutory scheme does not prohibit damages for emotional distress. Doubly lucky, it's still good caselaw.

John has been successful with this argument in a few of his lawsuits, and the judge in my old case at least signed off on the ~$8,000 I requested in the default judgement for my old case for retaliation by defamation.

In my current case, the other larger drops in the retaliation bucket includes (at minimum) intentional misrepresentation to a state agency and attempts at outrage/harassment. So, if all else fails, I'm leaning towards just adding this latest incident to the later bucket.
