#+title:      Ch 6: Humanizing the Client
#+date:       [2025-02-19 Wed 15:23]
#+filetags:   :ch:client:hornbook:notebook:trial:
#+identifier: 20250219T152317
#+signature:  27=6

* Call Your Client By Name

If you would like the judge or jury to understand that you are representing an actual human being with senses and emotions, memories and anticipations, duties and obligations, who is entitled to fundamental dignity and a rightful place in the world, then ytou night consider using his or her name.

- First and last name

- First name (keeping in mind some sensible limitations dictated by good taste)


It is usually wise to start out the trial talking about your client with his full name: "Mr. Ronald Carlson."  As the trial progresses, you start referring to him as "Ronald Carlson" or "Ron Carlson" and then finally just "Ron."
This natural progression helps the jury fee lthey are becoming acquainted with someone rather than having familiarity thrust upon them.

There is the virtually absolute principle that you should never do anything inconsistent with your theory of the case.  What sort of feeling do you want the jury to have about your clinet?  It is a question that can only be answered the the vantage point of your theory of the case.  The anwer will help you choose the degree of formality you want to surround the person you represent.

* Introduce Your Client Right

Ladies and Gentlemen, I would like you to meet Mr. Tom Read, the man who was crossing the street when the defendant's truck cam crashing through the light (as he walks toward where his client is seated).  Tom, would you stand up, please? (And Read rises--paving previously been told that when he stands, he should get /all the way up/--not just list his backside from the chair an inch or two--and looks at the jury.)  Ladies and Gentlemen, this is Tom Read. (Then to the client) Thank you Tom, you can sit down again.

* Other Rules

- Every time the judge comes in or goes out of the courtroom, rise fully.  The jury is always watching the lawyers and clients and they may take even unintentional lapses in protocol into account.
- During the selction of the jury, turn your chair so you looking directing at the jury panel.  Don't sit with your back to them.
- If you have something to tell me during the trial, write it down.  I will give you a legal pad and a pencil.  Never whisper to me if you can avoid it.
- When you testify, look the jurors in the eyes when answering questions, and not at me.

* Dress

Dress conservatively.
Don't wear jewelry.
Attractive and presentable.

* How to Convey that the Client is Decent Person

Don't say it--act like it.
Your interpersonal transaction should reflect that the lawyer has absolute trust in the client.
The message? When this person takes the stand, he can be believed.

Reasonable amounts of personal background are admitted for all witnesses, essentially on the basis that is is importnt for the jury to know who is talking to them.  Within the discretion of the trial court, somewhat more time for such background information is permitted for parties.
