#+title:      RCW 49.60.222 Unfair practices with respect to real estate transactions, facilities, or services
#+date:       [2025-09-15 Mon 09:28]
#+filetags:   :discrimination:real:ud:unfair:
#+identifier: 20250915T092854
#+signature:  rcw=49=60=222

* RCW 59.60.222 Unfair practices with respect to real estate transactions, facilities, or services.

** (1) [Unfair Practices]

It is an unfair practice for any person, whether acting for himself,
herself, or another, because of sex, marital status, sexual
orientation, race, creed, color, national origin, citizenship or
immigration status, families with children status, honorably
discharged veteran or military status, the presence of any sensory,
mental, or physical disability, or the use of a trained dog guide or
service animal by a person with a disability:

*** (a) [Refuse to Engage]

To refuse to engage in a real estate transaction with a person;

*** (b) [Discriminate]

 To discriminate against a person in the terms, conditions, or privileges of a real estate transaction or in the furnishing of facilities or services in connection therewith;

*** (c) [Offer]

To refuse to receive or to fail to transmit a bona fide offer to engage in a real estate transaction from a person;

*** (d) [Negotiate]

To refuse to negotiate for a real estate transaction with a person;

*** (e) [Available]

To represent to a person that real property is not available for inspection, sale, rental, or lease when in fact it is so available, or to fail to bring a property listing to his or her attention, or to refuse to permit the person to inspect real property;

*** (f) [Sale]

To discriminate in the sale or rental, or to otherwise make unavailable or deny a dwelling, to any person; or to a person residing in or intending to reside in that dwelling after it is sold, rented, or made available; or to any person associated with the person buying or renting;

*** (g) [Publish]

To make, print, circulate, post, or mail, or cause to be so made or published a statement, advertisement, or sign, or to use a form of application for a real estate transaction, or to make a record or inquiry in connection with a prospective real estate transaction, which indicates, directly or indirectly, an intent to make a limitation, specification, or discrimination with respect thereto;

*** (h) [Listing]

 To offer, solicit, accept, use, or retain a listing of real property with the understanding that a person may be discriminated against in a real estate transaction or in the furnishing of facilities or services in connection therewith;

*** (i) [Expel]

To expel a person from occupancy of real property;

*** (j) [Negotiating]

To discriminate in the course of negotiating, executing, or financing a real estate transaction whether by mortgage, deed of trust, contract, or other instrument imposing a lien or other security in real property, or in negotiating or executing any item or service related thereto including issuance of title insurance, mortgage insurance, loan guarantee, or other aspect of the transaction. Nothing in this section shall limit the effect of RCW 49.60.176 relating to unfair practices in credit transactions; or

*** (k) [Unfair Practice]

To attempt to do any of the unfair practices defined in this section.

** (2) [Discrimination Includes]

For the purposes of this chapter discrimination based on the presence
of any sensory, mental, or physical disability or the use of a trained
dog guide or service animal by a person who is blind, deaf, or
physically disabled includes:

*** (a) ...

** (3) [Separate the Sexes]

Notwithstanding any other provision of this chapter, it shall not be
an unfair practice or a denial of civil rights for any public or
private educational institution to separate the sexes or give
preference to or limit use of dormitories, residence halls, or other
student housing to persons of one sex or to make distinctions on the
basis of marital or families with children status.

** (4) [No Structural Changes]

Except pursuant to subsection (2)(a) of this section, this section
shall not be construed to require structural changes, modifications,
or additions to make facilities accessible to a person with a
disability except as otherwise required by law. Nothing in this
section affects the rights, responsibilities, and remedies of
landlords and tenants pursuant to chapter 59.18 or 59.20 RCW,
including the right to post and enforce reasonable rules of conduct
and safety for all tenants and their guests, provided that chapters
59.18 and 59.20 RCW are only affected to the extent they are
inconsistent with the nondiscrimination requirements of this
chapter. Nothing in this section limits the applicability of any
reasonable federal, state, or local restrictions regarding the maximum
number of occupants permitted to occupy a dwelling.

** (5) [Public Accommodation]

Notwithstanding any other provision of this chapter, it shall not be
an unfair practice for any public establishment providing for
accommodations offered for the full enjoyment of transient guests as
defined by RCW 9.91.010(1)(c) to make distinctions on the basis of
families with children status. Nothing in this section shall limit the
effect of RCW 49.60.215 relating to unfair practices in places of
public accommodation.

** (6) [Older Persons]

Nothing in this chapter prohibiting discrimination based on families
with children status applies to housing for older persons as defined
by the federal fair housing amendments act of 1988, 42
U.S.C. Sec. 3607(b)(1) through (3), as amended by the housing for
older persons act of 1995, P.L. 104-76, as enacted on December
28, 1995. Nothing in this chapter authorizes requirements for housing
for older persons different than the requirements in the federal fair
housing amendments act of 1988, 42 U.S.C. Sec. 3607(b)(1) through (3),
as amended by the housing for older persons act of 1995, P.L. 104-76,
as enacted on December 28, 1995.

** (7) [Shared Unit]

Nothing in this chapter shall apply to real estate transactions
involving the sharing of a dwelling unit, or rental or sublease of a
portion of a dwelling unit, when the dwelling unit is to be occupied
by the owner or subleasor. For purposes of this section, "dwelling
unit" has the same meaning as in RCW 59.18.030.

* Sources

[ 2020 c 52 s 14; 2007 c 187 s 13; 2006 c 4 s 14. Prior: 1997 c 400 s 3; 1997 c 271 s 14; 1995 c 259 s 3; prior: 1993 c 510 s 17; 1993 c 69 s 5; 1989 c 61 s 1; 1979 c 127 s 8; 1975 1st ex.s. c 145 s 1; 1973 c 141 s 13; 1969 ex.s. c 167 s 4.]

* Notes

Effective date—1995 c 259: See note following RCW 49.60.010.
