#+title:      Form of Judgment Summary
#+date:       [2025-10-16 Thu 12:07]
#+filetags:   :judgment:summary:
#+identifier: 20251016T120732
#+signature:  rcw=4=64=030

* RCW 4.64.030 -- Entry of judgment—Form of judgment summary

** (1) [Entry by Clerk]

The clerk shall enter all judgments in the execution docket, subject to the direction of the court and
shall specify clearly

- the amount to be recovered,
- the relief granted, or
- other determination of the action.

** (2) [Summary]

*** (a) [On First Page]

On the first page of each judgment which provides for the payment of money, including
- foreign judgments,
- judgments in rem,
- mandates of judgments, and
- judgments on garnishments,


the following shall be succinctly summarized:

- The judgment creditor and the name of his or her attorney,
- the judgment debtor,
- the amount of the judgment,
- the interest owed to the date of the judgment, and
- the total of the taxable costs and attorney fees, if known at the time of the entry of the judgment, and
- in the entry of a foreign judgment,
  - the filing and expiration dates of the judgment under the laws of the original jurisdiction.

*** (b) [Real Property Summary]

If the judgment provides for the award of any right, title, or interest in real property,
the first page must also include

- an abbreviated legal description of the property in which the right, title, or interest was awarded by the judgment,
  - including
    - lot, block, plat, or
    - section, township, and range, and
    - reference to the judgment page number where the full legal description is included, if applicable;
- or
  - the assessor's property tax parcel or account number,
  - consistent with RCW 65.04.045(1) (f) and (g).

*** (c) [Damages Relating to a Motor Vehicle]

If the judgment provides for damages arising from
- the ownership,
- maintenance, or
- use of a motor vehicle as specified in RCW 46.29.270,

the first page of the judgment summary must clearly state that
- the judgment is awarded pursuant to RCW 46.29.270 and that
- the clerk must give notice to the department of licensing as outlined in *RCW 46.29.310.

** (3) [Cost Bill]

If the attorney fees and costs are not included in the judgment,
  they shall be summarized in the cost bill when filed.

The clerk may not enter a judgment, and a judgment does not take effect,
  until the judgment has a summary in compliance with this section.

The clerk is not liable for an incorrect summary.

** History
[ 2003 c 43 s 1; 2000 c 41 s 1; 1999 c 296 s 1; 1997 c 358 s 5; 1995 c 149 s 1; 1994 c 185 s 2; 1987 c 442 s 1107; 1984 c 128 s 6; 1983 c 28 s 2; Code 1881 s 305; 1877 p 62 s 309; 1869 p 75 s 307; RRS s 435.]

** Rules of Court
Cf.
- CR 58(a),
- CR 58(b),
- CR 78(e).

* Judgment Summary Form

- Judgment Creditor
- Judgment Creditor Attorney
- Judgment Debtor
- Judgment Debtor Attorney
- Amount of judgment
- Interest to date of judgment
- Taxable Costs
- Attorney Fees

* Judgment
Amount to be recovered;
Relief Granted;
Other determination of the action;
