#+title:      Ch 5: The Theory of the Case
#+date:       [2025-02-19 Wed 15:22]
#+filetags:   :case:ch:hornbook:notebook:theory:trial:
#+identifier: 20250219T152241
#+signature:  27=5

* Theory of the Case -- Fundamental Rule in Trial Practice

"Your technique was perfect.  What happened was, you committed the cardinal sin of doing something that is inconsistent with the theory of the case."

One of the most fundamental rules in tril practice.  It comes before the rules of evidence, techniques of persuasion, impressive demonstrative evidence, and sophisticated touches of elouence.  It is imple, understandable, and nearly absolute.

NEVER DO ANYTHING INCONSISTENT WITH YOUR THEORY OF THE CASE.

Just what is meant by the theory of the case is a study all itself.

1. First, it includes the legal theories of the claim or defense, but is is not so narrow.  A plaintiff can recover for negligence that causes harm, but that does not tell us very much.
2. Then, there is the factual theory.  It might be the plaintiff's factual theory that the defendant ran into him because he was not paying enough attention to where he was going as drove down the street.  This tells us something more, but not much.


The theory of the case is the basic, underlying idea that explains not only the legal theory and the factual background, but also ties as much of the evicence as possible into a coherrent and credible whole.  Whether it is simple and unadorned or subtle and sophisticated, the theory of the case is a product of the advocate.  It is the basic concept around which everything else revolves.

A good theory of the case is the very heart of advocacy, since it provides a comfortable viewpoint from whic hteh jury can look at all of the evidence--and if the ylook at the evidence from the viewpoint, they will be led ineluctably to decide in your favor.

The theory of the case is a sort of home case to be defended at all costs unless utter disaster commands that it be dserted in favor of some unfamiliar place further up the hill.
