#+title:      RCW 59.18.130 Duties of Tenant
#+date:       [2025-09-19 Fri 08:36]
#+filetags:   :duties:rcw:rtc:tenant:
#+identifier: 20250919T083611
#+signature:  rcw=59=18=130

* RCW 59.18.130 -- Duties of a Tenant

Each tenant shall pay the rental amount at such times and in such
amounts as provided for in the rental agreement or as otherwise
provided by law
and
comply with all obligations imposed upon tenants
by applicable provisions of all municipal, county, and state codes,
statutes, ordinances, and regulations, and in addition shall:


** (1) [Clean and Sanitary]

Keep that part of the premises which he or she occupies and uses as
clean and sanitary as the conditions of the premises permit;

** (2) [Dispose Rubbish]

 Properly dispose from his or her dwelling unit all
 - rubbish,
 - garbage, and
 - other organic or
 - flammable waste,
 - in a clean and sanitary manner
 - at reasonable and regular intervals, and
 - assume all costs of extermination and fumigation for infestation caused by the tenant;

** (3) [Properly Operate Appliances]

Properly use and operate all
- electrical,
- gas,
- heating,
- plumbing and
- other fixtures and appliances supplied by the landlord;

** (4) [Don't Destroy]

 Not intentionally or negligently
 - destroy,
 - deface,
 - damage,
 - impair, or
 - remove

 any part of the structure or dwelling, with the appurtenances
 thereto, including the facilities, equipment, furniture, furnishings,
 and appliances,

 or

 permit any member of his or her family, invitee,
 licensee, or any person acting under his or her control to do
 so.

 Violations may be prosecuted under chapter 9A.48 RCW if the
 destruction is intentional and malicious;

** (5) [No Nuisance or Common Waste]

Not permit a nuisance or common waste;

** (6) [No Drug-Related Activity]

Not engage in drug-related activity at the rental premises,

-or-

allow a subtenant, sublessee, resident, or anyone else to engage in
drug-related activity at the rental premises

with the knowledge or consent of the tenant.

- "Drug-related activity" means ::
  - that activity which constitutes a violation of chapter 69.41, 69.50, or 69.52 RCW;

** (7) [Maintain Smoke Detector Devices]

Maintain the smoke detection device in accordance with the
manufacturer's recommendations,

including
- the replacement of batteries where required
- for the proper operation of the smoke detection device,
- as required in RCW 43.44.110(3);

** (8) [Avoid Activity]

*** (a) [Hazardous]

Imminently hazardous to the physical safety of other persons on the
premises; and

*** (b)

**** (i) [Physical Assaults]

Entails physical assaults upon another person which result in an arrest; or

**** (ii) [Firearm]

Entails the unlawful use of a firearm or other deadly weapon as
defined in RCW 9A.04.110
- which results in an arrest,
  - including threatening another tenant
  - or the landlord
  - with a firearm or other deadly weapon
  - under RCW 59.18.352.


Nothing in this subsection (8) shall
- authorize the termination of tenancy and eviction of the victim of a physical assault
  -or-
- the victim of the use or threatened use of a firearm or other deadly weapon;

** (9) [Gang-Related Activity]

Not engage in any gang-related activity at the premises,
- as defined in RCW 59.18.030,
-or-
- allow another to engage in such activity at the premises,
- that renders people in at least two or more dwelling units or residences insecure in life or the use of property
- or that injures or endangers the safety or health of people in at least two or more dwelling units or residences.


In determining whether a tenant is engaged in gang-related activity, a
court should consider
- the totality of the circumstances, including factors such as
  - whether there have been a significant number of complaints to the landlord about the tenant's activities at the property,
  - damages done by the tenant to the property,
  - including the property of other tenants or neighbors,
  - harassment or threats made by the tenant to other tenants or neighbors that have been reported to law enforcement agencies,
  - any police incident reports involving the tenant,
  - and the tenant's criminal history; and

** (10) [Restore Premises]

Upon termination and vacation, restore the premises to their initial
condition except for wear resulting from ordinary use of the premises
or conditions caused by failure of the landlord to comply with his or
her obligations under this chapter.

The tenant shall not be charged for normal cleaning if he or she has
paid a nonrefundable cleaning fee.
