#+title:      Set-Off and Counterclaim -- Westlaw Key Number Cites
#+date:       [2025-12-05 Fri 09:16]
#+filetags:   :counterclaim:setoff:
#+identifier: 20251205T091615
#+signature:  31b=352k

* 352 K Set-Off and Counterclaim

** 352 K I Nature and Grounds of Remedy

*** 352k1 Nature and Purpose

[EXPRESSION OF THE COMMON LAW EQUITABLE PRINCIPLE]

our  long-settled rule  that,

where two liabilities are owed by  and through the same parties in the
same right,  they are properly  the subject  of *off-set*,

and that the right of *set-off*  is to be liberally construed.

Our last expression  to that effect is cited in  /Johnson v.  Aberdeen/,
147 Wash. 482, 266 P. 707.

/Johnson v. California-Washington Timber Co./, 161 Wash. 96, 103, 296 P. 159, 161 (1931)


Offset

Thomas contends  that he is entitled  to offset what MidTown  owes him
against the debt he owes to Hugh on the note. We disagree.

“The right of  setoff (also called ‘offset’) allows  entities that owe
each  other money  to apply  their  mutual debts  against each  other,
thereby avoiding  ‘the absurdity of  making A pay  B when Bowes  A.’ ”
/Citizens Bank of Maryland v. Strumpf/,  516 U.S. 16, 18, 116 S. Ct.286,
133 L.Ed. 2d  258 (1995) (quoting /Studley v. Boylston  Nat'l Bank/, 229
U.S. 523, 528, 33  S. Ct. 806, 57 L.Ed. 1313  (1913) ).

Offset applies only when the claims  are mutual, meaning that they are
between the  same parties  acting in the  same capacity.   /Kriedler v.
Statewide Gen.   Ins.  Agency, Inc./, 182  Wn. App. 557, 568,  329 P.3d
928 (2014) (insurance and bankruptcy);  /Cunningham v.  Long/, 134 Wash.
433, 436,  235 P. 964  (1925) (debt due to  plaintiff to only  part of
joint defendants cannot be set  off against joint debt due plaintiff);
/Johnson v. City of Aberdeen/, 147  Wash. 482, 485, 266 P.707 (1928) (to
be  the subject  of set-off,  demands  must be  due to  and from  same
parties in same capacity).

/Bangasser v. Bangasser/, 7 Wn. App. 2d 1011 (2019) [NOT REPORTED]


Here, Thomas seeks to offset Hugh's claim against him on the note with
his  own  claim  against  MidTown.   But  there  is  no  mutuality  of
obligation.6 MidTown  is not a  party to  the note between  Thomas and
Hugh. Thomas  incurred the  debt to  take advantage  of a  real estate
opportunity entirely unrelated to MidTown.

/Bangasser v. Bangasser/, 7 Wn. App. 2d 1011 (2019) [NOT REPORTED]

**** Assignment relating to Mutuality

Offset cases  cited by Thomas in  support of his claim  are inapposite
because they involve claims that meet the mutuality requirement. /In re
Smith's Estate/, 179 Wash. 417, 38 P.2d 244 (1934); /Peoples Nat'l Bank
of  Wash. v.   Nat'l Bank  of Commerce/,  69 Wn.2d  682, 420  P.2d 208
(1966).

Thomas  also   claims  that  CR   13(j)  authorizes  offset   in  this
situation. But that rule expressly authorizes setoffs for the assignee
of a note. Hugh is not an assignee.

/Bangasser v. Bangasser/, 7 Wn. App. 2d 1011 (2019) [NOT REPORTED]

*** 352k2 What Law Governs

*** 352k3 Statutory Provisions

[NOW SEE RCW 4.56.060 for general civil set-offs; RRS s 271 1/2]
[SEE RCW 62A-9A for bank deposit set-offs]
[SEE RCW 12.08.120 for Justice Courts]

The statute in this state allowing *set-off* reads:

‘The defendant in a civil action upon a contract expressed or implied,
may  *set off*  any demand  of a  /like nature/  against the  plaintiff in
interest,  which existed  and  belonged  to him  at  the  time of  the
commencement of the suit. * * *’ Rem. Rev. Stat. § 266.

/Edwards v. Sur. Fin. Co. of Seattle/, 176 Wash. 534, 539, 30 P.2d 225, 227 (1934)


The  right to  set-off  is  wholly statutory,  and  in  this case  its
existence and  its definition must  depend upon the provisions  of the
statutes of the state of Washington.  The Code of Washington (2 Hill's
Code, Sec. 806) provides as follows:

#+begin_quote
‘Sec. 806. The  defendant in a civil action upon  a contract expressed
or  implied may  set  off any  demand  of a  like  nature against  the
plaintiff in interest which existed and belonged to him at the time of
the commencement of the suit. And in all such actions, other than upon
a negotiable  promissory note or  bill of exchange negotiated  in good
faith, and without  notice before due, which has been  assigned to the
plaintiff, he  may also  set off  a demand of  a like  nature existing
against the person  to whom he was originally liable,  or any assignee
prior to the plaintiff of  such contract, provided such demand existed
at the time of the assignment  thereof, and belonging to the defendant
in good faith before notice of  such assignment, and was such a demand
as  might  have been  set  off  against such  person  to  whom he  was
originally liable,  or such  assignee while  the contract  belonged to
him.‘
#+end_quote

/Harrisburg Tr. Co. v. Shufeldt/, 87 F. 669, 670 (9th Cir. 1898)

**** Like Nature

[contract express or implied]

As already stated,  the present action is upon a  contract, implied in
law.  At the  time of  the  commencement of  this action,  appellant's
liability in  the former action was  still upon the note;  no judgment
had been taken.

...

Being the owner of a demand of a /contractual nature/ against appellant,
respondent was entitled to have it *set off* against appellant's present
demand.

/Edwards v. Sur. Fin. Co. of Seattle/, 176 Wash. 534, 539, 30 P.2d 225, 227 (1934)


The  *right of  set-off*, being  in existence  under one  form, was  not
extinguished merely because it assumed another form. It is the rule in
this   state  that   the  *right   of  set-off*   is  to   be  liberally
construed. /Johnson v. California-Washington  Timber Co./, 161 Wash. 96,
296 P. 159.

/Edwards v. Sur. Fin. Co. of Seattle/, 176 Wash. 534, 540, 30 P.2d 225, 227 (1934)

**** RCW 12.08.120 Setoff—Pleading.

To entitle a  defendant to any setoff  he or she may  have against the
plaintiff, he or  she must allege the  same in his or  her answer; and
the statutes  regulating setoffs in  the superior court, shall  in all
respects be applicable to a setoff in a justice's court, if the amount
claimed to  be setoff,  after deducting  the amount  found due  to the
plaintiff, be  within the  jurisdiction of the  justice of  the peace;
judgment may, in  like manner, be rendered by the  justice in favor of
the defendant, for the balance found due the plaintiff.

**** Appeal of Issue of Right to Set-Off

[RSS 266 includes right to set off amounts owed by assignor held by an assignee]

The proceedings now before us were instituted by the supervisor in the
superior  court of  Grays  Harbor  county to  enforce  payment of  the
warrants. He made  parties defendant thereto the city  of Aberdeen and
its  treasurer.   The defendants  appeared  in  the proceedings,  and,
setting forth the facts, *claimed the  right of set-off*.  After a trial
the  court denied  the right,  and  entered a  judgment directing  the
payment  of  the warrants.   From  this  judgment,  the city  and  the
treasurer  appeal.  /The sole  question  presented  by the  appeal  is
whether the right of set-off existed./

/Johnson v. City of Aberdeen/, 147 Wash. 482, 484, 266 P. 707, 709 (1928)


The statute relating to set-off is found at section 266 of the Code (Rem. Comp. Stat.), and reads as follows:

#+begin_quote
‘The defendant in a civil action upon a contract expressed or implied,
may  *set off*  any demand  of a  *like nature*  against the  plaintiff in
interest,  which existed  and  belonged  to him  at  the  time of  the
commencement of the  suit. And in all such actions,  other than upon a
negotiable promissory  note or  bill of  exchange, negotiated  in good
faith and  without notice before due,  which has been *assigned*  to the
plaintiff, he  may also  set off  a demand of  a like  nature existing
against the person  to whom he was originally liable,  or any assignee
prior to the plaintiff, of such contract, provided such demand existed
at the time of the assignment  thereof, and belonging to the defendant
in good faith, before notice of such assignment, and was such a demand
as might  have been set  off against such person  *485 to whom  he was
originally liable,  or such  assignee while  the contract  belonged to
him.’
#+end_quote

/Johnson v. City of Aberdeen/, 147 Wash. 482, 484–85, 266 P. 707, 709 (1928)

** 352 K II Subject Matter

** 352 K III Operation and Effect
