#+title:      RCW 59.18.140 -- Reasonable obligations or restrictions—Tenant's duty to conform—Landlord's duty to provide written notice in increase of rent.
#+date:       [2025-09-19 Fri 08:52]
#+filetags:   :duties:notice:rcw:rtc:tenant:
#+identifier: 20250919T085230
#+signature:  rcw=59=18=140

* RCW 59.18.140 -- Reasonable obligations or restrictions—Tenant's duty to conform—Landlord's duty to provide written notice in increase of rent.

** (1) [Tenant Shall Conform]

The tenant shall conform to all reasonable obligations or
restrictions,
whether denominated by the landlord as
- rules,
- rental agreement,
- rent,
- or otherwise,

concerning the
- use,
- occupation, and
- maintenance of his or her dwelling unit,
- appurtenances thereto, and
- the property of which the dwelling unit is a part

if such obligations and restrictions are not in violation of any of
the terms of this chapter and are not otherwise contrary to law,

and if such obligations and restrictions are brought to the attention
of the tenant at the time of his or her initial occupancy of the
dwelling unit and thus become part of the rental agreement.

** (2) [New Rules after 30 Days]

Except for
- termination of tenancy and
- an increase in the amount of rent,

after 30 days' written notice to each affected tenant,

a new rule of tenancy may become effective upon completion of the term
of the rental agreement or sooner upon mutual consent.

** (3) [Rent Increase]

*** (a) [90 days' notice]

Except as provided in (b) and (c) of this subsection,

a landlord shall provide a minimum of 90 days' prior written notice of
an increase in the amount of rent to each affected tenant,

and any increase in the amount of rent may not become effective prior
to the completion of the term of the rental agreement.

*** (b) [Subsidized Tenancy]

If the rental agreement governs a subsidized tenancy where the amount
of rent is based on the income of the tenant or circumstances specific
to the subsidized household,

a landlord shall provide a minimum of 30 days' prior written notice of
an increase in the amount of rent to each affected tenant.

An increase in the amount of rent may become effective upon completion
of the term of the rental agreement or sooner upon mutual consent.

*** (c) [May 7, 2025]

For a tenant whose lease or rental agreement was entered into or
renewed before May 7, 2025, and whose tenancy is for a specified time,
if the lease or rental agreement has more than 60 days but less than
90 days left before the end of the specified time as of May 7, 2025,
the landlord must provide written notice to the affected tenant a
minimum of 60 days before the effective date of an increase in the
amount of rent.
