#+title:      Ch 7: The Credibility of the Lawyer
#+date:       [2025-02-19 Wed 15:23]
#+filetags:   :ch:credibility:hornbook:notebook:trial:
#+identifier: 20250219T152355
#+signature:  27=7

* The Progression of Trust

Underlying every trial is a simple progression:

- I am honest.
- You should believe me.
- I believe in the justice of my client's cause.
- Therefore you should decide for my client.

* Belief if the Client's Cause

The ethical rule forbids that you /say/ you personally believe in your client's cause.  It does not forbid you actually to believe in or to show that belief in ways other than words.

Usually the case you do not believe in is the case you do not win.  Usually, the mosteffective thing you can do as an advocate is believe in your case.

The real function of body language is to betray the inner feelings.

The starting point, then is to frame your case so you can believe in it.  Now we are concerned with how the credibility of the lawyer transcends mere belief in the case.  Here, the emphasis is on how the lawyer's credibility is a concern that touches all levels of trial techniques.

The question "How will this affect my credibility as an advocate?" is a good vantage point for exasmining every thing you do during the course of a trial.  It is an excellent starting point for any serious self-evaluation.

* Don't Promise More than you can Deliver

You hear warnings about not promissing too much during opening statements.  Why?  Your credibility.

When you state what you anticipate the evidence will be and then do not deliver, your case is damaged even though it is technically as valid as ever.  Your believability has suffered, and your case along with it.

* The Challenge of Re-creating the First Impression

Direct examination presents special problems of the lawyer's credibility.  Theater people call it the challenge of re-creating the first impression.  Obviously you know what the answers to all the questions on direct examination should be.  Nothing should be a surprise.

The trouble is, if you do not show any response to the testimony, something seems wrong.  You must resopnd to the evidence almost as if you were hearing it for the first time.  You must fee lfree to respond as a normal person to what you are hearing.

What is the best way?  List to the answer.  Listen to the answers on direct examination so your response will be a normal, human one--not something that fails to mesh with what is going on in the courtroom.

* Standard Bits of Advice About Trial Behavior

It is important to be deferential to the court.  It will help the jurors see you as credible.  There are exceptions, but they are rare.

It is important to be fair to your opponent.  Hostility may lead you to act as if you have something to hide with the resultant damaging message about your credibility.

Follow the standard amenities.  Cite to the pages of the documents you refer to; show your opponent exhibits before you offer them.  Not onlly does it seem open and fair, it cuts off any opportunity your opponent may have to make an objection which suggests you are trying to get some evidence in without giving him a chance to see what it is.

* What Jurors Like Least About Trials: Bench Conferences

What they liked least were bench conferences, sidebar discussions.

Jurors resent being left out, excluded.

Therefore do not ask for a bench conference if you can avoid it.  Asking for a bench conference is a signal you have something to hide from the jury, and they will resent it.  It will damage your credibility.

Anticipate evidentiary problems with a motion in limine.  Avoid asking to approach the bench.

* Avoid Needless Objections and the Stupid Attack

Each time you object, you run the risk of looking like you are trying to keep some essential truth from the jury.

The first rule of cross examination: avoid the stupid attack.  It will harm your credibility.

What is a stupid attack? One that can be exposed as incorrect, misguided, or dishonest.  Any time a stupid attack is exposed, the party making it is worse off than if the attack had never been made.

* Things to Avoid

- Don't "um" and "uh"
- Don't "Let me ask you this question."
- Don't "O.K."
- Don't read your closing argument.
- Be careful with analogies; use your own and use only a few
