#+title:      Expiration of 3-Day Notice
#+date:       [2025-04-04 Fri 11:03]
#+filetags:   :3day:expire:notice:nuisance:rcw5918190:waste:
#+identifier: 20250404T110353

* Email on Briefing

Chris Brunetti via groups.nwjustice.org <chris.brunetti=nwjustice.org@groups.nwjustice.org>
Apr 3, 2025, 6:01 PM (17 hours ago)
to EPowell@ccsww.org, Tyler, skylar.brett@wearepda.org, HTF@groups.nwjustice.org

I agree with Tyler.  I think RCW 59.18.190 applies to 3-day nuisance notices because RCW 59.18.190 references “breach[es] of RCW 59.18.130”, and one of the tenant duties in RCW 59.18.130(5) is to “[n]ot permit a nuisance or common waste.”  I agree that the language in RCW 59.18.190 regarding the tenant being given the opportunity to “remedy the nonconformance” creates some tension because RCW 59.18.650(2)(c) does not require the landlord to give the tenant an opportunity to cure the alleged nuisance.  However, it’s worth noting that in certain situations, RCW 59.18.180 does provide the tenant an opportunity to remedy noncompliance with their tenant duties under RCW 59.18.130.  Also, maybe there is an argument that the language in .190 itself requires landlord to give tenant an opportunity to remedy any alleged nonconformance of any tenant duty under .130—which, again, include the duty to “[n]ot permit a nuisance or common waste.”  IDK, maybe we should start making this argument.

I’ll add that in practice, we generally argue that 3-day notices are subject to RCW 59.18.190, and at least most of the courts I practice in (in SW part of the state) seem to agree.  Of course, you should always fall back on the argument that the RLTA is in derogation of the common law and should be strictly construed in favor of the tenant.  In that regard, if and to the extent a court finds ambiguity in .190, it should err on the side of the tenant.

Now, as for the applicable time periods in terms of measuring when the 60 days begins to run and when it ends, I always argue that it begins upon service of the notice (this is what COA did in K&H v. Daniels), and ends upon both service and filing of the S&C.  RCW 59.18.190 says nothing about commencement of the action.  It speaks only about the landlord pursuing a remedy.  Admittedly, what it means to “pursue a remedy” is a bit ambiguous.  But again, leaning on the basic principle that the RLTA is in derogation of the common law, etc., and that a court can’t provide a remedy (or do anything for a plaintiff) unless and until they file and serve the S&C, I think you can craft a pretty solid argument that the notice expires unless the landlord serves and files the S&C within 60 days of issuance of the notice.  Of course, this is an unsettled question, and as you can imagine we’ve gotten conflicting results in different courts.  It’ll probably eventually have to be resolved by COA.

* Here’s some briefing I’ve developed on the issue:

This unlawful detainer action should be dismissed because it is predicated on an expired notice.  Plaintiff failed to pursue a remedy under the RLTA within sixty days of issuance of the Notice, as required under RCW 59.18.190, which provides:

"Whenever the landlord learns of a breach of RCW 59.18.130 or has accepted performance by the tenant which is at variance with the terms of the rental agreement or rules enforceable after the commencement of the tenancy, he or she may immediately give notice to the tenant to remedy the nonconformance.  Said notice shall expire after sixty days unless the landlord pursues any remedy under this chapter."

In Kiemle & Hagood Co. v. Daniels, the landlord brought an unlawful detainer action based upon seven notices.  26 Wn.App.2d 199, 205, 528 P.3d 834 (2023).  The landlord commenced the action on January 10, 2022. Id. at 206.  The most recent notice was issued on December 27, 2021.  Id.  Prior to that, the next most recent notices were issued on November 3, 2021.  Id.  The notices issued on November 3, alleged that the tenant was in violation of her lease terms, and gave her 10 days to either comply or vacate the premises.  Id.  The Court of Appeals held that since the landlord "did not pursue a remedy under the RLTA within 60 days of providing [the tenant] with a notice to cure or vacate under RCW 59.18.650(2)(b), the November 3 notice expired."  Id. at 214.  In so holding, the Court of Appeals measured the 60 days for the landlord to pursue a remedy from the date of issuance of the notice (November 3, 2021) to the date the action was filed (January 10, 2022).  "The only notice still operative by the time [the landlord] filed suit on January 10, 2022, was the one dated December 27, 2021."  Id.

The Daniels Court, in interpreting RCW 59.18.190, noted that "[a] remedy is generally defined as something ‘a court can do for a litigant who has been wronged.'" Id. at 213, quoting Douglas Laycock & Richard L. Hasen, Modern American Remedies: Cases and Materials 1 (5th ed. 2019).  It is axiomatic that a Court cannot grant a remedy—or do anything for a litigant—until the action is filed.  As such, the Court of Appeals rejected the landlord’s argument that the service of a subsequent notice on December 27, 2021, constituted a remedy for purposes of determining whether the November 3 notice had expired under RCW 59.18.190.  "A landlord’s service of a notice to terminate a tenancy is not a remedy."  Id. at 214.  "It is a legal prerequisite to avail oneself of the superior court’s jurisdiction."  Id.  Similarly, "[p]roper service of the summons and complaint is a prerequisite to a court obtaining jurisdiction over a party."  Harvey v. Obermeit, 163 Wn.App. 311, 318, 261 P.3d 671 (2011).  It is not a remedy.  Accordingly, the Court should reject any attempt by Plaintiff to argue that its pre-filing service of the summons on Defendant, constituted the pursuit of a remedy under RCW 59.18.190.
