#+title:      RCW 59.18.710 Landlord—Prohibition on certain rent increases—Exemptions
#+date:       [2025-11-07 Fri 10:29]
#+filetags:   :exemptions:increase:law:limits:rcw:rent:rlta:statute:
#+identifier: 20251107T102903
#+signature:  rcw=59=18=710

* RCW 59.18.710 -- Landlord—Prohibition on certain rent increases—Exemptions

** (1) [List of Exemptions]

A landlord may  increase rent in an amount greater  than allowed under
RCW 59.18.700 only  as authorized by the exemptions  described in this
section. Rent  increases are not limited  by RCW 59.18.700 for  any of
the following types of tenancies:

*** (a) [Less than 12 years old]

A  tenancy in  a  dwelling unit  for which  the  first certificate  of
occupancy was issued 12 or less years before the date of the notice of
the rent increase.qqqq

*** (b) [Exemptions for Public or Nonprofit Landlords]

A tenancy in a dwelling unit owned by a:

**** (i) [PHA]

Public housing authority;

**** (ii) [PDA]

Public development authority;

**** (iii) [Nonprofit]

Nonprofit  organization, where  maximum rents  are regulated  by other
laws  or   local,  state,   or  federal  affordable   housing  program
requirements; or

**** (iv) [Other Nonprofit]

Nonprofit  entity, as  defined  in RCW  84.36.560,  where a  nonprofit
organization, housing  authority, or public development  authority has
the majority decision-making  power on behalf of  the general partner,
and where maximum  rents are regulated by other laws  or local, state,
or federal affordable housing program requirements.

*** (c) [Qualified Low-Income Housing Development]

A tenancy in a qualified  low-income housing development as defined in
RCW 82.45.010, where the property is owned by any of the organizations
described in (b)(i) through (iv) of this subsection.

*** (d) [Low-Income Housing Tax Credits]

A  tenancy in  a qualified  low-income housing  development which  was
allocated federal  low-income housing tax credits  authorized under 26
U.S.C. Sec. 42  or successor statute, by the  Washington state housing
finance commission or successor state-authorized tax credit allocating
agency, so long  as there is an enforceable  regulatory agreement with
the Washington  state housing finance commission  under the low-income
housing tax credit program.

*** (e) [Shared Tenancy]

A tenancy in a dwelling unit in  which the tenant shares a bathroom or
kitchen facility with the owner who maintains a principal residence at
the residential real property.

*** (f) [Single-Family Owner-Occupied Residence]

A  tenancy in  a single-family  owner-occupied residence,  including a
residence in which the owner-occupant rents or leases no more than two
units  or bedrooms  including,  but  not limited  to,  an attached  or
detached accessory dwelling unit.

*** (g) [Duplex,Triplex,Fourplex]

A  tenancy in  a  duplex,  triplex, or  fourplex  in  which the  owner
occupied one of the units as  the owner's principal place of residence
at the  beginning of the tenancy,  so long as the  owner continues the
occupancy.

** (2) [Exemptions e-g Do Not Apply to Corporate Owners]

Subsection (1)(e)  through (g)  of this section  only apply  where the
owner is not any of the following:

*** (a) [REIT]

A  real estate  investment trust,  as defined  in section  856 of  the
internal revenue code;

*** (b) [Corporation]

A corporation; or

*** (c) [LLC]

A  limited  liability company  in  which  at  least  one member  is  a
corporation.

** (3) [Expires July 1, 2040]

This section expires July 1, 2040.

* 2025 c 209 s 102

[[https://lawfilesext.leg.wa.gov/biennium/2025-26/Pdf/Bills/Session%20Laws/House/1217.SL.pdf?cite=2025%20c%20209%20s%20102][ENGROSSED HOUSE BILL 1217]]

* Effective Date

Effective date—2025 c 209: See note following RCW 59.18.700.
