#+title:      VAWA
#+date:       [2025-05-15 Thu 09:12]
#+filetags:   :federal:law:protection:vawa:
#+identifier: 20250515T091250
#+signature:  23e

* HUD VAWA Website
:PROPERTIES:
:CUSTOM_ID: h:4F8E32FB-889E-4F8F-B49E-1E3319DB76EA
:END:

https://www.hud.gov/vawa

* VAWA Statutes and Resources

** Statutes
[[https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title34-section12291&num=0&edition=prelim][34 U.S.C. § 12291]]

[[https://www.hud.gov/hud-partners/fair-housing-vawa#:~:text=34%20U.S.C.%20%C2%A7%C2%A7%2012471%2D12496][34 U.S.C. §§ 12471-12496]]

** Notices
[[https://www.hud.gov/sites/dfiles/FHEO/documents/FHEO-2023-01-%20FHEO%20VAWA%20Notice.pdf][FHEO Notice 2023-01]]

[[https://www.govinfo.gov/content/pkg/FR-2016-11-16/pdf/2016-25888.pdf][HUD’s 2016 Final Rule]]

[[https://www.hud.gov/sites/documents/17-05hsgn.pdf][HUD’s Office of Multifamily Housing Program Guidance (H 2017-05)]]

[[https://www.hud.gov/sites/documents/pih-2017-08vawra2013.pdf][HUD’s Office of Public and Indian Housing Program Guidance (PIH-2017-08)]]

** HUD VAWA FORMS

[[https://www.hud.gov/sites/dfiles/OCHCO/documents/5380.pdf][Notice of Occupancy Rights Under the Violence Against Women Act]]

[[https://www.hud.gov/sites/dfiles/OCHCO/documents/5381.pdf][Model Emergency Transfer Plan for Victims of Domestic Violence, Dating Violence, Sexual Assault, or Stalking]]

[[https://www.hud.gov/sites/dfiles/OCHCO/documents/5382.pdf][Certification of Domestic Violence, Dating Violence, Sexual Assault, or Stalking, and Alternate Documentation]]

[[https://www.hud.gov/sites/dfiles/OCHCO/documents/5383.pdf][Emergency Transfer Request for Certain Victims of Domestic Violence, Dating Violence, Sexual Assault, or Stalking]]

[[https://www.hud.gov/sites/documents/91067.doc][Section 8 VAWA Lease Addendum]]

* Your Rights Under the Violence Against Women Act (VAWA)
[[https://www.hud.gov/hud-partners/fair-housing-vawa#:~:text=VAWA's%20protections%20include%2C%20for%20example,survivor%20of%20VAWA%20violence%2Fabuse.][Cite]]

** VAWA’s Protections and Coverage

If you are

- applying for,
- receiving assistance under,
- or living in public housing,
- any housing operated by a public housing authority,
- voucher programs,
- homeless assistance programs,
- federally assisted housing for persons with disabilities or for elderly persons,
- or any other housing receiving assistance from HUD,

you may have housing protections under VAWA.

If you are a tenant in a HUD-funded program, certain VAWA protections
may also apply to other residents and persons associated with you,
including residents and affiliated individuals.

VAWA applies to many different HUD grantees under what are called “covered housing programs.” (See 34 U.S.C. § 12491(a)(3)).
HUD’s covered housing programs include:

- Section 202 *Supportive Housing for the Elderly*, including the direct loan program under section 202;

- Section 811 *Supportive Housing for Persons with Disabilities*;

- *Housing Opportunities for Persons With AIDS* (HOPWA) program;

- Homeless programs under title IV of the McKinney-Vento Homeless Assistance Act, including

  - the Emergency Solutions Grants program,

  - the Continuum of Care program, and

  - the Rural Housing Stability Assistance program;

- *HOME Investment Partnerships* (HOME) program;

- Multifamily rental housing under section 221(d)(3)/(d)(5) of the National Housing Act with a below-market interest rate (BMIR);

- Multifamily rental housing under section 236 of the National Housing Act;

- HUD programs assisted under the *United States Housing Act of 1937*; specifically,

  - public housing under section 6 of the 1937 Act,

  - tenant-based and project-based rental assistance under section 8 of the 1937 Act, and

  - the Section 8 Moderate Rehabilitation Single Room Occupancy;

- *Housing Trust Fund*; and

- Other Federal housing programs that provide affordable housing to
  low and moderate-income persons through restricted rents or rental
  assistance, or other affordable housing opportunities, which HUD
  identifies as covered by VAWA. This will ordinarily occur in a
  Notice of Funding Opportunity (NOFO).

- (See 34 U.S.C. § 12491.)


VAWA also protects your right to report crime and emergencies from
your home, regardless of whether your housing is assisted under a
covered housing program. (See 34 U.S.C. § 12495).

*** Example Protections under VAWA

If you feel these or any other of your VAWA rights have been violated, you may file a complaint with HUD [[https://www.hud.gov/fairhousing/fileacomplaint][here]].

You may also file a complaint alleging that your rights under multiple laws have been violated. Read more about the other fair housing laws enforced by FHEO [[https://www.hud.gov/stat/fheo/rights-obligations][here]].

- Non-discrimination ::
  It is illegal
  - to deny you admission to or assistance under,
  - or to evict you from or terminate your participation in,
  - a covered housing program
  - if you or a member of your household is or has been a survivor of
    VAWA violence/abuse.
  - You or a member of your household must be otherwise eligible for
    the program.
  - In addition, it is illegal to deny you tenancy or occupancy rights
    (for example, you cannot be evicted) in a covered housing program
    solely on the basis of criminal activity directly relating to the
    VAWA violence/abuse.
  - HUD refers to these protections as VAWA’s “core” housing
    protections. (See 24 C.F.R. § 5.2005(b)).


- Notification of Occupancy Rights ::
  If you are an applicant or tenant,
  - a covered housing provider
  - must provide to you
  - two HUD-approved documents:
    (1) Notice of Occupancy Rights under VAWA, and
    (2) VAWA certification form.
  - The covered housing provider
  - must provide you these forms at certain specified times.
  - (See 34 U.S.C. § 12491(d); 24 C.F.R. § 5.2005(a)).


- Emergency Transfers ::
  You can request an emergency transfer for you and your household in a covered housing program if you:
    - (1) expressly request the transfer; and

    - (2)(a) you reasonably believe there is a threat of imminent harm
      from further violence if you remain in the same unit; or

    - (2)(b) in the case of sexual assault, the sexual assault
      occurred at your housing during the 90-calendar-day period
      preceding the date of the transfer request.

  - Public housing agencies and other covered housing programs must adopt an emergency transfer plan based on a model plan from HUD.

  - This emergency transfer plan must, among other requirements,
    - allow you to make an internal emergency transfer (to a unit where you would not be categorized as a new applicant) when a safe unit is immediately available.
    - A safe unit is a unit that you believe is safe. (See 24 C.F.R. § 5.2005(e)).


- Confidentiality Requirements ::
  - Covered housing providers have specific obligations to maintain
    the confidentiality of the fact that a person is a survivor of
    domestic violence, dating violence, sexual assault, or stalking.

  - Any information you provide under VAWA’s housing protections,
    including the fact that you are a VAWA survivor, must be kept
    confidential by the covered housing provider.

  - These obligations include
    - keeping any such information out of a shared database

    - and not disclosing such information to others
      - unless you consent in writing to such disclosure,

      - it is required for use in an eviction proceeding,

      - or the law otherwise requires it.

  - If your information is used by a covered housing provider in
    violation of the confidentiality requirements, you may file a
    complaint with HUD. (See 34 U.S.C. § 12491(c)(4); 24 C.F.R. §
    5.2007(c)).


- Documentation ::
  - If you inform a public housing agency or owner or manager of housing assisted under a covered housing program
  - that you are a survivor of VAWA violence/abuse entitled to VAWA protections,
  - the covered housing provider may request, in writing,
    - that you submit documentation of the occurrence of the domestic violence, dating violence, sexual assault, or stalking.
  - If your housing provider simply provides a VAWA reporting form to you, without a dated letter requesting documentation,
    - the housing provider has not sufficiently made the request in writing.
  - You have the discretion to choose which documentation to provide from the list identified in HUD’s VAWA rule, unless there is conflicting information of VAWA violence/abuse.[2]
  - For example, a housing provider may not require a police report to provide VAWA housing protections (but you may choose to provide one). (See 34 U.S.C. § 12491(c); 24 C.F.R. § 5.2007).


- Lease Bifurcation ::
  VAWA protects you and other members of your household
  - when a covered housing provider removes a household member from a lease, in order to
    - evict,
    - remove,
    - terminate occupancy rights,
    - or terminate assistance
    - to a household member who engages in criminal activity directly relating to VAWA violence/abuse
  - (known as “bifurcating” a lease).
  - Your housing provider may choose whether to bifurcate the lease, and if it is done, it must be done consistent with applicable federal, state, or local laws and the requirements of your covered housing program.
  - In the event of a lease bifurcation, if the household member who was removed was the tenant who made your household eligible for assistance under your covered housing program, your housing provider must give those who remain a reasonable time to establish eligibility under the same program, under a different program, or to find other housing.
  - While this is generally 90 days, it may be a different amount of time, depending on which covered housing program you are participating in. (See 24 C.F.R. § 5.2009).


- Prohibition on Retaliation ::
  It is illegal for a public housing agency or an owner or manager of housing assisted under a covered housing program
  - to retaliate against you
  - because you opposed any action they took or practice they have
  - that is prohibited by VAWA.
  The housing provider also cannot
  - subject you to
    - retaliation,
    - coercion,
    - intimidation,
    - or threats
  - because you
    - testified,
    - assisted,
    - or participated
    - in an action to enforce your VAWA rights,
    - including encouraging another or exercising your own rights under VAWA.
  - This includes
    - retaliating against you
      - for filing a complaint with FHEO or another entity,
      - or for participating in an investigation of your own complaint or another complaint by giving information as a witness.
  - This right applies even if you did not file a complaint over what
    you believe was the initial violation of VAWA rights or if you
    filed such a complaint and received a determination that there is
    no reasonable cause to believe that a VAWA violation occurred or
    is about to occur. (See 34 U.S.C. § 12494)


- The Right to Report Crime and Emergencies from One’s Home ::
  Landlords, homeowners, tenants, residents, occupants, guests of, or applicants for, any housing
  - have the right to seek law enforcement or emergency assistance on their own behalf or on behalf of another person in need of assistance.

  They may not be penalized
  - based on their requests for assistance,
  - based on criminal activity for which they are a victim,
  - or based on activity for which they are otherwise not at fault under a law, ordinance, regulation, or policy adopted by or enforced by a governmental entity that receives certain HUD funding.

  This means it is unlawful
  - to threaten or subject individuals seeking assistance to any of the following:
    - monetary or criminal penalties, fines, or fees;
    - eviction;
    - refusals to rent or renew tenancy;
    - refusals to issue an occupancy or landlord permit;
    - withdrawing certifications or permits for operation of the property; and
    - designation of the property as a nuisance or a similar negative designation.
  - (See 34 U.S.C. § 12495).

** How to File a Complaint, Coverage, and Protections

*** Overview

- The Violence Against Women Act (VAWA, 34 U.S.C. § 12471 et seq.)

The Violence Against Women Act (VAWA, 34 U.S.C. § 12471 et seq.)
provides housing protections for survivors of domestic violence,
dating violence, sexual assault, and/or stalking (collectively
referred to on this page as “VAWA violence/abuse”).[1] (See 34
U.S.C. § 12291).

Despite the name of the law, VAWA’s protections apply regardless of
sex, sexual orientation, or gender identity (See 24 C.F.R. § 5.2001).

VAWA was reauthorized and amended in March 2022, and it became
effective on October 1, 2022.  As part of that reauthorization,
Congress required HUD to implement and enforce the housing provisions
of VAWA consistent with, and in a manner that provides, the same
rights and remedies as those provided for in the Fair Housing
Act. Therefore, if you believe your VAWA rights have been violated,
you may file a complaint with HUD’s Office of Fair Housing and Equal
Opportunity (FHEO).

*** How to File a VAWA Complaint

If you believe your VAWA rights have been violated, you can [[https://www.hud.gov/fairhousing/fileacomplaint][visit this
link]] to file a complaint with HUD’s Office of Fair Housing and Equal
Opportunity (FHEO). You can also [[https://www.hud.gov/stat/fheo/intake-investigation][find out more]] about the complaint
process.
