#+title:      [HTF] Fw: Eviction law firm meets FDCPA definition of "debt collector"
#+date:       [2025-04-16 Wed 12:52]
#+filetags:   :collector:debt:fdcpa:federal:htf:
#+identifier: 20250416T125209

* Email 2025-04-10

Karen Phillips via groups.nwjustice.org <karen.phillips=nwjustice.org@groups.nwjustice.org>
Apr 10, 2025, 9:23 AM (6 days ago)
to NJP, HTF@groups.nwjustice.org

FYI.

Karen M. Phillips (she/her)
Statewide Advocacy Counsel
Northwest Justice Project
1814 Cornwall Ave., Bellingham, WA 98225
Direct: 206.707.7217 | Fax:  1.206.299.3025
www.nwjustice.org | www.washingtonlawhelp.org
Combating Injustice • Strengthening Communities • Protecting Human Dignity
Confidentiality Notice: This e-mail may contain confidential and privileged information. If you have received this message by mistake, please notify me immediately by replying to this message or telephoning me (206) 707-7217, and do not review, disclose, copy or distribute it. Thank you.

* Email Source 2025-04-10
From: April Kuehnhoff
Sent: Thursday, April 10, 2025 5:46 AM
To: protect-tenants@nclc.org
Subject: Eviction law firm meets FDCPA definition of "debt collector"

Caution: This is an external email. Please take care when clicking links or opening attachments.

*Judge Rules Law Firm Specializing in Evictions Meets FDCPA’s Definition of ‘Debt Collector’*
mikegibbby mikegibb   April 10, 2025  in Compliance, FDCPA

A District Court judge in Minnesota has denied a defendant’s motion for judgment on the pleadings in a Fair Debt Collection Practices Act case, ruling the defendant — a law firm that specializes in representing landlords — meets the statute’s definition of a “debt collector.”

- The background ::
  - The case was filed after the defendant pursued eviction actions on behalf of clients against several tenants.
  - In each instance, the defendant was hired to evict tenants over rental arrears, but

- the plaintiffs argue that ::
  - the defendant’s actions extended beyond simply evicting them.
  - For instance, in one case, a tenant alleges that
    - the defendant tried to collect an incorrect debt after a landlord improperly assessed duplicate charges following an overpayment.
  - Similarly, other plaintiffs allege that
    - the defendant’s eviction actions sought to recover amounts that they did not legally owe, including excessive fees and overstated rental arrears.

- The plaintiffs argue that ::
  - the defendant’s conduct violated multiple provisions of the FDCPA,
  - including the prohibition against misleading representations and unlawful collection practices.

- In response, the defendant filed motions for judgment on the pleadings in three separate cases, asserting that ::
  - its actions were exempt from the FDCPA’s reach because
    - they were primarily related to enforcing a security interest, similar to actions in nonjudicial foreclosure cases.

- The ruling ::
  - Judge Katherine Menendez of the District Court for the District of Minnesota _disagreed_ with the defendant’s position, like that in the Obduskey v. McCarthy & Holthus LLP case, that its eviction efforts were merely to enforce a security interest and should fall outside the scope of the FDCPA.

  - Judge Menendez explained in her ruling that ::
    - while Obduskey limited debt collector status to specific cases involving security interest enforcement,
    - it did not create an exemption for eviction proceedings under Minnesota law.
    - She emphasized that eviction actions, particularly when related to rent collection or disputes, often qualify as debt collection, a position previously supported in similar cases within the district.
    - “Although the Eighth Circuit has not addressed this issue, courts in this District have observed that under Minnesota law, an eviction action is ‘equivalent to a demand for rent,’ and therefore qualifies as debt collection activity for purposes of the main coverage of FDCPA,” Judge Menendez wrote in her ruling.

[[https://www.accountsrecovery.net/wp-content/uploads/2025/04/Johnson-v.-Landlord-Resource-Network.pdf][Read the Ruling]]

* Email with Different Source

Meredith Bruch via groups.nwjustice.org <meredithb=nwjustice.org@groups.nwjustice.org>
Apr 10, 2025, 12:54 PM (6 days ago)
to HTF@groups.nwjustice.org

L/T law meet Consumer law-  interesting case out of Minnesota- see below.

If you want to see the ruling here it is (to save you a few clicks):  https://www.accountsrecovery.net/wp-content/uploads/2025/04/Johnson-v.-Landlord-Resource-Network.pdf

Meredith

Meredith O. Bruch
Statewide Advocacy Counsel
Northwest Justice Project

* Email from Chris Brunetti 2025-04-10

Chris Brunetti via groups.nwjustice.org <chris.brunetti=nwjustice.org@groups.nwjustice.org>
Apr 10, 2025, 2:42 PM (6 days ago)
to Nick, Karen, NJP, HTF@groups.nwjustice.org

Thanks for sharing, Karen.  Very interesting case that has me thinking about how we can use FDCPA, and Collection Agency Act (CAA), RCW 19.16 (WA’s analogue to FDCPA) in connection with our representation of tenants facing eviction.

Nick, in addition to CR 3(e), RCW 19.16.250(27) also prohibits a collection agency from “[s]erv[ing] a debtor with a summons and complaint unless the summons and complaint have been filed with the court…”.  Violations of RCW 19.16.250 are per se violations of the CPA, and could entitle debtor/tenant to damages under the CPA.  RCW 19.16.440.  Of course this gets into the discussion of whether by raising this as a defense in UDAs we’d be discouraging LLs from pocket service, which means more UDAs being filed.  But honestly, I think the benefits of keeping UDAs unfiled seem to be dwindling.

I’ll further note that although the CAA seems to exclude “lawyers” from its definition of “collection agency” (see RCW 19.16.100(5)(c)), the courts have interpreted that as only excluding lawyers who are attempting to collect their own debts.  Paris v. Steinberg & Steinberg, 828 F.Supp.2d 1212 (2011); Jenkins v. Puckett and Redford PLLC, 2020 WL 45179333 (2020).

I’ve only just started thinking about how we could potentially use FDCPA and CAA in the context of representing tenants being evicted, so I’m not entirely sure how applicable it is, or how often it would even make sense strategically to raise claims/defenses based on the FDCPA/CAA.  That being said, I think we should try to familiarize ourselves to some extent with the prohibited acts in [[https://www.law.cornell.edu/uscode/text/15/1692f][15 USC 1692f]] and [[https://app.leg.wa.gov/rcw/default.aspx?cite=19.16.250][RCW 19.16.250]] (Also, would landlord attorneys be subject to the licensing requirements in the CAA, RCW 19.16.110 and .260?), and continue the discussion about how and when to use these statutes to benefit our clients.  In that regard, I’m very interested in hearing others’ thoughts on this.
