#+title:      Defense of Payment
#+date:       [2025-04-15 Tue 13:30]
#+filetags:   :accounting:defense:payment:
#+identifier: 20250415T133000
#+signature:  payment01

* Payment-Key Number Topics 294k1--Nature and Requisites in General

“Payment”, as a defense to a suit, connotes tender by the debtor with the intention to satisfy the debt, coupled with its acceptance as satisfaction by the creditor.

But recognizing the Government's long-standing power to set off is far different from finding that the Government's setoff is ‘payment’ which enables the Government to plead in admiralty foreign and unrelated **860 transactions.
- See
  - United States v. Munsey Trust Co. of Washington, D.C., 332 U.S. 234, 239, 67 S.Ct. 1599, 1601, 91 L.Ed. 2022;
  - McKnight v. United States, 13 Ct.Cl. 292, 306, affirmed 98 U.S. 179. 25 L.Ed. 115;
  - Climatic Rainwear Co. v. United States, 88 F.Supp. 415, 418, 115 Ct.Cl. 520.

In other situations, the claim of withholding and applying has traditionally been treated as setoff. Virginia-Carolina Chemical Co. v. Kirven, 215 U.S. 252, 257—258, 30 S.Ct. 78, 79—80, 54 L.Ed. 179;
  - Merchants Heat & Light Co. v. James B. Clow & Sons, 204 U.S. 286, 289—290, 27 S.Ct. 285, 286, 51 L.Ed. 488 (a recoupment case);
  - Scammon v. Kimball, 92 U.S. 362, 367, 23 L.Ed. 483; United States v. Eckford, 6 Wall. 484, 18 L.Ed. 920.

See also 3 Williston, Contracts (rev. ed. 1936), s 887E. In this context, ‘payment’ connotes tender by the debtor with the intention to satisfy the debt *319 coupled with its acceptance as satisfaction by the creditor.
- See
  - Luckenbach v. W. J. McCahan Sugar Co., 248 U.S. 139, 149, 39 S.Ct. 53, 55, 63 L.Ed. 170;
  - Bronson v. Rodes, 7 Wall. 229, 250, 19 L.Ed. 141;
  - Sheehy v. Mandeville, 6 Cranch 253, 264, 3 L.Ed. 215;
  - United States to Use of Par-Lock Appliers of New Jersey, Inc. v. J.A.J. Const. Co., 3 Cir., 137 F.2d 584, 586.

- United States v. Isthmian Steamship Co., 359 U.S. 314, 318–19, 79 S. Ct. 857, 859–60, 3 L. Ed. 2d 845 (1959)



** Payment is Based upon the Intention of the Parties

- Note :: "Intention" as used by these case decisions seems to refer to the underlying contract that produced the debt, not the act of tender or acceptance.  To determine how the tendered money is to be applied, one must seek an understanding of the contract, as well as common law.
- Note 2 :: But see Thrifty Supply Co. of Seattle v. Deverian Builders, Inc., 3 Wn. App. 425, 428–29, 475 P.2d 905, 907 (1970)


*** Thrift Supply Co. of Seattle

Payment is established only with the receipt of funds by the creditors, coupled with _an intention on behalf of both parties_ that the funds received constitute payment. Fisher v. Seattle, 55 Wash. 396, 104 P. 655 (1909); *429 Union States Life Ins. Co. v. Bernert, 161 Or. 44, 87 P.2d 774 (1939). When an owner makes a check payable jointly to a contractor and a materialman, the payees should ordinarily understand the owner's intention is the money be used to discharge the lien rights of the materialman. However, _the intention of the parties is a question of fact_, and it is not necessarily improper for the contractor to retain the proceeds of such a joint check, keeping alive the materialman's claim. [[*B&J Constr. Co.][B. & J. Constr. Co. v. Spacious Homes, Inc., 204 Cal.App.2d 216, 22 Cal.Rptr. 41 (1962)]].

- Thrifty Supply Co. of Seattle v. Deverian Builders, Inc., 3 Wn. App. 425, 428–29, 475 P.2d 905, 907 (1970)


Where the parties, by express or implied agreement, consent to a different application of payments even though a check made out to joint payees is given, the court will effectuate this intent. Pioneer Sand & Gravel Co. v. Grevstad, 181 Wash. 239, 42 P.2d 438 (1935). Finding of fact 19 specifically held that:

- Thrifty Supply Co. of Seattle v. Deverian Builders, Inc., 3 Wn. App. 425, 429, 475 P.2d 905, 907 (1970)


**** B&J Constr. Co.

When an owner makes a check payable jointly to a contractor and a materialman, the payees should ordinarily understand that the owner's intention is that the money be used to discharge the lien rights of the materialman. ( **46 Westwood Bldg. Materials Co. v. Valdez, 158 Cal.App.2d 107, 322 P.2d 79.) However, _the intention of the parties is a question of fact_, and it is not necessarily improper for the contractor to retain the proceeds of such a joint check, keeping alive the materialman's claim. (See J. S. Schirm Co. v. Rollingwood Homes Co., 56 Cal.2d 789, 17 Cal.Rptr. 1, 366 P.2d 444; Petaluma Building Materials, Inc. v. Foremost Properties, Inc., 180 Cal.App.2d 83, 4 Cal.Rptr. 268.)

In the present case Stone Hills made progress payments from time to time, but the record does not reveal how the amounts were being calculated, nor does it show that plaintiff was told how the amounts of the checks were determined.

The payments were apparently not based on plaintiff's invoices.

The original Spacious Homes-Walker contract contained specific provisions for progress payments, _but the parties apparently were not following that_.

Plaintiff's manager, Kaldenberg, testified that when a joint check dated April 24 for $2,306.25 was received, plaintiff only had approximately $1,800 in rental earned, so he allowed Britton to retain $500 while plaintiff received and credited $1,806.25. He gave a similar *224 explanation with respect to a $2,550 check, of which Britton was allowed to retain $250.

It was not necessary that the trial court accept plaintiff's explanation, but the evidence is significant because the trial court did not make a finding that plaintiff acted in bad faith or intended to defraud.

- B. & J. Const. Co. v. Spacious Homes, Inc., 204 Cal. App. 2d 216, 223–24, 22 Cal. Rptr. 41, 45–46 (Cal. Ct. App. 1962)

*** Luckenback

It is essential to the performance of the insurer's service, that the insured be promptly put in funds, so that his business may be continued without embarrassment. Unless this is provided for, credits which are commonly issued against drafts or notes with bills of lading attached, would not be granted. Whether the transfer of money or other thing shall operate as a payment, is ordinarily a matter which is determined by _the intention of the parties to the transaction_. Compare The Kimball, 3 Wall. 37, 44, 18 L. Ed. 50.

- Luckenbach v. W.J. McCahan Sugar Ref. Co., 248 U.S. 139, 149, 39 S. Ct. 53, 55, 63 L. Ed. 170 (1918)


*** The Kimball
The second question for determination is, whether the notes given for a portion of the charter-money constituted payment of the same?

The notes were given before the termination of the voyage, and, consequently, before the balance of the charter-money became due. Treating them as an advance of a portion of the freight, they could be recovered back, or their amount, if paid, if the vessel did not arrive. Freight being *45 the compensation for the carriage of goods, if paid in advance, is in all cases, unless there is a special agreement to the contrary, to be refunded, if from any cause not attributable to the shipper the goods be not carried.13 And there was no such special agreement in this case. The notes were drawn so as to mature near the time of the anticipated arrival of the ship, and according to the statement of the broker who made the arrangement, they were given for the accommodation of the ship-owner, and were to be held over or renewed in case they fell due before the arrival. This statement is consistent with the nature of the transaction, and is sufficient to repel any presumption, under the law of Massachusetts, that the notes were taken in discharge or payment of the claim for the charter-money.

The presumption which prevails in that State, that a promissory note extinguishes the debt or claim for which it is given, may be repelled by any circumstances showing that such was not the intention of the parties.

- The Kimball, 70 U.S. 37, 44–45, 18 L. Ed. 50 (1865)


**7 By the general commercial law, as well of England as of the United States, a promissory note does not discharge the debt for which it is given unless such be _the express agreement of the parties_; it only operates to extend until its maturity the period for the payment of the debt. The creditor may return the note when dishonored, and proceed upon the original debt. The acceptance of the note is considered as accompanied with the condition of its payment. Thus it was said, as long ago as the time of Lord Holt, that ‘a bill shall never go in discharge of a precedent debt, except it be part of the contract that it should be so.'14 Such has been the rule in England ever since; and the same rule prevails, with few exceptions, in the United States. The doctrine proceeds upon the obvious ground, that nothing can be justly considered as payment in fact, but that which is in truth such, unless something else is expressly agreed to be received in its place. That a mere promise to *46 pay cannot of itself be regarded as an effective payment is manifest.

- The Kimball, 70 U.S. 37, 45–46, 18 L. Ed. 50 (1865)

*** Fisher v. City of Seattle

The fact that the city of Seattle appropriated from its general fund $72,500 for the purpose of retiring certain outstanding warrants issued by the city of Ballard, and actually paid $65,000 thereof, did not necessarily extinguish such indebtedness so as to relieve the taxable property of Ballard, unless it was clearly intended to do so. Bardsley v. Sternberg, 18 Wash. 612, 52 Pac. 251, 524. It was said in that case: ‘ _The intention of the obligor_ is important in determining the **656 question whether obligations have or have not been extinguished.’

- Fisher v. City of Seattle, 55 Wash. 396, 399, 104 P. 655, 655–56 (1909)

*** Bardsley v. Sternberg

From the above cases it appears that something more may be necessary to constitute payment on the part of municipal or other public corporations than the delivery to the holder of its warrants or other obligations of the amount of money evidenced thereby, and that _the intention of the obligor_ is important in determining the question whether the obligations have or have not been extinguished.

Other authorities expressly announce the doctrine that _upon the question of payment the intent or purpose of the parties to the transaction_ is not to be disregarded.

In 18 Am. & Eng. Enc. Law, p. 150, it is said: “Payment is a mode of extinguishing obligations. It is is an act calling for the exercise of will,–of consent. To constitute a payment, money or some other valuable thing must be delivered by the debtor to the creditor for the purpose of extinguishing the debt, and the creditor must receive it for the same purpose.”

In Cushing v. Wyman, 44 Me. 121, it was held that: “To enable a party to set up the defense of payment, there must be the concurring intention of the party making and the party receiving the payment. The payment must be received as well as made in satisfaction of the debt.”

And in Bloodworth v. Jacobs, 2 La. Ann. 24, the court said: “By the term ‘payment’ is meant not only the delivery of a sum of money, but the performance of an obligation. *** It is an act requiring the exercise of the will,–of consent,–without which it has not the characteristics of that mode of extinguishing obligations.”

*618 And Daniel's definition of the term is as follows: “By ‘payment’ is meant the discharge of a contract to pay money by giving to the party entitled to receive it the amount agreed to be paid by one of the parties who entered into the agreement.

Payment is not a contract. It is the discharge **253 of a contract in which the party of the first part has a right to demand payment, and the party of the second part has a right to make payment.” 2 Daniel, Neg. Inst. (4th Ed.) § 1221.

- Bardsley v. Sternberg, 18 Wash. 612, 617–18, 52 P. 251, 252–53 (1898)
