#+title:      Subsidized Housing Basics 2025
#+date:       [2025-11-03 Mon 11:40]
#+filetags:   :federal:hud:subsidized:training:
#+identifier: 20251103T114046
#+signature:  training

* Email
:LOGBOOK:
- Note taken on [2025-06-20 Fri 12:43]\\
  EMAIL GIVING SCHOLARSHIP:
  -------------------------
  PLI Info <info@pli.edu>
  Jun 20, 2025, 12:43 PM
  to me

  PLI Logo

  Dear W. Lincoln Harvey:

  We are pleased to inform you that you have been registered with a 100% scholarship to view our archived seminar, Subsidized Housing Basics 2025.

  PLI Scholarships are non transferrable and cannot be used towards another program, nor can this scholarship be given to anyone else.

  You can access the course materials via the "My Library" area of the homepage, after you have logged in. Please note that you have will access to this On Demand Web Program for a limited time only.

  Web Access Instructions

  - Go to [[https://www.pli.edu][www.pli.edu]] and click "Sign In" in the upper right corner.

  - In the Business Email box enter the email address associated with your account and your password.

  - If you do not know your password, please click "Forgot Password?" and you will be sent a link to reset your password.

  - Check your email for the temporary password and follow the link to www.PLI.edu

  - Enter your email and temporary password. Create a new password and click "Submit" to log in.

  - Please click on your initials in the upper right corner of the site. Your program(s) will be located in the "My Library" section of your PLI home page.

  - On the morning of the webcast, click the title of the program. A window regarding program credit information and verifying your attendance will appear. Please proceed through the windows and read the information and scroll down to click the Start Watching button under *"By continuing, you understand the credit status and attendance verification requirements."*

  - If requesting credit: Verify your viewing by clicking the time stamp pop ups during the program. If viewing a live webcast, it is not required to click the time stamp during breaks. Upon completion please click the “Credit” icon that resembles a checkbox in a circle located in the upper right corner of the program screen.

  PLI greatly values your business, and we look forward to seeing you at the seminar. If you have any further questions, please feel free to respond to this email or contact PLI Customer Service at 1-800-260-4754.

  Sincerely,

  Leonard McKenzie
  Scholarship/Pro Bono Privileged Membership Manager
  Practising Law Institute
  1177 Avenue of the Americas | New York, NY 10036
:END:
