#+title:      RCW 59.18.670 Security deposit—Landlord waiver, disclosure form—Fee in lieu—Claims for losses—Judicial action, collection activity—Violation.
#+date:       [2025-06-30 Mon 14:09]
#+filetags:   :deposit:fees:law:security:
#+identifier: 20250630T140918
#+signature:  rcw=59=18=670

* RCW 59.18.670
1. Notwithstanding any other provision of law, if a landlord chooses to waive a security deposit requirement, and a tenant agrees to instead pay a fee in lieu of a security deposit, the landlord shall:
   - (a) Ensure that the fee in lieu of a security deposit is strictly optional for the tenant, and the tenant may choose to pay a full security deposit rather than a fee in lieu of a security deposit;
   - (b) Not use a prospective tenant's choice to pay a fee in lieu of a security deposit or a traditional security deposit as a criterion in the determination of whether to approve an application for occupancy;
   - (c) If choosing to offer the fee in lieu of a security deposit option, offer it to every prospective tenant whose application for occupancy has been approved, without further regard to income, race, gender, disability, source of income, sexual orientation, immigration status, size of household, or credit score;
   - (d) Allow any tenant that agrees to pay a fee in lieu of a security deposit to opt out of the continuing fee in lieu of a security deposit obligation upon full payment of the security deposit that is listed in the disclosure form pursuant to (f)(ii) of this subsection, and in the event the tenant seeks to pay a security deposit, RCW 59.18.610 shall apply;
   - (e) Provide a written checklist to the tenant pursuant to RCW 59.18.260; and
   - (f)
     - (i) Disclose to the tenant in writing:
       - (A) The terms of any insurance coverage purchased by the landlord for landlord's losses associated with any unpaid amounts due from the tenant to the landlord pursuant to the lease, including but not limited to rent, fees, or unit damage in excess of wear resulting from ordinary use of the premises, and including the amount of exclusions or caps, if any, on coverage of any amounts due from the tenant to the landlord pursuant to the lease; and
       - (B) If the insurance provider requires the landlord to first attempt reimbursement from the tenant before filing a claim, that payment of the fee in lieu of a security deposit does not preclude the insurer or the landlord from proceeding against the tenant to recover any unpaid amounts due to the landlord pursuant to the lease and unpaid costs to repair damage to the property for which the tenant is responsible pursuant to the lease but never to include any sums for wear resulting from ordinary use of the premises, together with reasonable attorneys' fees.
     - (ii) Such disclosures to the tenant must be in substantially the following form:

* About

** Query
From: Samantha Adams <sama@nwjustice.org>
Sent: Monday, June 30, 2025 9:51 AM
To: Housing Task Force <htf@groups.nwjustice.org>
Cc: NJP Internal - HTF <NJPInternal-HTF@nwjustice.org>
Subject: Leap Easy - a (predatory) product for landlords to exploit tenants?

Have you heard about https://www.leapeasy.com/?  This company apparently offers (unnecessary) deposit assistance in the form of what looks like a loan or insurance policy to pay security deposits or even co-sign on a tenant’s lease. From the website: “Leap Insurance Agency, LLC arranges coverage for residential landlords in states where it is licensed to offer insurance products.” Let me know if you have any experience pushing back on auto-enrollment in the program via a property manager portal and/or the additional charges that may have accrued. Thanks, all!

Samantha L. Adams | Staff Attorney  (She/Her)
Northwest Justice Project | 400 Warren Ave., Ste. 350 | Bremerton, WA 98337
sama@nwjustice.org | P. 360-377-6378 | F. 360-627-9256 | D. 206-707-0838

** Response
Scott Crain via groups.nwjustice.org <scottc=nwjustice.org@groups.nwjustice.org>
12:18 PM (1 hour ago)
to Samantha, Housing

At least for the deposit product, this appears to be a version of LeaseLock that was approved by the legislature in 2022, and codified at RCW 59.18.670. I think our analysis was that on a short-term basis this could be financially beneficial for a renter that couldn’t meet the deposit amount, but got less advantageous the longer they stayed in the unit. It all depends on how much the monthly fee is and what the deposit is. Sarah Nagy might remember more.
