#+title:      Reasonable Accommodations
#+date:       [2025-10-30 Thu 17:12]
#+filetags:   :accommodation:cases:reasonable:
#+identifier: 20251030T171214
#+signature:  law

* Kiemle & Hagood Company v. Daniels -- 26 Wash.App.2d 199, 528 P.3d 834 (Div 3 April 27, 2023)

** Synopsis

*** Background

 Landlord initiated unlawful detainer action against tenant, alleging
 she violated lease provisions requiring her to keep her apartment
 clean and sanitary. Tenant asserted affirmative defense of failure to
 reasonably accommodate her disability. After granting landlord's
 request for writ of restitution and denying tenant's request for jury
 trial, the Superior Court, Spokane County, Julie M. McKay, J.,
 entered judgment for landlord. Tenant appealed.

*** Holdings

The Court of Appeals, Pennell, J., held that:
1. landlord's notice of termination gave tenant sufficient opportunity
   to defend against landlord's allegations;
2. genuine issue of material facts existed to require jury trial
   determination as to whether landlord established basis for
   eviction;
3. tenant provided sufficient facts to require jury trial on issue of
   landlord's knowledge or constructive knowledge of her disability;
4. tenant provided sufficient facts to require jury trial on issue of
   necessity of accommodation for her disability; and
5. tenant provided sufficient facts to require jury trial on issue of
   reasonableness of the requested accommodation.

Reversed and remanded.

** Law

*** Defense of Failure to Accommodate

Tenant expressly requested discontinuation of eviction as
accommodation, which would give her time to find resources to help her
with those tasks.

**** Elements of Defense

A tenant raising failure to accommodate under federal and state law as
an affirmative defense to eviction in an unlawful detainer case must
show five elements:

1. they have a disability as that term is statutorily defined,
2. their landlord knew or reasonably should have known of the
   disability,
3. the requested accommodation may be necessary to afford the tenant
   an equal opportunity to use and enjoy their dwelling,
4. the landlord denied the request, and
5. the requested accommodation is reasonable.


See
- 42 U.S.C.A. §§ 3604(f)(2),
- 3604(f)(3)(B);
- Wash. Rev. Code Ann. §§ 49.60.222(1)(f),
- 49.60.222(2)(b),
- 59.18.650(2)(c).


**** 3rd Party Verification is Unwarranted when LL Knew or Should Have Known

In context of a tenant's claim of failure to accommodate under state
and federal law, as affirmative defense to eviction in an unlawful
detainer action, third-party verification of a tenant's disability is
unwarranted when a tenant's disability is obvious or otherwise known
to the landlord.

See:
- 42 U.S.C.A. §§ 3604(f)(2),
- 3604(f)(3)(B);
- Wash. Rev. Code Ann. §§ 49.60.222(1)(f),
- 49.60.222(2)(b),
- 59.18.650(2)(c).

**** Reasonableness of Requested Accommodation is Generally a Jury Question of Fact

Generally, the reasonableness of a tenant's accommodation under
federal and state housing discrimination statutes is a question of
fact demanding case-by-case scrutiny, and questions of fact are
usually proper jury issues; however, a trial court may resolve
reasonableness as a matter of law if reasonable minds could come to
only one conclusion.  [In other words, the judge could decide the
issue of reasonableness as a matter of law in the tenant's favor
here.]

* Josephinium Associates v. Kahli (Division 1.May 6, 2002) 111 Wash.App. 617, 45 P.3d 627

** Synopsis

- Landlord brought unlawful detainer action against tenant for nonpayment of rent.
- The Superior Court, King County, Larry Jordan, J., issued a writ of restitution.
- Landlord and tenant appealed.
- The Court of Appeals, Ellington, J., held that:
  - (1) as a matter of first impression, tenant could raise the defense of unlawful discrimination in landlord's unlawful detainer action, and
  - (2) evidence was sufficient to support finding that landlord did not intentionally discriminate against tenant or fail to reasonably accommodate her disability.


Affirmed.

** Law

*** Summary

 An accommodation is reasonable, and therefore required, if it does
 not cause a “fundamental alteration in the nature of a program” or “
 ‘undue financial and administrative burdens.’ ”
 - 12 Groner, 250 F.3d at 1044 (quoting Smith & Lee Assocs.,
   Inc. v. City of Taylor, 102 F.3d 781, 795–96 (6th Cir.1996)).

 To accommodate a handicapped tenant, a landlord may be required to
 incur reasonable costs and/or change a generally applicable rule so
 that the burden is less onerous on the disabled tenant.
 - 13 Hubbard v. Samson Mgmt. Corp., 994 F.Supp. 187, 189
   (S.D.N.Y.1998).

 Whether a requested accommodation is required under the FHAA is “
 ‘highly fact-specific, requiring case-by-case determination.’ ”
-  14 Groner, 250 F.3d at 1044 (quoting California Mobile Home Park,
  29 F.3d at 1418.)

 In determining what constitutes a reasonable accommodation, the
 fact-finder should balance the burdens *624 imposed on the landlord
 and the benefits gained by the tenant.
 - 15 Bronk v. Ineichen, 54 F.3d 425, 428 (7th. Cir.1995); Marthon
   v. Maple Grove Condominium Ass'n, 101 F.Supp.2d 1041, 1051
   (N.D.Ill.2000); Groner, 250 F.3d at 1044.


Kahli alleges she was denied transfer to a less-expensive unit, or
redesignation of her own unit, because of her disability. She also
alleges she was denied reasonable accommodation for her disability by
way of assistance in becoming eligible for the transfer.

If Kahli's contentions are true, the Josephinium violated the
discrimination laws.

*** Issue

We must determine whether unlawful discrimination can constitute a
defense in an unlawful detainer action.

*** Discrimination in Housing on the Basis of Handicap is prohibited under the FHA

The federal Fair Housing Amendments Act of 1988 (FHAA) prohibits
discrimination in housing on the basis of handicap. 42 U.S.C. §
3604(f).

**** Includes Discriminatino in Terms, Conditions, or Privileges of Sale or Rental or the Provision of Services or Facilities

Unlawful discrimination includes discrimination in “terms, conditions,
or privileges of sale or rental of a dwelling, or in the provision of
services or facilities in connection with such dwelling.” 42
U.S.C. 3604(f)(a).

**** Discriminatino Includes Refusal to Make Reasonabe Accommodations in Rules, Policies, Practices, or Services When Such Maybe Necessary Equal Opportunity

Discrimination also includes “refusal to make reasonable
accommodations in rules, policies, practices, or services, when such
accommodations may be necessary to afford such person equal
opportunity to use and enjoy a dwelling.”

- 42 U.S.C. § 3604(f)(3)(B);
- United States v. California Mobile Home Park Mgmt. Co., 29 F.3d 1413, 1416 (9th Cir.1994);
- Groner v. Golden Gate Gardens Apartments, 250 F.3d 1039, 1044 (6th Cir.2001).

**** Washington Law is the Same

Washington law imposes the same prohibitions and requirements, and
provides for various remedies, including injunctive relief. RCW
49.60.222, .225.

*** Civil Rights -- Key Number Topics 78k1083 -- Discrimination by reason of handicap, disability, or illness

**** An Accommodation Is Reasonable When No Fundamental Alteration in Nature of Program Occurs

An accommodation is reasonable, and therefore required under the Fair
Housing Amendments Act, if it does not cause a fundamental alteration
in the nature of a program or undue financial and administrative
burdens. Civil Rights Act of 1968, § 804(f), as amended, 42 U.S.C.A. §
3604(f).

**** LL May Be Required to Incur a Reasonable Cost or Change a Rule to Lessen Burden

To accommodate a handicapped tenant, a landlord may be required under
the Fair Housing Amendments Act to incur reasonable costs and/or
change a generally applicable rule so that the burden is less onerous
on the disabled tenant. Civil Rights Act of 1968, § 804(f), as
amended, 42 U.S.C.A. § 3604(f).

**** To Determine Reasonableness, Balance Burdens against Benefits

In determining what constitutes a reasonable accommodation under the
Fair Federal Housing Amendments Act, the fact-finder should balance
the burdens imposed on the landlord and the benefits gained by the
tenant. Civil Rights Act of 1968, § 804(f), as amended, 42 U.S.C.A. §
3604(f).

**** Discrimination Can Be Raised as a Defense When Discrimination Arises Out of the Tenancy

Discrimination may be raised as a defense in summary eviction
proceedings when the discrimination arises out of the tenancy. West's
RCWA 59.18.380.

**** Tenant Defended Nonpayment of Rent on LL's Discrimination

Tenant asserted a cognizable unlawful discrimination defense in
landlord's unlawful detainer action, where tenant's asserted defense
to nonpayment of rent was landlord's discrimination. West's RCWA
59.18.380.

***** Facts

In January 1999, Kahli lost her rent subsidy, leaving only her
disability benefits.

Loss of the subsidy meant that Kahli was eligible for a 30 percent
unit, and she repeatedly requested that the Josephinium either
transfer her to an available 30 percent unit or redesignate her 60
percent unit as a 30 percent unit. A 30 percent unit was available and
such transfers were permitted, but the Josephinium refused to transfer
Kahli. The Josephinium also refused to redesignate her unit as a 30
percent unit.

Kahli alleges direct discrimination and refusal to make reasonable
accommodation.

Kahli's lease expired at the end of November, 1999. The Josephinium
offered her a new lease,1 which Kahli signed.

In December, however, she tendered only $276 in rent, which she
testified was the rent for a vacant 30 percent unit on her floor.

Her tender was refused. The Josephinium filed an unlawful detainer
action for nonpayment of rent.

***** Defense

Kahli asserted disability discrimination as a defense.

Specifically, she claimed that the Josephinium refused to redesignate
her unit **630 or transfer her because of her disability, and refused
to make reasonable accommodation for her disability.

The Josephinium denied discrimination, and also argued that
discrimination was not a cognizable defense in an unlawful detainer
action for nonpayment.

**** Evidence Supported Finding that LL Did not Discriminate Against Tenant

Evidence in unlawful detainer action was sufficient to support finding
that landlord did not intentionally discriminate against tenant or
fail to reasonably accommodate her disability by failing to transfer
her to a lower income apartment or converting her apartment to a lower
income unit; tenant failed to pay her rent, and redesignation of
tenant's unit to a unit available to lower income tenants would have
cost $3,000 per year in rent and would have set a negative precedent
to other tenants since tenant's apartment was much larger than other
apartments offered to families with similar incomes. Civil Rights Act
of 1968, § 804, as amended, 42 U.S.C.A. § 3604; West's RCWA 59.12.010
et seq., 59.18.380.

*** Forcible Entry and Detainer -- Key Number Topics 179k12 -- Defenses

**** Summary

The unlawful detainer statute permits a tenant to assert “any legal or
equitable defense or set-off arising out of the tenancy.”
- 20 RCW 59.18.380.


An equitable defense arises when “there is ‘a substantive legal right,
that is, a right that comes within the scope of judicial [juridicial]
action, as distinguished from a mere moral right’ ” and the usual
legal *625 remedies are unavailing.
- 21 Port of Longview v. Int'l Raw Mats., Ltd., 96 Wash.App. 431, 437,
  979 P.2d 917 (1999) (quoting Motoda v. Donohoe, 1 Wash.App. 174,
  175, 459 P.2d 654 (1969)).


To protect the summary nature of the unlawful detainer action,
defenses “arise out of the tenancy” only when they affect the tenant's
right of possession or are “ ‘based on facts which excuse a tenant's
breach.’ ”
- 22 Munden, 105 Wash.2d at 45, 711 P.2d 295 (quoting First Union
  Mgmt., Inc. v. Slack, 36 Wash.App. 849, 854, 679 P.2d 936 (1984)).


Where a defense exists that arises out of the tenancy, the court must
consider it.
- 23 Sprincin King St. Partners v. Sound Conditioning Club Inc., 84
  Wash.App. 56, 67, 925 P.2d 217 (1996) (“when the counterclaim is
  based on facts which excuse a tenant's breach, the court must
  consider it”).


Conversely, where a defense or counterclaim is not necessary to
determining the right to possession, the court has no jurisdiction to
consider it in an unlawful detainer action.
- 24 See First Union Mgmt., Inc. v. Slack, 36 Wash.App. 849, 853–54,
  679 P.2d 936 (1984).


When the tenant's breach is failure to pay rent, the inquiry is
“whether there is any legal justification for nonpayment.”
- 25 Heaverlo, 80 Wash.App. at 731, 911 P.2d 406.
- See also Income Prop. Inv. Corp. v. Trefethen, 155 Wash. 493, 284 P. 782 (1930)
  (equitable defenses available in unlawful detainer actions);
- Andersonian Inv. Co. v. Wade, 108 Wash. 373, 184 P. 327 (1919) (rule
  prohibiting defenses too broad;
- tenant may defend by setting up any defense, legal or equitable,
  which will excuse his breach);
- Brown v. Baruch, 24 Wash. 572, 64 P. 789 (1901) (equitable estoppel
  defense permitted);
- Himpel v. Lindgren, 159 Wash. 20, 291 P. 1085 (1930) (tenants may
  raise affirmative equitable defenses);
- Watkins v. Balch, 41 Wash. 310, 83 P. 321 (1906) (same—part
  performance of an oral contract);
- Northcraft v. Blumauer, 53 Wash. 243, 101 P. 871 (1909) (same—part
  performance of an oral lease).


**** Freedom from Discriminatory Eviction is a Substantive Legal Right

The right to be free from discriminatory eviction is a substantive
legal right, and ordinary civil remedies are unavailing in the face of
a summary eviction proceeding. A landlord cannot simply decide to
evict all tenants of color. If unlawful discrimination is the reason
for an eviction, the defense certainly affects the tenant's right of
possession.

**** Issue of First Impression in Washington

Most jurisdictions permit unlawful discrimination to be asserted as a
defense in summary eviction proceedings.
- 26 See Newell v. Rolling Hills Apartments, 134 F.Supp.2d 1026, 1038
  (N.D.Iowa 2001) (collecting and summarizing cases; holding defense
  applies in Iowa); Ansonia Acquisition I. LLC v. Francis, 1999 WL
  1076142, *5, 26 Conn. L. Rptr. 363 (Conn.Super.1999); Lable &
  Co. v. Flowers, 104 Ohio App.3d 227, 235, 661 N.E.2d 782 (1995);
  Mascaro v. Hudson, 496 So.2d 428, 429 (La.App.1986); Ellis
  v. Minneapolis Comm'n on Civil Rights, 319 N.W.2d 702, 704
  (Minn.1982); Marine Park Assocs. v. Johnson, 1 Ill.App.3d 464, 274
  N.E.2d 645 (1971); Abstract Inv. Co. v. Hutchinson, 204 Cal.App.2d
  242, 248, 22 Cal.Rptr. 309 (1962). See also Arnold Murray Constr.,
  L.L.C. v. Hicks, 621 N.W.2d 171 (S.D.2001); Malibu
  Inv. Co. v. Sparks, 996 P.2d 1043 (Utah 2000); Boulder Meadows
  v. Saville, 2 P.3d 131 (Colo.App.2000); Hous. Auth. of City of
  Bangor v. Maheux, 748 A.2d 474, 476 (Me.2000); City Wide
  Assocs. v. Penfield, 409 Mass. 140, 564 N.E.2d 1003 (1991); Schuett
  Inv. Co. v. Anderson, 386 N.W.2d 249 (Minn.App.1986). But see Lake
  in the Woods Apartment v. Carson, 651 S.W.2d 556, 558 (Mo.App.1983).


Washington cases have not previously confronted this precise
question. The only discussion in our cases occurred in Housing
Authority v. Terry.
- 27 114 Wash.2d 558, 789 P.2d 745 (1990).


Discrimination may be a defense that arises out of the tenancy. When
it does, the statute permits a tenant to assert the defense and
requires the court to consider it.

**** An Equitable Defense to an UD Action - Substantive Legal Right without a Remedy

An equitable defense to an unlawful detainer action arises when there
is a substantive legal right, that is, a right that comes within the
scope of judicial action, as distinguished from a mere moral right and
the usual legal remedies are unavailing. West's RCWA 59.12.010 et seq.

**** A Defense Arises Out of the Tenancy When they Affect T's Right of Possession or Excuse a T's Breach

To protect the summary nature of the unlawful detainer action,
defenses arise out of the tenancy only when they affect the tenant's
right of possession or are based on facts which excuse a tenant's
breach. West's RCWA 59.12.010 et seq.

*** Landlord and Tenant -- Key Number Topics 233k1755 -- Defenses

**** Discrimination May Be Raised as a Defense when it Arises Out of the Tenancy

Discrimination may be raised as a defense in summary eviction
proceedings when the discrimination arises out of the tenancy. West's
RCWA 59.18.380.

*** Landlord and Tenant -- Key Number Topics 233k1766 -- Answer

**** T Asserted Cognizable Defense to Nonpayment of Rent Based upon LL's Discrimination

Tenant asserted a cognizable unlawful discrimination defense in
landlord's unlawful detainer action, where tenant's asserted defense
to nonpayment of rent was landlord's discrimination. West's RCWA
59.18.380.

*** Landlord and Tenant -- Key Number Topics 233k1768(4) -- Weight and sufficiency

**** Evidence did not Support Discrimination by LL

Evidence in unlawful detainer action was sufficient to support finding
that landlord did not intentionally discriminate against tenant or
fail to reasonably accommodate her disability by failing to transfer
her to a lower income apartment or converting her apartment to a lower
income unit; tenant failed to pay her rent, and redesignation of
tenant's unit to a unit available to lower income tenants would have
cost $3,000 per year in rent and would have set a negative precedent
to other tenants since tenant's apartment was much larger than other
apartments offered to families with similar incomes. Civil Rights Act
of 1968, § 804, as amended, 42 U.S.C.A. § 3604; West's RCWA 59.12.010
et seq., 59.18.380.

* Radecki v. Joura, 114 F.3d 115 (8th Cir. 1997)
¶58 Furthermore, we note that a reasonable accommodation may be
requested up until the date of physical eviction.

See Radecki v. Joura, 114 F.3d 115, 116 (8th Cir. 1997);

Douglas, 884 A.2d at 1121

(“[A] reasonable accommodation defense will be timely until the
proverbial last minute.”). This is consistent with landlords'
obligation to reasonably make accommodations to not only their “rules”
but also their “policies, practices, or services.” RCW 49.60.222(2)(b)
(emphasis added); see Douglas, 884 A.2d at 1127.

* Fair Housing Claims in an Eviction: Disabilitiy Discrimination

https://vimeo.com/985225057/c4cd13838c?share=copy
