#+title:      Evidencing Breach of Warranty of Habitability
#+date:       [2026-02-19 Thu 10:51]
#+filetags:   :breach:evidence:habitability:ud:
#+identifier: 20260219T105138
#+signature:  email

* Documenting conditions (was Re: [HTF] junk fees for cleaning re move out)

** Email from Ben Ramm [2026-02-18 Wed 10:30]
:LOGBOOK:
- Note taken on [2026-02-19 Thu 10:54] \\
  Benjamin Ramm via groups.nwjustice.org <bramm=kitsaplegalaid.org@groups.nwjustice.org>
  Feb 18, 2026, 10:30 AM (1 day ago)
  to HTF@groups.nwjustice.org, craig.watt@nwjustice.org, EPowell@ccsww.org

  When I litigated habitability cases, I advised three photographs of each condition: up close, middle distance, and context. Let the judge (or jury) zoom in and zoom out on the conditions photographed.

  Gaps in the frames of windows or doors that let in air are difficult to photograph. Insert an object, like a sheet of paper, into the gap and photograph that set up. Put a pencil in the gap between a door and the floor.

  Leaks under a sink can be documented by putting a brown paper bag under the leaking pipe and then photographed every couple of minutes. The drops of water will change the color of the bag over time. The photographs can be arranged in order on a single sheet of paper to show the progress. One picture per page doesn’t show the process. The effect is better with video, especially video that can be sped up. Videos can be uploaded to a dedicated YouTube account and a link included in documentation. Of course  they’ll still be ignored, but at least you tried.

  Lack of hot water can be documented with a thermometer in a glass and then running water into the glass from the tap. Video is usually required.

  If possible, roaches should be trapped in a glue trap and then glue traps labelled: Monday roaches, Tuesday roaches, etc.

  Also, this noun “newspaper” … explain?
:END:

** Email from Elizabeth Powell [2026-02-18 Wed 10:05]
:LOGBOOK:
- Note taken on [2026-02-19 Thu 10:54] \\
  On Feb 18, 2026, at 10:05 AM, Elizabeth Powell via groups.nwjustice.org <EPowell=ccsww.org@groups.nwjustice.org> wrote:

  I tell folks that after they have taken out their stuff, buy that day’s newspaper, and put it in some of the photographs they take of the rental. Open drawers, under the sinks, inside the oven – not real estate listing photos, but rather photos to show what the condition of the property was when they moved out.

  Judges appear to love this. They get to draw their own conclusions regarding the conditions of the place. I tell them please don’t send me videos because I have to extract still photos from their videos, and the court is not going to accept a flash drive or look at the tenant’s phone.

  YES, a newspaper could be photoshopped, but it is a lot harder than changing a date/time stamp. Elizabeth
:END:
