#+title:      WA Law Against Discrimination
#+date:       [2026-02-05 Thu 10:04]
#+filetags:   :discrimination:law:wa:
#+identifier: 20260205T100441
#+signature:  wa

* Chapter 49.60 RCW Discriination--Human Rights Commission

** RCW 49.60.030 Freedom from discrimination—-Declaration of civil rights.

*** (1)

 The  right to  be free  from discrimination  because of  race, creed,
 color,  national  origin,  citizenship or  immigration  status,  sex,
 honorably discharged veteran or  military status, sexual orientation,
 or the presence of any sensory, mental, or physical disability or the
 use of  a trained  dog guide  or service  animal by  a person  with a
 disability is  recognized as and declared  to be a civil  right. This
 right shall include, but not be limited to:

- (a) The right to obtain and hold employment without discrimination;

- (b) The  right to the full  enjoyment of any of  the accommodations,
  advantages, facilities, or privileges of any place of public resort,
  accommodation, assemblage, or amusement;

- (c)  The  right  to  engage  in  real  estate  transactions  without
  discrimination,  including  discrimination   against  families  with
  children;

- (d)   The   right  to   engage   in   credit  transactions   without
  discrimination;

- (e) The  right to engage  in insurance transactions  or transactions
  with  health   maintenance  organizations   without  discrimination:
  PROVIDED, That a practice which is not unlawful under RCW 48.30.300,
  48.44.220, or 48.46.370  does not constitute an  unfair practice for
  the purposes of this subparagraph;

- (f) The  right to  engage in commerce  free from  any discriminatory
  boycotts or  blacklists. Discriminatory  boycotts or  blacklists for
  purposes  of this  section  shall  be defined  as  the formation  or
  execution of any express or implied agreement, understanding, policy
  or contractual arrangement for  economic benefit between any persons
  which  is not  specifically authorized  by  the laws  of the  United
  States  and  which  is  required  or  imposed,  either  directly  or
  indirectly, overtly or covertly, by  a foreign government or foreign
  person in order to restrict,  condition, prohibit, or interfere with
  or  in order  to exclude  any person  or persons  from any  business
  relationship  on the  basis of  race, color,  creed, religion,  sex,
  honorably discharged veteran or military status, sexual orientation,
  the presence of any sensory,  mental, or physical disability, or the
  use of  a trained  dog guide or  service animal by  a person  with a
  disability, or  national origin, citizenship or  immigration status,
  or  lawful business  relationship:  PROVIDED  HOWEVER, That  nothing
  herein contained shall prohibit the use of boycotts as authorized by
  law pertaining to labor disputes and unfair labor practices; and

- (g) The right  of a mother to  breastfeed her child in  any place of
  public resort, accommodation, assemblage, or amusement.

*** (2)

Any person deeming himself or herself  injured by any act in violation
of this  chapter shall  have a  civil action in  a court  of competent
jurisdiction to  enjoin further violations,  or to recover  the actual
damages sustained  by the person, or  both, together with the  cost of
suit  including reasonable  attorneys' fees  or any  other appropriate
remedy authorized  by this chapter  or the United States  Civil Rights
Act of 1964 as amended, or  the Federal Fair Housing Amendments Act of
1988 (42 U.S.C. Sec. 3601 et seq.).

*** (3)

 Except for  any unfair practice  committed by an employer  against an
 employee or a prospective employee, or  any unfair practice in a real
 estate transaction  which is  the basis for  relief specified  in the
 amendments to  RCW 49.60.225 contained  in chapter 69, Laws  of 1993,
 any unfair practice prohibited by  this chapter which is committed in
 the course of trade or commerce as defined in the Consumer Protection
 Act, chapter 19.86 RCW, is, for the purpose of applying that chapter,
 a matter affecting the public interest, is not reasonable in relation
 to the development and preservation of  business, and is an unfair or
 deceptive act in trade or commerce.

*** History

[ 2020 c 52 s 4; 2009 c 164 s 1; 2007 c 187 s 3; 2006 c 4 s 3; 1997 c 271 s 2; 1995 c 135 s 3. Prior: 1993 c 510 s 3; 1993 c 69 s 1; 1984 c 32 s 2; 1979 c 127 s 2; 1977 ex.s. c 192 s 1; 1974 ex.s. c 32 s 1; 1973 1st ex.s. c 214 s 3; 1973 c 141 s 3; 1969 ex.s. c 167 s 2; 1957 c 37 s 3; 1949 c 183 s 2; Rem. Supp. 1949 s 7614-21.]

** RCW 49.60.222 Unfair practices with respect to real estate transactions, facilities, or services.

*** (1)

It is an  unfair practice for any person, whether  acting for himself,
herself,  or   another,  because   of  sex,  marital   status,  sexual
orientation,  race,  creed,  color, national  origin,  citizenship  or
immigration   status,  families   with   children  status,   honorably
discharged veteran  or military status,  the presence of  any sensory,
mental, or physical  disability, or the use of a  trained dog guide or
service animal by a person with a disability:

- (a) To refuse to engage in a real estate transaction with a person;

- (b) To  discriminate against a  person in the terms,  conditions, or
  privileges  of a  real estate  transaction or  in the  furnishing of
  facilities or services in connection therewith;

- (c) To refuse to receive or to fail to transmit a bona fide offer to
  engage in a real estate transaction from a person;

- (d) To  refuse to  negotiate for  a real  estate transaction  with a
  person;

- (e) To represent to a person that real property is not available for
  inspection, sale, rental, or lease when  in fact it is so available,
  or to fail to  bring a property listing to his  or her attention, or
  to refuse to permit the person to inspect real property;

- (f) To  discriminate in  the sale  or rental,  or to  otherwise make
  unavailable  or deny  a  dwelling, to  any person;  or  to a  person
  residing in  or intending  to reside  in that  dwelling after  it is
  sold, rented,  or made available;  or to any person  associated with
  the person buying or renting;

- (g) To make, print, circulate, post, or mail, or cause to be so made
  or published a  statement, advertisement, or sign, or to  use a form
  of application for a real estate transaction, or to make a record or
  inquiry in  connection with  a prospective real  estate transaction,
  which  indicates,  directly  or  indirectly, an  intent  to  make  a
  limitation, specification, or discrimination with respect thereto;

- (h) To  offer, solicit,  accept, use,  or retain  a listing  of real
  property with the  understanding that a person  may be discriminated
  against  in  a real  estate  transaction  or  in the  furnishing  of
  facilities or services in connection therewith;

- (i) To expel a person from occupancy of real property;

- (j)  To discriminate  in the  course of  negotiating, executing,  or
  financing a  real estate  transaction whether  by mortgage,  deed of
  trust,  contract,  or other  instrument  imposing  a lien  or  other
  security in real  property, or in negotiating or  executing any item
  or service  related thereto  including issuance of  title insurance,
  mortgage  insurance,   loan  guarantee,  or  other   aspect  of  the
  transaction. Nothing in  this section shall limit the  effect of RCW
  49.60.176 relating to unfair practices in credit transactions; or

- (k) To  attempt to do  any of the  unfair practices defined  in this
  section.

*** (2)

 For the purposes of this chapter discrimination based on the presence
 of  any sensory,  mental,  or physical  disability or  the  use of  a
 trained dog guide  or service animal by a person  who is blind, deaf,
 or physically disabled includes:

 - (a)  A refusal  to permit,  at  the expense  of the  person with  a
   disability, reasonable modifications  of existing premises occupied
   or  to be  occupied by  such person  if such  modifications may  be
   necessary to  afford such  person full  enjoyment of  the dwelling,
   except that, in the case of a rental, the landlord may, where it is
   reasonable to do so, condition permission for a modification on the
   renter  agreeing to  restore the  interior of  the dwelling  to the
   condition that existed before the modification, reasonable wear and
   tear excepted;

 - (b) To refuse to make  reasonable accommodation in rules, policies,
   practices, or services when such accommodations may be necessary to
   afford  a person  with  the  presence of  any  sensory, mental,  or
   physical  disability and/or  the  use  of a  trained  dog guide  or
   service  animal by  a  person  who is  blind,  deaf, or  physically
   disabled equal opportunity to use and enjoy a dwelling; or

 - (c) To fail  to design and construct  covered multifamily dwellings
   and  premises   in  conformance  with  the   federal  fair  housing
   amendments act of 1988 (42 U.S.C.  Sec. 3601 et seq.) and all other
   applicable laws or regulations pertaining to access by persons with
   any sensory, mental, or physical disability or use of a trained dog
   guide or  service animal.  Whenever the requirements  of applicable
   laws or regulations differ,  the requirements which require greater
   accessibility  for persons  with any  sensory, mental,  or physical
   disability shall govern.


 Nothing  in (a)  or (b)  of  this subsection  shall apply  to: (i)  A
 single-family house rented  or leased by the owner if  the owner does
 not own or have an interest in the proceeds of the rental or lease of
 more than three such single-family houses  at one time, the rental or
 lease  occurred without  the use  of a  salesperson, or  a broker  as
 defined in  RCW 18.85.011, and  the rental or lease  occurred without
 the publication, posting,  or mailing of any  advertisement, sign, or
 statement in violation of subsection  (1)(g) of this section; or (ii)
 rooms or  units in dwellings  containing living quarters  occupied or
 intended  to  be  occupied  by  no more  than  four  families  living
 independently of each  other if the owner maintains  and occupies one
 of the rooms or units as his or her residence.

*** (3)

Notwithstanding any other  provision of this chapter, it  shall not be
an  unfair practice  or a  denial of  civil rights  for any  public or
private  educational  institution  to   separate  the  sexes  or  give
preference to or  limit use of dormitories, residence  halls, or other
student housing to  persons of one sex or to  make distinctions on the
basis of marital or families with children status.

*** (4)

Except pursuant  to subsection  (2)(a) of  this section,  this section
shall not  be construed to require  structural changes, modifications,
or  additions  to  make  facilities  accessible to  a  person  with  a
disability  except  as otherwise  required  by  law. Nothing  in  this
section  affects   the  rights,  responsibilities,  and   remedies  of
landlords  and  tenants  pursuant  to  chapter  59.18  or  59.20  RCW,
including the  right to post  and enforce reasonable rules  of conduct
and safety  for all tenants  and their guests, provided  that chapters
59.18  and  59.20  RCW  are  only affected  to  the  extent  they  are
inconsistent   with  the   nondiscrimination   requirements  of   this
chapter.  Nothing in  this  section limits  the  applicability of  any
reasonable federal, state, or local restrictions regarding the maximum
number of occupants permitted to occupy a dwelling.

*** (5)

Notwithstanding any other  provision of this chapter, it  shall not be
an  unfair  practice  for   any  public  establishment  providing  for
accommodations offered for  the full enjoyment of  transient guests as
defined by  RCW 9.91.010(1)(c)  to make distinctions  on the  basis of
families with children status. Nothing in this section shall limit the
effect  of RCW  49.60.215 relating  to unfair  practices in  places of
public accommodation.

*** (6)

Nothing in  this chapter prohibiting discrimination  based on families
with children status  applies to housing for older  persons as defined
by   the   federal  fair   housing   amendments   act  of   1988,   42
U.S.C.  Sec. 3607(b)(1)  through (3),  as amended  by the  housing for
older  persons  act of  1995,  P.L.  104-76,  as enacted  on  December
28, 1995. Nothing in this  chapter authorizes requirements for housing
for older persons different than  the requirements in the federal fair
housing amendments act of 1988, 42 U.S.C. Sec. 3607(b)(1) through (3),
as amended by the housing for  older persons act of 1995, P.L. 104-76,
as enacted on December 28, 1995.

*** (7)

Nothing  in  this chapter  shall  apply  to real  estate  transactions
involving the sharing  of a dwelling unit, or rental  or sublease of a
portion of a  dwelling unit, when the dwelling unit  is to be occupied
by the  owner or  subleasor. For purposes  of this  section, "dwelling
unit" has the same meaning as in RCW 59.18.030.

*** History

[ 2020 c 52 s 14; 2007 c 187 s 13; 2006 c 4 s 14. Prior: 1997 c 400 s 3; 1997 c 271 s 14; 1995 c 259 s 3; prior: 1993 c 510 s 17; 1993 c 69 s 5; 1989 c 61 s 1; 1979 c 127 s 8; 1975 1st ex.s. c 145 s 1; 1973 c 141 s 13; 1969 ex.s. c 167 s 4.]

** RCW 49.60.2235 Unfair practice to coerce, intimidate, threaten, or interfere regarding secured real estate transaction rights.

It  is  an  unlawful  practice to  coerce,  intimidate,  threaten,  or
interfere  with any  person in  the exercise  or enjoyment  of, or  on
account of  his or her having  exercised or enjoyed, or  on account of
his or her having aided or encouraged any other person in the exercise
or enjoyment of, rights regarding  real estate transactions secured by
RCW 49.60.030, 49.60.040, and 49.60.222 through 49.60.224.
