#+title:      A New Notice Waives a Prior Notice in Washington
#+date:       [2026-01-16 Fri 14:02]
#+filetags:   :multiple:notice:waiver:
#+identifier: 20260116T140252
#+signature:  note

* Headnotes From Hinkhouse v. Wacker 112 Wash. 253 2020-08-18

See [[denote:20260116T140038][sc  hinkhouse-v-wacker-112-wash-253-2020-08-18]]


2 Landlord and Tenant
233k960Vitiation of notice already given

Landlord, by giving tenant a sufficient notice to quit, waives all prior notices.
Cases that cite this headnote

233
Landlord and Tenant
233IV
Particular Kinds of Tenancies and Attributes Thereof
233IV(F)
Termination
233IV(F)5
Landlord's Notice of Termination
233k960
Vitiation of notice already given
(Formerly 233k94(5))

3 Landlord and Tenant
233k958Service

Where notice to quit is served by leaving copy of notice with suitable person at rented premises, a copy must also be mailed to tenant at his place of residence to constitute sufficient notice under Rem.Code 1915, § 814, subd. 2.
Cases that cite this headnote

233
Landlord and Tenant
233IV
Particular Kinds of Tenancies and Attributes Thereof
233IV(F)
Termination
233IV(F)5
Landlord's Notice of Termination
233k956
Sufficiency
233k958
Service
(Formerly 233k94(4))

4 Landlord and Tenant
233k960Vitiation of notice already given

A notice to quit, which was ineffective, because not served as required by Rem.Code 1915, § 814, did not constitute a waiver of prior notices.

* Decision

- NOTE: No appellate cases cite this case for this waiver proposition,
  and the court does not cite to cases to support this position.

The appellant seriously contends that the giving of the last notice on
February 25,  1919, is a  waiver of the other  notices.

*We are of the  opinion that this would be correct,  if the last notice
was sufficient.*

We are  of the opinion  that the notice last  given was of  no effect,
because it was not served in  the manner provided by law. Section 814,
Rem. Code, provides that such notice  shall be served either—— ‘(1) By
delivering a copy personally to the person entitled thereto; or (2) if
he be  absent from the  premises unlawfully  held, by leaving  there a
copy, with some  person of suitable age and discretion,  and sending a
copy through the mail addressed to  the person entitled thereto at his
place of residence.’

- _Hinkhouse v. Wacker_, 112 Wash. 253, 257, 191 P. 881, 882 (1920), aff'd, 112 Wash. 253, 195 P. 218 (1921)


We are of the opinion, therefore, that the first notice was sufficient
upon which  to base the action  for unlawful detainer. We  are also of
the opinion that  the giving of the subsequent notices  did not amount
to a waiver of the first notice.

- Hinkhouse v. Wacker, 112 Wash. 253, 258, 191 P. 881, 883 (1920), aff'd, 112 Wash. 253, 195 P. 218 (1921)
