#+title:      RCW 59.20.090 Term of rental agreements—Renewal—Nonrenewal—Termination—Armed forces exception—Notices
#+date:       [2026-03-04 Wed 09:44]
#+filetags:   :increase:limits:mhlta:rent:statute:
#+identifier: 20260304T094424
#+signature:  rcw=59=20=090

* RCW 59.20.090 -- Term of rental agreements—Renewal—Nonrenewal—Termination—Armed forces exception—Notices.

** (1) [Term of Rental Agreements--1 Year or as Agreed--Automatic Renewal]
Unless otherwise agreed rental agreements shall be for a term of one year. Any rental agreement of whatever duration shall be automatically renewed for the term of the original rental agreement, unless a different specified term is agreed upon.

** (2) [3 Month Notice Required for Rent Increase]
A landlord seeking to increase the rent upon expiration of the term of a rental agreement of any duration shall notify the tenant in writing three months prior to the effective date of any increase in rent.

** (3) [1 Month Notice Required Not To Renew by Tenant]
A tenant shall notify the landlord in writing one month prior to the expiration of a rental agreement of an intention not to renew.

** (4) [Allowed Early Terminations]

*** (a) [Change in Location of Tenant's Employment]
The tenant may terminate the rental agreement upon thirty days written notice whenever a change in the location of the tenant's employment requires a change in his or her residence, and shall not be liable for rental following such termination unless after due diligence and reasonable effort the landlord is not able to rent the mobile home lot at a fair rental. If the landlord is not able to rent the lot, the tenant shall remain liable for the rental specified in the rental agreement until the lot is rented or the original term ends.

*** (b) [Armed Forces Exception for Early Termination]
Any tenant who is a member of the armed forces, including the national guard and armed forces reserves, or that tenant's spouse or dependent, may terminate a rental agreement with less than thirty days notice if the tenant receives permanent change of station or deployment orders which do not allow greater notice. The service member shall provide the landlord a copy of the official military orders or a signed letter from the service member's commanding officer confirming any of the following criteria are met:

**** (i)
The service member is required, pursuant to permanent change of station orders, to move thirty-five miles or more from the location of the rental premises;

**** (ii)
The service member is prematurely or involuntarily discharged or released from active duty;

**** (iii)
The service member is released from active duty after having leased the rental premises while on active duty status and the rental premises is thirty-five miles or more from the service member's home of record prior to entering active duty;

**** (iv)
After entering into a rental agreement, the commanding officer directs the service member to move into government provided housing;

**** (v)
The service member receives temporary duty orders, temporary change of station orders, or state active duty orders to an area thirty-five miles or more from the location of the rental premises, provided such orders are for a period not less than ninety days; or

**** (vi)
The service member has leased the property, but prior to taking possession of the rental premises, receives change of station orders to an area that is thirty-five miles or more from the location of the rental premises.

** Source
[ 2019 c 23 s 5; 2010 c 8 s 19034; 2003 c 7 s 3; 1998 c 118 s 3; 1980 c 152 s 2; 1979 ex.s. c 186 s 7; 1977 ex.s. c 279 s 9.]
